# Generated by Django 5.2.13 on 2026-04-19 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase", "0053_alter_purchase_rsc_usd_rate"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("expert_insights", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Editor who first created this feedback row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_peer_review_editorial_feedbacks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unified_document",
                    models.OneToOneField(
                        db_comment="At most one editorial feedback row per unified document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_peer_review_editorial_feedback",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Editor who last saved changes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_peer_review_editorial_feedbacks_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_editorial_feedback",
            },
        ),
        migrations.CreateModel(
            name="RFPSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("summary_content", models.TextField(blank=True)),
                (
                    "executive_comparison_summary",
                    models.TextField(
                        blank=True,
                        db_comment="Funder-facing comparison across proposals.",
                    ),
                ),
                (
                    "executive_comparison_updated_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rfp_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_peer_review_rfp_summary",
                        to="purchase.grant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_rfp_summary",
                "ordering": ["-updated_date"],
            },
        ),
        migrations.CreateModel(
            name="EditorialFeedbackCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "category_code",
                    models.CharField(
                        choices=[
                            ("funding_opportunity_fit", "funding_opportunity_fit"),
                            ("methods_rigor", "methods_rigor"),
                            ("statistical_analysis_plan", "statistical_analysis_plan"),
                            ("feasibility_and_execution", "feasibility_and_execution"),
                            ("scientific_impact", "scientific_impact"),
                            (
                                "clinical_or_translational_impact",
                                "clinical_or_translational_impact",
                            ),
                            (
                                "societal_and_broader_impact",
                                "societal_and_broader_impact",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="ai_peer_review.editorialfeedback",
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_editorial_feedback_category",
                "unique_together": {("feedback", "category_code")},
            },
        ),
        migrations.CreateModel(
            name="ProposalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("poor", "poor"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("overall_rationale", models.TextField(blank=True, default="")),
                (
                    "overall_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("overall_score_numeric", models.IntegerField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=512)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_proposal_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Funding opportunity context; null for standalone review.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_reviews",
                        to="purchase.grant",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        db_comment="Proposal unified document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_reviews",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_proposalreview",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["grant", "status"],
                        name="ai_peer_review_pr_grant_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("grant__isnull", False)),
                        fields=("unified_document", "grant"),
                        name="ai_peer_review_pr_ud_grant_nn",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("grant__isnull", True)),
                        fields=("unified_document",),
                        name="ai_peer_review_pr_ud_standalone",
                    ),
                ],
            },
        ),
    ]
