# Generated by Django 5.2.12 on 2026-04-01 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_peer_review", "0001_initial"),
        ("purchase", "0051_remove_balance_lock_type"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "fundability_expert",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "feasibility_expert",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "novelty_expert",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "impact_expert",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reproducibility_expert",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expert_insights", models.TextField(blank=True)),
                (
                    "proposal_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_feedbacks",
                        to="ai_peer_review.proposalreview",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        db_comment="Denormalized from proposal_review for querying.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_editorial_feedbacks",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_peer_review_editorial_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_editorial_feedback",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "proposal_review"),
                        name="ai_peer_review_edit_fb_user_pr",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "proposal_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_entitlements",
                        to="ai_peer_review.proposalreview",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_peer_review_report_entitlements",
                        to="purchase.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_peer_review_report_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_report_entitlement",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "proposal_review"),
                        name="ai_peer_review_report_ent_user_pr",
                    )
                ],
            },
        ),
    ]
