# Generated by Django 5.2.13 on 2026-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_peer_review", "0002_alter_editorialfeedbackcategory_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposalreview",
            name="overall_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("good", "good"),
                    ("adequate", "adequate"),
                    ("marginal", "marginal"),
                    ("poor", "poor"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
