# Generated by Django 5.2.13 on 2026-04-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_peer_review", "0003_alter_proposalreview_overall_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalKeyInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("tldr", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "proposal_review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_insight",
                        to="ai_peer_review.proposalreview",
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_proposal_key_insight",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ProposalKeyInsightItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("strength", "strength"), ("weakness", "weakness")],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "key_insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ai_peer_review.proposalkeyinsight",
                    ),
                ),
            ],
            options={
                "db_table": "ai_peer_review_proposal_key_insight_item",
                "ordering": ["item_type", "order", "id"],
            },
        ),
    ]
