# Generated by Django 5.2.13 on 2026-04-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_peer_review", "0004_proposalkeyinsight_proposalkeyinsightitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposalreview",
            name="overall_confidence",
        ),
    ]
