# Generated by Django 2.2.6 on 2019-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191007_2154'),
        ('user', '0006_auto_20191008_1952'),
    ]

    operations = [
    ]
