# Generated by Django 2.2.6 on 2019-10-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191023_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
