# Generated by Django 2.2.6 on 2019-11-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_author_description'),
        ('user', '0008_auto_20191031_1400'),
    ]

    operations = [
    ]
