# Generated by Django 2.2.6 on 2019-11-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20191101_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/author_profile_images/%Y/%m/%d'),
        ),
    ]
