# Generated by Django 2.2.7 on 2019-11-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191109_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload_tutorial_complete',
            field=models.BooleanField(default=False),
        ),
    ]
