# Generated by Django 2.2.7 on 2019-11-12 21:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191109_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, storage=user.models.ProfileImageStorage(), upload_to='uploads/author_profile_images/%Y/%m/%d'),
        ),
    ]
