# Generated by Django 2.2.7 on 2019-11-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20191112_2159'),
        ('user', '0013_user_upload_tutorial_complete'),
    ]

    operations = [
    ]
