# Generated by Django 2.2.7 on 2019-11-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_bookmarks'),
        ('user', '0014_merge_20191112_2247'),
    ]

    operations = [
    ]
