# Generated by Django 2.2.7 on 2019-11-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20191119_2054'),
        ('user', '0015_merge_20191115_1905'),
    ]

    operations = [
    ]
