# Generated by Django 2.2.8 on 2019-12-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_wallet'),
        ('user', '0017_emailpreference'),
    ]

    operations = [
    ]
