# Generated by Django 2.2.8 on 2019-12-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_emailpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailPreference',
        ),
    ]
