# Generated by Django 2.2.8 on 2019-12-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_first_vote_modal',
            field=models.BooleanField(default=False),
        ),
    ]
