# Generated by Django 2.2.8 on 2019-12-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_first_vote_on_paper_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_seen_first_vote_modal',
            new_name='has_seen_first_coin_modal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_vote_on_paper_distribution',
        ),
    ]
