# Generated by Django 2.2.8 on 2019-12-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_emailpreference'),
        ('user', '0020_auto_20191213_1922'),
    ]

    operations = [
    ]
