# Generated by Django 2.2.8 on 2020-01-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_hub_acronym'),
        ('user', '0024_action_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='hub',
        ),
        migrations.AddField(
            model_name='action',
            name='hub',
            field=models.ManyToManyField(related_name='actions', to='hub.Hub'),
        ),
    ]
