# Generated by Django 2.2.9 on 2020-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200117_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_date']},
        ),
    ]
