# Generated by Django 2.2.10 on 2020-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_user_moderator'),
        ('user', '0028_merge_20200217_2101'),
    ]

    operations = [
    ]
