# Generated by Django 2.2.10 on 2020-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_merge_20200219_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='orcid_uid',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, unique=True),
        ),
    ]
