# Generated by Django 2.2.10 on 2020-02-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_author_orcid_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='orcid_uid',
            new_name='orcid_id',
        ),
    ]
