# Generated by Django 2.2.10 on 2020-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_author_orcid_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_orcid_connect_modal',
            field=models.BooleanField(default=False),
        ),
    ]
