# Generated by Django 2.2.13 on 2020-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_user_has_seen_orcid_connect_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
