# Generated by Django 2.2.13 on 2020-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_analyticmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
