# Generated by Django 2.2.16 on 2020-09-23 20:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='headline',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
