# Generated by Django 2.2.16 on 2020-09-21 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_user_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='occupation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=[], size=None),
            preserve_default=False,
        ),
    ]
