# Generated by Django 2.2.16 on 2020-09-28 23:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20200923_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
