# Generated by Django 2.2.16 on 2020-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_author_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
