# Generated by Django 2.2.16 on 2020-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20200928_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOD1P', models.IntegerField()),
                ('major', models.CharField(max_length=128)),
                ('major_category', models.CharField(max_length=64)),
            ],
        ),
    ]
