# Generated by Django 2.2.16 on 2020-10-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_score',
            field=models.IntegerField(default=0),
        ),
    ]
