# Generated by Django 2.2 on 2020-10-07 00:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_author_author_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='education',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
