# Generated by Django 2.2 on 2020-10-19 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20201007_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='referral_code',
            field=models.CharField(default=uuid.UUID('d302b23b-641b-4432-9ac0-2d0b9ebbd4b3'), max_length=36),
        ),
    ]
