# Generated by Django 2.2 on 2020-10-19 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_author_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='referral_code',
            field=models.CharField(default=uuid.UUID('2ac38415-5de7-4327-b218-3932afa7aabe'), max_length=36),
        ),
    ]
