# Generated by Django 2.2 on 2020-10-19 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20201019_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
