# Generated by Django 2.2 on 2020-10-19 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20201019_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
