# Generated by Django 2.2 on 2020-10-19 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20201019_2132'),
    ]

    operations = []
