# Generated by Django 2.2 on 2020-10-29 22:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_stripe_modal',
            field=models.BooleanField(default=False),
        )
    ]
