# Generated by Django 2.2 on 2020-10-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20201029_2259'),
        ('user', '0049_auto_20201024_0035'),
    ]

    operations = [
    ]
