# Generated by Django 2.2 on 2020-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_merge_20201030_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='probable_spammer',
            field=models.BooleanField(default=False),
        ),
    ]
