# Generated by Django 2.2 on 2020-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_user_probable_spammer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spam_updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
