# Generated by Django 2.2 on 2020-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20201105_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
