# Generated by Django 2.2 on 2020-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sift_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
