# Generated by Django 2.2 on 2020-12-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='academic_verification',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
