# Generated by Django 2.2 on 2020-12-17 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_author_academic_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
