# Generated by Django 2.2 on 2020-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_author_academic_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='academic_verification',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
