# Generated by Django 2.2 on 2021-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0003_auto_20210603_2150'),
        ('user', '0059_auto_20210326_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cover_image', models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='organizations/cover_image/%Y/%m/%d')),
                ('description', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=64)),
                ('access_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='researchhub_access_group.ResearchhubAccessGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
