# Generated by Django 2.2 on 2021-08-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20210326_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='claimed',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
