# Generated by Django 2.2 on 2021-09-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_organization'),
        ('user', '0060_author_claimed'),
    ]

    operations = [
    ]
