# Generated by Django 2.2 on 2021-09-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_author_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='merged_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='academic_verification',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='claimed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
