# Generated by Django 2.2 on 2021-09-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_merge_20210907_1738'),
        ('user', '0061_auto_20210913_2308'),
    ]

    operations = [
    ]
