# Generated by Django 2.2 on 2021-09-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_merge_20210916_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='', max_length=1024),
        ),
    ]
