# Generated by Django 2.2 on 2021-09-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_auto_20210930_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
