# Generated by Django 2.2 on 2021-10-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0008_auto_20211007_0028'),
        ('user', '0068_remove_organization_access_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='permissions',
            field=models.ManyToManyField(related_name='direct_organization', to='researchhub_access_group.Permission'),
        ),
    ]
