# Generated by Django 2.2 on 2021-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_organization_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatekeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ELN', 'ELN'), ('CLIENT_PERMISSIONS', 'CLIENT_PERMISSIONS')], db_index=True, max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
