# Generated by Django 2.2 on 2021-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_organization_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='note_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
