# Generated by Django 2.2 on 2021-10-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_organization_note_created'),
        ('user', '0070_gatekeeper'),
    ]

    operations = [
    ]
