# Generated by Django 2.2 on 2021-10-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='permissions',
        ),
    ]
