# Generated by Django 2.2 on 2021-10-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_merge_20211019_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='permissions',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('ORGANIZATION', 'ORGANIZATION')], default='ORGANIZATION', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='note_created',
            field=models.BooleanField(default=False),
        ),
    ]
