# Generated by Django 2.2 on 2021-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0010_auto_20211015_2159'),
        ('user', '0071_remove_organization_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_permissions',
            field=models.ManyToManyField(related_name='direct_organization', to='researchhub_access_group.Permission'),
        ),
    ]
