# Generated by Django 2.2 on 2021-10-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_auto_20211020_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cover_image',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to='organizations/cover_image/%Y/%m/%d'),
        ),
    ]
