# Generated by Django 2.2 on 2021-10-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_organization_org_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_permissions',
        ),
    ]
