# Generated by Django 2.2 on 2021-10-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_remove_organization_org_permissions'),
        ('user', '0070_organization_note_created'),
    ]

    operations = [
    ]
