# Generated by Django 2.2 on 2022-01-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20211022_0126'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
