# Generated by Django 2.2 on 2022-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20211022_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
