# Generated by Django 2.2 on 2022-02-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20220125_2305'),
        ('user', '0074_auto_20220201_2239'),
    ]

    operations = [
    ]
