# Generated by Django 2.2 on 2022-02-09 23:15

from django.db import migrations
import user.models.user_model


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_merge_20220205_0646'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.user_model.UserManager()),
            ],
        ),
    ]
