# Generated by Django 2.2 on 2021-10-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_auto_20211019_2044'),
        ('user', '0071_merge_20211019_2037'),
    ]

    operations = [
    ]
