# Generated by Django 2.2 on 2022-02-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_auto_20220210_2140'),
        ('user', '0076_auto_20220208_0508'),
    ]

    operations = [
    ]
