# Generated by Django 2.2 on 2022-03-11 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_merge_20220211_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatekeeper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gatekeeper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatekeeper',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
