# Generated by Django 2.2 on 2022-05-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0045_flag_hubs'),
        ('user', '0080_userapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('verdict_choice', models.CharField(choices=[('ABUSIVE_OR_RUDE', 'ABUSIVE_OR_RUDE'), ('COPYRIGHT', 'COPYRIGHT'), ('LOW_QUALITY', 'LOW_QUALITY'), ('NOT_CONSTRUCTIVE', 'NOT_CONSTRUCTIVE'), ('PLAGIARISM', 'PLAGIARISM'), ('SPAM', 'SPAM')], max_length=32)),
                ('is_content_removed', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to=settings.AUTH_USER_MODEL)),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='discussion.Flag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
