# Generated by Django 2.2 on 2022-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_userapitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatekeeper',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gatekeeper',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
