# Generated by Django 2.2 on 2022-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_auto_20220524_2238'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=models.Index(condition=models.Q(user=None), fields=['user'], name='user_action_user_null_ix'),
        ),
    ]
