# Generated by Django 2.2 on 2022-05-25 20:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0084_auto_20220525_2015'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_date'], name='user_action_createdate_brin_ix', pages_per_range=2),
        ),
    ]
