# Generated by Django 2.2 on 2022-05-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_auto_20220524_1823'),
        ('user', '0085_auto_20220525_2043'),
    ]

    operations = [
    ]
