# Generated by Django 2.2 on 2022-10-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0086_auto_20220621_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='should_display_rsc_balance_home',
            field=models.BooleanField(default=True),
        ),
    ]
