# Generated by Django 2.2 on 2022-11-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_user_should_display_rsc_balance_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='h_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AuthorCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_count', models.IntegerField(default=0)),
                ('citation_name', models.CharField(max_length=256)),
                ('cited_by_url', models.URLField(max_length=256, null=True)),
                ('publish_year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='user.Author')),
            ],
        ),
    ]
