# Generated by Django 2.2 on 2022-10-19 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_user_should_display_rsc_balance_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clicked_on_balance_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
