# Generated by Django 2.2 on 2022-11-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_auto_20221019_1903'),
        ('user', '0088_auto_20221108_2239'),
    ]

    operations = [
    ]
