# Generated by Django 4.1 on 2022-11-11 00:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0089_merge_20221109_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="education",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="headline",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
