# Generated by Django 4.1 on 2022-11-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0090_alter_author_education_alter_author_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
