# Generated by Django 4.1 on 2023-10-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0092_remove_verification_file_verification_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
