# Generated by Django 4.1 on 2023-10-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0093_author_openalex_id_user_is_verified"),
        ("user", "0093_user_linkedin_data"),
    ]

    operations = []
