# Generated by Django 4.1 on 2023-10-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0094_merge_20231012_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
