# Generated by Django 4.1 on 2023-10-20 19:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0095_author_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="openalex_id",
        ),
        migrations.AddField(
            model_name="author",
            name="openalex_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, default=None, max_length=64, null=True, unique=True
                ),
                default=list,
                size=None,
            ),
        ),
    ]
