# Generated by Django 4.1 on 2024-01-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0097_remove_user_linkedin_data_author_linkedin_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="verdict",
            name="is_paper_pdf_removed",
            field=models.BooleanField(default=False),
        ),
    ]
