# Generated by Django 4.1 on 2024-01-12 16:47

from django.db import migrations, models

def initialize_to_has_seen_orcid_connect_modal(apps, schema_editor):
    User = apps.get_model("user", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).all().update(
        has_completed_onboarding=models.F("has_seen_orcid_connect_modal")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0098_verdict_is_paper_pdf_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(initialize_to_has_seen_orcid_connect_modal, reverse_code=migrations.RunPython.noop),
    ]
