# Generated by Django 4.1 on 2024-01-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0099_user_has_completed_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="google_scholar",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
