# Generated by Django 4.1 on 2024-03-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0100_author_google_scholar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyticModel",
        ),
    ]
