# Generated by Django 4.1 on 2024-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0101_delete_analyticmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationfile",
            name="verification",
        ),
        migrations.DeleteModel(
            name="Verification",
        ),
        migrations.DeleteModel(
            name="VerificationFile",
        ),
    ]
