# Generated by Django 4.1.13 on 2024-04-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0102_remove_verificationfile_verification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="linkedin_data",
        ),
    ]
