# Generated by Django 4.1 on 2024-05-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0104_author_country_code_author_i10_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="academic_verification",
        ),
        migrations.RemoveField(
            model_name="author",
            name="merged_with",
        ),
        migrations.RemoveField(
            model_name="author",
            name="orcid_account",
        ),
    ]
