# Generated by Django 4.1 on 2024-05-21 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0109_coauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coauthor",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coauthors",
                to="user.author",
            ),
        ),
    ]
