# Generated by Django 4.1 on 2024-05-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0110_alter_coauthor_author"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="authorinstitution",
            unique_together=set(),
        ),
    ]
