# Generated by Django 4.1 on 2024-05-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0111_alter_authorinstitution_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="orcid_id",
            field=models.CharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
