# Generated by Django 4.1 on 2024-05-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0113_authorcontributionsummary"),
        ("user", "0113_remove_authorinstitution_is_primary"),
    ]

    operations = []
