# Generated by Django 4.1 on 2024-05-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0114_merge_20240524_0059"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_source",
            field=models.CharField(
                choices=[("OPENALEX", "OpenAlex"), ("RESEARCHHUB", "ResearchHub")],
                default="RESEARCHHUB",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="last_full_fetch_from_openalex",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
