# Generated by Django 4.1 on 2024-05-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0114_merge_20240523_0259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorcontributionsummary",
            name="citation_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="authorcontributionsummary",
            name="works_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
