# Generated by Django 4.1 on 2024-05-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0115_alter_authorcontributionsummary_citation_count_and_more"),
        ("user", "0115_author_created_source_and_more"),
    ]

    operations = []
