# Generated by Django 4.2.13 on 2024-07-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0116_merge_20240524_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="merged_with_author_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_authors",
                to="user.author",
            ),
        ),
    ]
