# Generated by Django 4.2.15 on 2024-09-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_associated_institutions_and_more"),
        ("user", "0121_alter_userverification_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="authorinstitution",
            unique_together={("author", "institution", "years")},
        ),
    ]
