# Generated by Django 4.2.15 on 2024-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0123_alter_author_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_official_account",
            field=models.BooleanField(default=False),
        ),
    ]
