# Generated by Django 5.1.3 on 2024-11-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0125_remove_user_bookmarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_seen_stripe_modal",
        ),
    ]
