# Generated by Django 4.2.16 on 2024-12-06 11:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0126_remove_user_has_seen_stripe_modal"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["openalex_ids"], name="user_author_openalex_ids_idx"
            ),
        ),
    ]
