# Generated by Django 4.2.17 on 2024-12-20 18:09

from django.db import migrations, models
import user.related_models.profile_image_storage


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0127_author_user_author_openalex_ids_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="orcid_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="profile_image",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=2048,
                null=True,
                storage=user.related_models.profile_image_storage.ProfileImageStorage(),
                upload_to="uploads/author_profile_images/%Y/%m/%d",
            ),
        ),
    ]
