# Generated by Django 5.1.4 on 2025-01-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0128_alter_author_orcid_id_alter_author_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
