# Generated by Django 5.1.5 on 2025-01-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0130_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["hub", "paper", "user", "author"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
