# Generated by Django 5.1.5 on 2025-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0131_alter_follow_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
