# Generated by Django 5.2.1 on 2025-06-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0131_alter_follow_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ["hub", "paper", "researchhubpost", "user", "author"]
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
