# Generated by Django 5.2.2 on 2025-07-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0132_alter_follow_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
