# Generated by Django 5.2.1 on 2025-06-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0132_alter_follow_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clicked_on_balance_date",
        ),
    ]
