# Generated by Django 5.2.2 on 2025-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0133_remove_author_is_verified_remove_user_is_verified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(
                    ("is_active", True),
                    ("is_suspended", False),
                    ("probable_spammer", False),
                ),
                fields=["is_active", "is_suspended", "probable_spammer"],
                name="user_active_spam_idx",
            ),
        ),
    ]
