# Generated by Django 5.2.7 on 2025-10-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0134_user_user_active_spam_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sift_risk_score",
        ),
    ]
