# Generated by Django 5.2.6 on 2025-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0135_remove_user_sift_risk_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="headline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
