# Generated by Django 5.2.7 on 2025-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="last_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
