# Generated by Django 5.2.8 on 2025-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="first_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="last_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="userverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("first_name__isnull", False),
                        models.Q(("first_name", ""), _negated=True),
                    ),
                    models.Q(
                        ("last_name__isnull", False),
                        models.Q(("last_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="user_verification_name_required",
                violation_error_message="Either first_name or last_name must be provided",
            ),
        ),
    ]
