# Generated by Django 5.2.10 on 2026-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
