# Generated by Django 5.2.10 on 2026-01-31 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("FUNDRAISE_PAYOUT", "Fundraise Payout"),
                            ("BOUNTY_PAYOUT", "Bounty Payout"),
                            ("TIP_DOCUMENT", "Document Tip"),
                            ("TIP_REVIEW", "Review Tip"),
                            ("FEE", "Platform Fee"),
                        ],
                        help_text="Type of funding activity",
                        max_length=32,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total RSC amount for this activity",
                        max_digits=19,
                    ),
                ),
                (
                    "activity_date",
                    models.DateTimeField(
                        db_index=True, help_text="When the funding activity occurred"
                    ),
                ),
                ("source_object_id", models.PositiveIntegerField()),
                (
                    "funder",
                    models.ForeignKey(
                        help_text="The user who provided the funding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funding_activities",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Activity",
                "verbose_name_plural": "Funding Activities",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="FundingActivityRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="RSC amount received by this recipient",
                        max_digits=19,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="The funding activity this recipient belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="user.fundingactivity",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        help_text="The user who received the funding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funding Activity Recipient",
                "verbose_name_plural": "Funding Activity Recipients",
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[("FUNDER", "Funder"), ("EARNER", "Earner")],
                        help_text="Type of leaderboard (funder or earner)",
                        max_length=16,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("7_DAYS", "7 Days"),
                            ("30_DAYS", "30 Days"),
                            ("6_MONTHS", "6 Months"),
                            ("1_YEAR", "1 Year"),
                            ("ALL_TIME", "All Time"),
                        ],
                        help_text="Time period for the leaderboard",
                        max_length=16,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="User's rank in this leaderboard"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Total RSC amount for ranking",
                        max_digits=19,
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this leaderboard entry was computed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this leaderboard entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard",
                "verbose_name_plural": "Leaderboards",
            },
        ),
        migrations.AddIndex(
            model_name="fundingactivity",
            index=models.Index(
                fields=["funder", "activity_date"], name="funding_funder_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundingactivity",
            index=models.Index(
                fields=["source_type", "activity_date"], name="funding_type_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundingactivity",
            index=models.Index(
                fields=["unified_document", "activity_date"],
                name="funding_doc_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingactivity",
            constraint=models.UniqueConstraint(
                fields=("source_content_type", "source_object_id"),
                name="unique_funding_source",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingactivityrecipient",
            index=models.Index(
                fields=["recipient_user"], name="funding_recipient_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingactivityrecipient",
            constraint=models.UniqueConstraint(
                fields=("activity", "recipient_user"), name="unique_activity_recipient"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["leaderboard_type", "period", "rank"],
                name="lb_type_period_rank_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                fields=("user", "leaderboard_type", "period"),
                name="unique_user_leaderboard_period",
            ),
        ),
    ]
