# Generated by Django 5.2.12 on 2026-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0138_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staking_opted_in",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
