# Generated by Django 5.2.12 on 2026-03-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0139_user_is_staking_opted_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staking_opted_in_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
