# Generated by Django 5.2.13 on 2026-04-10 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0140_user_staking_opted_in_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staking_opted_in",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="staking_opted_in_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
