# Generated by Django 5.2.13 on 2026-04-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0141_auto_opt_in_staking_defaults"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneVerification",
        ),
    ]
