# Generated by Django 5.2.13 on 2026-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0142_delete_phoneverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserApiToken",
        ),
    ]
