# Generated by Django 5.2.14 on 2026-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0146_riskscoreevent_action_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskscore",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="riskscoreevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("WORK_APPROVED", "Work approved"),
                    ("WORK_DECLINED", "Work declined"),
                    ("CONTENT_CENSORED", "Content censored"),
                    ("BOUNTY_AWARDED", "Bounty awarded"),
                    ("PEER_REVIEW_TIPPED", "Peer review tipped"),
                    ("PEER_REVIEW_ASSESSED", "Peer review assessed"),
                    ("EXPERT_FINDER_SIGNUP", "Expert Finder signup"),
                    ("EDU_EMAIL", "Verified edu email"),
                    ("GOOGLE_SIGNUP", "Signed up via Google"),
                    ("ACCOUNT_AGE_BONUS", "Account age bonus"),
                    (
                        "PERSONA_VERIFIED_WHITELISTED",
                        "Persona verified (whitelisted country)",
                    ),
                    (
                        "PERSONA_VERIFIED_NON_WHITELISTED",
                        "Persona verified (non-whitelisted country)",
                    ),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="riskscoreevent",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
