# Generated by Django 5.2.14 on 2026-06-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0147_alter_riskscore_id_alter_riskscoreevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingactivity",
            name="usd_cents",
            field=models.IntegerField(
                db_comment="USD amount in cents for this activity", default=0
            ),
        ),
        migrations.AddField(
            model_name="fundingactivityrecipient",
            name="usd_cents",
            field=models.IntegerField(
                db_comment="USD amount in cents received by this recipient", default=0
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivity",
            name="activity_date",
            field=models.DateTimeField(
                db_comment="When the funding activity occurred", db_index=True
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivity",
            name="funder",
            field=models.ForeignKey(
                db_comment="The user who provided the funding",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivity",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("FUNDRAISE_PAYOUT", "Fundraise Payout"),
                    ("USD_FUNDRAISE_PAYOUT", "USD Fundraise Payout"),
                    ("BOUNTY_PAYOUT", "Bounty Payout"),
                    ("TIP_DOCUMENT", "Document Tip"),
                    ("TIP_REVIEW", "Review Tip"),
                    ("FEE", "Platform Fee"),
                ],
                db_comment="Type of funding activity",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivity",
            name="total_amount",
            field=models.DecimalField(
                db_comment="Total RSC amount for this activity",
                decimal_places=8,
                max_digits=19,
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivityrecipient",
            name="activity",
            field=models.ForeignKey(
                db_comment="The funding activity this recipient belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="user.fundingactivity",
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivityrecipient",
            name="amount",
            field=models.DecimalField(
                db_comment="RSC amount received by this recipient",
                decimal_places=8,
                max_digits=19,
            ),
        ),
        migrations.AlterField(
            model_name="fundingactivityrecipient",
            name="recipient_user",
            field=models.ForeignKey(
                db_comment="The user who received the funding",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
