# Generated by Django 5.2.14 on 2026-06-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0148_fundingactivity_usd_cents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fundingactivity",
            old_name="usd_cents",
            new_name="total_usd_cents",
        ),
        migrations.RenameField(
            model_name="fundingactivityrecipient",
            old_name="usd_cents",
            new_name="amount_usd_cents",
        ),
    ]
