# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0150_author_user_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="authorcontributionsummary",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="AuthorContributionSummary",
        ),
    ]
