# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0151_delete_authorcontributionsummary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coauthor",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="coauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="coauthor",
            name="coauthor",
        ),
        migrations.RemoveField(
            model_name="coauthor",
            name="paper",
        ),
        migrations.DeleteModel(
            name="CoAuthor",
        ),
    ]
