"""Resolver: map an ``Expert`` to an OpenAlex author id.

Resolution ladder, most to least certain -- it stops at the first rung that
produces a match and returns "unresolved" rather than guess:

1. **source-link** -- an OpenAlex author URL or ORCID iD the expert finder
   already cited in ``expert.sources``. An ORCID here is only a lookup key
   into OpenAlex's ``/authors`` endpoint; there is no ORCID API integration.
2. **name+affiliation** -- the affiliation string is resolved to an OpenAlex
   *institution* (OpenAlex's own entity resolution handles abbreviations,
   aliases, and other languages), then the author search is scoped to that
   institution id.
3. **name** -- the strongest name match among the search results, with
   OpenAlex's own relevance/citation ordering breaking ties. v1 takes the top
   candidate rather than disambiguating ambiguous matches.

Note the expert's ``affiliation``/``expertise`` are machine-generated by the
expert finder, not self-reported -- both sides of the match are noisy. Only
candidates clearing ``NAME_SCORE_STRONG`` are ever considered, so even the
take-the-top name rung will miss rather than accept a weak match.
"""

import logging
import re
import unicodedata
from dataclasses import dataclass

from research_ai.services.researcher_external_context import (
    fetch_openalex_author_record,
)
from utils.openalex import OpenAlex

logger = logging.getLogger(__name__)

# Minimum name-match strength for a record to count as a candidate at all.
# Deliberately conservative: a wrong match would attribute someone else's
# track record to the expert. Tunable without code changes.
NAME_SCORE_STRONG = 0.6


def _norm(value: str) -> str:
    """Lowercase, strip accents, collapse to ``[a-z0-9 ]`` tokens."""
    s = unicodedata.normalize("NFKD", str(value or ""))
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = re.sub(r"[^a-z0-9\s]", " ", s.lower())
    return re.sub(r"\s+", " ", s).strip()


@dataclass
class AuthorResolution:
    openalex_author_id: str | None = None
    display_name: str | None = None
    match_score: float = 0.0
    match_method: str = "unresolved"
    candidates_considered: int = 0
    record: dict | None = None  # raw OpenAlex author entity; not serialized
    error: str | None = None

    def as_dict(self) -> dict:
        return {
            "openalex_author_id": self.openalex_author_id,
            "display_name": self.display_name,
            "match_score": round(self.match_score, 3),
            "match_method": self.match_method,
            "candidates_considered": self.candidates_considered,
        }


def _name_score(expert, record: dict) -> float:
    """0..1 confidence the candidate's name matches the expert's."""
    first = _norm(getattr(expert, "first_name", ""))
    # Compound surnames ("van der Berg", "Garcia-Lopez") span several tokens.
    last_tokens = set(_norm(getattr(expert, "last_name", "")).split())
    if not last_tokens:
        return 0.0
    candidates = [record.get("display_name") or ""]
    candidates.extend(record.get("display_name_alternatives") or [])
    best = 0.0
    for cand in candidates:
        toks = _norm(cand).split()
        if not toks or not last_tokens.issubset(toks):
            continue
        if first and first in toks:
            best = max(best, 1.0 if toks[0] == first else 0.85)
        elif first and toks[0][:1] == first[:1]:
            best = max(best, 0.6)
        else:
            best = max(best, 0.3)
    return best


def _name_scored_candidates(expert, records: list[dict]) -> list[tuple[float, dict]]:
    """Candidates with a strong-enough name match, best first."""
    scored = [
        (ns, rec)
        for rec in records
        if (ns := _name_score(expert, rec)) >= NAME_SCORE_STRONG
    ]
    scored.sort(key=lambda t: (t[0], t[1].get("cited_by_count") or 0), reverse=True)
    return scored


def _resolve_institution_id(affiliation: str, *, client: OpenAlex) -> str | None:
    """Resolve the finder-generated affiliation string to an OpenAlex institution.

    Delegates entity resolution (abbreviations, aliases, other languages) to
    OpenAlex's institutions search. Best-effort: returns ``None`` on any miss.
    """
    query = (affiliation or "").strip()
    if not query:
        return None
    try:
        resp = client.search_institutions(query)
        results = (resp or {}).get("results") or []
        for inst in results:
            inst_id = (inst or {}).get("id")
            if inst_id:
                return inst_id
    except Exception as exc:  # noqa: BLE001 - institution scoping is best-effort
        logger.info("OpenAlex institution search failed for %r: %s", query, exc)
    return None


def resolve_openalex_author(
    expert, *, client: OpenAlex | None = None
) -> AuthorResolution:
    """
    Resolve an ``Expert`` to an OpenAlex author record.

    Walks the resolution ladder in the module docstring; every rung prefers
    returning an unresolved result over guessing.
    """
    oa = client or OpenAlex()

    # 1. Explicit id links already cited by the expert finder.
    src_orcid, src_oa = expert.source_ids
    if src_orcid or src_oa:
        record = fetch_openalex_author_record(
            orcid_bare=src_orcid, openalex_author_ref=src_oa, client=oa
        )
        if record:
            return AuthorResolution(
                openalex_author_id=record.get("id")
                or (f"https://openalex.org/{src_oa}" if src_oa else None),
                display_name=record.get("display_name"),
                match_score=1.0,
                match_method="source-link",
                record=record,
            )
        # No OpenAlex record behind the cited id -> fall through to name search.

    name = expert.full_name
    if not name:
        return AuthorResolution(match_method="unresolved")

    # 2. Name search scoped to the OpenAlex-resolved institution.
    institution_id = _resolve_institution_id(
        getattr(expert, "affiliation", ""), client=oa
    )
    if institution_id:
        try:
            resp = oa.search_authors_via_name(name, institution_id=institution_id)
            scored = _name_scored_candidates(expert, resp.get("results") or [])
        except Exception as exc:  # noqa: BLE001 - fall through to unscoped search
            logger.info("Institution-scoped author search failed: %s", exc)
            scored = []
        if scored:
            name_s, record = scored[0]
            return AuthorResolution(
                openalex_author_id=record.get("id"),
                display_name=record.get("display_name"),
                match_score=0.6 * name_s + 0.4,
                match_method="name+affiliation",
                candidates_considered=len(scored),
                record=record,
            )

    # 3. Unscoped name search.
    try:
        resp = oa.search_authors_via_name(name)
    except Exception as exc:  # noqa: BLE001 - network/parse errors are non-fatal
        logger.info("OpenAlex author search failed for %r: %s", name, exc)
        return AuthorResolution(match_method="unresolved", error=str(exc))
    candidates = resp.get("results") or []
    scored = _name_scored_candidates(expert, candidates)
    if not scored:
        return AuthorResolution(
            match_method="unresolved", candidates_considered=len(candidates)
        )

    # Take the strongest name match; OpenAlex's relevance/citation ordering
    # (folded into the candidate sort) breaks ties. v1 does not adjudicate
    # ambiguity -- a single exact match scores 1.0, weaker ones score lower.
    name_s, record = scored[0]
    return AuthorResolution(
        openalex_author_id=record.get("id"),
        display_name=record.get("display_name"),
        match_score=name_s,
        match_method="name",
        candidates_considered=len(candidates),
        record=record,
    )
