CLIENT_PERMISSIONS = "CLIENT_PERMISSIONS"
EDITOR_PAYOUT_ADMIN = "EDITOR_PAYOUT_ADMIN"
ELN = "ELN"
PAYOUT_EXCLUSION_LIST = "PAYOUT_EXCLUSION"
PERMISSIONS_DASH = "PERMISSIONS_DASH"

GATE_KEEPER_TYPES = (
    (EDITOR_PAYOUT_ADMIN, EDITOR_PAYOUT_ADMIN),
    (ELN, ELN),
    (CLIENT_PERMISSIONS, CLIENT_PERMISSIONS),
    (PAYOUT_EXCLUSION_LIST, PAYOUT_EXCLUSION_LIST),
    (PERMISSIONS_DASH, PERMISSIONS_DASH),
)
