# Generated by Django 2.2.6 on 2019-10-24 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0002_hub_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_hubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
