# Generated by Django 2.2.6 on 2019-10-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_hub_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
