# Generated by Django 2.2.6 on 2019-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20191101_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
