# Generated by Django 2.2.9 on 2020-01-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_hub_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
