# Generated by Django 2.2.11 on 2020-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20200117_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='slug_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
