# Generated by Django 2.2.16 on 2020-09-12 03:50

from django.db import migrations, models
import django.db.models.deletion
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20200318_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hub',
            name='hub_image',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to='uploads/hub_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='hub',
            name='category',
            field=models.ForeignKey(default=hub.models.get_default_hub_category, on_delete=django.db.models.deletion.CASCADE, to='hub.HubCategory'),
        ),
    ]
