# Generated by Django 2.2.16 on 2020-09-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_auto_20200912_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='discussion_count',
            field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name='hub',
            name='paper_count',
            field=models.IntegerField(default=0),
        ),
    ]
