# Generated by Django 2.2.16 on 2020-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20200925_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='subscriber_count',
            field=models.IntegerField(default=0),
        ),
    ]
