# Generated by Django 2.2 on 2020-11-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_hub_subscriber_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Hides the hub because it is not allowed.'),
        ),
    ]
