# Generated by Django 2.2 on 2021-02-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_auto_20210211_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='subscribers',
        ),
    ]
