# Generated by Django 2.2 on 2021-02-11 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0017_remove_hub_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_hubs', through='hub.HubMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
