# Generated by Django 2.2 on 2021-02-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_hub_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubmembership',
            name='created_at',
        ),
    ]
