# Generated by Django 4.1 on 2023-07-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_remove_hubmembership_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubProvider",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("is_user", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="HubV2",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HubMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_data", models.JSONField()),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.hubv2"
                    ),
                ),
                (
                    "hub_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hub.hubprovider",
                    ),
                ),
            ],
        ),
    ]
