# Generated by Django 4.2.13 on 2024-06-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0006_alter_topic_keywords"),
        ("hub", "0022_alter_hub_concept"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="subfield",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hub",
                to="topic.subfield",
            ),
        ),
    ]
