# Generated by Django 4.2.13 on 2024-06-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0023_hub_subfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="is_used_for_rep",
            field=models.BooleanField(default=False),
        ),
    ]
