# Generated by Django 4.2.15 on 2024-09-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0024_hub_is_used_for_rep"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="namespace",
            field=models.TextField(choices=[("journal", "Journal")], null=True),
        ),
    ]
