# Generated by Django 4.2.15 on 2024-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0025_hub_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="namespace",
            field=models.TextField(choices=[("journal", "journal")], null=True),
        ),
    ]
