# Generated by Django 4.2.15 on 2024-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0025_hub_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AddConstraint(
            model_name="hub",
            constraint=models.UniqueConstraint(
                fields=("name", "namespace"), name="unique_name_namespace"
            ),
        ),
    ]
