# Generated by Django 4.2.15 on 2024-10-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0026_alter_hub_name_hub_unique_name_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="namespace",
            field=models.TextField(
                choices=[("journal", "Journal")], default=None, null=True
            ),
        ),
    ]
