# Generated by Django 4.2.16 on 2024-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0027_alter_hub_namespace"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hub",
            index=models.Index(
                models.Func("name", function="UPPER"), name="hub_hub_name_upper_idx"
            ),
        ),
    ]
