# Generated by Django 4.2.15 on 2024-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="namespace",
            field=models.TextField(
                choices=[
                    ("journal", "Journal"),
                    ("subcategory", "Subcategory"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
