# Generated by Django 5.2.2 on 2025-10-03 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
        ("tag", "0004_remove_concept_hub"),
        ("topic", "0008_alter_unifieddocumenttopics_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hub",
            constraint=models.UniqueConstraint(
                models.Func("name", function="UPPER"),
                models.F("namespace"),
                name="unique_name_namespace_case_insensitive",
            ),
        ),
    ]
