# Generated by Django 5.2.2 on 2025-10-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0029_hub_unique_name_namespace_case_insensitive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hub",
            name="unique_name_namespace",
        ),
    ]
