# Generated by Django 5.2.7 on 2025-10-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0030_remove_hub_unique_name_namespace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hub",
            name="category",
        ),
        migrations.DeleteModel(
            name="HubCategory",
        ),
    ]
