# Generated by Django 5.2.7 on 2025-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0031_remove_hub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="namespace",
            field=models.TextField(
                choices=[
                    ("journal", "Journal"),
                    ("category", "Category"),
                    ("subcategory", "Subcategory"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
