# Generated by Django 5.2.17 on 2026-08-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0032_alter_hub_namespace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hub",
            name="is_used_for_rep",
        ),
    ]
