# Generated by Django 5.2.17 on 2026-08-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0033_remove_hub_is_used_for_rep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hub",
            name="concept",
        ),
    ]
