ADMIN_PASS = "PLACEHOLDER"
SECRET_KEY = "PLACEHOLDER"
RH_API_KEY = "PLACEHOLDER"

AWS_REGION_NAME = "PLACEHOLDER"
AWS_SES_REGION_ENDPOINT = "PLACEHOLDER"
AWS_STORAGE_BUCKET_NAME = "PLACEHOLDER"
AWS_PROFILE = ""
AWS_S3_CUSTOM_DOMAIN = ""

EMAIL_WHITELIST = "PLACEHOLDER"

GHOSTSCRIPT_LAMBDA_ARN = "PLACEHOLDER"

ORCID_CLIENT_ID = "PLACEHOLDER"
ORCID_CLIENT_SECRET = "PLACEHOLDER"
ORCID_ACCESS_TOKEN = "PLACEHOLDER"
ORCID_REDIRECT_URL = "PLACEHOLDER"

OSF_TOKEN = "PLACEHOLDER"

MAILCHIMP_KEY = "PLACEHOLDER"
MAILCHIMP_LIST_ID = "PLACEHOLDER"

RECAPTCHA_SECRET_KEY = "PLACEHOLDER"


AMPLITUDE_API_KEY = "PLACEHOLDER"

STRIPE_API_KEY = "PLACEHOLDER"
STRIPE_SECRET_KEY = "PLACEHOLDER"
STRIPE_WEBHOOK_SIGNING_SECRET = "PLACEHOLDER"

SENTRY_DSN = "PLACEHOLDER"

APM_URL = "PLACEHOLDER"

OPENSEARCH_HOST = ""

# Development only

# Development only
CKEDITOR_CLOUD_ACCESS_KEY = (
    "RUcoP7fKjMbJTbFV2CskLMjzg1OXIx13cY3yAqyWeoeskzczY3PILTGVmkEL"
)
CKEDITOR_CLOUD_ENVIRONMENT_ID = "5hIaZQMIBYp8SnodwKdm"

MORALIS_API_KEY = "PLACEHOLDER"

WEB3_RSC_ADDRESS = ""
WEB3_BASE_RSC_ADDRESS = ""
WEB3_PROVIDER_URL = ""
WEB3_BASE_PROVIDER_URL = ""
WEB3_KEYSTORE_BUCKET = ""
WEB3_KEYSTORE_FILE = ""
WEB3_KEYSTORE_PASSWORD = ""
WEB3_WALLET_ADDRESS = ""
WEB3_NETWORK = ""
WEB3_KEYSTORE_SECRET_ID = ""
WEB3_KEYSTORE_PASSWORD_SECRET_ID = ""
CROSSREF_LOGIN_ID = ""
CROSSREF_LOGIN_PASSWORD = ""

MJML_APP_ID = ""
MJML_SECRET_KEY = ""

TRANSPOSE_KEY = ""
OPENALEX_KEY = ""

# USE_DEBUG_TOOLBAR = True

SEGMENT_WRITE_KEY = ""

ETHERSCAN_API_KEY = ""
BASESCAN_API_KEY = ""
COIN_GECKO_API_KEY = ""

PERSONA_WEBHOOK_SECRET = ""

HEALTH_CHECK_TOKEN = "PLACEHOLDER"

ENDAOMENT_ACCOUNT_ID = ""
RESEARCHHUB_JOURNAL_ID = ""
