ADMIN_PASS = "PLACEHOLDER"
SECRET_KEY = "PLACEHOLDER"
RH_API_KEY = "PLACEHOLDER"

AWS_ACCESS_KEY_ID = "PLACEHOLDER"
AWS_SECRET_ACCESS_KEY = "PLACEHOLDER"

INFURA_PROJECT_ID = "PLACEHOLDER"
INFURA_PROJECT_SECRET = "PLACEHOLDER"
INFURA_RINKEBY_ENDPOINT = f"https://rinkeby.infura.io/v3/{INFURA_PROJECT_ID}"

ORCID_CLIENT_ID = "PLACEHOLDER"
ORCID_CLIENT_SECRET = "PLACEHOLDER"
ORCID_ACCESS_TOKEN = "PLACEHOLDER"

OSF_TOKEN = "PLACEHOLDER"

MAILCHIMP_KEY = "PLACEHOLDER"
MAILCHIMP_LIST_ID = "PLACEHOLDER"

RECAPTCHA_SECRET_KEY = "PLACEHOLDER"

SIFT_ACCOUNT_ID = "PLACEHOLDER"
SIFT_REST_API_KEY = "PLACEHOLDER"

AMPLITUDE_API_KEY = "PLACEHOLDER"

STRIPE_API_KEY = "PLACEHOLDER"

SENTRY_DSN = "PLACEHOLDER"

APM_URL = "PLACEHOLDER"

ELASTICSEARCH_HOST = ""
LAMBDA_API_KEY = ""
# Development only
CERMINE_FUNCTION_ARN = (
    "arn:aws:lambda:us-west-2:794128250202:function:ResearchHub-Backend-Staging"
)
SIFT_WEBHOOK_SECRET_KEY = "PLACEHOLDER"

# Development only
CKEDITOR_CLOUD_ACCESS_KEY = (
    "RUcoP7fKjMbJTbFV2CskLMjzg1OXIx13cY3yAqyWeoeskzczY3PILTGVmkEL"
)
CKEDITOR_CLOUD_ENVIRONMENT_ID = "5hIaZQMIBYp8SnodwKdm"

MORALIS_API_KEY = "PLACEHOLDER"

ASYNC_SERVICE_API_KEY = ""

WEB3_RSC_ADDRESS = "0x82620900630a2Ab6a319791140891110B4cAA033"
PROVIDER_URL = ""
WEB3_KEYSTORE_BUCKET = ""
WEB3_KEYSTORE_FILE = ""
WEB3_KEYSTORE_PASSWORD = ""
WEB3_KEYSTORE_ADDRESS = ""
CROSSREF_LOGIN_ID = ""
CROSSREF_LOGIN_PASSWORD = ""
# USE_DEBUG_TOOLBAR = True
