TWITER_ACCESS_TOKEN="PLACEHOLDER"
TWITER_ACCESS_TOKEN_ALT="PLACEHOLDER"

TWITTER_ACCESS_TOKEN_SECRET="PLACEHOLDER"
TWITTER_ACCESS_TOKEN_SECRET_ALT="PLACEHOLDER"

TWITTER_CONSUMER_KEY="PLACEHOLDER"
TWITTER_CONSUMER_KEY_ALT="PLACEHOLDER"

TWITTER_CONSUMER_SECRET="PLACEHOLDER"
TWITTER_CONSUMER_SECRET_ALT="PLACEHOLDER"

