# Generated by Django 2.2 on 2021-06-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0078_merge_20210311_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchhubUnifiedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public posts are visible in home feed')),
                ('document_type', models.CharField(choices=[('PAPER', 'PAPER'), ('POST', 'POST')], default='PAPER', help_text='Papers are imported from external src. Posts are in-house', max_length=32)),
                ('hot_score', models.IntegerField(db_index=True, default=0, help_text='Feed ranking score')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unified_document', to='paper.Paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchhubPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('ELN', 'ELN')], default='DISCUSSION', max_length=32)),
                ('version_number', models.IntegerField(default=1)),
                ('prev_version', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='researchhub_document.ResearchhubPost')),
                ('unified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
        ),
    ]
