# Generated by Django 2.2 on 2021-06-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0001_initial'),
        ('researchhub_document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchhubunifieddocument',
            name='is_public',
        ),
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='access_group',
            field=models.OneToOneField(blank=True, help_text='Mostly used for ELN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='researchhub_access_group.ResearchhubAccessGroup'),
        ),
        migrations.AlterField(
            model_name='researchhubpost',
            name='post_type',
            field=models.CharField(choices=[('PAPER', 'PAPER'), ('DISCUSSION', 'DISCUSSION'), ('ELN', 'ELN')], default='DISCUSSION', max_length=32),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='document_type',
            field=models.CharField(choices=[('PAPER', 'PAPER'), ('DISCUSSION', 'DISCUSSION'), ('ELN', 'ELN')], default='PAPER', help_text='Papers are imported from external src. Posts are in-house', max_length=32),
        ),
    ]
