# Generated by Django 2.2 on 2021-06-04 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchhub_document', '0006_researchhubpost_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchhubunifieddocument',
            name='created_by',
        ),
        migrations.AddField(
            model_name='researchhubpost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
