# Generated by Django 2.2 on 2021-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0008_auto_20210604_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubpost',
            name='preview_img',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
