# Generated by Django 2.2 on 2021-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0010_remove_researchhubpost_hubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='hot_score',
            field=models.IntegerField(db_index=True, default=0, help_text='Feed ranking score.'),
        ),
    ]
