# Generated by Django 2.2 on 2021-06-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0014_researchhubpost_discussion_count'),
        ('researchhub_document', '0015_auto_20210616_1806'),
    ]

    operations = [
    ]
