# Generated by Django 2.2 on 2021-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0016_merge_20210616_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False, help_text='Unified Document is removed (deleted)'),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='hot_score',
            field=models.IntegerField(default=0, help_text='Feed ranking score.'),
        ),
    ]
