# Generated by Django 2.2 on 2021-06-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0018_researchhubunifieddocument_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
