# Generated by Django 2.2 on 2021-07-01 19:09

from django.db import migrations, models
from django.utils.text import slugify
from django.utils.crypto import get_random_string


def add_post_slugs(apps, schema_editor):
    Posts = apps.get_model('researchhub_document', 'researchhubpost')
    posts = Posts.objects.filter(slug='RH_PLACEHOLDER_SLUG')

    for post in posts.iterator():
        suffix = get_random_string(length=32)
        slug = slugify(post.title)
        if not slug:
            slug += suffix
        post.slug = slug
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0019_auto_20210617_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubpost',
            name='slug',
            field=models.SlugField(default='RH_PLACEHOLDER_SLUG', max_length=1024),
            preserve_default=False,
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(add_post_slugs),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
