# Generated by Django 2.2 on 2021-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0004_auto_20211005_0004'),
        ('researchhub_document', '0022_auto_20210824_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchhubunifieddocument',
            name='access_group',
        ),
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='access_group',
            field=models.ManyToManyField(help_text='Mostly used for ELN', related_name='document', to='researchhub_access_group.ResearchhubAccessGroup'),
        ),
    ]
