# Generated by Django 2.2 on 2021-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0023_auto_20211005_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchhubunifieddocument',
            old_name='access_group',
            new_name='access_groups',
        ),
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Unified document is public'),
        ),
    ]
