# Generated by Django 2.2 on 2021-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0006_remove_permission_access_group'),
        ('researchhub_document', '0024_auto_20211006_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchhubunifieddocument',
            name='access_groups',
        ),
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='permissions',
            field=models.ManyToManyField(help_text='Mostly used for ELN', related_name='document', to='researchhub_access_group.Permission'),
        ),
    ]
