# Generated by Django 2.2 on 2022-01-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0026_remove_researchhubunifieddocument_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RscExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField(help_text='\n            RSC to target currency rate.\n            For example, rate of 3 to USD represents 3 dollars per RSC.\n            This is may not reflect the marget fully for internal purposes.\n            We may adjust the rate for different purposes.\n        ')),
                ('target_currency', models.CharField(choices=[('USD', 'USD'), ('ETHER', 'ETHER')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
