# Generated by Django 2.2 on 2022-01-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20211022_0126'),
        ('researchhub_document', '0026_remove_researchhubunifieddocument_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubpost',
            name='authors',
            field=models.ManyToManyField(related_name='authored_posts', to='user.Author'),
        ),
    ]
