# Generated by Django 2.2 on 2022-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0028_auto_20220129_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rscexchangerate',
            name='rate',
            field=models.FloatField(help_text='\n            RSC to target currency rate.\n            For example, rate of 3 to USD represents 3 dollars per RSC.\n            This is may not reflect the market fully for internal purposes.\n            We may adjust the rate for different purposes.\n        '),
        ),
    ]
