# Generated by Django 2.2 on 2022-02-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0028_researchhubpost_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='hot_score_v2',
            field=models.IntegerField(default=0, help_text='Feed ranking score.'),
        ),
    ]
