# Generated by Django 2.2 on 2022-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0029_researchhubunifieddocument_hot_score_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubpost',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
