# Generated by Django 2.2 on 2022-05-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0030_researchhubpost_doi'),
        ('paper', '0097_paper_uni_doc')
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchhubunifieddocument',
            name='paper',
        ),
    ]
