# Generated by Django 2.2 on 2022-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0031_remove_researchhubunifieddocument_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhubpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
