# Generated by Django 2.2 on 2022-05-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0031_remove_researchhubunifieddocument_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hub_id', models.IntegerField(db_index=True, default=False)),
                ('unified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_from_feeds', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
