# Generated by Django 2.2 on 2022-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0032_auto_20220510_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='researchhubpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
