# Generated by Django 2.2 on 2022-05-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0033_auto_20220512_2017'),
        ('researchhub_document', '0033_auto_20220512_1957'),
    ]

    operations = [
    ]
