# Generated by Django 2.2 on 2022-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0034_merge_20220526_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedexclusion',
            name='hub_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
