# Generated by Django 2.2 on 2022-06-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0035_auto_20220526_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hub_id', models.IntegerField(db_index=True)),
                ('unified_document', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='featured_in_hubs', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
