# Generated by Django 2.2 on 2022-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0038_auto_20220610_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='hot_score_v2',
            field=models.IntegerField(db_index=True, default=0, help_text='Feed ranking score.'),
        ),
    ]
