# Generated by Django 2.2 on 2022-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0039_auto_20220616_1910'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='researchhubunifieddocument',
            index=models.Index(fields=['created_date'], name='uni_doc_created_date_idx'),
        ),
    ]
