# Generated by Django 2.2 on 2022-06-17 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0040_auto_20220617_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcontent',
            name='unified_document',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='featured_in_hubs', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
