# Generated by Django 2.2 on 2022-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0040_auto_20220617_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubpost',
            name='document_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('ELN', 'ELN'), ('HYPOTHESIS', 'HYPOTHESIS'), ('NOTE', 'NOTE'), ('PAPER', 'PAPER'), ('QUESTION', 'QUESTION')], default='DISCUSSION', max_length=32),
        ),
        migrations.AlterField(
            model_name='researchhubunifieddocument',
            name='document_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('ELN', 'ELN'), ('HYPOTHESIS', 'HYPOTHESIS'), ('NOTE', 'NOTE'), ('PAPER', 'PAPER'), ('QUESTION', 'QUESTION')], default='PAPER', help_text='Papers are imported from external src. Posts are in-house', max_length=32),
        ),
    ]
