# Generated by Django 2.2 on 2022-08-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0041_auto_20220705_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('answered', models.BooleanField(db_index=True, default=False)),
                ('author_claimed', models.BooleanField(db_index=True, default=False)),
                ('bounty_closed', models.BooleanField(db_index=True, default=False)),
                ('bounty_expired', models.BooleanField(db_index=True, default=False)),
                ('bounty_open', models.BooleanField(db_index=True, default=False)),
                ('has_bounty', models.BooleanField(db_index=True, default=False)),
                ('open_access', models.BooleanField(db_index=True, default=False)),
                ('peer_reviewed', models.BooleanField(db_index=True, default=False)),
                ('bounty_expiration_date', models.DateTimeField(null=True)),
                ('bounty_total_amount', models.DecimalField(null=True, db_index=True, decimal_places=10, max_digits=19)),
                ('discussed_today', models.IntegerField(db_index=True, default=0)),
                ('discussed_week', models.IntegerField(db_index=True, default=0)),
                ('discussed_month', models.IntegerField(db_index=True, default=0)),
                ('discussed_year', models.IntegerField(db_index=True, default=0)),
                ('discussed_all', models.IntegerField(db_index=True, default=0)),
                ('discussed_date', models.DateTimeField(auto_now_add=True)),
                ('upvoted_today', models.IntegerField(db_index=True, default=0)),
                ('upvoted_week', models.IntegerField(db_index=True, default=0)),
                ('upvoted_month', models.IntegerField(db_index=True, default=0)),
                ('upvoted_year', models.IntegerField(db_index=True, default=0)),
                ('upvoted_all', models.IntegerField(db_index=True, default=0)),
                ('upvoted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(fields=['created_date'], name='flt_created_date_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(fields=['bounty_expiration_date'], name='flt_bounty_expiration_date_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(fields=['discussed_date'], name='flt_discussed_date_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(fields=['upvoted_date'], name='flt_upvoted_date_idx'),
        ),
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='document_filter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_document', to='researchhub_document.DocumentFilter'),
        ),
    ]
