# Generated by Django 2.2 on 2022-09-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0042_auto_20220830_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfilter',
            name='discussed_date_ts',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
