# Generated by Django 2.2 on 2022-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('researchhub_document', '0043_auto_20220905_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubunifieddocument',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='tag.Concept'),
        ),
    ]
