# Generated by Django 2.2 on 2022-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0043_documentfilter_discussed_date_ts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date__lte='2019-01-01'), fields=['discussed_date'], name='flt_discussed_date_2019'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date__lte='2020-01-01'), fields=['discussed_date'], name='flt_discussed_date_2020'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date__lte='2021-01-01'), fields=['discussed_date'], name='flt_discussed_date_2021'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date__lte='2022-01-01'), fields=['discussed_date'], name='flt_discussed_date_2022'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date__lte='2023-01-01'), fields=['discussed_date'], name='flt_discussed_date_2023'),
        ),
    ]
