# Generated by Django 2.2 on 2022-10-12 00:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0044_researchhubunifieddocument_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfilter',
            name='hubs_excluded',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
