# Generated by Django 2.2 on 2022-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0044_auto_20220903_1007'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date_ts__lte=1546300800.0), fields=['discussed_date'], name='flt_discussed_date_ts_2019'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date_ts__lte=1577836800.0), fields=['discussed_date'], name='flt_discussed_date_ts_2020'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date_ts__lte=1609459200.0), fields=['discussed_date'], name='flt_discussed_date_ts_2021'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date_ts__lte=1640995200.0), fields=['discussed_date'], name='flt_discussed_date_ts_2022'),
        ),
        migrations.AddIndex(
            model_name='documentfilter',
            index=models.Index(condition=models.Q(discussed_date_ts__lte=1672531200.0), fields=['discussed_date'], name='flt_discussed_date_ts_2023'),
        ),
    ]
