# Generated by Django 2.2 on 2022-10-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0046_auto_20221012_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedExclusion',
        ),
    ]
