# Generated by Django 2.2 on 2022-10-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0047_delete_feedexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhubpost',
            name='bounty_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
