# Generated by Django 2.2 on 2022-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0048_researchhubpost_bounty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubpost',
            name='editor_type',
            field=models.CharField(choices=[('CK_EDITOR', 'CK_EDITOR'), ('DRAFT_JS', 'DRAFT_JS'), ('TEXT_FIOELD', 'TEXT_FIOELD')], default='CK_EDITOR', help_text='Editor used to compose the post', max_length=32),
        ),
    ]
