# Generated by Django 2.2 on 2022-11-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0049_auto_20221111_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubpost',
            name='editor_type',
            field=models.CharField(choices=[('CK_EDITOR', 'CK_EDITOR'), ('DRAFT_JS', 'DRAFT_JS'), ('TEXT_FIELD', 'TEXT_FIELD')], default='CK_EDITOR', help_text='Editor used to compose the post', max_length=32),
        ),
    ]
