# Generated by Django 4.1 on 2023-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0050_auto_20221116_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfilter",
            name="has_hubs",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
