# Generated by Django 4.1 on 2023-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0051_researchhubunifieddocument_is_removed_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="researchhubpost",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
