# Generated by Django 4.1 on 2023-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0003_concept_hub"),
        (
            "researchhub_document",
            "0053_remove_researchhubunifieddocument_concepts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="researchhubunifieddocument",
            name="concepts",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                through="researchhub_document.UnifiedDocumentConcepts",
                to="tag.concept",
            ),
        ),
    ]
