# Generated by Django 4.1 on 2023-09-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_unique_concept_openalex_id"),
        ("researchhub_document", "0053_remove_researchhubunifieddocument_concepts"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedDocumentConcept",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("relevancy_score", models.IntegerField(default=0)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept",
                        to="tag.concept",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="researchhubunifieddocument",
            name="concepts",
            field=models.ManyToManyField(
                related_name="documents",
                to="researchhub_document.unifieddocumentconcept",
            ),
        ),
    ]
