# Generated by Django 4.1 on 2023-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0054_unifieddocumentconcept_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifieddocumentconcept",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="unifieddocumentconcept",
            name="relevancy_score",
            field=models.FloatField(default=0.0),
        ),
    ]
