# Generated by Django 4.1 on 2023-11-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0004_remove_concept_hub"),
        (
            "researchhub_document",
            "0055_rename_is_excluded_documentfilter_is_excluded_in_feed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="unifieddocumentconcepts",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="through_unified_document",
                to="tag.concept",
            ),
        ),
    ]
