# Generated by Django 4.2.15 on 2024-08-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0058_researchhubunifieddocument_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchhubpost",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DISCUSSION", "DISCUSSION"),
                    ("ELN", "ELN"),
                    ("NOTE", "NOTE"),
                    ("PAPER", "PAPER"),
                    ("QUESTION", "QUESTION"),
                    ("PREREGISTRATION", "PREREGISTRATION"),
                ],
                default="DISCUSSION",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="researchhubunifieddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DISCUSSION", "DISCUSSION"),
                    ("ELN", "ELN"),
                    ("NOTE", "NOTE"),
                    ("PAPER", "PAPER"),
                    ("QUESTION", "QUESTION"),
                    ("PREREGISTRATION", "PREREGISTRATION"),
                ],
                default="PAPER",
                help_text="Papers are imported from external src. Posts are in-house",
                max_length=32,
            ),
        ),
    ]
