# Generated by Django 4.2.15 on 2024-10-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0026_alter_hub_name_hub_unique_name_namespace"),
        ("researchhub_document", "0059_alter_researchhubpost_document_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchhubUnifiedDocumentHub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["hot_score_v2"], name="idx_unified_doc_hot_score_v2"
            ),
        ),
        migrations.AddField(
            model_name="researchhubunifieddocumenthub",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hub.hub"
            ),
        ),
        migrations.AddField(
            model_name="researchhubunifieddocumenthub",
            name="researchhubunifieddocument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocumenthub",
            index=models.Index(
                fields=["hub", "researchhubunifieddocument"], name="idx_hub_unified_doc"
            ),
        ),
    ]
