# Generated by Django 4.2.15 on 2024-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0060_researchhubunifieddocumenthub_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["is_removed", "document_type", "hot_score_v2"],
                name="idx_document_type_hot_score",
            ),
        ),
    ]
