# Generated by Django 4.2.15 on 2024-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0026_alter_hub_name_hub_unique_name_namespace"),
        (
            "researchhub_document",
            "0061_researchhubunifieddocument_idx_document_type_hot_score",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="researchhubunifieddocumenthub",
            unique_together={("researchhubunifieddocument", "hub")},
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(fields=["document_type"], name="idx_document_type"),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocumenthub",
            index=models.Index(
                fields=["researchhubunifieddocument", "hub"], name="idx_unified_doc_hub"
            ),
        ),
    ]
