# Generated by Django 4.2.15 on 2024-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0063_documentfilter_idx_excluded_in_feed_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["document_type", "-hot_score_v2"], name="doc_type_hot_score_idx"
            ),
        ),
    ]
