# Generated by Django 5.1.5 on 2025-02-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0064_researchhubunifieddocument_doc_type_hot_score_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchhubunifieddocument",
            name="hot_score",
        ),
    ]
