# Generated by Django 5.1.5 on 2025-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
        ("researchhub_document", "0065_remove_researchhubunifieddocument_hot_score"),
        ("tag", "0004_remove_concept_hub"),
        ("topic", "0008_alter_unifieddocumenttopics_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_unified_doc_hot_score_v2",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_document_type_hot_score",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_paper_filter_sort",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="doc_type_hot_score_idx",
        ),
        migrations.RenameField(
            model_name="researchhubunifieddocument",
            old_name="hot_score_v2",
            new_name="hot_score",
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["document_type", "-hot_score"], name="doc_type_hot_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                condition=models.Q(("document_type", "PAPER")),
                fields=["is_removed", "document_type", "hot_score", "document_filter"],
                name="idx_paper_filter_sort",
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(fields=["hot_score"], name="idx_unified_doc_hot_score"),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["is_removed", "document_type", "hot_score"],
                name="idx_document_type_hot_score",
            ),
        ),
    ]
