# Generated by Django 5.1.5 on 2025-03-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0066_remove_researchhubunifieddocument_idx_unified_doc_hot_score_v2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchhubpost",
            name="unified_document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
    ]
