# Generated by Django 5.1.5 on 2025-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0066_remove_researchhubunifieddocument_idx_unified_doc_hot_score_v2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="researchhubpost",
            name="image",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
