# Generated by Django 5.2.14 on 2026-06-02 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0032_alter_hub_namespace"),
        ("note", "0008_add_document_type_to_note"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("tag", "0004_remove_concept_hub"),
        ("topic", "0008_alter_unifieddocumenttopics_unique_together"),
        ("user", "0147_alter_riskscore_id_alter_riskscoreevent_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="researchhubpost",
            index=models.Index(
                fields=["document_type", "-created_date"],
                name="post_doc_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubpost",
            index=models.Index(
                fields=["document_type", "created_by_id"],
                name="post_doc_type_created_by_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["is_removed", "is_public"], name="ud_removed_public_idx"
            ),
        ),
    ]
