# Generated by Django 5.2.14 on 2026-06-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentfilter",
            name="author_claimed",
        ),
    ]
