# Generated by Django 5.2 on 2026-05-28 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0069_remove_documentfilter_author_claimed"),
        ("user", "0145_riskscore_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="researchhubpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="APPROVED",
                help_text="Moderation status used to gate public visibility.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="researchhubpost",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who approved or declined this work",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="reviewed_researchhubposts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchhubpost",
            name="reviewed_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was approved or declined",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="researchhubpost",
            index=models.Index(
                fields=["status"], name="researchhub_post_status_idx"
            ),
        ),
    ]
