# Generated by Django 5.2.14 on 2026-06-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0069_researchhubpost_post_doc_type_created_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="researchhubpost",
            name="post_doc_type_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="researchhubpost",
            name="post_doc_type_created_by_idx",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="ud_removed_public_idx",
        ),
    ]
