# Generated by Django 5.2.14 on 2026-06-25 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0074_researchhubpost_journey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchhubunifieddocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who approved or declined this work",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
