# Generated by Django 5.2.15 on 2026-07-20 09:16

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("researchhub_document", "0075_alter_researchhubunifieddocument_reviewed_by"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="researchhubunifieddocument",
            index=models.Index(
                fields=["is_removed", "document_type"], name="idx_is_removed_doc_type"
            ),
        ),
    ]
