# Generated by Django 5.2.15 on 2026-07-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0076_add_idx_is_removed_doc_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="doc_type_hot_score_idx",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_paper_filter_sort",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_unified_doc_hot_score",
        ),
        migrations.RemoveIndex(
            model_name="researchhubunifieddocument",
            name="idx_document_type_hot_score",
        ),
        migrations.RemoveField(
            model_name="researchhubunifieddocument",
            name="hot_score",
        ),
    ]
