# Generated by Django 5.2.16 on 2026-08-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0079_alter_researchhubpost_preview_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchhubpost",
            name="eln_src",
        ),
    ]
