# Generated by Django 5.2.16 on 2026-08-11 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0079_alter_researchhubpost_preview_img"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedDocumentShareLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Who last generated the link. Audit only, grants no privileges.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unified_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_link",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
