# Generated by Django 5.2.17 on 2026-08-21 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researchhub_document", "0082_researchhubpostauthor_ordering"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchhubunifieddocument",
            name="concepts",
        ),
        migrations.DeleteModel(
            name="UnifiedDocumentConcepts",
        ),
    ]
