# Generated by Django 2.2.10 on 2020-03-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='base',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_base_of', to='bullet_point.BulletPoint'),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='is_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='is_top',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='next',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='bullet_point.BulletPoint'),
        ),
    ]
