# Generated by Django 2.2.10 on 2020-03-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0002_auto_20200311_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='is_top',
            new_name='is_head',
        ),
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='is_base',
            new_name='is_tail',
        ),
        migrations.RemoveField(
            model_name='bulletpoint',
            name='base',
        ),
        migrations.RemoveField(
            model_name='bulletpoint',
            name='next',
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='previous',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='bullet_point.BulletPoint'),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='tail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_tail_for', to='bullet_point.BulletPoint'),
        ),
    ]
