# Generated by Django 2.2.12 on 2020-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0003_auto_20200311_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='bullet_type',
            field=models.CharField(choices=[('KEY_TAKEAWAY', 'KEY_TAKEAWAY'), ('LIMITATION', 'LIMITATION')], default='KEY_TAKEAWAY', max_length=16),
            preserve_default=False,
        ),
    ]
