# Generated by Django 2.2.12 on 2020-05-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0004_bulletpoint_bullet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='created_location',
            field=models.CharField(blank=True, choices=[('PROGRESS', 'PROGRESS')], default=None, max_length=255, null=True),
        ),
    ]
