# Generated by Django 2.2 on 2020-11-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0005_bulletpoint_created_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='sift_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
