# Generated by Django 2.2 on 2020-11-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullet_point', '0007_auto_20201116_2230'),
        ('bullet_point', '0007_remove_bulletpoint_sift_risk_score'),
    ]

    operations = [
    ]
