# Generated by Django 4.2.14 on 2024-08-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bullet_point", "0009_alter_bulletpoint_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endorsement",
            name="bullet_point",
        ),
        migrations.RemoveField(
            model_name="endorsement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="flag",
            name="bullet_point",
        ),
        migrations.RemoveField(
            model_name="flag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="bulletpoint",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="BulletPoint",
        ),
        migrations.DeleteModel(
            name="Endorsement",
        ),
        migrations.DeleteModel(
            name="Flag",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
