branch-defaults:
  case/3:
    environment: production-worker-twitter
environment-defaults:
  production-worker-twitter:
    branch: null
    repository: null
global:
  application_name: researchhub-backend
  default_ec2_keyname: researchhub-q5
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
