# Generated by Django 2.2 on 2021-05-05 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorClaimCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('AUTHOR_CLAIM', 'AUTHOR_CLAIM')], max_length=32)),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('DENIED', 'DENIED'), ('NULLIFIED', 'NULLIFIED'), ('OPEN', 'OPEN')], default='OPEN', max_length=32)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case_creator', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_moderator', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case_requestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
