# Generated by Django 2.2 on 2021-05-11 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20210326_0027'),
        ('researchhub_case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorclaimcase',
            name='target_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='claim_case', to='user.Author'),
        ),
        migrations.AddField(
            model_name='authorclaimcase',
            name='validation_attempt_count',
            field=models.IntegerField(default=-1, help_text='Number of attempts to validate themselves given token'),
        ),
        migrations.AddField(
            model_name='authorclaimcase',
            name='validation_token',
            field=models.CharField(blank=True, help_text="Used to authenticate User's identity. See post_save signal", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_case', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderating_case', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='requestor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requested_case', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'CLOSED'), ('DENIED', 'DENIED'), ('NULLIFIED', 'NULLIFIED'), ('NULLIFIED', 'NULLIFIED')], default='NULLIFIED', max_length=32),
        ),
    ]
