# Generated by Django 2.2 on 2021-05-12 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0002_auto_20210511_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderating_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='requestor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requested_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'CLOSED'), ('DENIED', 'DENIED'), ('INITIATED', 'INITIATED'), ('NULLIFIED', 'NULLIFIED'), ('OPEN', 'OPEN')], default='INITIATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='target_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_claim_cases', to='user.Author'),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='validation_token',
            field=models.CharField(blank=True, default=None, help_text="Used to authenticate User's identity. See post_save signal", max_length=255, null=True),
        ),
    ]
