# Generated by Django 2.2 on 2021-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0003_auto_20210512_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorclaimcase',
            name='token_generated_time',
            field=models.IntegerField(blank=True, default=None, help_text='Intentionally setting as a int field', null=True),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='validation_token',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='See author_claim_case_post_create_signal', max_length=255, null=True, unique=True),
        ),
    ]
