# Generated by Django 2.2 on 2021-05-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0003_auto_20210518_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('INITIATED', 'INITIATED'), ('INVALIDATED', 'INVALIDATED'), ('NULLIFIED', 'NULLIFIED'), ('OPEN', 'OPEN')], default='INITIATED', max_length=32),
        ),
    ]
