# Generated by Django 2.2 on 2021-05-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0004_auto_20210507_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='validation_token',
            field=models.CharField(blank=True, help_text="Used to authenticate User's identity. See pre_save signal", max_length=32, null=True),
        ),
    ]
