# Generated by Django 2.2 on 2021-05-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0004_auto_20210511_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='validation_token',
            field=models.CharField(blank=True, default=None, help_text="Used to authenticate User's identity. See post_save signal", max_length=32, null=True),
        ),
    ]
