# Generated by Django 2.2 on 2021-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0004_auto_20210512_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorclaimcase',
            name='provided_email',
            field=models.EmailField(default='', help_text='Requestors may use this field to validate themselves with this email', max_length=254),
            preserve_default=False,
        ),
    ]
