# Generated by Django 2.2 on 2021-05-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0005_auto_20210507_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorclaimcase',
            name='validation_attempt_count',
            field=models.IntegerField(default=0, help_text='Number of attempts to validate themselves given token'),
        ),
    ]
