# Generated by Django 2.2 on 2021-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0006_authorclaimcase_validation_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='validation_attempt_count',
            field=models.IntegerField(default=-1, help_text='Number of attempts to validate themselves given token'),
        ),
    ]
