# Generated by Django 2.2 on 2022-02-11 20:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0007_auto_20210524_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorclaimcase',
            name='claim_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
