# Generated by Django 2.2 on 2022-02-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('researchhub_case', '0008_authorclaimcase_claim_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorclaimcase',
            name='claim_context',
        ),
        migrations.AddField(
            model_name='authorclaimcase',
            name='context_content_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='authorclaimcase',
            name='context_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
