# Generated by Django 2.2 on 2022-02-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0011_authorclaimcase_target_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='target_author_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='target_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_claim_cases', to='paper.Paper'),
        ),
    ]
