# Generated by Django 2.2 on 2022-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0012_auto_20220217_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='target_author_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
