# Generated by Django 2.2 on 2022-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0015_auto_20220422_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
