# Generated by Django 2.2 on 2022-10-25 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchhub_case', '0016_auto_20220705_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorclaimcase',
            name='case_type',
            field=models.CharField(choices=[('AUTHOR_CLAIM', 'AUTHOR_CLAIM'), ('PAPER_CLAIM', 'PAPER_CLAIM'), ('EXTERNAL_AUTHOR_CLAIM', 'EXTERNAL_AUTHOR_CLAIM')], max_length=32),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorclaimcase_created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorclaimcase_moderating_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorclaimcase',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorclaimcase_requested_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExternalAuthorClaimCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('AUTHOR_CLAIM', 'AUTHOR_CLAIM'), ('PAPER_CLAIM', 'PAPER_CLAIM'), ('EXTERNAL_AUTHOR_CLAIM', 'EXTERNAL_AUTHOR_CLAIM')], max_length=32)),
                ('h_index', models.IntegerField(default=0)),
                ('publication_count', models.IntegerField(default=0)),
                ('semantic_scholar_id', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('INITIATED', 'INITIATED'), ('INVALIDATED', 'INVALIDATED'), ('NULLIFIED', 'NULLIFIED'), ('OPEN', 'OPEN')], default='INITIATED', max_length=32)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalauthorclaimcase_created_cases', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalauthorclaimcase_moderating_cases', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalauthorclaimcase_requested_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
