# Generated by Django 2.2 on 2022-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_case', '0017_auto_20221025_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalauthorclaimcase',
            name='google_scholar_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='externalauthorclaimcase',
            name='h_index',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='externalauthorclaimcase',
            name='publication_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='externalauthorclaimcase',
            name='semantic_scholar_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
