# Generated by Django 4.1 on 2023-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0020_alter_authorclaimcase_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorclaimcase",
            name="target_doi",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
