# Generated by Django 4.1 on 2023-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0022_rename_target_doi_authorclaimcase_target_paper_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorclaimcase",
            name="target_paper_title",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
