# Generated by Django 4.1.13 on 2024-04-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0023_authorclaimcase_target_paper_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExternalAuthorClaimCase",
        ),
    ]
