# Generated by Django 4.2.13 on 2024-07-25 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0087_paperreward_hubcitationvalue"),
        ("researchhub_case", "0025_alter_authorclaimcase_case_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorclaimcase",
            name="open_data_url",
            field=models.URLField(blank=True, help_text="URL to open data", null=True),
        ),
        migrations.AddField(
            model_name="authorclaimcase",
            name="paper_reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reputation.paperreward",
            ),
        ),
        migrations.AddField(
            model_name="authorclaimcase",
            name="preregistration_url",
            field=models.URLField(
                blank=True, help_text="URL to preregistration", null=True
            ),
        ),
    ]
