# Generated by Django 4.2.13 on 2024-07-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0026_authorclaimcase_open_data_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorclaimcase",
            name="version",
            field=models.IntegerField(default=1, help_text="Version of the case"),
        ),
    ]
