# Generated by Django 4.2.13 on 2024-07-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0027_authorclaimcase_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorclaimcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "APPROVED"),
                    ("DENIED", "DENIED"),
                    ("INITIATED", "INITIATED"),
                    ("INVALIDATED", "INVALIDATED"),
                    ("NULLIFIED", "NULLIFIED"),
                    ("OPEN", "OPEN"),
                ],
                default="OPEN",
                max_length=32,
            ),
        ),
    ]
