# Generated by Django 4.2.13 on 2024-07-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0127_historicalpaper"),
        ("researchhub_case", "0028_alter_authorclaimcase_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorclaimcase",
            name="target_author",
        ),
        migrations.RemoveField(
            model_name="authorclaimcase",
            name="target_author_name",
        ),
        migrations.AddField(
            model_name="authorclaimcase",
            name="authorship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_claim_cases",
                to="paper.authorship",
            ),
        ),
    ]
