# Generated by Django 4.2.13 on 2024-07-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0127_historicalpaper"),
        ("researchhub_case", "0029_remove_authorclaimcase_target_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorclaimcase",
            name="authorship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_claim_cases",
                to="paper.authorship",
            ),
        ),
    ]
