# Generated by Django 4.2.14 on 2024-08-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0030_alter_authorclaimcase_authorship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorclaimcase",
            name="authorship",
        ),
    ]
