# Generated by Django 5.2.14 on 2026-06-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_case", "0031_remove_authorclaimcase_authorship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorClaimCase",
        ),
    ]
