# Generated by Django 4.1 on 2024-05-03 01:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("openalex_id", models.CharField(max_length=255, unique=True)),
                ("ror_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.TextField()),
                ("country_code", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=60)),
                (
                    "lineage",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "image_thumbnail_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("two_year_mean_citedness", models.FloatField(default=0)),
                ("h_index", models.IntegerField(default=0)),
                ("i10_index", models.IntegerField(default=0)),
                ("works_count", models.IntegerField(default=0)),
                (
                    "associated_institutions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
                (
                    "display_name_alternatives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
