# Generated by Django 4.1 on 2024-05-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0002_alter_institution_city_alter_institution_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="country_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
