# Generated by Django 4.1 on 2024-05-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0003_alter_institution_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="openalex_created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="openalex_updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
