# Generated by Django 4.1 on 2024-05-20 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0004_institution_openalex_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="associated_institutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500, null=True),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="h_index",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="i10_index",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="two_year_mean_citedness",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="works_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
