# Generated by Django 5.2.7 on 2025-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0005_alter_institution_associated_institutions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="openalex_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
