# Generated by Django 2.2.6 on 2019-10-17 21:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
