# Generated by Django 2.2.7 on 2019-11-22 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0003_auto_20191122_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distribution',
            name='is_removed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 22, 14, 9, 964408)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='is_removed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 22, 14, 25, 40775)),
            preserve_default=False,
        ),
    ]
