# Generated by Django 2.2.7 on 2019-12-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0005_auto_20191122_2323'),
        ('reputation', '0003_auto_20191125_2325'),
    ]

    operations = [
    ]
