# Generated by Django 2.2.7 on 2019-12-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0006_merge_20191202_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='distribution',
            name='paid_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='paid_status',
            field=models.CharField(choices=[('failed', 'failed'), ('paid', 'paid'), ('pending', 'pending')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='withdrawal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reputation.Withdrawal'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paid_status',
            field=models.CharField(choices=[('failed', 'failed'), ('paid', 'paid'), ('pending', 'pending')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='token_address',
            field=models.CharField(choices=[('0x7D50101BbFa12f4A1B4e6de0Dd58Ad36dE150D55', 'Research Coin address')], default='0x7D50101BbFa12f4A1B4e6de0Dd58Ad36dE150D55', max_length=255),
            preserve_default=False,
        ),
    ]
