# Generated by Django 2.2.8 on 2019-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0009_auto_20191203_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount',
            field=models.CharField(default='0.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='paid_status',
            field=models.CharField(choices=[('failed', 'failed'), ('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(paid_status='pending'), fields=('user', 'paid_status'), name='user_paid_status_pending'),
        ),
    ]
