# Generated by Django 2.2.8 on 2019-12-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0013_auto_20191213_1922'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distribution',
            name='recipient_vote_on_paper',
        ),
    ]
