# Generated by Django 2.2.9 on 2020-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0014_auto_20191213_1928'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawal',
            name='user_paid_status_pending',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distributed_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('DISTRIBUTED', 'DISTRIBUTED'), ('PENDING', 'PENDING')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='paid_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='paid_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default='PENDING', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(paid_status='PENDING'), fields=('user', 'paid_status'), name='user_paid_status_pending'),
        ),
    ]
