# Generated by Django 2.2.9 on 2020-01-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0015_auto_20200121_2002'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawal',
            name='user_paid_status_pending',
        ),
    ]
