# Generated by Django 2.2.10 on 2020-02-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0016_auto_20200128_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-updated_date']},
        ),
    ]
