# Generated by Django 2.2.10 on 2020-02-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0017_auto_20200211_1731'),
        ('reputation', '0017_auto_20200213_2026'),
    ]

    operations = [
    ]
