# Generated by Django 2.2.12 on 2020-05-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20200318_2137'),
        ('reputation', '0020_auto_20200410_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='hub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reputation_records', to='hub.Hub'),
            preserve_default=False,
        ),
    ]
