# Generated by Django 2.2.12 on 2020-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20200318_2137'),
        ('reputation', '0021_distribution_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='hub',
        ),
        migrations.AddField(
            model_name='distribution',
            name='hubs',
            field=models.ManyToManyField(related_name='reputation_records', to='hub.Hub'),
        ),
    ]
