# Generated by Django 2.2 on 2020-10-23 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0028_contribution_distributionamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionamount',
            name='amount',
            field=models.IntegerField(default=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionamount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('SUBMITTER', 'SUBMITTER'), ('UPVOTER', 'UPVOTER'), ('CURATOR', 'CURATOR'), ('COMMENTER', 'COMMENTER')], max_length=16),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('FLAG_PAPER', 'FLAG_PAPER'), ('PAPER_UPVOTED', 'PAPER_UPVOTED'), ('CREATE_BULLET_POINT', 'CREATE_BULLET_POINT'), ('BULLET_POINT_FLAGGED', 'BULLET_POINT_FLAGGED'), ('COMMENT_CENSORED', 'COMMENT_CENSORED'), ('COMMENT_FLAGGED', 'COMMENT_FLAGGED'), ('COMMENT_UPVOTED', 'COMMENT_UPVOTED'), ('COMMENT_DOWNVOTED', 'COMMENT_DOWNVOTED'), ('REPLY_CENSORED', 'REPLY_CENSORED'), ('REPLY_FLAGGED', 'REPLY_FLAGGED'), ('REPLY_UPVOTED', 'REPLY_UPVOTED'), ('REPLY_DOWNVOTED', 'REPLY_DOWNVOTED'), ('THREAD_CENSORED', 'THREAD_CENSORED'), ('THREAD_FLAGGED', 'THREAD_FLAGGED'), ('THREAD_UPVOTED', 'THREAD_UPVOTED'), ('THREAD_DOWNVOTED', 'THREAD_DOWNVOTED'), ('CREATE_SUMMARY', 'CREATE_SUMMARY'), ('REWARD', 'REWARD')], max_length=255),
        ),
    ]
