# Generated by Django 2.2 on 2020-10-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0028_contribution_distributionamount'),
        ('reputation', '0028_auto_20201023_2003'),
    ]

    operations = [
    ]
