# Generated by Django 2.2 on 2020-10-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0028_auto_20201023_2003'),
        ('reputation', '0029_auto_20201023_2238'),
    ]

    operations = [
    ]
