# Generated by Django 2.2 on 2020-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0031_auto_20201024_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionamount',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='distributionamount',
            name='amount',
            field=models.IntegerField(default=1000000),
        ),
    ]
