# Generated by Django 2.2 on 2020-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0032_auto_20201030_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionamount',
            name='distributed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
