# Generated by Django 2.2 on 2020-12-05 02:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0033_distributionamount_distributed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='proof_item_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='proof_item_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
