# Generated by Django 2.2 on 2021-01-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0037_auto_20201216_1851'),
        ('reputation', '0036_auto_20210104_2043'),
    ]

    operations = [
    ]
