# Generated by Django 2.2 on 2021-06-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0019_auto_20210617_2159'),
        ('reputation', '0037_auto_20210412_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='unified_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
