# Generated by Django 2.2 on 2021-06-25 20:25

from django.db import migrations


def migrate_paper_to_unified_document(apps, schema_editor):
    Contribution = apps.get_model(
        'reputation',
        'contribution'
    )

    contributions = Contribution.objects.filter(unified_document__isnull=True)
    for contribution in contributions.iterator():
        paper = contribution.paper
        if paper:
            unified_doc = contribution.paper.unified_document
            contribution.unified_document = unified_doc
            contribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0038_contribution_unified_document'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(migrate_paper_to_unified_document),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
        migrations.RemoveField(
            model_name='contribution',
            name='paper',
        ),
    ]
