# Generated by Django 2.2 on 2021-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0039_remove_contribution_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Reward',
            },
        ),
    ]
