# Generated by Django 2.2 on 2021-12-17 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reputation', '0040_rewardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_removed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('paid_date', models.DateTimeField(default=None, null=True)),
                ('paid_status', models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default=None, max_length=255, null=True)),
                ('token_address', models.CharField(choices=[('0xD101dCC414F310268c37eEb4cD376CcFA507F571', 'ResearchCoin address')], max_length=255)),
                ('amount', models.CharField(default='0.0', max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default='PENDING', max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
