# Generated by Django 2.2 on 2021-12-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0041_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='token_address',
        ),
    ]
