# Generated by Django 2.2 on 2022-03-03 02:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0043_auto_20220209_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('from_host', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='token_address',
            field=models.CharField(choices=[('0x82620900630a2Ab6a319791140891110B4cAA033', 'ResearchCoin address')], max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
