# Generated by Django 2.2 on 2022-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0044_auto_20220303_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='fee',
            field=models.CharField(default='0.0', max_length=255),
        ),
    ]
