# Generated by Django 2.2 on 2022-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0045_withdrawal_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
