# Generated by Django 2.2 on 2022-04-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0046_auto_20220318_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='token_address',
            field=models.CharField(choices=[('0x82620900630a2Ab6a319791140891110B4cAA033', 'ResearchCoin address')], max_length=255),
        ),
    ]
