# Generated by Django 2.2 on 2022-03-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0046_auto_20220317_1623'),
        ('reputation', '0046_auto_20220318_1913'),
    ]

    operations = [
    ]
