# Generated by Django 2.2 on 2022-03-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_auto_20220311_2215'),
        ('paper', '0084_auto_20220209_0543'),
        ('reputation', '0047_merge_20220329_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('FLAG_PAPER', 'FLAG_PAPER'), ('PAPER_UPVOTED', 'PAPER_UPVOTED'), ('CREATE_BULLET_POINT', 'CREATE_BULLET_POINT'), ('BULLET_POINT_FLAGGED', 'BULLET_POINT_FLAGGED'), ('BULLET_POINT_UPVOTED', 'BULLET_POINT_UPVOTED'), ('BULLET_POINT_DOWNVOTED', 'BULLET_POINT_DOWNVOTED'), ('COMMENT_CENSORED', 'COMMENT_CENSORED'), ('COMMENT_FLAGGED', 'COMMENT_FLAGGED'), ('COMMENT_UPVOTED', 'COMMENT_UPVOTED'), ('COMMENT_DOWNVOTED', 'COMMENT_DOWNVOTED'), ('REPLY_CENSORED', 'REPLY_CENSORED'), ('REPLY_FLAGGED', 'REPLY_FLAGGED'), ('REPLY_UPVOTED', 'REPLY_UPVOTED'), ('REPLY_DOWNVOTED', 'REPLY_DOWNVOTED'), ('THREAD_CENSORED', 'THREAD_CENSORED'), ('THREAD_FLAGGED', 'THREAD_FLAGGED'), ('THREAD_UPVOTED', 'THREAD_UPVOTED'), ('THREAD_DOWNVOTED', 'THREAD_DOWNVOTED'), ('CREATE_SUMMARY', 'CREATE_SUMMARY'), ('SUMMARY_UPVOTED', 'SUMMARY_UPVOTED'), ('SUMMARY_DOWNVOTED', 'SUMMARY_DOWNVOTED'), ('UPVOTE_RSC_POT', 'UPVOTE_RSC_POT'), ('REWARD', 'REWARD'), ('PURCHASE', 'PURCHASE'), ('REFERRAL', 'REFERRAL'), ('EDITOR_COMPENSATION', 'EDITOR_COMPENSATION')], max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='token_address',
            field=models.CharField(choices=[('0x82620900630a2Ab6a319791140891110B4cAA033', 'ResearchCoin address')], max_length=255),
        ),
        migrations.CreateModel(
            name='AuthorRSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_rsc', to='user.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_rsc', to='paper.Paper')),
            ],
        ),
    ]
