# Generated by Django 2.2 on 2022-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0048_auto_20220406_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('SUBMITTER', 'SUBMITTER'), ('UPVOTER', 'UPVOTER'), ('CURATOR', 'CURATOR'), ('COMMENTER', 'COMMENTER'), ('SUPPORTER', 'SUPPORTER'), ('VIEWER', 'VIEWER'), ('PEER_REVIEWER', 'PEER_REVIEWER')], max_length=16),
        ),
    ]
