# Generated by Django 2.2 on 2022-04-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0048_auto_20220329_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorrsc',
            name='claimed',
        ),
        migrations.AlterField(
            model_name='authorrsc',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_rsc', to='user.Author'),
        ),
    ]
