# Generated by Django 2.2 on 2022-04-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0047_auto_20220405_0106'),
        ('reputation', '0049_auto_20220406_0020'),
    ]

    operations = [
    ]
