# Generated by Django 2.2 on 2022-04-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0048_auto_20220406_1834'),
        ('reputation', '0050_merge_20220406_1818'),
    ]

    operations = [
    ]
