# Generated by Django 2.2 on 2022-04-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0049_auto_20220412_1921'),
        ('reputation', '0051_merge_20220414_2111'),
    ]

    operations = [
    ]
