# Generated by Django 2.2 on 2022-05-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reputation', '0052_merge_20220419_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_handed_out', to=settings.AUTH_USER_MODEL),
        ),
    ]
