# Generated by Django 2.2 on 2022-07-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0056_bounty_escrow_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorRSC',
        ),
    ]
