# Generated by Django 2.2 on 2022-07-05 22:16

from django.db import migrations, models
import django.db.models.deletion
import reputation.related_models.author_rsc


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0056_bounty_escrow_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='term',
            field=models.ForeignKey(default=reputation.related_models.author_rsc.get_current_term, on_delete=django.db.models.deletion.CASCADE, to='reputation.Term'),
        ),
    ]
