# Generated by Django 2.2 on 2022-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0057_delete_authorrsc'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['item_content_type', 'item_object_id', 'solution_content_type', 'solution_object_id'], name='reputation__item_co_3716af_idx'),
        ),
    ]
