# Generated by Django 2.2 on 2022-07-05 23:13

from django.db import migrations


def migrate_author_rsc_to_escrow(apps, schema_editor):
    User = apps.get_model('user', 'user')
    AuthorRSC = apps.get_model('reputation', 'authorrsc')
    Escrow = apps.get_model('reputation', 'escrow')
    Paper = apps.get_model('paper', 'paper')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    bank_user = User.objects.filter(email="bank@researchhub.com")
    if bank_user.exists():
        user = bank_user.first()
    else:
        user = User.objects.first()

    for author_rsc in AuthorRSC.objects.all().iterator():
        escrow = Escrow.objects.create(
            created_by=user,
            content_type=ContentType.objects.get_for_model(Paper),
            object_id=author_rsc.paper.id,
            amount=author_rsc.amounts
        )
        if author_rsc.claim_case.exists():
            author_rsc.claimed_rsc.through.objects.all().delete()
            author_rsc.claimed_rsc.add(escrow.id)


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0057_auto_20220705_2216'),
    ]

    operations = [
        migrations.RunPython(migrate_author_rsc_to_escrow),
        migrations.DeleteModel(
            name='AuthorRSC',
        ),
    ]
