# Generated by Django 2.2 on 2022-07-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('reputation', '0058_auto_20220713_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountySolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='bounty',
            name='reputation__solutio_952e43_idx',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='solution_content_type',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='solution_object_id',
        ),
        migrations.AddField(
            model_name='bountysolution',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='reputation.Bounty'),
        ),
        migrations.AddField(
            model_name='bountysolution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bountysolution',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bounty_solution', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bountysolution',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrow',
            name='amount_paid',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
    ]
