# Generated by Django 2.2 on 2022-08-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0041_auto_20220705_1646'),
        ('reputation', '0060_auto_20220721_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='unified_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_bounties', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='unified_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bounties', to='researchhub_document.ResearchhubUnifiedDocument')
        )
    ]
