# Generated by Django 2.2 on 2022-09-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0062_auto_20220926_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='bounty_for_expiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='reputation.Bounty'),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PARTIALLY_PAID', 'PARTIALLY_PAID'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('EXPIRY_CLOSED', 'EXPIRY_CLOSED'), ('EXPIRY_PAID', 'EXPIRY_PAID')], default='PENDING', max_length=16),
        ),
    ]
