# Generated by Django 2.2 on 2022-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0063_auto_20220930_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='effort_level',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
