# Generated by Django 4.1 on 2022-12-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0066_alter_distribution_proof_alter_webhook_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escrow",
            old_name="bounty_for_expiry",
            new_name="connected_bounty",
        ),
    ]
