# Generated by Django 4.1 on 2023-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0067_rename_bounty_for_expiry_escrow_connected_bounty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("AUTHOR", "AUTHOR"),
                    ("SUBMITTER", "SUBMITTER"),
                    ("UPVOTER", "UPVOTER"),
                    ("CURATOR", "CURATOR"),
                    ("COMMENTER", "COMMENTER"),
                    ("SUPPORTER", "SUPPORTER"),
                    ("VIEWER", "VIEWER"),
                    ("PEER_REVIEWER", "PEER_REVIEWER"),
                    ("BOUNTY_CREATED", "BOUNTY_CREATED"),
                    ("BOUNTY_SOLUTION", "BOUNTY_SOLUTION"),
                ],
                max_length=16,
            ),
        ),
    ]
