# Generated by Django 4.1 on 2023-02-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0068_alter_contribution_contribution_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bounty",
            name="effort_level",
        ),
        migrations.RemoveField(
            model_name="escrow",
            name="connected_bounty",
        ),
        migrations.AddField(
            model_name="bounty",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="reputation.bounty",
            ),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="escrow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bounties",
                to="reputation.escrow",
            ),
        ),
        migrations.AlterField(
            model_name="escrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("PARTIALLY_PAID", "PARTIALLY_PAID"),
                    ("PENDING", "PENDING"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRY_CLOSED", "EXPIRY_CLOSED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
