# Generated by Django 4.1 on 2023-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0069_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="distribution",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
