# Generated by Django 4.1 on 2023-02-28 23:25

from django.conf import settings
from django.db import migrations, models


def migrate_recipients(apps, schema_editor):
    Escrow = apps.get_model('reputation', 'Escrow')

    for escrow in Escrow.objects.filter(recipient__isnull=False).iterator():
        escrow.recipients.add(escrow.recipient)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reputation", "0070_alter_escrow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="target_escrows", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(migrate_recipients),
        migrations.RemoveField(
            model_name="escrow",
            name="recipient",
        ),
        migrations.RenameField(
            model_name="escrow",
            old_name="amount",
            new_name="amount_holding",
        ),
    ]
