# Generated by Django 4.1 on 2023-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0072_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("PARTIALLY_PAID", "PARTIALLY_PAID"),
                    ("PENDING", "PENDING"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
