# Generated by Django 4.1 on 2023-03-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0069_alter_distribution_distribution_type"),
        ("reputation", "0073_alter_escrow_status"),
    ]

    operations = []
