# Generated by Django 4.1 on 2023-03-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0070_deposit_is_public_distribution_is_public_and_more"),
        ("reputation", "0074_merge_20230324_2046"),
    ]

    operations = []
