# Generated by Django 4.1 on 2023-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0077_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("AUTHOR", "AUTHOR"),
                    ("SUBMITTER", "SUBMITTER"),
                    ("UPVOTER", "UPVOTER"),
                    ("CURATOR", "CURATOR"),
                    ("COMMENTER", "COMMENTER"),
                    ("SUPPORTER", "SUPPORTER"),
                    ("VIEWER", "VIEWER"),
                    ("PEER_REVIEWER", "PEER_REVIEWER"),
                    ("BOUNTY_CREATED", "BOUNTY_CREATED"),
                    ("BOUNTY_SOLUTION", "BOUNTY_SOLUTION"),
                    ("REPLICATION_VOTE", "REPLICATION_VOTE"),
                ],
                max_length=16,
            ),
        ),
    ]
