# Generated by Django 4.1 on 2023-11-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0078_alter_contribution_contribution_type"),
        ("reputation", "0078_bounty_bounty_type"),
    ]

    operations = []
