# Generated by Django 4.1 on 2023-12-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0079_merge_20231128_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrow",
            name="hold_type",
            field=models.CharField(
                choices=[
                    ("BOUNTY", "BOUNTY"),
                    ("AUTHOR_RSC", "AUTHOR_RSC"),
                    ("FUNDRAISE", "FUNDRAISE"),
                ],
                max_length=16,
            ),
        ),
    ]
