# Generated by Django 4.1 on 2024-01-08 18:23

from django.db import migrations, models


def add_default_support_fee(apps, schema_editor):
    SupportFee = apps.get_model("reputation", "SupportFee")
    SupportFee.objects.create(
        rh_pct=0.02,
        dao_pct=0.01
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0080_alter_escrow_hold_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportFee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("expiration_date", models.DateTimeField(null=True)),
                ("rh_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dao_pct", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(add_default_support_fee),
    ]
