# Generated by Django 4.1 on 2024-01-19 19:34

# We're updating the support fee tip to 3% for the RH and 0% for the DAO.
# Because, sending 30% of revenue to the DAO is a lot, especially when
# our core focus is financial sustainability for the Inc.
# In the future, when we're more financially stable, we can bring the DAO % back up.

from django.db import migrations

def add_support_fee_entry(apps, schema_editor):
    
    SupportFee = apps.get_model("reputation", "SupportFee")
    SupportFee.objects.create(
        rh_pct=0.03,
        dao_pct=0.00
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0081_supportfee"),
    ]

    operations = [
        migrations.RunPython(add_support_fee_entry),
    ]
