# Generated by Django 4.1 on 2024-03-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0082_update_support_fee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RewardModel",
        ),
    ]
