# Generated by Django 4.2.13 on 2024-06-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("user", "0116_merge_20240524_2253"),
        ("hub", "0022_alter_hub_concept"),
        ("reputation", "0084_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmVariables",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("variables", models.JSONField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.hub"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.author"
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.hub"
                    ),
                ),
            ],
            options={
                "unique_together": {("author", "hub")},
            },
        ),
        migrations.CreateModel(
            name="ScoreChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("algorithm_version", models.IntegerField(default=1)),
                ("score_after_change", models.IntegerField()),
                ("score_change", models.IntegerField()),
                ("raw_value_change", models.IntegerField()),
                ("changed_object_id", models.PositiveIntegerField()),
                ("changed_object_field", models.CharField(max_length=100)),
                ("variable_counts", models.JSONField(default=dict)),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "algorithm_variables",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reputation.algorithmvariables",
                    ),
                ),
                (
                    "changed_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reputation.score",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
