# Generated by Django 4.2.13 on 2024-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0085_algorithmvariables_score_scorechange"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scorechange",
            name="score_version",
            field=models.IntegerField(default=1),
        ),
    ]
