# Generated by Django 4.2.14 on 2024-07-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0127_historicalpaper"),
        ("user", "0121_alter_userverification_status"),
        ("hub", "0024_hub_is_used_for_rep"),
        ("reputation", "0086_score_version_scorechange_score_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperReward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation_change", models.PositiveIntegerField()),
                ("citation_count", models.PositiveIntegerField()),
                ("rsc_value", models.FloatField()),
                ("is_open_data", models.BooleanField(default=False)),
                ("is_preregistered", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.author"
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paper.paper"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HubCitationValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rsc_per_citation", models.FloatField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.hub"
                    ),
                ),
            ],
        ),
    ]
