# Generated by Django 4.2.14 on 2024-07-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0090_remove_hubcitationvalue_rsc_per_citation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperreward",
            name="hub_citation_value",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reputation.hubcitationvalue",
            ),
        ),
    ]
