# Generated by Django 4.2.14 on 2024-08-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0091_paperreward_hub_citation_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="version",
        ),
        migrations.RemoveField(
            model_name="scorechange",
            name="score_version",
        ),
    ]
