# Generated by Django 4.2.15 on 2024-10-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0092_remove_score_version_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DistributionAmount",
        ),
    ]
