# Generated by Django 4.2.15 on 2024-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0092_remove_score_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="bounty_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REVIEW", "REVIEW"),
                    ("ANSWER", "ANSWER"),
                    ("GENERIC_COMMENT", "GENERIC_COMMENT"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
