# Generated by Django 4.2.15 on 2024-10-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0094_alter_bounty_bounty_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DistributionAmount",
        ),
    ]
