# Generated by Django 4.2.16 on 2024-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0095_delete_distributionamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="network",
            field=models.CharField(
                choices=[("BASE", "Base"), ("ETHEREUM", "Ethereum")],
                default="ETHEREUM",
                max_length=10,
            ),
        ),
    ]
