# Generated by Django 5.1.4 on 2024-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0096_withdrawal_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="network",
            field=models.CharField(
                choices=[("BASE", "Base"), ("ETHEREUM", "Ethereum")],
                db_default="ETHEREUM",
                max_length=10,
            ),
        ),
    ]
