# Generated by Django 5.1.5 on 2025-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0100_bountysolution_awarded_amount_bountysolution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="distribution_type",
            field=models.CharField(
                choices=[
                    ("FLAG_PAPER", "FLAG_PAPER"),
                    ("STORED_PAPER_POT", "STORED_PAPER_POT"),
                    ("PAPER_REWARD", "PAPER_REWARD"),
                    ("REWARD", "REWARD"),
                    ("PURCHASE", "PURCHASE"),
                    ("EDITOR_COMPENSATION", "EDITOR_COMPENSATION"),
                    ("EDITOR_PAYOUT", "EDITOR_PAYOUT"),
                ],
                max_length=255,
            ),
        ),
    ]
