# Generated by Django 5.2.2 on 2025-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0102_remove_locked_balance_distribution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "OPEN"),
                    ("CLOSED", "CLOSED"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                    ("REVIEW_PERIOD", "REVIEW_PERIOD"),
                ],
                default="OPEN",
                max_length=16,
            ),
        ),
    ]
