# Generated by Django 5.2.2 on 2025-09-02 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
        ("reputation", "0102_remove_locked_balance_distribution_type"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bounty",
            index=models.Index(fields=["created_by"], name="bounty_creator_idx"),
        ),
        migrations.AddIndex(
            model_name="distribution",
            index=models.Index(
                fields=["giver", "is_removed", "distribution_type"],
                name="dist_giver_removed_type_idx",
            ),
        ),
    ]
