# Generated by Django 5.2.9 on 2026-01-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0103_bounty_bounty_creator_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="assessment_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="End date for the assessment phase when managers can review and award solutions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "OPEN"),
                    ("ASSESSMENT", "ASSESSMENT"),
                    ("CLOSED", "CLOSED"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                default="OPEN",
                max_length=16,
            ),
        ),
    ]
