# Generated by Django 5.2.7 on 2025-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reputation", "0103_bounty_bounty_creator_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorechange",
            name="contribution_type",
            field=models.CharField(
                db_index=True,
                default="UPVOTE",
                help_text="Type of contribution that triggered this score change",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="scorechange",
            index=models.Index(
                fields=["score", "contribution_type"],
                name="idx_score_contribution_type",
            ),
        ),
        migrations.AddIndex(
            model_name="scorechange",
            index=models.Index(
                fields=["contribution_type", "created_date"],
                name="idx_contribution_type_date",
            ),
        ),
    ]
