# Generated by Django 5.2.11 on 2026-02-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0104_add_bounty_assessment_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="circle_notification_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
