# Generated by Django 5.2.11 on 2026-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0105_add_circle_notification_id_to_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="sweep_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="sweep_transfer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
