# Generated by Django 5.2.11 on 2026-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0107_rename_circle_notification_id_to_circle_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="sweep_transfer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
