# Generated by Django 5.2.11 on 2026-03-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0109_rename_sweep_complete_to_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="circle_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIATED", "Initiated"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
