# Generated by Django 5.2.11 on 2026-03-06 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0110_add_circle_status_to_deposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deposit",
            index=models.Index(
                fields=["user", "paid_status"], name="reputation__user_id_73f39d_idx"
            ),
        ),
    ]
