# Generated by Django 5.2.11 on 2026-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0111_add_deposit_user_paid_status_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="circle_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIATED", "Initiated"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="sweep_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="sweep_transfer_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
