# Generated by Django 5.2.12 on 2026-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0113_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="distribution_type",
            field=models.CharField(
                choices=[
                    ("FLAG_PAPER", "FLAG_PAPER"),
                    ("STORED_PAPER_POT", "STORED_PAPER_POT"),
                    ("PAPER_REWARD", "PAPER_REWARD"),
                    ("REWARD", "REWARD"),
                    ("PURCHASE", "PURCHASE"),
                    ("REFERRAL_BONUS", "REFERRAL_BONUS"),
                    ("EDITOR_COMPENSATION", "EDITOR_COMPENSATION"),
                    ("EDITOR_PAYOUT", "EDITOR_PAYOUT"),
                    ("PREREGISTRATION_UPDATE_REWARD", "PREREGISTRATION_UPDATE_REWARD"),
                    ("STAKING_YIELD", "STAKING_YIELD"),
                ],
                max_length=255,
            ),
        ),
    ]
