# Generated by Django 5.2.12 on 2026-03-25 17:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0114_add_staking_yield_distribution_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emission_per_year",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "circulating_supply",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "staked_fraction",
                    models.DecimalField(
                        decimal_places=18, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "avg_multiplier",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=19
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "last_circulating_supply_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StakingYieldAccrual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accrual_date", models.DateField()),
                (
                    "stake_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "apy",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "proration_fraction",
                    models.DecimalField(
                        decimal_places=18, default=Decimal("1"), max_digits=19
                    ),
                ),
                (
                    "yield_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "distribution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staking_yield_accrual",
                        to="reputation.distribution",
                    ),
                ),
                (
                    "staking_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yield_accruals",
                        to="reputation.stakingconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_yield_accruals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "accrual_date")},
            },
        ),
    ]
