# Generated by Django 5.2.12 on 2026-03-26 16:31

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reputation", "0116_seed_staking_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingGlobalSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accrual_date", models.DateField(unique=True)),
                (
                    "emission_per_year",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "circulating_supply",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "total_staked",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "total_weighted_stake",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StakingUserSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stake_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=19
                    ),
                ),
                (
                    "weighted_stake",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                ("staking_opted_in_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "global_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_snapshots",
                        to="reputation.stakingglobalsnapshot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_user_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("global_snapshot", "user")},
            },
        ),
        migrations.CreateModel(
            name="StakingYieldRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annualized_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "proration_fraction",
                    models.DecimalField(
                        decimal_places=18, default=Decimal("1"), max_digits=19
                    ),
                ),
                (
                    "yield_amount",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=19
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "distribution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staking_yield_record",
                        to="reputation.distribution",
                    ),
                ),
                (
                    "user_snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yield_record",
                        to="reputation.stakingusersnapshot",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StakingSnapshot",
        ),
        migrations.DeleteModel(
            name="StakingYieldAccrual",
        ),
    ]
