# Generated by Django 5.2.14 on 2026-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0117_stakingglobalsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="broadcast_nonce",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="paid_status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("INITIATED", "INITIATED"),
                    ("PAID", "PAID"),
                    ("PENDING", "PENDING"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="paid_status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("INITIATED", "INITIATED"),
                    ("PAID", "PAID"),
                    ("PENDING", "PENDING"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="paid_status",
            field=models.CharField(
                choices=[
                    ("FAILED", "FAILED"),
                    ("INITIATED", "INITIATED"),
                    ("PAID", "PAID"),
                    ("PENDING", "PENDING"),
                ],
                default="INITIATED",
                max_length=255,
            ),
        ),
    ]
