# Generated by Django 5.2.15 on 2026-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reputation",
            "0118_withdrawal_broadcast_nonce_alter_deposit_paid_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="distribution_type",
            field=models.CharField(
                choices=[
                    ("FLAG_PAPER", "FLAG_PAPER"),
                    ("STORED_PAPER_POT", "STORED_PAPER_POT"),
                    ("PAPER_REWARD", "PAPER_REWARD"),
                    ("REWARD", "REWARD"),
                    ("PURCHASE", "PURCHASE"),
                    ("REFERRAL_BONUS", "REFERRAL_BONUS"),
                    ("GIFT_FOR_FUNDING", "GIFT_FOR_FUNDING"),
                    ("EDITOR_COMPENSATION", "EDITOR_COMPENSATION"),
                    ("EDITOR_PAYOUT", "EDITOR_PAYOUT"),
                    ("PREREGISTRATION_UPDATE_REWARD", "PREREGISTRATION_UPDATE_REWARD"),
                    ("STAKING_YIELD", "STAKING_YIELD"),
                ],
                max_length=255,
            ),
        ),
    ]
