# Generated by Django 5.2.17 on 2026-09-09 14:06

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0120_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotWalletNonceReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_id", models.PositiveBigIntegerField()),
                ("sender", models.CharField(max_length=42)),
                ("nonce", models.PositiveBigIntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("to_address", models.CharField(max_length=42)),
                ("amount", models.CharField(max_length=255)),
                ("transaction_hash", models.CharField(blank=True, max_length=255)),
                ("error", models.TextField(blank=True)),
                (
                    "withdrawal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nonce_reservation",
                        to="reputation.withdrawal",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("chain_id"),
                        django.db.models.functions.text.Lower("sender"),
                        models.F("nonce"),
                        name="unique_hot_wallet_nonce",
                    )
                ],
            },
        ),
    ]
