# Generated by Django 5.2.17 on 2026-09-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0120_alter_distribution_distribution_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperreward",
            name="hub_citation_value",
        ),
        migrations.RemoveField(
            model_name="paperreward",
            name="author",
        ),
        migrations.RemoveField(
            model_name="paperreward",
            name="distribution",
        ),
        migrations.RemoveField(
            model_name="paperreward",
            name="paper",
        ),
        migrations.DeleteModel(
            name="HubCitationValue",
        ),
        migrations.DeleteModel(
            name="PaperReward",
        ),
    ]
