# Generated by Django 5.2.17 on 2026-09-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0121_remove_paperreward_hub_citation_value_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Webhook",
        ),
    ]
