# Generated by Django 2.2 on 2021-09-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_merge_20210907_1738'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0004_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(default='Template', max_length=128)),
                ('src', models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='note/template/uploads/%Y/%m/%d')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='user.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
