# Generated by Django 2.2 on 2022-04-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_notetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
