# Generated by Django 5.1.5 on 2025-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0006_notetemplate_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="notecontent",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
