# Generated by Django 5.2.11 on 2026-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0007_notecontent_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DISCUSSION", "DISCUSSION"),
                    ("ELN", "ELN"),
                    ("GRANT", "GRANT"),
                    ("NOTE", "NOTE"),
                    ("PAPER", "PAPER"),
                    ("QUESTION", "QUESTION"),
                    ("PREREGISTRATION", "PREREGISTRATION"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
