# Generated by Django 5.1.5 on 2025-03-12 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0007_notecontent_json"),
        ("purchase", "0028_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonprofitOrg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the nonprofit organization", max_length=255
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        blank=True,
                        help_text="Employer Identification Number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "endaoment_org_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the organization in the Endaoment system",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "base_wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain wallet address for the organization",
                        max_length=42,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nonprofit Organization",
                "verbose_name_plural": "Nonprofit Organizations",
                "db_table": "nonprofit_org",
                "indexes": [
                    models.Index(
                        fields=["endaoment_org_id"],
                        name="nonprofit_o_endaome_630692_idx",
                    ),
                    models.Index(fields=["ein"], name="nonprofit_o_ein_f2e472_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NonprofitFundraiseLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Specific notes about this nonprofit for this fundraise",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "fundraise",
                    models.ForeignKey(
                        help_text="The fundraising campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonprofit_links",
                        to="purchase.fundraise",
                    ),
                ),
                (
                    "nonprofit",
                    models.ForeignKey(
                        help_text="The nonprofit organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraise_links",
                        to="note.nonprofitorg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nonprofit-Fundraise Link",
                "verbose_name_plural": "Nonprofit-Fundraise Links",
                "db_table": "nonprofit_fundraise_link",
                "indexes": [
                    models.Index(
                        fields=["nonprofit"], name="nonprofit_f_nonprof_9626cc_idx"
                    ),
                    models.Index(
                        fields=["fundraise"], name="nonprofit_f_fundrai_b2019f_idx"
                    ),
                ],
                "unique_together": {("nonprofit", "fundraise")},
            },
        ),
    ]
