# Generated by Django 5.2.14 on 2026-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0008_add_document_type_to_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DISCUSSION", "DISCUSSION"),
                    ("ELN", "ELN"),
                    ("GRANT", "GRANT"),
                    ("NOTE", "NOTE"),
                    ("PAPER", "PAPER"),
                    ("QUESTION", "QUESTION"),
                    ("PREREGISTRATION", "PREREGISTRATION"),
                    ("REGISTERED_REPORT", "REGISTERED_REPORT"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
