# Generated by Django 5.2.16 on 2026-08-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0009_alter_note_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notecontent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_note_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notecontent",
            name="created_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("editor", "editor"),
                    ("agent", "agent"),
                    ("system", "system"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notecontent",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="note.notecontent",
            ),
        ),
    ]
