# Generated by Django 5.2.15 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0009_alter_note_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notecontent",
            name="schema_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
