# Generated by Django 2.2 on 2022-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='openalex_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
