# Generated by Django 2.2 on 2022-03-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='papers',
        ),
    ]
