"""
Constants for AWS Personalize item data export.

Defines field names, CSV headers, and data types matching the Avro schema.
"""

# CSV Field Names (matching Avro schema)
ITEM_ID = "ITEM_ID"
ITEM_TYPE = "ITEM_TYPE"
HUB_L1 = "HUB_L1"
HUB_L2 = "HUB_L2"
HUB_IDS = "HUB_IDS"
AUTHOR_IDS = "AUTHOR_IDS"
CREATION_TIMESTAMP = "CREATION_TIMESTAMP"
TEXT = "TEXT"
TITLE = "TITLE"
SCORE = "SCORE"
BLUESKY_COUNT_TOTAL = "BLUESKY_COUNT_TOTAL"
TWEET_COUNT_TOTAL = "TWEET_COUNT_TOTAL"
CITATION_COUNT_TOTAL = "CITATION_COUNT_TOTAL"
BOUNTY_AMOUNT = "BOUNTY_AMOUNT"
BOUNTY_EXPIRES_AT = "BOUNTY_EXPIRES_AT"
BOUNTY_NUM_OF_SOLUTIONS = "BOUNTY_NUM_OF_SOLUTIONS"
PROPOSAL_AMOUNT = "PROPOSAL_AMOUNT"
PROPOSAL_EXPIRES_AT = "PROPOSAL_EXPIRES_AT"
PROPOSAL_NUM_OF_FUNDERS = "PROPOSAL_NUM_OF_FUNDERS"
REQUEST_FOR_PROPOSAL_AMOUNT = "REQUEST_FOR_PROPOSAL_AMOUNT"
REQUEST_FOR_PROPOSAL_EXPIRES_AT = "REQUEST_FOR_PROPOSAL_EXPIRES_AT"
REQUEST_FOR_PROPOSAL_NUM_OF_APPLICANTS = "REQUEST_FOR_PROPOSAL_NUM_OF_APPLICANTS"
LAST_COMMENT_AT = "LAST_COMMENT_AT"

# CSV Headers (in order for the CSV file)
CSV_HEADERS = [
    ITEM_ID,
    ITEM_TYPE,
    HUB_L1,
    HUB_L2,
    HUB_IDS,
    AUTHOR_IDS,
    CREATION_TIMESTAMP,
    TEXT,
    TITLE,
    SCORE,
    BLUESKY_COUNT_TOTAL,
    TWEET_COUNT_TOTAL,
    CITATION_COUNT_TOTAL,
    BOUNTY_AMOUNT,
    BOUNTY_EXPIRES_AT,
    BOUNTY_NUM_OF_SOLUTIONS,
    PROPOSAL_AMOUNT,
    PROPOSAL_EXPIRES_AT,
    PROPOSAL_NUM_OF_FUNDERS,
    REQUEST_FOR_PROPOSAL_AMOUNT,
    REQUEST_FOR_PROPOSAL_EXPIRES_AT,
    REQUEST_FOR_PROPOSAL_NUM_OF_APPLICANTS,
    LAST_COMMENT_AT,
]

# Document types to exclude from export
EXCLUDED_DOCUMENT_TYPES = ["NOTE", "HYPOTHESIS"]

# Text field maximum length (to prevent CSV cell overflow)
MAX_TEXT_LENGTH = 10000
