# Generated by Django 2.2 on 2022-11-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField()),
                ('key', models.CharField(max_length=32, unique=True)),
                ('recipient_email', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('JOIN_RH', 'JOIN_RH'), ('BOUNTY', 'BOUNTY')], default='JOIN_RH', max_length=32)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referralinvite_sent_invites', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referralinvite_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
