# Generated by Django 5.1.5 on 2025-06-27 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("signup_date", models.DateTimeField(auto_now_add=True)),
                (
                    "referred",
                    models.OneToOneField(
                        help_text="User who signed up via referral",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_signup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        help_text="User who made the referral",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["referrer", "signup_date"],
                        name="referral_re_referre_0bc739_idx",
                    )
                ],
            },
        ),
    ]
