# Generated by Django 2.2 on 2022-11-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralinvite',
            old_name='status',
            new_name='invite_type',
        ),
    ]
