# Generated by Django 2.2 on 2022-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_referralinvite_unified_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralinvite',
            name='referral_first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='referralinvite',
            name='referral_last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
