DISCUSSION = 'DISCUSSION'
HYPOTHESIS = 'HYPOTHESIS'
ELN = 'ELN'
PAPER = 'PAPER'
POSTS = 'POSTS'  # POSTS include discussion and eln
ALL = 'ALL'  # ALL includes paper and posts

DOCUMENT_TYPES = (
    (PAPER, PAPER),
    (DISCUSSION, DISCUSSION),
    (ELN, ELN),
    (HYPOTHESIS, HYPOTHESIS)
)
