ALL = "ALL"  # ALL includes paper and posts
DISCUSSION = "DISCUSSION"
ELN = "ELN"
HYPOTHESIS = "HYPOTHESIS"
NOTE = "NOTE"
PAPER = "PAPER"
POSTS = "POSTS"  # POSTS include discussion and eln
QUESTION = "QUESTION"

DOCUMENT_TYPES = (
    (DISCUSSION, DISCUSSION),
    (ELN, ELN),
    (HYPOTHESIS, HYPOTHESIS),
    (NOTE, NOTE),
    (PAPER, PAPER),
    (QUESTION, QUESTION),
)

RESEARCHHUB_POST_DOCUMENT_TYPES = [DISCUSSION, ELN, POSTS, QUESTION]
