from researchhub_document.related_models.constants.document_type import (
    GRANT,
    PREREGISTRATION,
    REGISTERED_REPORT,
)

JOURNEY_STAGE_GRANT = "grant"
JOURNEY_STAGE_PROPOSAL = "proposal"
JOURNEY_STAGE_REGISTERED_REPORT = "registered_report"

JOURNEY_STAGE_BY_DOCUMENT_TYPE = {
    GRANT: JOURNEY_STAGE_GRANT,
    PREREGISTRATION: JOURNEY_STAGE_PROPOSAL,
    REGISTERED_REPORT: JOURNEY_STAGE_REGISTERED_REPORT,
}

JOURNEY_STAGE_ORDER = {
    JOURNEY_STAGE_GRANT: 1,
    JOURNEY_STAGE_PROPOSAL: 2,
    JOURNEY_STAGE_REGISTERED_REPORT: 3,
}
