# Generated by Django 5.2.11 on 2026-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_expert_finder", "0003_documentinvitedexpert_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedemail",
            name="expert_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
