# Generated by Django 5.2.11 on 2026-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_expert_finder", "0004_alter_generatedemail_expert_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="email_body",
            field=models.TextField(
                blank=True,
                db_comment="Body for fixed-template; may contain {{entity.field}}.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="email_subject",
            field=models.TextField(
                blank=True,
                db_comment="Subject for fixed-template; may contain {{entity.field}}.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("prompt-context", "Prompt context"),
                    ("fixed-template", "Fixed template"),
                ],
                db_comment="prompt-context (LLM) or fixed-template (variable substitution).",
                default="prompt-context",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("sending", "sending"),
                    ("send_failed", "send_failed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
