# Generated by Django 5.2.12 on 2026-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_expert_finder", "0006_remove_emailtemplate_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("sending", "sending"),
                    ("send_failed", "send_failed"),
                    ("closed", "closed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
