# Generated by Django 5.2.12 on 2026-03-31 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_expert_finder", "0007_alter_generatedemail_status"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentinvitedexpert",
            name="research_ai_die_doc_user_unique",
        ),
        migrations.RenameIndex(
            model_name="documentinvitedexpert",
            new_name="aef_die_unified_doc",
            old_name="research_ai_die_unified_doc",
        ),
        migrations.RenameIndex(
            model_name="documentinvitedexpert",
            new_name="aef_die_expert_search",
            old_name="research_ai_die_expert_search",
        ),
        migrations.RenameIndex(
            model_name="emailtemplate",
            new_name="aef_et_created_by",
            old_name="research_ai_et_created_by",
        ),
        migrations.RenameIndex(
            model_name="expertsearch",
            new_name="aef_es_user_status",
            old_name="research_ai_es_user_status",
        ),
        migrations.RenameIndex(
            model_name="expertsearch",
            new_name="aef_es_status",
            old_name="research_ai_es_status",
        ),
        migrations.RenameIndex(
            model_name="generatedemail",
            new_name="aef_ge_created_by",
            old_name="research_ai_ge_created_by",
        ),
        migrations.AddConstraint(
            model_name="documentinvitedexpert",
            constraint=models.UniqueConstraint(
                fields=("unified_document", "user"), name="aef_die_doc_user_unique"
            ),
        ),
        migrations.AlterModelTable(
            name="documentinvitedexpert",
            table="ai_expert_finder_document_invited_expert",
        ),
        migrations.AlterModelTable(
            name="emailtemplate",
            table="ai_expert_finder_email_template",
        ),
        migrations.AlterModelTable(
            name="expertsearch",
            table="ai_expert_finder_expert_search",
        ),
        migrations.AlterModelTable(
            name="generatedemail",
            table="ai_expert_finder_generated_email",
        ),
    ]
