from citation.csl_constants import (
    ARTICLE,
    ARTICLE_JOURNAL,
    ARTICLE_MAGAZINE,
    ARTICLE_NEWSPAPER,
    BROADCAST,
    CHAPTER,
    ENTRY_DICTIONARY,
    ENTRY_ENCYCLOPEDIA,
    GRAPHIC,
    LEGAL_CASE,
    LEGISLATION,
    MOTION_PICTURE,
    PAPER_CONFERENCE,
    PERSONAL_COMMUNICATION,
    POST,
    POST_WEBLOG,
    SONG,
    SPEECH,
)

ARTWORK = "ARTWORK"
AUDIO_RECORDING = "AUDIO_RECORDING"
BILL = "BILL"
BLOG_POST = "BLOG_POST"
BOOK = "BOOK"
BOOK_SECTION = "BOOK_SECTION"
CASE = "CASE"
CONFERENCE_PAPER = "CONFERENCE_PAPER"
DICTIONARY_ENTRY = "DICTIONARY_ENTRY"
DOCUMENT = "DOCUMENT"
EMAIL = "EMAIL"
ENCYCLOPEDIA_ARTICLE = "ENCYCLOPEDIA_ARTICLE"
FILM = "FILM"
FORUM_POST = "FORUM_POST"
HEARING = "HEARING"
INSTANT_MESSAGE = "INSTANT_MESSAGE"
INTERVIEW = "INTERVIEW"
JOURNAL_ARTICLE = "JOURNAL_ARTICLE"
LETTER = "LETTER"
MAGAZINE_ARTICLE = "MAGAZINE_ARTICLE"
MANUSCRIPT = "MANUSCRIPT"
MAP = "MAP"
NEWSPAPER_ARTICLE = "NEWSPAPER_ARTICLE"
PATENT = "PATENT"
PODCAST = "PODCAST"
PREPRINT = "PREPRINT"
PRESENTATION = "PRESENTATION"
RADIO_BROADCAST = "RADIO_BROADCAST"
REPORT = "REPORT"
SOFTWARE = "SOFTWARE"
STATUTE = "STATUTE"
THESIS = "THESIS"
TV_BROADCAST = "TV_BROADCAST"
VIDEO_RECORDING = "VIDEO_RECORDING"
WEBPAGE = "WEBPAGE"

ZOTERO_TO_CSL_MAPPING = {
    ARTWORK: GRAPHIC,
    AUDIO_RECORDING: SONG,
    BILL: BILL,
    BLOG_POST: POST_WEBLOG,
    BOOK: BOOK,
    BOOK_SECTION: CHAPTER,
    CASE: LEGAL_CASE,
    CONFERENCE_PAPER: PAPER_CONFERENCE,
    DICTIONARY_ENTRY: ENTRY_DICTIONARY,
    DOCUMENT: DOCUMENT,
    EMAIL: PERSONAL_COMMUNICATION,
    ENCYCLOPEDIA_ARTICLE: ENTRY_ENCYCLOPEDIA,
    FILM: MOTION_PICTURE,
    FORUM_POST: POST,
    HEARING: HEARING,
    INSTANT_MESSAGE: PERSONAL_COMMUNICATION,
    INTERVIEW: INTERVIEW,
    JOURNAL_ARTICLE: ARTICLE_JOURNAL,
    LETTER: PERSONAL_COMMUNICATION,
    MAGAZINE_ARTICLE: ARTICLE_MAGAZINE,
    MANUSCRIPT: MANUSCRIPT,
    MAP: MAP,
    NEWSPAPER_ARTICLE: ARTICLE_NEWSPAPER,
    PATENT: PATENT,
    PODCAST: BROADCAST,
    PREPRINT: ARTICLE,
    PRESENTATION: SPEECH,
    RADIO_BROADCAST: BROADCAST,
    REPORT: REPORT,
    SOFTWARE: SOFTWARE,
    STATUTE: LEGISLATION,
    THESIS: THESIS,
    TV_BROADCAST: BROADCAST,
    VIDEO_RECORDING: MOTION_PICTURE,
    WEBPAGE: WEBPAGE,
}

CSL_TO_ZOTERO_MAPPING = {value: key for key, value in ZOTERO_TO_CSL_MAPPING.items()}

CITATION_TYPE_CHOICES = (
    (ARTWORK, ARTWORK),
    (AUDIO_RECORDING, AUDIO_RECORDING),
    (BILL, BILL),
    (BLOG_POST, BLOG_POST),
    (BOOK, BOOK),
    (BOOK_SECTION, BOOK_SECTION),
    (CASE, CASE),
    (CONFERENCE_PAPER, CONFERENCE_PAPER),
    (DICTIONARY_ENTRY, DICTIONARY_ENTRY),
    (DOCUMENT, DOCUMENT),
    (EMAIL, EMAIL),
    (ENCYCLOPEDIA_ARTICLE, ENCYCLOPEDIA_ARTICLE),
    (FILM, FILM),
    (FORUM_POST, FORUM_POST),
    (HEARING, HEARING),
    (INSTANT_MESSAGE, INSTANT_MESSAGE),
    (INTERVIEW, INTERVIEW),
    (JOURNAL_ARTICLE, JOURNAL_ARTICLE),
    (LETTER, LETTER),
    (MAGAZINE_ARTICLE, MAGAZINE_ARTICLE),
    (MANUSCRIPT, MANUSCRIPT),
    (MAP, MAP),
    (NEWSPAPER_ARTICLE, NEWSPAPER_ARTICLE),
    (PATENT, PATENT),
    (PODCAST, PODCAST),
    (PREPRINT, PREPRINT),
    (PRESENTATION, PRESENTATION),
    (RADIO_BROADCAST, RADIO_BROADCAST),
    (REPORT, REPORT),
    (SOFTWARE, SOFTWARE),
    (STATUTE, STATUTE),
    (THESIS, THESIS),
    (TV_BROADCAST, TV_BROADCAST),
    (VIDEO_RECORDING, VIDEO_RECORDING),
    (WEBPAGE, WEBPAGE),
)


DEPRECATED_CITATION_TYPE_FIELDS = {
    # LOGICAL ORDERING
    JOURNAL_ARTICLE: [
        "title",
        "abstract_note",
        "publication_title",
        "volume",
        "issue",
        "pages",
        # "date",
        "series",
        "series_title",
        # "series_text",
        "journal_abbreviation",
        "language",
        "DOI",
        "ISSN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    ARTWORK: [
        "title",
        "abstract_note",
        # "artwork_medium",
        "medium",
        "artwork_size",
        # "date",
        "language",
        "short_title",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    # ATTACHMENT: ["title", "access_date", "url"],
    AUDIO_RECORDING: [
        "title",
        "abstract_note",
        # "audio_recording_format",
        "medium",
        "series_title",
        "volume",
        "number_of_volumes",
        "place",
        # "label",
        "publisher",
        # "date",
        "running_time",
        "language",
        "ISBN",
        "short_title",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    BILL: [
        "title",
        "abstract_note",
        # "bill_number",
        "number",
        "code",
        # "code_volume",
        "volume",
        "section",
        # "code_pages",
        "pages",
        # "legislative_body",
        "authority",
        "session",
        "history",
        # "date",
        "language",
        "url",
        # "access_date",
        "short_title",
        "rights",
        # "extra",
    ],
    BLOG_POST: [
        "title",
        "abstract_note",
        # "blog_title",
        "publication_title",
        # "website_type",
        "type",
        # "date",
        "url",
        # "access_date",
        "language",
        "short_title",
        "rights",
        # "extra",
    ],
    BOOK: [
        "title",
        "abstract_note",
        "series",
        "series_number",
        "volume",
        "number_of_volumes",
        "edition",
        "place",
        "publisher",
        # "date",
        "num_pages",
        "language",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    BOOK_SECTION: [
        "title",
        "abstract_note",
        # "book_title",
        "publication_title",
        "series",
        "series_number",
        "volume",
        "number_of_volumes",
        "edition",
        "place",
        "publisher",
        # "date",
        "pages",
        "language",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    CASE: [
        # "case_name",
        "title",
        "abstract_note",
        # "court",
        "authority",
        # "date_decided",
        # "date",
        # "docket_number",
        "number",
        "reporter",
        # "reporter_volume",
        "volume",
        # "first_page",
        "pages",
        "history",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    SOFTWARE: [
        "title",
        "abstract_note",
        "series_title",
        "version_number",
        # "date",
        "system",
        "place",
        # "company",
        "publisher",
        "programming_language",
        "ISBN",
        "short_title",
        "url",
        "rights",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        # "access_date",
        # "extra",
    ],
    CONFERENCE_PAPER: [
        "title",
        "abstract_note",
        # "date",
        # "proceedings_title",
        "publication_title",
        "conference_name",
        "place",
        "publisher",
        "volume",
        "pages",
        "series",
        "language",
        "DOI",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    DICTIONARY_ENTRY: [
        "title",
        "abstract_note",
        # "dictionary_title",
        "publication_title",
        "series",
        "series_number",
        "volume",
        "number_of_volumes",
        "edition",
        "place",
        "publisher",
        # "date",
        "pages",
        "language",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    DOCUMENT: [
        "title",
        "abstract_note",
        "publisher",
        # "date",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    EMAIL: [
        # "subject",
        "title",
        "abstract_note",
        # "date",
        "short_title",
        "url",
        # "access_date",
        "language",
        "rights",
        # "extra",
    ],
    ENCYCLOPEDIA_ARTICLE: [
        "title",
        "abstract_note",
        # "encyclopedia_title",
        "publication_title",
        "series",
        "series_number",
        "volume",
        "number_of_volumes",
        "edition",
        "place",
        "publisher",
        # "date",
        "pages",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "language",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    FILM: [
        "title",
        "abstract_note",
        # "distributor",
        "publisher",
        # "date",
        # "genre",
        "type",
        # "video_recording_format",
        "medium",
        "running_time",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    FORUM_POST: [
        "title",
        "abstract_note",
        # "forum_title",
        "publication_title",
        # "post_type",
        "type",
        # "date",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    HEARING: [
        "title",
        "abstract_note",
        "committee",
        "place",
        "publisher",
        "number_of_volumes",
        # "document_number",
        "number",
        "pages",
        # "legislative_body",
        "authority",
        "session",
        "history",
        # "date",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    INSTANT_MESSAGE: [
        "title",
        "abstract_note",
        # "date",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    INTERVIEW: [
        "title",
        "abstract_note",
        # "date",
        # "interview_medium",
        "medium",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    LETTER: [
        "title",
        "abstract_note",
        # "letter_type",
        "type",
        # "date",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    MAGAZINE_ARTICLE: [
        "title",
        "abstract_note",
        "publication_title",
        "volume",
        "issue",
        # "date",
        "pages",
        "language",
        "ISSN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    MANUSCRIPT: [
        "title",
        "abstract_note",
        # "manuscript_type",
        "type",
        "place",
        # "date",
        "num_pages",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    MAP: [
        "title",
        "abstract_note",
        # "map_type",
        "type",
        "scale",
        "series_title",
        "edition",
        "place",
        "publisher",
        # "date",
        "language",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    NEWSPAPER_ARTICLE: [
        "title",
        "abstract_note",
        "publication_title",
        "place",
        "edition",
        # "date",
        "section",
        "pages",
        "language",
        "short_title",
        "ISSN",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    # NOTE: [],
    PATENT: [
        "title",
        "abstract_note",
        "place",
        # "country",
        # "assignee",
        # "issuing_authority",
        "authority",
        # "patent_number",
        "number",
        # "filing_date",
        "pages",
        "application_number",
        "priority_numbers",
        # "issue_date",
        # "date",
        "references",
        # "legal_status",
        "status",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    PODCAST: [
        "title",
        "abstract_note",
        "series_title",
        # "episode_number",
        "number",
        # "audio_file_type",
        "medium",
        "running_time",
        "url",
        # "access_date",
        "language",
        "short_title",
        "rights",
        # "extra",
    ],
    PREPRINT: [
        "title",
        "abstract_note",
        # "genre",
        "type",
        # "repository",
        "publisher",
        # "archive_ID",
        "number",
        "place",
        # "date",
        "series",
        "series_number",
        "DOI",
        # "citation_key",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "short_title",
        "language",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    PRESENTATION: [
        "title",
        "abstract_note",
        # "presentation_type",
        "type",
        # "date",
        "place",
        "meeting_name",
        "url",
        # "access_date",
        "language",
        "short_title",
        "rights",
        # "extra",
    ],
    RADIO_BROADCAST: [
        "title",
        "abstract_note",
        # "program_title",
        "publication_title",
        # "episode_number",
        "number",
        # "audio_recording_format",
        "medium",
        "place",
        # "network",
        "publisher",
        # "date",
        "running_time",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    REPORT: [
        "title",
        "abstract_note",
        # "report_number",
        "number",
        # "report_type",
        "type",
        "series_title",
        "place",
        # "institution",
        "publisher",
        # "date",
        "pages",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    STATUTE: [
        # "name_of_act",
        "title",
        "abstract_note",
        "code",
        "code_number",
        # "public_law_number",
        "number",
        # "date_enacted",
        # "date",
        "pages",
        "section",
        "session",
        "history",
        "language",
        "short_title",
        "url",
        # "access_date",
        "rights",
        # "extra",
    ],
    THESIS: [
        "title",
        "abstract_note",
        # "thesis_type",
        "type",
        # "university",
        "publisher",
        "place",
        # "date",
        "num_pages",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    TV_BROADCAST: [
        "title",
        "abstract_note",
        # "program_title",
        "publication_title",
        # "episode_number",
        "number",
        # "video_recording_format",
        "medium",
        "place",
        # "network",
        "publisher",
        # "date",
        "running_time",
        "language",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    VIDEO_RECORDING: [
        "title",
        "abstract_note",
        # "video_recording_format",
        "medium",
        "series_title",
        "volume",
        "number_of_volumes",
        "place",
        # "studio",
        "publisher",
        # "date",
        "running_time",
        "language",
        "ISBN",
        "short_title",
        "url",
        # "access_date",
        "archive",
        "archive_location",
        "library_catalog",
        "call_number",
        "rights",
        # "extra",
    ],
    WEBPAGE: [
        "title",
        "abstract_note",
        # "website_title",
        "publication_title",
        # "website_type",
        "type",
        # "date",
        "short_title",
        "url",
        # "access_date",
        "language",
        "rights",
        # "extra",
    ],
}

FIELD_NAME_ALT = {
    "artwork_medium": "medium",
    "audio_recording_format": "medium",
    "label": "publisher",
    "bill_number": "number",
    "code_volume": "volume",
    "code_pages": "pages",
    "blog_title": "publication_title",
    "website_type": "type",
    "book_title": "publication_title",
    "case_name": "title",
    "date_decided": "date",
    "docket_number": "number",
    "reporter_volume": "volume",
    "first_page": "pages",
    "company": "publisher",
    "proceedings_title": "publication_title",
    "dictionary_title": "publication_title",
    "subject": "title",
    "encyclopedia_title": "publication_title",
    "distributor": "publisher",
    "genre": "type",
    "video_recording_format": "medium",
    "forum_title": "publication_title",
    "post_type": "type",
    "document_number": "number",
    "interview_medium": "medium",
    "letter_type": "type",
    "manuscript_type": "type",
    "map_type": "type",
    "patent_number": "number",
    "issue_date": "date",
    "episode_number": "number",
    "audio_file_type": "medium",
    "repository": "publisher",
    "archive_ID": "number",
    "presentation_type": "type",
    "program_title": "publication_title",
    "network": "publisher",
    "report_number": "number",
    "report_type": "type",
    "institution": "publisher",
    "name_of_act": "title",
    "public_law_number": "number",
    "date_enacted": "date",
    "thesis_type": "type",
    "university": "publisher",
    "studio": "publisher",
    "website_title": "publication_title",
}

CREATOR_TYPES = {
    # "annotation": [],
    ARTWORK: ["artist", "contributor"],
    # ATTACHMENT: [],
    AUDIO_RECORDING: ["performer", "contributor", "composer", "words_by"],
    BILL: ["sponsor", "cosponsor", "contributor"],
    BLOG_POST: ["author", "commenter", "contributor"],
    BOOK: ["author", "contributor", "editor", "translator", "series_editor"],
    BOOK_SECTION: [
        "author",
        "contributor",
        "editor",
        "book_author",
        "translator",
        "series_editor",
    ],
    CASE: ["author", "counsel", "contributor"],
    SOFTWARE: ["programmer", "contributor"],
    CONFERENCE_PAPER: [
        "author",
        "contributor",
        "editor",
        "translator",
        "series_editor",
    ],
    DICTIONARY_ENTRY: [
        "author",
        "contributor",
        "editor",
        "translator",
        "series_editor",
    ],
    DOCUMENT: ["author", "contributor", "editor", "translator", "reviewed_author"],
    EMAIL: ["author", "contributor", "recipient"],
    ENCYCLOPEDIA_ARTICLE: [
        "author",
        "contributor",
        "editor",
        "translator",
        "series_editor",
    ],
    FILM: ["director", "contributor", "scriptwriter", "producer"],
    FORUM_POST: ["author", "contributor"],
    HEARING: ["contributor"],
    INSTANT_MESSAGE: ["author", "contributor", "recipient"],
    INTERVIEW: ["interviewee", "contributor", "interviewer", "translator"],
    JOURNAL_ARTICLE: [
        "author",
        "contributor",
        "editor",
        "translator",
        "reviewed_author",
    ],
    LETTER: ["author", "contributor", "recipient"],
    MAGAZINE_ARTICLE: ["author", "contributor", "translator", "reviewed_author"],
    MANUSCRIPT: ["author", "contributor", "translator"],
    MAP: ["cartographer", "contributor", "series_editor"],
    NEWSPAPER_ARTICLE: ["author", "contributor", "translator", "reviewed_author"],
    # NOTE: [],
    PATENT: ["inventor", "attorney_agent", "contributor"],
    PODCAST: ["podcaster", "contributor", "guest"],
    PREPRINT: ["author", "contributor", "editor", "translator", "reviewed_author"],
    PRESENTATION: ["presenter", "contributor"],
    RADIO_BROADCAST: [
        "director",
        "scriptwriter",
        "producer",
        "cast_member",
        "contributor",
        "guest",
    ],
    REPORT: ["author", "contributor", "translator", "series_editor"],
    STATUTE: ["author", "contributor"],
    THESIS: ["author", "contributor"],
    TV_BROADCAST: [
        "director",
        "scriptwriter",
        "producer",
        "cast_member",
        "contributor",
        "guest",
    ],
    VIDEO_RECORDING: [
        "director",
        "scriptwriter",
        "producer",
        "cast_member",
        "contributor",
    ],
    WEBPAGE: ["author", "contributor", "translator"],
}

ZOTERO_FIELDS_TO_CSL_MAPPING = {
    "abstract_note": "abstract",
    "archive": "archive",
    "archive_location": "archive_location",
    "authority": "authority",
    "call_number": "call-number",
    "application_number": "call-number",
    "session": "chapter-number",
    "series_number": "collection-number",
    "series_title": "collection-title",
    "series": "collection-title",
    "publication_title": "container-title",
    "reporter": "container-title",
    "code": "container-title",
    "artwork_size": "dimensions",
    "running_time": "dimensions",
    "DOI": "DOI",
    "edition": "edition",
    "place": "publisher-place",
    "meeting_name": "event-title",
    "conference_name": "event-title",
    "type": "genre",
    "programming_language": "genre",
    "ISBN": "ISBN",
    "ISSN": "ISSN",
    "issue": "issue",
    "priority_numbers": "issue",
    "journal_abbreviation": "journalAbbreviation",
    "language": "language",
    "rights": "license",
    "medium": "medium",
    "system": "medium",
    "extra": "note",
    "number": "number",
    "num_pages": "number-of-pages",
    "number_of_volumes": "number-of-volumes",
    "pages": "page",
    "publisher": "publisher",
    "history": "references",
    "references": "references",
    "scale": "scale",
    "section": "section",
    "committee": "section",
    "short_title": "title-short",
    "library_catalog": "source",
    "status": "status",
    "title": "title",
    "url": "URL",
    "version_number": "version",
    "volume": "volume",
    "code_number": "volume",
}

# res = {}
# for key, value in CITATION_TYPE_FIELDS.items():
#     new_values = []
#     for x in value:
#         new_value = ZOTERO_FIELDS_TO_CSL_MAPPING[x]
#         new_values.append(new_value)
#     res[key] = new_values


CITATION_TYPE_FIELDS = {
    JOURNAL_ARTICLE: [
        "title",
        "abstract",
        "container-title",
        "volume",
        "issue",
        "page",
        "collection-title",
        "collection-title",
        "journalAbbreviation",
        "language",
        "DOI",
        "ISSN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    ARTWORK: [
        "title",
        "abstract",
        "medium",
        "dimensions",
        "language",
        "title-short",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "URL",
        "license",
    ],
    AUDIO_RECORDING: [
        "title",
        "abstract",
        "medium",
        "collection-title",
        "volume",
        "number-of-volumes",
        "publisher-place",
        "publisher",
        "dimensions",
        "language",
        "ISBN",
        "title-short",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "URL",
        "license",
    ],
    BILL: [
        "title",
        "abstract",
        "number",
        "container-title",
        "volume",
        "section",
        "page",
        "authority",
        "chapter-number",
        "references",
        "language",
        "URL",
        "title-short",
        "license",
    ],
    BLOG_POST: [
        "title",
        "abstract",
        "container-title",
        "genre",
        "URL",
        "language",
        "title-short",
        "license",
    ],
    BOOK: [
        "title",
        "abstract",
        "collection-title",
        "collection-number",
        "volume",
        "number-of-volumes",
        "edition",
        "publisher-place",
        "publisher",
        "number-of-pages",
        "language",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    BOOK_SECTION: [
        "title",
        "abstract",
        "container-title",
        "collection-title",
        "collection-number",
        "volume",
        "number-of-volumes",
        "edition",
        "publisher-place",
        "publisher",
        "page",
        "language",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    CASE: [
        "title",
        "abstract",
        "authority",
        "number",
        "container-title",
        "volume",
        "page",
        "references",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    SOFTWARE: [
        "title",
        "abstract",
        "collection-title",
        "version",
        "medium",
        "publisher-place",
        "publisher",
        "genre",
        "ISBN",
        "title-short",
        "URL",
        "license",
        "archive",
        "archive_location",
        "source",
        "call-number",
    ],
    CONFERENCE_PAPER: [
        "title",
        "abstract",
        "container-title",
        "event-title",
        "publisher-place",
        "publisher",
        "volume",
        "page",
        "collection-title",
        "language",
        "DOI",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    DICTIONARY_ENTRY: [
        "title",
        "abstract",
        "container-title",
        "collection-title",
        "collection-number",
        "volume",
        "number-of-volumes",
        "edition",
        "publisher-place",
        "publisher",
        "page",
        "language",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    DOCUMENT: [
        "title",
        "abstract",
        "publisher",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    EMAIL: ["title", "abstract", "title-short", "URL", "language", "license"],
    ENCYCLOPEDIA_ARTICLE: [
        "title",
        "abstract",
        "container-title",
        "collection-title",
        "collection-number",
        "volume",
        "number-of-volumes",
        "edition",
        "publisher-place",
        "publisher",
        "page",
        "ISBN",
        "title-short",
        "URL",
        "language",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    FILM: [
        "title",
        "abstract",
        "publisher",
        "genre",
        "medium",
        "dimensions",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    FORUM_POST: [
        "title",
        "abstract",
        "container-title",
        "genre",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    HEARING: [
        "title",
        "abstract",
        "section",
        "publisher-place",
        "publisher",
        "number-of-volumes",
        "number",
        "page",
        "authority",
        "chapter-number",
        "references",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    INSTANT_MESSAGE: [
        "title",
        "abstract",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    INTERVIEW: [
        "title",
        "abstract",
        "medium",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    LETTER: [
        "title",
        "abstract",
        "genre",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    MAGAZINE_ARTICLE: [
        "title",
        "abstract",
        "container-title",
        "volume",
        "issue",
        "page",
        "language",
        "ISSN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    MANUSCRIPT: [
        "title",
        "abstract",
        "genre",
        "publisher-place",
        "number-of-pages",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    MAP: [
        "title",
        "abstract",
        "genre",
        "scale",
        "collection-title",
        "edition",
        "publisher-place",
        "publisher",
        "language",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    NEWSPAPER_ARTICLE: [
        "title",
        "abstract",
        "container-title",
        "publisher-place",
        "edition",
        "section",
        "page",
        "language",
        "title-short",
        "ISSN",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    PATENT: [
        "title",
        "abstract",
        "publisher-place",
        "authority",
        "number",
        "page",
        "call-number",
        "issue",
        "references",
        "status",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    PODCAST: [
        "title",
        "abstract",
        "collection-title",
        "number",
        "medium",
        "dimensions",
        "URL",
        "language",
        "title-short",
        "license",
    ],
    PREPRINT: [
        "title",
        "abstract",
        "genre",
        "publisher",
        "number",
        "publisher-place",
        "collection-title",
        "collection-number",
        "DOI",
        "URL",
        "archive",
        "archive_location",
        "title-short",
        "language",
        "source",
        "call-number",
        "license",
    ],
    PRESENTATION: [
        "title",
        "abstract",
        "genre",
        "publisher-place",
        "event-title",
        "URL",
        "language",
        "title-short",
        "license",
    ],
    RADIO_BROADCAST: [
        "title",
        "abstract",
        "container-title",
        "number",
        "medium",
        "publisher-place",
        "publisher",
        "dimensions",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    REPORT: [
        "title",
        "abstract",
        "number",
        "genre",
        "collection-title",
        "publisher-place",
        "publisher",
        "page",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    STATUTE: [
        "title",
        "abstract",
        "container-title",
        "volume",
        "number",
        "page",
        "section",
        "chapter-number",
        "references",
        "language",
        "title-short",
        "URL",
        "license",
    ],
    THESIS: [
        "title",
        "abstract",
        "genre",
        "publisher",
        "publisher-place",
        "number-of-pages",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    TV_BROADCAST: [
        "title",
        "abstract",
        "container-title",
        "number",
        "medium",
        "publisher-place",
        "publisher",
        "dimensions",
        "language",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    VIDEO_RECORDING: [
        "title",
        "abstract",
        "medium",
        "collection-title",
        "volume",
        "number-of-volumes",
        "publisher-place",
        "publisher",
        "dimensions",
        "language",
        "ISBN",
        "title-short",
        "URL",
        "archive",
        "archive_location",
        "source",
        "call-number",
        "license",
    ],
    WEBPAGE: [
        "title",
        "abstract",
        "container-title",
        "genre",
        "title-short",
        "URL",
        "language",
        "license",
    ],
}
