# Generated by Django 4.1 on 2023-01-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="researchhub_comment.rhcommentmodel",
            ),
        ),
    ]
