# Generated by Django 4.1 on 2023-06-01 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rhcommentmodel",
            name="anonymous",
        ),
        migrations.RemoveField(
            model_name="rhcommentmodel",
            name="encryptcomment_ptr",
        ),
        migrations.AddField(
            model_name="rhcommentmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rhcommentmodel",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="EncryptComment",
        ),
    ]
