# Generated by Django 4.1 on 2023-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0002_rhcommentmodel_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="legacy_model_name",
            field=models.CharField(
                choices=[
                    ("COMMENT", "COMMENT"),
                    ("REPLY", "REPLY"),
                    ("THREAD", "THREAD"),
                ],
                default="QUILL_EDITOR",
                max_length=144,
            ),
        ),
    ]
