# Generated by Django 4.1 on 2023-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0003_rhcommentmodel_legacy_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rhcommentmodel",
            name="legacy_model_name",
        ),
        migrations.AddField(
            model_name="rhcommentmodel",
            name="legacy_model_type",
            field=models.CharField(
                choices=[
                    ("LEGACY_COMMENT", "LEGACY_COMMENT"),
                    ("LEGACY_REPLY", "LEGACY_REPLY"),
                    ("LEGACY_THREAD", "LEGACY_THREAD"),
                ],
                default="LEGACY_COMMENT",
                max_length=144,
            ),
        ),
    ]
