# Generated by Django 4.1 on 2023-01-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0003_alter_rhcommentmodel_created_by_and_more"),
        (
            "researchhub_comment",
            "0004_remove_rhcommentmodel_legacy_model_name_and_more",
        ),
    ]

    operations = []
