# Generated by Django 4.1 on 2023-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0005_merge_20230119_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="legacy_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
