# Generated by Django 4.1 on 2023-03-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0007_alter_rhcommentthreadmodel_thread_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="comment_content_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="context_title",
            field=models.TextField(
                blank=True,
                help_text="\n            Provides a sumamry / headline to give context to the comment.\n            A commont use-case for this is for inline comments & citation comments\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="researchhub_comment.rhcommentmodel",
            ),
        ),
    ]
