# Generated by Django 4.1 on 2023-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0009_alter_rhcommentthreadmodel_thread_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="comment_content_src",
            field=models.FileField(
                blank=True,
                help_text="Src may be blank but never null upon saving.",
                max_length=1024,
                null=True,
                upload_to="uploads/rh_comment/%Y/%m/%d/",
            ),
        ),
    ]
