# Generated by Django 4.1 on 2023-04-11 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researchhub_comment", "0010_alter_rhcommentmodel_comment_content_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Last user to update the instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rhcommentthreadmodel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rhcommentthreadmodel",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Last user to update the instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
