# Generated by Django 4.1 on 2023-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0012_rhcommentmodel_is_accepted_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="is_removed_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
