# Generated by Django 4.1 on 2023-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0013_rhcommentmodel_is_removed_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
