# Generated by Django 4.1 on 2023-04-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0012_alter_rhcommentmodel_updated_by_and_more"),
        ("researchhub_comment", "0014_rhcommentmodel_score"),
    ]

    operations = []
