# Generated by Django 4.1 on 2023-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0015_merge_20230411_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentthreadmodel",
            name="anchor",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
