# Generated by Django 4.1 on 2023-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0016_rhcommentthreadmodel_anchor"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("GENERIC_COMMENT", "GENERIC_COMMENT"),
                    ("INNER_CONTENT_COMMENT", "INNER_CONTENT_COMMENT"),
                    ("ANSWER", "ANSWER"),
                    ("REVIEW", "REVIEW"),
                    ("SUMMARY", "SUMMARY"),
                ],
                default="GENERIC_COMMENT",
                max_length=144,
            ),
        ),
    ]
