# Generated by Django 4.2.16 on 2024-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0018_alter_rhcommentmodel_comment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="comment_type",
            field=models.CharField(
                choices=[
                    ("GENERIC_COMMENT", "GENERIC_COMMENT"),
                    ("INNER_CONTENT_COMMENT", "INNER_CONTENT_COMMENT"),
                    ("ANSWER", "ANSWER"),
                    ("REVIEW", "REVIEW"),
                    ("PEER_REVIEW", "PEER_REVIEW"),
                    ("SUMMARY", "SUMMARY"),
                    ("REPLICABILITY_COMMENT", "REPLICABILITY_COMMENT"),
                ],
                default="GENERIC_COMMENT",
                max_length=144,
            ),
        ),
        migrations.AlterField(
            model_name="rhcommentthreadmodel",
            name="thread_type",
            field=models.CharField(
                choices=[
                    ("GENERIC_COMMENT", "GENERIC_COMMENT"),
                    ("INNER_CONTENT_COMMENT", "INNER_CONTENT_COMMENT"),
                    ("ANSWER", "ANSWER"),
                    ("REVIEW", "REVIEW"),
                    ("PEER_REVIEW", "PEER_REVIEW"),
                    ("SUMMARY", "SUMMARY"),
                    ("REPLICABILITY_COMMENT", "REPLICABILITY_COMMENT"),
                ],
                default="GENERIC_COMMENT",
                max_length=144,
            ),
        ),
    ]
