# Generated by Django 5.1.4 on 2025-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0019_alter_rhcommentmodel_comment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="html",
            field=models.TextField(
                blank=True,
                help_text="HTML representation of the comment content",
                null=True,
            ),
        ),
    ]
