# Generated by Django 5.1.5 on 2025-02-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0019_alter_rhcommentmodel_comment_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rhcommentmodel",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="rhcommentmodel",
            name="legacy_model_type",
        ),
    ]
