# Generated by Django 5.1.4 on 2025-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0020_alter_rhcommentmodel_comment_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhcommentmodel",
            name="comment_content_type",
            field=models.CharField(
                choices=[
                    ("CK_EDITOR", "CK_EDITOR"),
                    ("QUILL_EDITOR", "QUILL_EDITOR"),
                    ("TEXT", "TEXT"),
                ],
                default="QUILL_EDITOR",
                max_length=144,
            ),
        ),
    ]
