# Generated by Django 5.1.4 on 2025-03-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0020_remove_rhcommentmodel_legacy_id_and_more"),
        ("researchhub_comment", "0021_alter_rhcommentmodel_comment_content_type"),
    ]

    operations = []
