# Generated by Django 5.1.4 on 2025-04-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0020_alter_rhcommentmodel_comment_content_type"),
        ("researchhub_comment", "0022_merge_20250306_1232"),
    ]

    operations = []
