# Generated by Django 5.2.7 on 2025-10-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_comment', '0023_alter_rhcommentmodel_comment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhcommentthreadmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
