# Generated by Django 5.2.8 on 2025-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0023_alter_rhcommentmodel_comment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rhcommentthreadmodel",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
