# Generated by Django 5.2.2 on 2025-08-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0023_alter_rhcommentmodel_comment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhcommentmodel",
            name="ai_score",
            field=models.FloatField(
                blank=True,
                help_text="AI-generated probability in [0,1]. Use -1 to indicate scoring error.",
                null=True,
            ),
        ),
    ]
