# Generated by Django 5.2

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("researchhub_comment", "0024_alter_rhcommentthreadmodel_updated_date"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="rhcommentmodel",
            index=models.Index(fields=["comment_type"], name="rh_comment_type_idx"),
        ),
    ]
