# Generated by Django 2.2.5 on 2019-09-23 22:22

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete='CASCADE', related_name='summary', to='paper.Paper')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
