# Generated by Django 2.2.5 on 2019-10-02 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0004_auto_20191002_1744'),
        ('summary', '0003_auto_20191002_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='user',
        ),
        migrations.AddField(
            model_name='summary',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='SET NULL', related_name='approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summary',
            name='paper',
            field=models.ForeignKey(default=None, on_delete='CASCADE', related_name='summaries', to='paper.Paper'),
        ),
        migrations.AddField(
            model_name='summary',
            name='proposed_by',
            field=models.ForeignKey(default=None, on_delete='SET NULL', related_name='edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='previous',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='SET NULL', related_name='next', to='summary.Summary'),
        ),
    ]
