# Generated by Django 2.2.5 on 2019-10-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20191002_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='paper.Paper'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to=settings.AUTH_USER_MODEL),
        ),
    ]
