# Generated by Django 2.2.6 on 2019-10-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_auto_20191002_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='approved_at',
            new_name='approved_date',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
