# Generated by Django 2.2 on 2020-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_summary_created_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
