# Generated by Django 2.2 on 2020-11-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_summary_sift_risk_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='sift_risk_score',
        ),
    ]
