# Generated by Django 2.2 on 2020-11-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_auto_20201116_2230'),
        ('summary', '0012_remove_summary_sift_risk_score'),
    ]

    operations = [
    ]
