# Generated by Django 4.2.14 on 2024-08-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0014_alter_summary_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="summary",
        ),
        migrations.DeleteModel(
            name="Summary",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
