# Generated by Django 4.1 on 2023-02-15 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0091_action_is_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citation_type",
                    models.CharField(
                        choices=[
                            ("ARTWORK", "ARTWORK"),
                            ("AUDIO_RECORDING", "AUDIO_RECORDING"),
                            ("BILL", "BILL"),
                            ("BLOG_POST", "BLOG_POST"),
                            ("BOOK", "BOOK"),
                            ("BOOK_SECTION", "BOOK_SECTION"),
                            ("CASE", "CASE"),
                            ("CONFERENCE_PAPER", "CONFERENCE_PAPER"),
                            ("DICTIONARY_ENTRY", "DICTIONARY_ENTRY"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("EMAIL", "EMAIL"),
                            ("ENCYCLOPEDIA_ARTICLE", "ENCYCLOPEDIA_ARTICLE"),
                            ("FILM", "FILM"),
                            ("FORUM_POST", "FORUM_POST"),
                            ("HEARING", "HEARING"),
                            ("INSTANT_MESSAGE", "INSTANT_MESSAGE"),
                            ("INTERVIEW", "INTERVIEW"),
                            ("JOURNAL_ARTICLE", "JOURNAL_ARTICLE"),
                            ("LETTER", "LETTER"),
                            ("MAGAZINE_ARTICLE", "MAGAZINE_ARTICLE"),
                            ("MANUSCRIPT", "MANUSCRIPT"),
                            ("MAP", "MAP"),
                            ("NEWSPAPER_ARTICLE", "NEWSPAPER_ARTICLE"),
                            ("PATENT", "PATENT"),
                            ("PODCAST", "PODCAST"),
                            ("PREPRINT", "PREPRINT"),
                            ("PRESENTATION", "PRESENTATION"),
                            ("RADIO_BROADCAST", "RADIO_BROADCAST"),
                            ("REPORT", "REPORT"),
                            ("SOFTWARE", "SOFTWARE"),
                            ("STATUTE", "STATUTE"),
                            ("THESIS", "THESIS"),
                            ("TV_BROADCAST", "TV_BROADCAST"),
                            ("VIDEO_RECORDING", "VIDEO_RECORDING"),
                            ("WEB_PAGE", "WEB_PAGE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("checksum", models.CharField(max_length=16)),
                ("fields", models.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_citations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_citations",
                        to="user.organization",
                    ),
                ),
            ],
        ),
    ]
