# Generated by Django 4.1 on 2023-04-07 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationentry",
            name="attachment",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=1024,
                null=True,
                upload_to="uploads/citation_entry/attachment/%Y/%m/%d",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="citationentry",
            name="doi",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
