# Generated by Django 4.1 on 2023-04-11 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("citation", "0002_citationentry_attachment_citationentry_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationentry",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citationentry",
            name="updated_by",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                help_text="Last user to update the instance",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="citationentry",
            name="updated_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 4, 11, 9, 19, 52, 758860, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="citationentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
