# Generated by Django 4.1 on 2023-04-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0004_citationproject_citationentry_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                related_query_name="citations",
                to="citation.citationproject",
            ),
        ),
    ]
