# Generated by Django 4.1 on 2023-05-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0005_alter_citationentry_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationproject",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="citation.citationproject",
            ),
        ),
    ]
