# Generated by Django 4.1 on 2023-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0006_citationproject_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationproject",
            name="is_public",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
