# Generated by Django 4.1 on 2023-05-17 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0007_citationproject_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationproject",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="citation.citationproject",
            ),
        ),
    ]
