# Generated by Django 4.1 on 2023-06-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0112_paper_score"),
        ("citation", "0007_citationproject_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationentry",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citation_entries",
                to="paper.paper",
            ),
        ),
    ]
