# Generated by Django 4.1 on 2023-06-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0052_researchhubpost_score"),
        ("citation", "0008_citationentry_paper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citationentry",
            name="paper",
        ),
        migrations.AddField(
            model_name="citationentry",
            name="unified_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citation_entries",
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
    ]
