# Generated by Django 4.1 on 2023-08-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0052_researchhubpost_score"),
        ("citation", "0009_remove_citationentry_paper_citationentry_unified_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citationentry",
            name="unified_doc",
        ),
        migrations.AddField(
            model_name="citationentry",
            name="related_unified_doc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citation_entries",
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
    ]
