# Generated by Django 4.1 on 2023-08-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0011_citationproject_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationproject",
            name="parent_names",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
