# Generated by Django 4.1 on 2023-11-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0013_alter_citationentry_citation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationproject",
            name="status",
            field=models.CharField(default="full_access", max_length=32),
        ),
    ]
