# Generated by Django 5.2.2 on 2025-08-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0015_alter_citationentry_citation_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citationproject",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="citationproject",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="citationproject",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="citationproject",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="CitationEntry",
        ),
        migrations.DeleteModel(
            name="CitationProject",
        ),
    ]
