# Generated by Django 5.2.2 on 2025-07-03 09:45

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_post_slugs(apps, schema_editor):
    Flag = apps.get_model('discussion', 'flag')

    for flag in Flag.objects.all().iterator():
        if hasattr(flag, 'verdict'):
            veridct = flag.verdict
            flag.verdict_created_date = veridct.created_date
            flag.save()


class Migration(migrations.Migration):

    replaces = [('discussion', '0001_initial'), ('discussion', '0002_auto_20190920_2154'), ('discussion', '0003_vote'), ('discussion', '0004_flag'), ('discussion', '0005_auto_20190930_2241'), ('discussion', '0006_auto_20191001_2028'), ('discussion', '0007_auto_20191002_1514'), ('discussion', '0008_auto_20191007_2154'), ('discussion', '0009_auto_20191009_1036'), ('discussion', '0010_vote_updated_date'), ('discussion', '0011_endorsement'), ('discussion', '0012_auto_20191021_1556'), ('discussion', '0013_auto_20191030_2036'), ('discussion', '0014_auto_20191118_2247'), ('discussion', '0015_auto_20200110_1620'), ('discussion', '0016_auto_20200116_1617'), ('discussion', '0017_auto_20200122_1931'), ('discussion', '0018_auto_20200213_2311'), ('discussion', '0019_auto_20200213_2326'), ('discussion', '0020_auto_20200224_2002'), ('discussion', '0021_auto_20200429_2210'), ('discussion', '0022_externalcomment_externalreply_externalthread'), ('discussion', '0023_auto_20200529_2137'), ('discussion', '0024_auto_20200530_0131'), ('discussion', '0025_auto_20200602_2014'), ('discussion', '0026_auto_20200623_1640'), ('discussion', '0027_auto_20201104_2202'), ('discussion', '0028_auto_20201105_2054'), ('discussion', '0029_auto_20201114_0204'), ('discussion', '0030_auto_20210312_2017'), ('discussion', '0031_auto_20210312_2048'), ('discussion', '0032_auto_20210331_2158'), ('discussion', '0033_thread_context_title'), ('discussion', '0034_auto_20210406_1915'), ('discussion', '0035_remove_thread_metadata'), ('discussion', '0036_auto_20210415_2112'), ('discussion', '0037_thread_post'), ('discussion', '0038_thread_hypothesis'), ('discussion', '0039_auto_20210811_0348'), ('discussion', '0040_auto_20210915_2206'), ('discussion', '0041_auto_20211006_0640'), ('discussion', '0042_thread_peer_review'), ('discussion', '0043_thread_review'), ('discussion', '0044_auto_20220422_2006'), ('discussion', '0045_flag_hubs'), ('discussion', '0046_flag_reason_choice'), ('discussion', '0047_auto_20220517_1254'), ('discussion', '0048_auto_20220517_1322'), ('discussion', '0049_auto_20220524_2238'), ('discussion', '0050_auto_20220719_2333'), ('discussion', '0051_auto_20220720_1935'), ('discussion', '0052_thread_is_accepted_answer'), ('discussion', '0053_comment_is_accepted_answer'), ('discussion', '0054_alter_comment_external_metadata_alter_comment_text_and_more'), ('discussion', '0055_comment_score_reply_score_thread_score'), ('discussion', '0056_remove_thread_citation_remove_thread_hypothesis'), ('discussion', '0057_remove_thread_peer_review'), ('discussion', '0058_remove_reply_content_type_remove_reply_created_by_and_more')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hub', '0019_remove_hubmembership_created_at'),
        ('paper', '0001_initial'),
        ('paper', '0019_merge_20191202_1931'),
        ('paper', '0057_figure_created_location'),
        ('researchhub_document', '0013_auto_20210604_1925'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Upvote'), (2, 'Downvote')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_votes', to=settings.AUTH_USER_MODEL)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'created_by'), name='unique_vote')],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_endorsement')],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hubs', models.ManyToManyField(related_name='flags', to='hub.hub')),
                ('reason_choice', models.CharField(blank=True, choices=[('ABUSIVE_OR_RUDE', 'ABUSIVE_OR_RUDE'), ('COPYRIGHT', 'COPYRIGHT'), ('LOW_QUALITY', 'LOW_QUALITY'), ('NOT_CONSTRUCTIVE', 'NOT_CONSTRUCTIVE'), ('PLAGIARISM', 'PLAGIARISM'), ('SPAM', 'SPAM'), ('NOT_SPECIFIED', 'NOT_SPECIFIED')], max_length=255)),
                ('verdict_created_date', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'created_by'), name='unique_flag')],
            },
        ),
        migrations.RunPython(
            code=add_post_slugs,
        ),
    ]
