# Generated by Django 2.2.5 on 2019-09-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='paper.Paper'),
        ),
    ]
