# Generated by Django 2.2.5 on 2019-10-02 15:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20191001_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
