# Generated by Django 2.2.6 on 2019-10-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_auto_20191002_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='was_edited',
            field=models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.'),
        ),
        migrations.AddField(
            model_name='reply',
            name='was_edited',
            field=models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='was_edited',
            field=models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.'),
        ),
    ]
