# Generated by Django 2.2.6 on 2019-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_auto_20191007_2154'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'created_by'), name='unique_vote'),
        ),
    ]
