# Generated by Django 2.2.6 on 2019-10-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_auto_20191009_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
