# Generated by Django 2.2.6 on 2019-10-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0011_endorsement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endorsement',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_endorsement'),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'created_by'), name='unique_flag'),
        ),
    ]
