# Generated by Django 2.2.9 on 2020-01-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0019_merge_20191202_1931'),
        ('discussion', '0014_auto_20191118_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.Paper'),
        ),
        migrations.AddField(
            model_name='reply',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.Paper'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paper.Paper'),
        ),
    ]
