# Generated by Django 2.2.9 on 2020-01-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0015_auto_20200110_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='paper.Paper'),
        ),
    ]
