# Generated by Django 2.2.9 on 2020-01-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0016_auto_20200116_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='paper',
        ),
    ]
