# Generated by Django 2.2.9 on 2020-02-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0017_auto_20200122_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_removed',
            new_name='is_censored',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='is_removed',
            new_name='is_censored',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='is_removed',
            new_name='is_censored',
        ),
    ]
