# Generated by Django 2.2.10 on 2020-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0019_auto_20200213_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
