# Generated by Django 2.2.12 on 2020-04-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0020_auto_20200224_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
