# Generated by Django 2.2.12 on 2020-05-29 21:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0021_auto_20200429_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('was_edited', models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.')),
                ('is_public', models.BooleanField(default=True, help_text='Hides the comment from the public.')),
                ('is_removed', models.BooleanField(default=False, help_text='Hides the comment because it is not allowed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, default='')),
                ('source_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('was_edited', models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.')),
                ('is_public', models.BooleanField(default=True, help_text='Hides the comment from the public.')),
                ('is_removed', models.BooleanField(default=False, help_text='Hides the comment because it is not allowed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, default='')),
                ('source_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('was_edited', models.BooleanField(default=False, help_text='True if the comment text was edited after first being created.')),
                ('is_public', models.BooleanField(default=True, help_text='Hides the comment from the public.')),
                ('is_removed', models.BooleanField(default=False, help_text='Hides the comment because it is not allowed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, default='')),
                ('source_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
