# Generated by Django 2.2.12 on 2020-05-30 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0023_auto_20200529_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_comments', to='discussion.ExternalThread'),
        ),
    ]
