# Generated by Django 2.2.12 on 2020-06-02 20:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0024_auto_20200530_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalreply',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='externalreply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='externalthread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='externalthread',
            name='paper',
        ),
        migrations.AddField(
            model_name='comment',
            name='external_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.CharField(default='researchhub', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='external_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='source',
            field=models.CharField(default='researchhub', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='external_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='source',
            field=models.CharField(default='researchhub', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='ExternalComment',
        ),
        migrations.DeleteModel(
            name='ExternalReply',
        ),
        migrations.DeleteModel(
            name='ExternalThread',
        ),
    ]
