# Generated by Django 2.2.13 on 2020-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0025_auto_20200602_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_location',
            field=models.CharField(blank=True, choices=[('PROGRESS', 'Progress')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='created_location',
            field=models.CharField(blank=True, choices=[('PROGRESS', 'Progress')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_location',
            field=models.CharField(blank=True, choices=[('PROGRESS', 'Progress')], default=None, max_length=255, null=True),
        ),
    ]
