# Generated by Django 2.2 on 2020-11-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0028_auto_20201105_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sift_risk_score',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='sift_risk_score',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='sift_risk_score',
        ),
    ]
