# Generated by Django 2.2 on 2021-03-12 20:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0029_auto_20201114_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='source',
            field=models.CharField(choices=[('paper', 'Paper'), ('inline_abstract', 'Inline Abstract'), ('inline_paper_body', 'Inline Paper Body')], default='paper', max_length=32),
        ),
    ]
