# Generated by Django 2.2 on 2021-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0032_auto_20210331_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='context_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
