# Generated by Django 2.2 on 2021-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0033_thread_context_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='context_title',
            field=models.TextField(blank=True, help_text="For inline-comments, indicates what's highlighted", null=True),
        ),
    ]
