# Generated by Django 2.2 on 2021-04-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0034_auto_20210406_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='metadata',
        ),
    ]
