# Generated by Django 2.2 on 2021-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0035_remove_thread_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='source',
            field=models.CharField(choices=[('researchhub', 'researchhub'), ('inline_abstract', 'Inline Abstract'), ('inline_paper_body', 'Inline Paper Body')], default='researchhub', max_length=32),
        ),
    ]
