# Generated by Django 2.2 on 2021-08-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('hypothesis', '0001_initial'),
        ('discussion', '0037_thread_post'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='thread',
        #     name='hypothesis',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypothesis', to='hypothesis.Hypothesis'),
        # ),
    ]
