# Generated by Django 2.2 on 2021-08-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0038_thread_hypothesis'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='thread',
        #     name='hypothesis',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='hypothesis.Hypothesis'),
        # ),
    ]
