# Generated by Django 2.2 on 2021-09-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0039_auto_20210811_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Upvote'), (2, 'Downvote')]),
        ),
    ]
