# Generated by Django 2.2 on 2021-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('hypothesis', '0007_auto_20210915_2305'),
        ('discussion', '0040_auto_20210915_2206'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='thread',
        #     name='citation',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='hypothesis.Citation'),
        # ),
        migrations.AlterField(
            model_name='thread',
            name='source',
            field=models.CharField(choices=[('citation_comment', 'Citation Comment'), ('inline_abstract', 'Inline Abstract'), ('inline_paper_body', 'Inline Paper Body'), ('researchhub', 'researchhub')], default='researchhub', max_length=32),
        ),
    ]
