# Generated by Django 2.2 on 2022-04-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0041_auto_20211006_0640'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='thread',
        #     name='peer_review',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='peer_review.PeerReview'),
        # ),
    ]
