# Generated by Django 2.2 on 2022-04-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0042_thread_peer_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=None, null=True)),
                ('thread', models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='discussion.Thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
