# Generated by Django 2.2 on 2022-04-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('discussion', '0042_thread_peer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='review',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='review.Review'),
        ),
    ]
