# Generated by Django 2.2 on 2022-04-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0043_thread_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='review.Review'),
        ),
    ]
