# Generated by Django 2.2 on 2022-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_remove_hubmembership_created_at'),
        ('discussion', '0044_auto_20220422_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='hubs',
            field=models.ManyToManyField(related_name='flags', to='hub.Hub'),
        ),
    ]
