# Generated by Django 2.2 on 2022-04-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0044_remove_review_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='review',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='discussion.Review'),
        ),
    ]
