# Generated by Django 2.2 on 2022-05-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0044_auto_20220422_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='reason_choices',
            field=models.CharField(choices=[('ABUSIVE_OR_RUDE', 'ABUSIVE_OR_RUDE'), ('COPY_RIGHT', 'COPY_RIGHT'), ('LOW_QUALITY', 'LOW_QUALITY'), ('NOT_CONSTRUCTIVE', 'NOT_CONSTRUCTIVE'), ('PLAGIARISM', 'PLAGIARISM'), ('SPAM', 'SPAM')], default='SPAM', max_length=225),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(blank=True, help_text='May be deprecated', max_length=255),
        ),
        migrations.AlterField(
            model_name='flag',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
