# Generated by Django 2.2 on 2022-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0045_flag_hubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='reason_choice',
            field=models.CharField(blank=True, choices=[('ABUSIVE_OR_RUDE', 'ABUSIVE_OR_RUDE'), ('COPYRIGHT', 'COPYRIGHT'), ('LOW_QUALITY', 'LOW_QUALITY'), ('NOT_CONSTRUCTIVE', 'NOT_CONSTRUCTIVE'), ('PLAGIARISM', 'PLAGIARISM'), ('SPAM', 'SPAM')], max_length=255),
        ),
    ]
