# Generated by Django 2.2 on 2022-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0047_auto_20220517_1254'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'created_by'), name='unique_flag'),
        ),
    ]
