# Generated by Django 2.2 on 2022-04-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0047_auto_20220420_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='review',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='review.Review'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
