# Generated by Django 2.2 on 2022-04-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0048_auto_20220421_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='review',
        ),
    ]
