# Generated by Django 2.2 on 2022-07-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0049_auto_20220524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discussion_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('SUMMARY', 'SUMMARY'), ('REVIEW', 'REVIEW'), ('ANSWER', 'ANSWER')], default='DISCUSSION', max_length=16),
        ),
        migrations.AddField(
            model_name='reply',
            name='discussion_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('SUMMARY', 'SUMMARY'), ('REVIEW', 'REVIEW'), ('ANSWER', 'ANSWER')], default='DISCUSSION', max_length=16),
        ),
        migrations.AddField(
            model_name='thread',
            name='discussion_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('SUMMARY', 'SUMMARY'), ('REVIEW', 'REVIEW'), ('ANSWER', 'ANSWER')], default='DISCUSSION', max_length=16),
        ),
    ]
