# Generated by Django 2.2 on 2022-05-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0049_auto_20220524_1823'),
        ('discussion', '0049_auto_20220524_2238'),
    ]

    operations = [
    ]
