# Generated by Django 2.2 on 2022-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0049_auto_20220524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
