# Generated by Django 2.2 on 2022-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0050_thread_is_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
