# Generated by Django 2.2 on 2022-07-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0051_auto_20220720_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_accepted_answer',
            field=models.BooleanField(blank=True, default=None, help_text="Used to indicate that this thread is a O/P's selected answer for bounties & Questions.             Empty field implies that related document is irrelevant to this field", null=True),
        ),
    ]
