# Generated by Django 2.2 on 2022-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0051_auto_20220712_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('SUMMARY', 'SUMMARY'), ('REVIEW', 'REVIEW'), ('ANSWER', 'ANSWER'), ('SUMMARY_REQUEST', 'SUMMARY_REQUEST'), ('REVIEW_REQUEST', 'REVIEW_REQUEST'), ('OTHER_REQUEST', 'OTHER_REQUEST')], default='DISCUSSION', max_length=16),
        ),
    ]
