# Generated by Django 2.2 on 2022-07-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0052_thread_thread_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('DISCUSSION', 'DISCUSSION'), ('SUMMARY', 'SUMMARY'), ('REVIEW', 'REVIEW'), ('ANSWER', 'ANSWER')], default='DISCUSSION', max_length=16),
        ),
    ]
