# Generated by Django 2.2 on 2022-08-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0052_thread_is_accepted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_accepted_answer',
            field=models.BooleanField(blank=True, default=None, help_text="Used to indicate that this thread is a O/P's selected answer for bounties & Questions.             Empty field implies that related document is irrelevant to this field", null=True),
        ),
    ]
