# Generated by Django 4.1 on 2022-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0053_comment_is_accepted_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="external_metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="external_metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="external_metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="text",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
