# Generated by Django 4.1 on 2023-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discussion",
            "0054_alter_comment_external_metadata_alter_comment_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reply",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="thread",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
