# Generated by Django 4.2.13 on 2024-06-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0055_comment_score_reply_score_thread_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="peer_review",
        ),
    ]
