# Generated by Django 4.2.14 on 2024-08-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0055_comment_score_reply_score_thread_score"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="thread",
        #     name="citation",
        # ),
        # migrations.RemoveField(
        #     model_name="thread",
        #     name="hypothesis",
        # ),
    ]
