# Generated by Django 5.1.5 on 2025-03-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0057_remove_thread_peer_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="paper",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="post",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="review",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
