# Generated by Django 5.2.2 on 2025-09-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discussion",
            "0058_remove_reply_content_type_remove_reply_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="reason_memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
