# Generated by Django 5.2.13 on 2026-04-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0059_flag_reason_memo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Endorsement",
        ),
    ]
