RH_COMMENT_FIELDS = [
    "children",
    "children_count",
    "comment_content_json",
    "comment_content_type",
    "context_title",
    "created_date",
    "created_by",
    "updated_by",
    "id",
    "is_accepted_answer",
    "is_edited",
    "parent",
    "thread",
    "updated_date",
]
RH_COMMENT_READ_ONLY_FIELDS = [
    "children",
    "created_date",
    "is_accepted_answer",
    "id",
    "is_edited",
    "updated_date",
    "legacy_model_type",
    "legacy_id",
]
