# Generated by Django 2.2.11 on 2020-03-19 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0030_paper_retrieved_from_external_source'),
        ('notification', '0002_auto_20200319_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paper.Paper'),
            preserve_default=False,
        ),
    ]
