# Generated by Django 2.2.11 on 2020-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
