# Generated by Django 2.2.11 on 2020-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_read_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator',
            new_name='action_user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
