# Generated by Django 2.2 on 2021-07-07 23:44

from django.db import migrations, models
import django.db.models.deletion


def migrate_paper_to_unified_document(apps, schema_editor):
    Notification = apps.get_model('notification', 'notification')
    notifications = Notification.objects.filter(paper__isnull=False)

    for notification in notifications.iterator():
        unified_document = notification.paper.unified_document
        notification.unified_document = unified_document
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0020_researchhubpost_slug'),
        ('notification', '0006_auto_20201027_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unified_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(migrate_paper_to_unified_document),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
