# Generated by Django 2.2 on 2021-09-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_remove_notification_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='extra',
        ),
    ]
