# Generated by Django 2.2 on 2022-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_remove_notification_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
