# Generated by Django 4.1 on 2023-03-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0010_auto_20220922_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DEPRECATED", "DEPRECATED"),
                    ("RSC_WITHDRAWAL_COMPLETE", "RSC_WITHDRAWAL_COMPLETE"),
                    ("RSC_SUPPORT_ON_DOC", "RSC_SUPPORT_ON_DOC"),
                    ("RSC_SUPPORT_ON_DIS", "RSC_SUPPORT_ON_DIS"),
                    ("FLAGGED_CONTENT_VERDICT", "FLAGGED_CONTENT_VERDICT"),
                    ("BOUNTY_EXPIRING_SOON", "BOUNTY_EXPIRING_SOON"),
                    ("DIS_ON_BOUNTY", "DIS_ON_BOUNTY"),
                    ("COMMENT", "COMMENT"),
                    ("COMMENT_ON_COMMENT", "COMMENT_ON_COMMENT"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
