# Generated by Django 2.2 on 2022-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20220922_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='navigation_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
