# Generated by Django 2.2 on 2022-09-26 22:32

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20220922_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
