# Generated by Django 4.1 on 2023-02-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0010_auto_20220922_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("DEPRECATED", "DEPRECATED"),
                    ("THREAD_ON_DOC", "THREAD_ON_DOC"),
                    ("COMMENT_ON_THREAD", "COMMENT_ON_THREAD"),
                    ("REPLY_ON_THREAD", "REPLY_ON_THREAD"),
                    ("RSC_WITHDRAWAL_COMPLETE", "RSC_WITHDRAWAL_COMPLETE"),
                    ("RSC_SUPPORT_ON_DOC", "RSC_SUPPORT_ON_DOC"),
                    ("RSC_SUPPORT_ON_DIS", "RSC_SUPPORT_ON_DIS"),
                    ("FLAGGED_CONTENT_VERDICT", "FLAGGED_CONTENT_VERDICT"),
                    ("BOUNTY_EXPIRING_SOON", "BOUNTY_EXPIRING_SOON"),
                    ("DIS_ON_BOUNTY", "DIS_ON_BOUNTY"),
                    ("BOUNTY_PAYOUT", "BOUNTY_PAYOUT"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
