# Generated by Django 4.1 on 2023-03-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_review_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="review",
            name="is_removed_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
