# Generated by Django 4.1 on 2023-06-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("review", "0003_review_is_public_review_is_removed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
