# Generated by Django 4.2.16 on 2024-11-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_comment", "0018_alter_rhcommentmodel_comment_type_and_more"),
        ("paper", "0143_alter_paperversion_paper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0004_review_content_type_review_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "is_removed_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("CHANGES_REQUESTED", "Changes Requested"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                    ),
                ),
                (
                    "comment_thread",
                    models.ForeignKey(
                        db_comment="The textual peer review content is stored in the comment thread.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_review",
                        to="researchhub_comment.rhcommentthreadmodel",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        db_comment="The paper that is under peer review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_reviews",
                        to="paper.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="The user who is assigned to the peer review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="peerreview",
            constraint=models.UniqueConstraint(
                fields=("user", "paper"), name="unique_paper_user"
            ),
        ),
    ]
