# Generated by Django 5.2.14 on 2026-06-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_review_add_is_assessed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PeerReview",
        ),
    ]
