ADMIN = "ADMIN"
EDITOR = "EDITOR"
VIEWER = "VIEWER"
MEMBER = "MEMBER"
COMMENTER = "COMMENTER"
NO_ACCESS = "NO_ACCESS"

PUBLIC = "PUBLIC"
PRIVATE = "PRIVATE"
WORKSPACE = "WORKSPACE"
SHARED = "SHARED"

ACCESS_TYPE_CHOICES = (
    (ADMIN, ADMIN),
    (EDITOR, EDITOR),
    (VIEWER, VIEWER),
    (MEMBER, MEMBER),
    (COMMENTER, COMMENTER),
    (NO_ACCESS, NO_ACCESS),
)
