ADMIN = 'ADMIN'
EDITOR = 'EDITOR'
VIEWER = 'VIEWER'
MEMBER = 'MEMBER'
COMMENTER = 'COMMENTER'
NO_ACCESS = 'NO_ACCESS'

ACCESS_TYPE_CHOICES = (
    (ADMIN, ADMIN),
    (EDITOR, EDITOR),
    (VIEWER, VIEWER),
    (MEMBER, MEMBER),
    (COMMENTER, COMMENTER),
    (NO_ACCESS, NO_ACCESS)
)
