# Generated by Django 5.1.5 on 2025-02-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_remove_feedentry_unique_parent_child_combination_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedEntry",
        ),
    ]
