# Generated by Django 5.1.5 on 2025-02-04 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0004_delete_feedentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "parent_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("action", models.TextField(choices=[("PUBLISH", "PUBLISH")])),
                ("action_date", models.DateTimeField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_entries",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_feed_entries",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="feed_parent_lookup_idx",
                    ),
                    models.Index(fields=["-action_date"], name="feed_action_date_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "content_type",
                            "object_id",
                            "parent_content_type",
                            "parent_object_id",
                            "action",
                            "user",
                        ),
                        name="unique_feed_entry",
                    )
                ],
            },
        ),
    ]
