# Generated by Django 5.1.5 on 2025-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_feedentry_feed_partition_action_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedentry",
            name="action",
            field=models.TextField(choices=[("OPEN", "OPEN"), ("PUBLISH", "PUBLISH")]),
        ),
    ]
