# Generated by Django 5.1.5 on 2025-02-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_alter_feedentry_action"),
        (
            "researchhub_document",
            "0064_researchhubunifieddocument_doc_type_hot_score_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="unified_document",
            field=models.ForeignKey(
                blank=True,
                db_comment="The unified document associated with the feed entry. Directly added to the feed entry for performance reasons.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_entries",
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
    ]
