# Generated by Django 5.1.5 on 2025-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_alter_feedentry_unified_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="content",
            field=models.JSONField(
                db_comment="A serialized JSON representation of the item.", default=dict
            ),
        ),
    ]
