# Generated by Django 5.1.5 on 2025-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0010_feedentry_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="metrics",
            field=models.JSONField(
                db_comment="A serialized JSON representation of the metrics for the item.",
                default=dict,
            ),
        ),
    ]
