# Generated by Django 5.1.5 on 2025-03-27 09:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0011_alter_feedentry_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="metrics",
            field=models.JSONField(
                db_comment="A serialized JSON representation of the metrics for the item.",
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
