# Generated by Django 5.1.5 on 2025-03-28 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0011_alter_feedentry_content"),
        (
            "researchhub_document",
            "0066_remove_researchhubunifieddocument_idx_unified_doc_hot_score_v2_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="hot_score",
            field=models.FloatField(
                db_comment="Score determining content hotness based on votes, comments, and monetary value",
                db_index=True,
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["-hot_score"], name="feed_hot_score_idx"),
        ),
    ]
