# Generated by Django 5.1.5 on 2025-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0012_feedentry_metrics"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE MATERIALIZED VIEW feed_feedentry_mv AS
                SELECT
                    fe.id,
                    fe.content_type_id,
                    fe.object_id,
                    fe.content,
                    fe.metrics,
                    fe.parent_content_type_id,
                    fe.parent_object_id,
                    fe.action,
                    fe.action_date,
                    fe.user_id,
                    fe.unified_document_id,
                    ud.hot_score,
                    fe.created_date,
                    fe.updated_date
                FROM
                    feed_feedentry fe
                JOIN
                    researchhub_document_researchhubunifieddocument ud ON fe.unified_document_id = ud.id
                WHERE
                    ud.is_removed = FALSE
                ORDER BY
                    ud.hot_score DESC;

            CREATE UNIQUE INDEX feed_feedentry_mv_unique_idx ON feed_feedentry_mv (id);
            CREATE INDEX feed_feedentry_mv_hotscore_idx ON feed_feedentry_mv (hot_score DESC);
            CREATE INDEX feed_feedentry_mv_action_date_idx ON feed_feedentry_mv (action_date DESC);
            CREATE INDEX feed_feedentry_mv_parent_lookup_idx ON feed_feedentry_mv (parent_content_type_id, parent_object_id);

            """,
            reverse_sql="""
                DROP MATERIALIZED VIEW IF EXISTS feed_feedentry_mv;
            """,
        ),
    ]
