# Generated by Django 5.1.5 on 2025-04-04 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0012_feedentry_metrics"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="hot_score",
            field=models.IntegerField(
                db_comment="Calculated popularity score for ranking in popular feeds. Considers votes, replies, and tips.",
                db_index=True,
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["created_date"], name="feed_created_date_idx"),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["-hot_score"], name="feed_hot_score_idx"),
        ),
    ]
