# Generated by Django 5.1.5 on 2025-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0013_create_feedentrypopular"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEntryPopular",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.TextField(
                        choices=[("OPEN", "OPEN"), ("PUBLISH", "PUBLISH")]
                    ),
                ),
                ("action_date", models.DateTimeField()),
                ("content", models.JSONField(default=dict)),
                ("hot_score", models.FloatField()),
                ("object_id", models.PositiveIntegerField()),
                ("metrics", models.JSONField(default=dict)),
                ("parent_object_id", models.PositiveIntegerField(null=True)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
            ],
            options={
                "db_table": "feed_feedentry_popular",
                "ordering": ["-hot_score"],
                "managed": False,
            },
        ),
    ]
