# Generated by Django 5.1.5 on 2025-04-14 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0017_prewarm_materialized_view"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["created_date"], name="feed_created_date_idx"),
        ),
    ]
