# Generated by Django 5.1.5 on 2025-04-15 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0018_feedentry_feed_created_date_idx"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="hot_score",
            field=models.IntegerField(default=0, help_text="Feed ranking score."),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(fields=["-hot_score"], name="feed_hot_score_idx"),
        ),
    ]
