# Generated by Django 5.1.5 on 2025-05-12 08:30

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0020_recreate_feedentrypopular_without_doc"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="hubs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                db_comment="Tags associated with the feed entry.",
                default=list,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["hubs"], name="feed_hubs_gin_idx"
            ),
        ),
    ]
