# Generated by Django 5.1.5 on 2025-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0020_recreate_feedentrypopular_without_doc"),
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="hubs",
            field=models.ManyToManyField(
                blank=True, related_name="feed_entries", to="hub.hub"
            ),
        ),
    ]
