# Generated by Django 5.1.5 on 2025-04-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0021_feedentry_hubs"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO feed_feedentry_hubs (feedentry_id, hub_id)
            SELECT f.id, f.parent_object_id
            FROM feed_feedentry f
            WHERE f.parent_content_type_id = (
                SELECT id
                FROM django_content_type
                WHERE app_label='hub' AND model='hub'
            ) AND NOT EXISTS (
                SELECT 1
                FROM feed_feedentry_hubs fh
                WHERE fh.feedentry_id = f.id
                AND fh.hub_id = f.parent_object_id
            );
            """,
            reverse_sql="""
            DELETE FROM feed_feedentry_hubs
            WHERE feedentry_id IN (
                SELECT id
                FROM feed_feedentry
                WHERE parent_content_type_id = (
                    SELECT id
                    FROM django_content_type
                    WHERE app_label='hub' AND model='hub'
                )
            );
            """,
        )
    ]
