# Generated by Django 5.1.5 on 2025-04-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0022_feedentry_backfill_hubs"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM feed_feedentry_hubs f
            WHERE NOT EXISTS (
                SELECT 1
                FROM (
                    SELECT MAX(id) AS id
                    FROM feed_feedentry
                    GROUP BY content_type_id, object_id
                ) latest
                WHERE latest.id = f.feedentry_id
            );

            DELETE FROM feed_feedentry f
            WHERE NOT EXISTS (
                SELECT 1
                FROM (
                    SELECT MAX(id) AS id
                    FROM feed_feedentry
                    GROUP BY content_type_id, object_id
                ) latest
                WHERE latest.id = f.id
            );
            """,
        )
    ]
