# Generated by Django 5.1.5 on 2025-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0023_feedentry_remove_duplicates"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedEntryLatestHubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "feed_feedentry_hubs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FeedEntryPopularHubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "feed_feedentry_hubs",
                "managed": False,
            },
        ),
    ]
