# Generated by Django 5.1.5 on 2025-05-16 08:50

from importlib import import_module

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0024_feedentrylatesthubs_feedentrypopularhubs"),
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="unique_feed_entry",
        ),
        migrations.RemoveIndex(
            model_name="feedentry",
            name="feed_parent_lookup_idx",
        ),
        # Django 6 no longer cascades column removal to dependent views.
        migrations.RunSQL(
            sql=[
                "DROP MATERIALIZED VIEW IF EXISTS feed_feedentry_latest;",
                "DROP MATERIALIZED VIEW IF EXISTS feed_feedentry_popular;",
            ],
            reverse_sql=[
                import_module(
                    "feed.migrations.0015_create_feedentrylatest"
                ).Migration.get_sql(),
                import_module(
                    "feed.migrations.0020_recreate_feedentrypopular_without_doc"
                ).Migration.get_sql(),
            ],
        ),
        migrations.RemoveField(
            model_name="feedentry",
            name="parent_content_type",
        ),
        migrations.RemoveField(
            model_name="feedentry",
            name="parent_object_id",
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "action", "user"),
                name="unique_feed_entry",
            ),
        ),
    ]
