# Generated by Django 5.1.5 on 2025-06-04 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0027_recreate_feedentrylatest_without_parent"),
        ("hub", "0028_hub_hub_hub_name_upper_idx"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedentry",
            name="unique_feed_entry",
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("content_type", "object_id", "action", "user"),
                name="unique_feed_entry_with_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("content_type", "object_id", "action"),
                name="unique_feed_entry_without_user",
            ),
        ),
    ]
