# Generated by Django 5.2.7 on 2025-10-18 19:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0030_add_hot_score_v2"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedentry",
            name="feed_hot_score_v2_idx",
        ),
        migrations.AddField(
            model_name="feedentry",
            name="hot_score_v2_breakdown",
            field=models.JSONField(
                blank=True,
                db_comment="Detailed breakdown of hot_score_v2 calculation.",
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Contains equation, steps, signals, time_factors, and calculation details for transparency and debugging.",
            ),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="hot_score",
            field=models.IntegerField(
                default=0, help_text="Feed ranking score (v1 - DEPRECATED)."
            ),
        ),
        migrations.AlterField(
            model_name="feedentry",
            name="hot_score_v2",
            field=models.IntegerField(
                db_index=True, default=0, help_text="New hot score algorithm (v2)"
            ),
        ),
    ]
