# Generated by Django 5.2.7 on 2025-11-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0031_remove_feedentry_feed_hot_score_v2_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedEntryLatest",
        ),
        migrations.DeleteModel(
            name="FeedEntryLatestHubs",
        ),
        migrations.DeleteModel(
            name="FeedEntryPopular",
        ),
        migrations.DeleteModel(
            name="FeedEntryPopularHubs",
        ),
    ]
