# Generated by Django 5.2.7 on 2025-11-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0031_remove_feedentry_feed_hot_score_v2_idx_and_more"),
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="feed_entries", to="user.author"
            ),
        ),
    ]
