# Generated by Django 5.2.8 on 2025-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0032_delete_feedentrylatest_delete_feedentrylatesthubs_and_more"),
        ("user", "0136_alter_author_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="feed_entries", to="user.author"
            ),
        ),
    ]
