# Generated by Django 5.2.7 on 2025-11-15 09:22

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0033_feedentry_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotScoreV2Breakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "breakdown_data",
                    models.JSONField(
                        blank=True,
                        db_comment="Detailed breakdown of hot_score_v2 calculation.",
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Contains equation, steps, signals, time_factors, and calculation details for transparency and debugging.",
                    ),
                ),
                (
                    "feed_entry",
                    models.OneToOneField(
                        help_text="The feed entry this breakdown belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hot_score_breakdown_v2",
                        to="feed.feedentry",
                    ),
                ),
            ],
            options={
                "db_table": "feed_hotscorev2breakdown",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed_entry",), name="unique_feed_entry_breakdown"
                    )
                ],
            },
        ),
    ]
