# Generated by Django 5.2.7 on 2025-11-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0035_migrate_hot_score_breakdown_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedentry",
            name="hot_score_v2_breakdown",
        ),
    ]
