# Generated by Django 5.2.9 on 2025-12-12 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0036_remove_feedentry_hot_score_v2_breakdown"),
        ("hub", "0032_alter_hub_namespace"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("user", "0136_alter_author_headline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedentry",
            name="pdf_copyright_allows_display",
            field=models.BooleanField(
                default=False,
                help_text="Whether the PDF copyright allows display on our site.",
            ),
        ),
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                condition=models.Q(("pdf_copyright_allows_display", False)),
                fields=["pdf_copyright_allows_display"],
                name="feed_pdf_no_display_idx",
            ),
        ),
    ]
