# Generated by Django 5.2.11 on 2026-02-22 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("feed", "0037_add_pdf_copyright_allows_display"),
        ("hub", "0032_alter_hub_namespace"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("user", "0137_funding_activity_and_leaderboard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedentry",
            index=models.Index(
                fields=["content_type", "unified_document"], name="feed_ct_unidoc_idx"
            ),
        ),
    ]
