import os

SECRET_KEY = os.environ.get("SECRET_KEY", "development")

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "PLACEHOLDER")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "PLACEHOLDER")

INFURA_PROJECT_ID = os.environ.get("INFURA_PROJECT_ID", "PLACEHOLDER")
INFURA_PROJECT_SECRET = os.environ.get("INFURA_PROJECT_SECRET", "PLACEHOLDER")
INFURA_RINKEBY_ENDPOINT = f"https://rinkeby.infura.io/v3/{INFURA_PROJECT_ID}"

ORCID_CLIENT_ID = os.environ.get("ORCID_CLIENT_ID")
ORCID_CLIENT_SECRET = os.environ.get("ORCID_CLIENT_SECRET")
ORCID_ACCESS_TOKEN = os.environ.get("ORCID_ACCESS_TOKEN")

MAILCHIMP_KEY = os.environ.get("MAILCHIMP_KEY", "PLACEHOLDER")
MAILCHIMP_LIST_ID = os.environ.get("MAILCHIMP_LIST_ID", "PLACEHOLDER")

RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "PLACEHOLDER")

SIFT_ACCOUNT_ID = os.environ.get("SIFT_ACCOUNT_ID", "PLACEHOLDER")
SIFT_REST_API_KEY = os.environ.get("SIFT_REST_API_KEY", "PLACEHOLDER")
SIFT_WEBHOOK_SECRET_KEY = os.environ.get("SIFT_WEBHOOK_SECRET_KEY", "PLACEHOLDER")

AMPLITUDE_API_KEY = os.environ.get("AMPLITUDE_API_KEY", "PLACEHOLDER")

STRIPE_API_KEY = os.environ.get("STRIPE_API_KEY", "PLACEHOLDER")

SENTRY_DSN = os.environ.get("SENTRY_DSN", "PLACEHOLDER")

APM_URL = os.environ.get("APM_URL", "PLACEHOLDER")

ELASTICSEARCH_HOST = os.environ.get("ELASTICSEARCH_HOST", "PLACEHOLDER")

CKEDITOR_CLOUD_ACCESS_KEY = os.environ.get("CKEDITOR_CLOUD_ACCESS_KEY", "PLACEHOLDER")
CKEDITOR_CLOUD_ENVIRONMENT_ID = os.environ.get(
    "CKEDITOR_CLOUD_ENVIRONMENT_ID", "PLACEHOLDER"
)

CROSSREF_LOGIN_ID = os.environ.get("CROSSREF_LOGIN_ID", "PLACEHOLDER")
CROSSREF_LOGIN_PASSWORD = os.environ.get("CROSSREF_LOGIN_PASSWORD", "PLACEHOLDER")

ASYNC_SERVICE_API_KEY = os.environ.get("ASYNC_SERVICE_API_KEY", "PLACEHOLDER")

MJML_APP_ID = os.environ.get("MJML_APP_ID", "PLACEHOLDER")
MJML_SECRET_KEY = os.environ.get("MJML_SECRET_KEY", "PLACEHOLDER")

MORALIS_API_KEY = os.environ.get("MORALIS_API_KEY", "PLACEHOLDER")
WEB3_NETWORK = os.environ.get("WEB3_NETWORK", "PLACEHOLDER")
PROVIDER_URL = os.environ.get("PROVIDER_URL", "PLACEHOLDER")
WEB3_KEYSTORE_BUCKET = os.environ.get("WEB3_KEYSTORE_BUCKET", "PLACEHOLDER")
WEB3_KEYSTORE_FILE = os.environ.get("WEB3_KEYSTORE_FILE", "PLACEHOLDER")
WEB3_KEYSTORE_PASSWORD = os.environ.get("WEB3_KEYSTORE_PASSWORD", "PLACEHOLDER")
WEB3_RSC_ADDRESS = os.environ.get(
    "WEB3_RSC_ADDRESS", "0x82620900630a2Ab6a319791140891110B4cAA033"
)
WEB3_KEYSTORE_ADDRESS = os.environ.get("WEB3_KEYSTORE_ADDRESS", "PLACEHOLDER")

TRANSPOSE_KEY = os.environ.get("TRANSPOSE_KEY", "PLACEHOLDER")
