import os

SECRET_KEY = os.environ.get("SECRET_KEY", "development")

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

INFURA_PROJECT_ID = os.environ.get("INFURA_PROJECT_ID", "")
INFURA_PROJECT_SECRET = os.environ.get("INFURA_PROJECT_SECRET", "")
INFURA_RINKEBY_ENDPOINT = f"https://goerli.infura.io/v3/{INFURA_PROJECT_ID}"

ORCID_CLIENT_ID = os.environ.get("ORCID_CLIENT_ID")
ORCID_CLIENT_SECRET = os.environ.get("ORCID_CLIENT_SECRET")
ORCID_ACCESS_TOKEN = os.environ.get("ORCID_ACCESS_TOKEN")

MAILCHIMP_KEY = os.environ.get("MAILCHIMP_KEY", "")
MAILCHIMP_LIST_ID = os.environ.get("MAILCHIMP_LIST_ID", "")

RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")

SIFT_ACCOUNT_ID = os.environ.get("SIFT_ACCOUNT_ID", "PLACEHOLDER")
SIFT_REST_API_KEY = os.environ.get("SIFT_REST_API_KEY", "PLACEHOLDER")
SIFT_WEBHOOK_SECRET_KEY = os.environ.get("SIFT_WEBHOOK_SECRET_KEY", "")

AMPLITUDE_API_KEY = os.environ.get("AMPLITUDE_API_KEY", "")

STRIPE_API_KEY = os.environ.get("STRIPE_API_KEY", "")

SENTRY_DSN = os.environ.get("SENTRY_DSN", "")

APM_URL = os.environ.get("APM_URL", "")

ELASTICSEARCH_HOST = os.environ.get("ELASTICSEARCH_HOST", "")

CKEDITOR_CLOUD_ACCESS_KEY = os.environ.get("CKEDITOR_CLOUD_ACCESS_KEY", "")
CKEDITOR_CLOUD_ENVIRONMENT_ID = os.environ.get("CKEDITOR_CLOUD_ENVIRONMENT_ID", "")

CROSSREF_LOGIN_ID = os.environ.get("CROSSREF_LOGIN_ID", "")
CROSSREF_LOGIN_PASSWORD = os.environ.get("CROSSREF_LOGIN_PASSWORD", "")

ASYNC_SERVICE_API_KEY = os.environ.get("ASYNC_SERVICE_API_KEY", "")

MJML_APP_ID = os.environ.get("MJML_APP_ID", "")
MJML_SECRET_KEY = os.environ.get("MJML_SECRET_KEY", "")

MORALIS_API_KEY = os.environ.get("MORALIS_API_KEY", "")
WEB3_NETWORK = os.environ.get("WEB3_NETWORK", "")
PROVIDER_URL = os.environ.get("PROVIDER_URL", "")
WEB3_KEYSTORE_BUCKET = os.environ.get("WEB3_KEYSTORE_BUCKET", "")
WEB3_KEYSTORE_FILE = os.environ.get("WEB3_KEYSTORE_FILE", "")
WEB3_KEYSTORE_PASSWORD = os.environ.get("WEB3_KEYSTORE_PASSWORD", "")
WEB3_RSC_ADDRESS = os.environ.get(
    "WEB3_RSC_ADDRESS", "0x82620900630a2Ab6a319791140891110B4cAA033"
)
WEB3_KEYSTORE_ADDRESS = os.environ.get("WEB3_KEYSTORE_ADDRESS", "")

TRANSPOSE_KEY = os.environ.get("TRANSPOSE_KEY", "")
OPENALEX_KEY = os.environ.get("OPENALEX_KEY", "")
LINKEDIN_CLIENT_ID = os.environ.get("LINKEDIN_CLIENT_ID", "")
LINKEDIN_CLIENT_SECRET = os.environ.get("LINKEDIN_CLIENT_SECRET", "")
LINKEDIN_CALLBACK_URL = os.environ.get("LINKEDIN_CALLBACK_URL", "")
ORCID_REDIRECT_URL = os.environ.get("ORCID_REDIRECT_URL", "")
