# Note:
# Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
# (Adding the "ports" property to this file will not forward from a Codespace.)

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    environment:
      DB_HOST: postgres
      DB_USER: researchhub
      DB_PASS: researchhub
      OPENSEARCH_HOST: http://opensearch:9200
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - researchhub

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile.opensearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - researchhub

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.3
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - researchhub

  postgres:
    image: postgres:16.3-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: researchhub
      POSTGRES_DB: researchhub
      POSTGRES_PASSWORD: researchhub
    networks:
      - researchhub

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - researchhub

networks:
  researchhub:
    driver: bridge

volumes:
  postgres-data:
