GENERIC_COMMENT = "GENERIC_COMMENT"
INNER_CONTENT_COMMENT = "INNER_CONTENT_COMMENT"
SUMMARY = "SUMMARY"
COMMUNITY_REVIEW = "REVIEW"
PEER_REVIEW = "PEER_REVIEW"
ANSWER = "ANSWER"
REPLICABILITY_COMMENT = "REPLICABILITY_COMMENT"

RH_COMMENT_THREAD_TYPES = (
    (GENERIC_COMMENT, GENERIC_COMMENT),
    (INNER_CONTENT_COMMENT, INNER_CONTENT_COMMENT),
    (ANSWER, ANSWER),
    (COMMUNITY_REVIEW, COMMUNITY_REVIEW),
    (PEER_REVIEW, PEER_REVIEW),
    (SUMMARY, SUMMARY),
    (REPLICABILITY_COMMENT, REPLICABILITY_COMMENT),
)
