CK_EDITOR = "CK_EDITOR"
QUILL_EDITOR = "QUILL_EDITOR"
TEXT = "TEXT"
HTML = "HTML"

RH_COMMENT_CONTENT_TYPES = (
    (CK_EDITOR, CK_EDITOR),
    (QUILL_EDITOR, QUILL_EDITOR),
    (TEXT, TEXT),
    (HTML, HTML),
)
