# AUTHOR_UPDATE is for updates that can only be posted by the original author
# of the document. This is used for comments on grants where authors can post
# updates as part of the grant process.
AUTHOR_UPDATE = "AUTHOR_UPDATE"
GENERIC_COMMENT = "GENERIC_COMMENT"
INNER_CONTENT_COMMENT = "INNER_CONTENT_COMMENT"
SUMMARY = "SUMMARY"
COMMUNITY_REVIEW = "REVIEW"
PEER_REVIEW = "PEER_REVIEW"
ANSWER = "ANSWER"
REPLICABILITY_COMMENT = "REPLICABILITY_COMMENT"
AUTHOR_UPDATE = "AUTHOR_UPDATE"

RH_COMMENT_THREAD_TYPES = (
    (AUTHOR_UPDATE, AUTHOR_UPDATE),
    (GENERIC_COMMENT, GENERIC_COMMENT),
    (INNER_CONTENT_COMMENT, INNER_CONTENT_COMMENT),
    (ANSWER, ANSWER),
    (COMMUNITY_REVIEW, COMMUNITY_REVIEW),
    (PEER_REVIEW, PEER_REVIEW),
    (SUMMARY, SUMMARY),
    (REPLICABILITY_COMMENT, REPLICABILITY_COMMENT),
    (AUTHOR_UPDATE, AUTHOR_UPDATE),
)
