CK_EDITOR = "CK_EDITOR"
QUILL_EDITOR = "QUILL_EDITOR"
TEXT = "TEXT"
TIPTAP = "TIPTAP"

RH_COMMENT_CONTENT_TYPES = (
    (CK_EDITOR, CK_EDITOR),
    (QUILL_EDITOR, QUILL_EDITOR),
    (TEXT, TEXT),
    (TIPTAP, TIPTAP),
)
