LEGACY_COMMENT = "LEGACY_COMMENT"
LEGACY_REPLY = "LEGACY_REPLY"
LEGACY_THREAD = "LEGACY_THREAD"

RH_COMMENT_MIGRATION_LEGACY_TYPES = (
    (LEGACY_COMMENT, LEGACY_COMMENT),
    (LEGACY_REPLY, LEGACY_REPLY),
    (LEGACY_THREAD, LEGACY_THREAD),
)
