BOUNTY = "BOUNTY"
GENERIC_COMMENT = "GENERIC_COMMENT"
INNER_CONTENT_COMMENT = "INNER_CONTENT_COMMENT"

RH_COMMENT_THREAD_TYPES = (
    (GENERIC_COMMENT, GENERIC_COMMENT),
    (INNER_CONTENT_COMMENT, INNER_CONTENT_COMMENT),
    (BOUNTY, BOUNTY),
)