# Generated by Django 2.2.12 on 2020-04-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=256)),
                ('http_method', models.CharField(max_length=8)),
                ('total_queries', models.CharField(max_length=8)),
                ('total_sql_time', models.CharField(max_length=64)),
                ('total_view_time', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traceback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(choices=[('SQL_TRACE', 'SQL_TRACE'), ('VIEW_TRACE', 'VIEW_TRACE')], max_length=16)),
                ('time', models.CharField(max_length=64)),
                ('trace', models.TextField()),
                ('sql', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceback', to='profiler.Profile')),
            ],
        ),
    ]
