# Generated by Django 2.2.12 on 2020-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_auto_20200416_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceback',
            name='trace',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='uploads/traceback/%Y/%m/%d'),
        ),
    ]
