# Generated by Django 2.2.12 on 2020-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_auto_20200416_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_sql_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_view_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traceback',
            name='time',
            field=models.FloatField(),
        ),
    ]
