# Generated by Django 4.2.15 on 2024-10-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiler", "0004_auto_20200420_1716"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traceback",
            name="profile",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Traceback",
        ),
    ]
