# Generated by Django 2.2.14 on 2020-08-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20200805_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throttle',
            name='captcha_ident',
        ),
    ]
