# Generated by Django 2.2.14 on 2020-08-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20200805_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='throttle',
            name='ident',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
