# Generated by Django 5.2.17 on 2026-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0006_throttle_ident"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Throttle",
        ),
    ]
