# Generated by Django 5.2.7 on 2025-10-09 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchhub_document', '0068_alter_researchhubpost_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_removed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user to update the instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_removed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('parent_list', models.ForeignKey(db_comment='The list that the item is saved to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_lists.list')),
                ('unified_document', models.ForeignKey(db_comment='The saved document that the item represents.', on_delete=django.db.models.deletion.CASCADE, related_name='user_list_items', to='researchhub_document.researchhubunifieddocument')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user to update the instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('created_by', 'name'), name='unique_not_removed_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('parent_list', 'unified_document'), name='unique_not_removed_document_per_list'),
        ),
    ]
