# Generated by Django 5.2.8 on 2025-11-11 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to update the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to update the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
