# Generated by Django 5.2.8 on 2025-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_lists", "0002_alter_list_updated_by_alter_list_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]

