# Generated by Django 5.2.8 on 2025-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_lists", "0003_list_default_functionality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
