"""
X (Twitter) bot accounts that post preprints.

These accounts are used to filter out bot posts when calculating X metrics.
"""

X_BOT_ACCOUNTS = {
    "biorxiv": {
        # General biorxiv bots (apply to all biorxiv queries)
        "neuroscience": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_behav",
            "GaryRitchison",
            "biorxiv_neursci",
        ],
        "biochemistry": ["adipose_papers", "SciencesNetwork", "biorxiv_biochem"],
        "bioengineering": [
            "adipose_papers",
            "SciencesNetwork",
            "bioRxiv_bioE",
            "biorxiv_bioeng",
        ],
        "bioinformatics": ["adipose_papers", "SciencesNetwork", "biorxiv_bioinfo"],
        "biophysics": ["adipose_papers", "SciencesNetwork", "biorxiv_biophys"],
        "cancer-biology": ["adipose_papers", "SciencesNetwork", "biorxiv_cancer"],
        "cell-biology": ["adipose_papers", "SciencesNetwork", "biorxiv_cellbio"],
        "clinical-trials": ["adipose_papers", "SciencesNetwork"],
        "developmental-biology": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_devbio",
        ],
        "ecology": ["adipose_papers", "SciencesNetwork", "biorxiv_ecology"],
        "epidemiology": ["adipose_papers", "SciencesNetwork"],
        "evolutionary-biology": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_evobio",
        ],
        "genetics-and-genomics": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_genetic",
            "biorxiv_genomic",
        ],
        "immunology": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_immuno",
            "Age_Ddr_Papers",
        ],
        "microbiology": ["adipose_papers", "SciencesNetwork", "biorxiv_micrbio"],
        "molecular-biology": ["adipose_papers", "SciencesNetwork", "biorxiv_molbio"],
        "paleontology": ["adipose_papers", "SciencesNetwork", "biorxiv_paleo"],
        "pathology": ["adipose_papers", "SciencesNetwork", "biorxiv_pathol"],
        "pharmacology": ["adipose_papers", "SciencesNetwork", "biorxiv_pharma"],
        "physiology": ["adipose_papers", "SciencesNetwork", "biorxiv_physio"],
        "plant-biology": ["adipose_papers", "SciencesNetwork", "biorxiv_plants"],
        "scientific-communication-and-education": [
            "adipose_papers",
            "SciencesNetwork",
            "biorxiv_scicomm",
        ],
        "synthetic-biology": [
            "adipose_papers",
            "SciencesNetwork",
            "bioRxiv_synbio",
        ],
        "systems-biology": ["adipose_papers", "SciencesNetwork", "biorxiv_sysbio"],
        "zoology": ["adipose_papers", "SciencesNetwork", "biorxiv_zoology"],
    },
    "arxiv": {
        # Astrophysics subcategories (astro-ph.*)
        "cosmology": ["Un1v3rs0Z3r0"],
        "planetary-science": ["Un1v3rs0Z3r0"],
        "galaxies": ["Un1v3rs0Z3r0"],
        "high-energy-astrophysics": ["Un1v3rs0Z3r0"],
        "solar-and-stellar": ["Un1v3rs0Z3r0"],
        # Condensed matter subcategories (cond-mat.*)
        "disordered-systems": ["Un1v3rs0Z3r0"],
        "mesoscale-physics": ["Un1v3rs0Z3r0"],
        "materials-science": ["Un1v3rs0Z3r0"],
        "other-condensed-matter": ["Un1v3rs0Z3r0"],
        "quantum-gases": ["Un1v3rs0Z3r0"],
        "soft-matter": ["Un1v3rs0Z3r0"],
        "statistical-mechanics": ["Un1v3rs0Z3r0"],
        "strongly-correlated": ["Un1v3rs0Z3r0"],
        "superconductivity": ["Un1v3rs0Z3r0"],
        # High energy physics
        "general-relativity": ["Un1v3rs0Z3r0", "krxiv_gr_qc"],
        "high-energy-experiment": ["Un1v3rs0Z3r0"],
        "lattice-physics": ["Un1v3rs0Z3r0"],
        "high-energy-phenomenology": ["Un1v3rs0Z3r0", "krxiv_hep_ph"],
        "high-energy-theory": ["Un1v3rs0Z3r0", "krxiv_hep_th"],
        "mathematical-physics": [
            "Un1v3rs0Z3r0",
            "krxiv_math_ph",
            "mathMPb",
            "mathNAb",
        ],
        # Nonlinear sciences subcategories (nlin.*)
        "adaptation-and-self-organization": ["Un1v3rs0Z3r0", "pixdotpink"],
        "chaotic-dynamics": ["Un1v3rs0Z3r0", "pixdotpink"],
        "cellular-automata": ["Un1v3rs0Z3r0", "pixdotpink"],
        "pattern-formation": ["Un1v3rs0Z3r0", "pixdotpink"],
        "exactly-solvable-systems": ["Un1v3rs0Z3r0", "pixdotpink"],
        # Nuclear physics
        "nuclear-experiment": ["Un1v3rs0Z3r0", "NuclearPapers"],
        "nuclear-theory": ["Un1v3rs0Z3r0"],
        # General physics subcategories (physics.*)
        "accelerator-physics": ["Un1v3rs0Z3r0"],
        "atmospheric-physics": ["Un1v3rs0Z3r0"],
        "applied-physics": ["Un1v3rs0Z3r0"],
        "atomic-clusters": ["Un1v3rs0Z3r0"],
        "atomic-physics": ["Un1v3rs0Z3r0"],
        "biological-physics": ["Un1v3rs0Z3r0"],
        "chemical-physics": ["Un1v3rs0Z3r0"],
        "classical-physics": ["Un1v3rs0Z3r0"],
        "computational-physics": ["Un1v3rs0Z3r0"],
        "data-analysis": ["Un1v3rs0Z3r0"],
        "physics-education": ["Un1v3rs0Z3r0"],
        "fluid-dynamics": ["Un1v3rs0Z3r0"],
        "general-physics": ["Un1v3rs0Z3r0"],
        "geophysics": ["Un1v3rs0Z3r0"],
        "history-of-physics": ["Un1v3rs0Z3r0"],
        "instrumentation": ["Un1v3rs0Z3r0"],
        "medical-physics": ["Un1v3rs0Z3r0"],
        "optics": ["Un1v3rs0Z3r0"],
        "plasma-physics": ["Un1v3rs0Z3r0"],
        "popular-physics": ["Un1v3rs0Z3r0"],
        "physics-and-society": ["Un1v3rs0Z3r0"],
        "space-physics": ["Un1v3rs0Z3r0"],
        # Quantum physics
        "quantum-physics": ["Un1v3rs0Z3r0", "krxiv_quant_ph"],
        # Mathematics subcategories (math.*)
        "commutative-algebra": ["Un1v3rs0Z3r0", "mathACb"],
        "algebraic-geometry": ["Un1v3rs0Z3r0", "mathAGb"],
        "analysis-of-pdes": ["Un1v3rs0Z3r0", "mathAPb"],
        "algebraic-topology": ["Un1v3rs0Z3r0", "mathATb"],
        "classical-analysis": ["Un1v3rs0Z3r0", "mathCAbot"],
        "combinatorics": ["Un1v3rs0Z3r0", "mathCObot"],
        "category-theory": ["Un1v3rs0Z3r0", "mathCTbot"],
        "complex-variables": ["Un1v3rs0Z3r0", "mathCVb"],
        "differential-geometry": ["Un1v3rs0Z3r0", "mathDGb"],
        "dynamical-systems": ["Un1v3rs0Z3r0", "mathDSb"],
        "functional-analysis": ["Un1v3rs0Z3r0", "mathFAbot"],
        "general-mathematics": ["Un1v3rs0Z3r0", "mathGMb"],
        "general-topology": ["Un1v3rs0Z3r0", "mathGNb"],
        "group-theory": ["Un1v3rs0Z3r0", "mathGRbot"],
        "geometric-topology": ["Un1v3rs0Z3r0", "mathGTb"],
        "history-and-overview": ["Un1v3rs0Z3r0", "mathHOb"],
        "information-theory": ["Un1v3rs0Z3r0", "mathITbot"],
        "k-theory": ["Un1v3rs0Z3r0", "mathKTb"],
        "logic": ["Un1v3rs0Z3r0", "mathLOb"],
        "metric-geometry": ["Un1v3rs0Z3r0", "mathMGb"],
        "numerical-analysis": ["Un1v3rs0Z3r0"],
        "number-theory": ["Un1v3rs0Z3r0", "mathNTb"],
        "operator-algebras": ["Un1v3rs0Z3r0", "mathOAb"],
        "optimization-and-control": ["Un1v3rs0Z3r0", "mathOCb"],
        "probability": ["Un1v3rs0Z3r0", "mathPRb"],
        "quantum-algebra": ["Un1v3rs0Z3r0", "mathQAb"],
        "rings-and-algebras": ["Un1v3rs0Z3r0", "mathRAb"],
        "representation-theory": ["Un1v3rs0Z3r0", "mathRTb"],
        "symplectic-geometry": ["Un1v3rs0Z3r0", "mathSGb"],
        "spectral-theory": ["Un1v3rs0Z3r0", "mathSPb"],
        "statistics-theory": ["Un1v3rs0Z3r0", "mathSTb"],
        # Computer science subcategories (cs.*)
        "artificial-intelligence": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "hardware-architecture": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "computational-complexity": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "computational-engineering": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "computational-geometry": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "natural-language-processing": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "cryptography-and-security": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "computer-vision": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "computers-and-society": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "databases": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "distributed-computing": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "digital-libraries": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "discrete-mathematics": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "data-structures-and-algorithms": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "emerging-technologies": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "formal-languages": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "general-literature": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "graphics": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "game-theory": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "human-computer-interaction": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "information-retrieval": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "machine-learning": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "multiagent-systems": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "multimedia": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "mathematical-software": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "neural-computing": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "networking": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "other": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "operating-systems": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "performance": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "programming-languages": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "robotics": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "symbolic-computation": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "sound": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "software-engineering": ["Un1v3rs0Z3r0", "ArxivScreener"],
        "social-networks": ["Un1v3rs0Z3r0", "ArxivScreener"],
        # Quantitative biology subcategories (q-bio.*)
        "biomolecules": ["Un1v3rs0Z3r0"],
        "molecular-networks": ["Un1v3rs0Z3r0"],
        "other-quantitative-biology": ["Un1v3rs0Z3r0"],
        "populations-and-evolution": ["Un1v3rs0Z3r0"],
        "quantitative-methods": ["Un1v3rs0Z3r0"],
        "subcellular-processes": ["Un1v3rs0Z3r0"],
        "tissues-and-organs": ["Un1v3rs0Z3r0"],
        # Quantitative finance subcategories (q-fin.*)
        "computational-finance": ["Un1v3rs0Z3r0", "chaumian"],
        "financial-economics": ["Un1v3rs0Z3r0", "chaumian"],
        "general-finance": ["Un1v3rs0Z3r0", "chaumian"],
        "mathematical-finance": ["Un1v3rs0Z3r0", "chaumian"],
        "portfolio-management": ["Un1v3rs0Z3r0", "chaumian"],
        "securities-pricing": ["Un1v3rs0Z3r0", "chaumian"],
        "risk-management": ["Un1v3rs0Z3r0", "chaumian"],
        "statistical-finance": ["Un1v3rs0Z3r0", "chaumian"],
        "trading-and-market-microstructure": ["Un1v3rs0Z3r0", "chaumian"],
        # Statistics subcategories (stat.*)
        "applications": ["Un1v3rs0Z3r0", "StatMLPapers"],
        "computation": ["Un1v3rs0Z3r0", "StatMLPapers"],
        "methodology": ["Un1v3rs0Z3r0", "StatMLPapers"],
        "miscellaneous": ["Un1v3rs0Z3r0", "StatMLPapers"],
        "general-statistics": ["Un1v3rs0Z3r0", "StatMLPapers"],
        # Electrical engineering subcategories (eess.*)
        "audio-and-speech-processing": ["Un1v3rs0Z3r0"],
        "image-and-video-processing": ["Un1v3rs0Z3r0"],
        "signal-processing": ["Un1v3rs0Z3r0"],
        "systems-and-control": ["Un1v3rs0Z3r0"],
        # Economics subcategories (econ.*)
        "econometrics": ["Un1v3rs0Z3r0", "CapybaraPapers"],
        "general-economics": ["Un1v3rs0Z3r0", "CapybaraPapers"],
        "economic-theory": ["Un1v3rs0Z3r0", "CapybaraPapers"],
    },
    "medrxiv": {
        # Medicine subcategories
        "psychiatry": ["medrxivpreprint"],
        "immunology": ["medrxivpreprint"],
        "anesthesiology": ["medrxivpreprint"],
        "cardiology": ["medrxivpreprint"],
        "dentistry": ["medrxivpreprint"],
        "dermatology": ["medrxivpreprint"],
        "emergency-medicine": ["medrxivpreprint"],
        "endocrinology": ["medrxivpreprint"],
        "epidemiology": ["medrxivpreprint"],
        "pathology": ["medrxivpreprint"],
        "gastroenterology": ["medrxivpreprint"],
        "genetics-and-genomics": ["medrxivpreprint"],
        "internal-medicine": ["medrxivpreprint"],
        "health-economics": ["medrxivpreprint"],
        "health-informatics": ["medrxivpreprint"],
        "health-policy": ["medrxivpreprint"],
        "hematology": ["medrxivpreprint"],
        "infectious-disease": ["medrxivpreprint"],
        "critical-care-medicine": ["medrxivpreprint"],
        "medical-education": ["medrxivpreprint"],
        "medical-ethics": ["medrxivpreprint"],
        "nephrology": ["medrxivpreprint"],
        "neurology": ["medrxivpreprint"],
        "nursing": ["medrxivpreprint"],
        "nutrition": ["medrxivpreprint"],
        "obstetrics-and-gynecology": ["medrxivpreprint"],
        "public-health": ["medrxivpreprint"],
        "oncology": ["medrxivpreprint"],
        "ophthalmology": ["medrxivpreprint"],
        "orthopedics": ["medrxivpreprint"],
        "otolaryngology": ["medrxivpreprint"],
        "pain-medicine": ["medrxivpreprint"],
        "palliative-medicine": ["medrxivpreprint"],
        "pediatrics": ["medrxivpreprint"],
        "pharmacology": ["medrxivpreprint"],
        "radiology": ["medrxivpreprint"],
        "physical-therapy": ["medrxivpreprint"],
        "pulmonology": ["medrxivpreprint"],
        "rheumatology": ["medrxivpreprint"],
        "reproductive-health": ["medrxivpreprint"],
        "sports-medicine": ["medrxivpreprint"],
        "surgery": ["medrxivpreprint"],
        "urology": ["medrxivpreprint"],
    },
    "chemrxiv": {
        # Chemistry subcategories
        "food-chemistry": ["chemRxivBiochem"],
        "analytical-chemistry": ["chemRxivBiochem"],
        "catalysis": ["chemRxivBiochem"],
        "chemical-education": ["chemRxivBiochem"],
        "inorganic-chemistry": ["chemRxivBiochem"],
        "materials-chemistry": ["chemRxivBiochem"],
        "materials-science": ["chemRxivBiochem"],
        "nanochemistry": ["chemRxivBiochem"],
        "organic-chemistry": ["chemRxivBiochem"],
        "organometallic-chemistry": ["chemRxivBiochem"],
        "physical-chemistry": ["chemRxivBiochem"],
        "analytical-biochemistry": ["chemRxivBiochem"],
        "computational-chemistry": ["chemRxivBiochem"],
        "environmental-chemistry": ["chemRxivBiochem"],
        "geochemistry": ["chemRxivBiochem"],
        "astrochemistry": ["chemRxivBiochem"],
        "electrochemistry": ["chemRxivBiochem"],
        "chemical-engineering": ["chemRxivBiochem"],
        "nuclear-chemistry": ["chemRxivBiochem"],
        "supramolecular-chemistry": ["chemRxivBiochem"],
        "medicinal-chemistry": ["chemRxivBiochem"],
        "surface-chemistry": ["chemRxivBiochem"],
        "chemical-biology": ["chemRxivBiochem"],
        # Biology subcategories (from chemrxiv)
        "biochemistry": ["chemRxivBiochem"],
        "bioengineering": ["chemRxivBiochem"],
        "biophysics": ["chemRxivBiochem"],
        "cell-biology": ["chemRxivBiochem"],
        "ecology": ["chemRxivBiochem"],
        "microbiology": ["chemRxivBiochem"],
        "plant-biology": ["chemRxivBiochem"],
        # Physics subcategories (from chemrxiv)
        "physics": ["chemRxivBiochem"],
        "optics": ["chemRxivBiochem"],
        "condensed-matter": ["chemRxivBiochem"],
        "statistical-mechanics": ["chemRxivBiochem"],
        # Engineering subcategories (from chemrxiv)
        "robotics": ["chemRxivBiochem"],
        # Computer science subcategories (from chemrxiv)
        "machine-learning": ["chemRxivBiochem"],
        "quantum-computing": ["chemRxivBiochem"],
    },
}
