# Generated by Django 2.2 on 2021-06-03 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchhubAccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text="Public means it's accessible disregarding user's status")),
                ('admin', models.ManyToManyField(blank=True, null=True, related_name='access_admin_groups', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ManyToManyField(blank=True, null=True, related_name='access_editor_groups', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ManyToManyField(blank=True, null=True, related_name='access_viewing_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
