# Generated by Django 2.2 on 2021-06-03 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchhubaccessgroup',
            name='admin',
            field=models.ManyToManyField(related_name='access_admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchhubaccessgroup',
            name='editor',
            field=models.ManyToManyField(related_name='access_editor_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchhubaccessgroup',
            name='viewer',
            field=models.ManyToManyField(related_name='access_viewing_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
