# Generated by Django 2.2 on 2021-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0002_auto_20210603_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchhubaccessgroup',
            old_name='admin',
            new_name='admins',
        ),
        migrations.RenameField(
            model_name='researchhubaccessgroup',
            old_name='editor',
            new_name='editors',
        ),
        migrations.RenameField(
            model_name='researchhubaccessgroup',
            old_name='viewer',
            new_name='viewers',
        ),
    ]
