# Generated by Django 2.2 on 2021-10-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0005_auto_20211006_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='access_group',
        ),
    ]
