# Generated by Django 2.2 on 2021-10-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0007_delete_researchhubaccessgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_doc_permissions', to='user.Organization'),
        ),
    ]
