# Generated by Django 2.2 on 2021-10-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0008_auto_20211007_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
    ]
