# Generated by Django 2.2 on 2021-10-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0009_remove_permission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user.Organization'),
            preserve_default=False,
        ),
    ]
