# Generated by Django 2.2 on 2021-10-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0010_auto_20211020_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_permissions', to='user.Organization'),
        ),
    ]
