# Generated by Django 2.2 on 2021-10-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0011_auto_20211018_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='user.Organization'),
        ),
    ]
