# Generated by Django 2.2 on 2022-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0011_auto_20211020_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
