# Generated by Django 4.1 on 2023-05-04 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researchhub_access_group", "0012_alter_permission_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="user",
            field=models.ForeignKey(
                help_text="single user that belongs to this permission",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
