# Generated by Django 2.2 on 2021-10-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_access_group', '0012_auto_20211018_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='organization',
            new_name='owner',
        ),
    ]
