# Generated by Django 4.2.15 on 2024-09-26 23:33

from django.db import migrations, models
from researchhub_access_group.constants import ASSISTANT_EDITOR, EDITOR


def migrate_hub_editors(apps, schema_editor):
    Permission = apps.get_model('researchhub_access_group', 'permission')
    ContentType = apps.get_model("contenttypes", "contenttype")
    Hub = apps.get_model('hub', 'hub')
    hub_content_type = ContentType.objects.get_for_model(Hub)

    for permission in Permission.objects.filter(
        access_type=EDITOR,
        content_type=hub_content_type
    ).iterator():
        permission.access_type = ASSISTANT_EDITOR
        permission.save(update_fields=['access_type'])


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_access_group", "0013_alter_permission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EDITOR", "EDITOR"),
                    ("ASSISTANT_EDITOR", "ASSISTANT_EDITOR"),
                    ("ASSOCIATE_EDITOR", "ASSOCIATE_EDITOR"),
                    ("SENIOR_EDITOR", "SENIOR_EDITOR"),
                    ("VIEWER", "VIEWER"),
                    ("MEMBER", "MEMBER"),
                    ("COMMENTER", "COMMENTER"),
                    ("NO_ACCESS", "NO_ACCESS"),
                ],
                default="VIEWER",
                max_length=16,
            ),
        ),
        # Migrate existing users to Assistant Editor
        migrations.RunPython(migrate_hub_editors),
    ]
