# Generated by Django 2.2.13 on 2020-06-09 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('purchase_type', models.CharField(choices=[('OFF_CHAIN', 'OFF_CHAIN'), ('ON_CHAIN', 'ON_CHAIN')], default='ON_CHAIN', max_length=16)),
                ('status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='INITIATED', max_length=16)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
