# Generated by Django 2.2.13 on 2020-06-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_method',
            field=models.CharField(choices=[('OFF_CHAIN', 'OFF_CHAIN'), ('ON_CHAIN', 'ON_CHAIN')], default='OFF_CHAIN', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('BOOST', 'BOOST')], max_length=16),
        ),
    ]
