# Generated by Django 2.2.13 on 2020-06-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchase', '0003_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='source',
        ),
        migrations.AddField(
            model_name='balance',
            name='content_type',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
