# Generated by Django 2.2.13 on 2020-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='boost_time',
            field=models.FloatField(null=True),
        ),
    ]
