# Generated by Django 2.2.13 on 2020-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_boost_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default='INITIATED', max_length=255, null=True),
        ),
    ]
