# Generated by Django 2.2.13 on 2020-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200619_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default=None, max_length=255, null=True),
        ),
    ]
