# Generated by Django 2.2.13 on 2020-06-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200612_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='balance_type',
        ),
    ]
