# Generated by Django 2.2.13 on 2020-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200619_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='boost_score',
            field=models.IntegerField(null=True),
        ),
    ]
