# Generated by Django 2.2.13 on 2020-06-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchase_boost_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='boost_score',
        ),
    ]
