# Generated by Django 2.2.13 on 2020-08-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_purchase_boost_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='testnet_amount',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
