# Generated by Django 2.2.13 on 2020-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='paid_status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('PAID', 'PAID'), ('PENDING', 'PENDING')], default='INITIATED', max_length=255, null=True),
        ),
    ]
