# Generated by Django 2.2.13 on 2020-06-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200618_2303'),
        ('purchase', '0008_auto_20200619_1805'),
    ]

    operations = [
    ]
