# Generated by Django 2.2.14 on 2020-08-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_balance_testnet_amount'),
        ('purchase', '0009_purchase_group'),
    ]

    operations = [
    ]
