# Generated by Django 2.2.16 on 2020-10-01 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0010_merge_20200803_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('STRIPE', 'STRIPE'), ('PAYPAL', 'PAYPAL'), ('ETH', 'ETH'), ('BTC', 'BTC'), ('RSC_ON_CHAIN', 'RSC_ON_CHAIN'), ('RSC_OFF_CHAIN', 'RSC_OFF_CHAIN')], max_length=16)),
                ('duration', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MONTHLY', 'MONTHLY')], max_length=8)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(blank=True, max_length=255, null=True)),
                ('btc_address', models.CharField(blank=True, max_length=255, null=True)),
                ('rsc_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
