# Generated by Django 2.2 on 2020-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20201006_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='testnet_amount',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
