# Generated by Django 2.2 on 2020-10-16 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0012_auto_20201006_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='supported_works', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
