# Generated by Django 2.2 on 2020-10-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20201020_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='stripe_acc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='stripe_verified',
            field=models.BooleanField(default=False),
        ),
    ]
