# Generated by Django 2.2 on 2020-10-16 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0013_support_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='support',
            name='recipient',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='supported_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
