# Generated by Django 2.2 on 2020-10-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_wallet_stripe_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='stripe_verified',
            field=models.BooleanField(default=False),
        ),
    ]
