# Generated by Django 2.2 on 2020-10-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20201029_2322'),
        ('purchase', '0015_merge_20201024_0009'),
    ]

    operations = [
    ]
