# Generated by Django 2.2 on 2020-10-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_wallet_stripe_verified'),
        ('purchase', '0013_auto_20201020_2217'),
    ]

    operations = [
    ]
