# Generated by Django 2.2 on 2020-10-22 19:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_wallet_stripe_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
