# Generated by Django 2.2 on 2020-10-23 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_auto_20201016_2318'),
        ('purchase', '0016_support_proof'),
    ]

    operations = [
    ]
