# Generated by Django 2.2 on 2020-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_merge_20201030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='btc_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
