# Generated by Django 2.2 on 2020-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_auto_20201030_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='btc_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
