# Generated by Django 2.2 on 2022-04-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_auto_20220405_0106'),
        ('purchase', '0020_auto_20220329_2327'),
    ]

    operations = [
    ]
