# Generated by Django 2.2 on 2022-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_merge_20220406_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='rscexchangerate',
            name='real_rate',
            field=models.FloatField(blank=True, help_text="\n            RSC exchange rate. This may differ from 'rate' field if real rate is lower\n            than the floor-rate (arbitrary) of the recorded date.\n        ", null=True),
        ),
    ]
