# Generated by Django 2.2 on 2022-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_merge_20220406_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rscexchangerate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rscexchangerate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
