# Generated by Django 4.1 on 2022-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0022_rscexchangerate_real_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="proof",
            field=models.JSONField(null=True),
        ),
    ]
