# Generated by Django 4.1 on 2023-02-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0023_alter_support_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="rscexchangerate",
            name="price_source",
            field=models.CharField(
                choices=[
                    ("COIN_GECKO", "COIN_GECKO"),
                    ("MORALIS", "MORALIS"),
                    ("UNI_SWAP", "UNI_SWAP"),
                ],
                default="MORALIS",
                help_text="API used to get the price",
                max_length=255,
                null=True,
            ),
        ),
    ]
