# Generated by Django 4.1 on 2023-12-11 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.related_models.fundraise_model


class Migration(migrations.Migration):

    dependencies = [
        (
            "researchhub_document",
            "0055_rename_is_excluded_documentfilter_is_excluded_in_feed_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reputation", "0080_alter_escrow_hold_type"),
        ("purchase", "0024_rscexchangerate_price_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("BOOST", "BOOST"),
                    ("DOI", "DOI"),
                    ("FUNDRAISE_CONTRIBUTION", "FUNDRAISE_CONTRIBUTION"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Fundraise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        default="OPEN",
                        max_length=32,
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(decimal_places=10, default=0, max_digits=19),
                ),
                ("goal_currency", models.CharField(default="USD", max_length=16)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        default=purchase.related_models.fundraise_model.get_default_expiration_date,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escrow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraises",
                        to="reputation.escrow",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraises",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
