# Generated by Django 5.1.3 on 2024-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0026_alter_fundraise_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="stripe_acc",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="stripe_verified",
        ),
        migrations.AlterField(
            model_name="support",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("PAYPAL", "PAYPAL"),
                    ("ETH", "ETH"),
                    ("BTC", "BTC"),
                    ("RSC_ON_CHAIN", "RSC_ON_CHAIN"),
                    ("RSC_OFF_CHAIN", "RSC_OFF_CHAIN"),
                ],
                max_length=16,
            ),
        ),
    ]
