# Generated by Django 4.1.13 on 2024-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0026_alter_fundraise_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="client_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
