# Generated by Django 5.1.5 on 2025-05-15 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0028_payment"),
        ("reputation", "0100_bountysolution_awarded_amount_bountysolution_status"),
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fundraise",
            index=models.Index(fields=["status"], name="purchase_fu_status_f91f44_idx"),
        ),
        migrations.AddIndex(
            model_name="fundraise",
            index=models.Index(
                fields=["end_date"], name="purchase_fu_end_dat_877cae_idx"
            ),
        ),
    ]
