# Generated by Django 5.1.5 on 2025-05-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0029_fundraise_purchase_fu_status_f91f44_idx_and_more"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total grant amount being provided",
                        max_digits=19,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency of the grant amount",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        help_text="Name of the granting organization", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Grant description, requirements, and application details"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="OPEN",
                        help_text="Current status of the grant",
                        max_length=32,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the grant was first posted"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for grant applications",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this grant entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        help_text="Associated unified document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="purchase_gr_status_73341b_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="purchase_gr_organiz_e0c7b2_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="purchase_gr_end_dat_1fca67_idx"
                    ),
                ],
            },
        ),
    ]
