# Generated by Django 5.1.5 on 2025-06-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0030_grant"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="purchase.grant",
                    ),
                ),
                (
                    "preregistration_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_applications",
                        to="researchhub_document.researchhubpost",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["grant"], name="purchase_gr_grant_i_86b6ac_idx"
                    ),
                    models.Index(
                        fields=["applicant"], name="purchase_gr_applica_192f2b_idx"
                    ),
                ],
                "unique_together": {("grant", "preregistration_post")},
            },
        ),
    ]
