# Generated by Django 5.1.5 on 2025-06-03 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0031_grantapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contact persons for this grant",
                related_name="grant_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Name of the granting organization",
                max_length=255,
                null=True,
            ),
        ),
    ]
