# Generated by Django 5.2.1 on 2025-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0032_grant_contacts_alter_grant_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="grantapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
            ),
        ),
    ]
