# Generated by Django 5.1.5 on 2025-06-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0032_grant_contacts_alter_grant_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="balance",
            name="lock_type",
            field=models.CharField(
                blank=True,
                choices=[("FUNDRAISE_CONTRIBUTION", "Fundraise Contribution")],
                max_length=50,
                null=True,
            ),
        ),
    ]
