# Generated by Django 5.1.5 on 2025-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0033_balance_is_locked_balance_lock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="lock_type",
            field=models.TextField(
                blank=True, choices=[("REFERRAL_BONUS", "Referral Bonus")], null=True
            ),
        ),
    ]
