# Generated by Django 5.2.2 on 2025-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0034_remove_fundraise_contribution_lock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="purpose",
            field=models.TextField(
                choices=[
                    ("APC", "Article Processing Charge"),
                    ("RSC_PURCHASE", "RSC Purchase"),
                ],
                default="APC",
            ),
        ),
    ]
