# Generated by Django 5.2.2 on 2025-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0034_remove_fundraise_contribution_lock_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="lock_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("REFERRAL_BONUS", "Referral Bonus"),
                    ("USD_PURCHASE", "USD Purchase"),
                ],
                null=True,
            ),
        ),
    ]
