# Generated by Django 5.2.2 on 2025-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0035_payment_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="lock_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("REFERRAL_BONUS", "Referral Bonus"),
                    ("RSC_PURCHASE", "RSC Purchase"),
                ],
                null=True,
            ),
        ),
    ]
