# Generated by Django 5.2.2 on 2025-09-02 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("purchase", "0036_alter_balance_lock_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "paid_status", "purchase_type"],
                name="purchase_usr_status_type_idx",
            ),
        ),
    ]
