# Generated by Django 5.2.2 on 2025-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0036_alter_balance_lock_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RscPurchaseFee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("expiration_date", models.DateTimeField(null=True)),
                ("rh_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dao_pct", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
