# Generated by Django 5.2.10 on 2026-01-19 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("purchase", "0037_purchase_purchase_usr_status_type_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsdBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount_cents",
                    models.IntegerField(
                        help_text="Amount in cents. Positive = credit, negative = debit"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usd_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="purchase_us_user_id_3fd105_idx"
                    ),
                    models.Index(
                        fields=["created_date"], name="purchase_us_created_d768f6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsdFundraiseContribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount_cents",
                    models.IntegerField(help_text="Contribution amount in cents"),
                ),
                (
                    "fee_cents",
                    models.IntegerField(default=0, help_text="9% fee in cents"),
                ),
                (
                    "fundraise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usd_contributions",
                        to="purchase.fundraise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usd_fundraise_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fundraise"], name="purchase_us_fundrai_18f038_idx"
                    ),
                    models.Index(
                        fields=["user"], name="purchase_us_user_id_37a934_idx"
                    ),
                ],
            },
        ),
    ]
