# Generated by Django 5.2.10 on 2026-01-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0038_usdbalance_usdfundraisecontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
    ]
