# Generated by Django 5.2.10 on 2026-01-22 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("purchase", "0038_usdbalance_usdfundraisecontribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingDistributionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "distribution_date",
                    models.DateField(
                        help_text="The date this distribution was executed", unique=True
                    ),
                ),
                (
                    "total_pool_amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Total funding credits available for distribution",
                        max_digits=19,
                    ),
                ),
                (
                    "total_weighted_balance",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Sum of all users' weighted balances",
                        max_digits=19,
                    ),
                ),
                (
                    "users_rewarded",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of users who received rewards"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if distribution failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["distribution_date"],
                        name="purchase_st_distrib_0ae390_idx",
                    ),
                    models.Index(
                        fields=["status"], name="purchase_st_status_93f2c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BalanceEntryDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "entry_date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this RSC batch entered the account",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Original amount when RSC entered account",
                        max_digits=19,
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Amount remaining after any FIFO withdrawals",
                        max_digits=19,
                    ),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entry_date_record",
                        to="purchase.balance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_entry_dates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "entry_date"],
                        name="purchase_ba_user_id_bec066_idx",
                    ),
                    models.Index(
                        fields=["user", "remaining_amount"],
                        name="purchase_ba_user_id_a6c239_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FundingCredit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Amount in RSC-equivalent. Positive = earned, negative = spent",
                        max_digits=19,
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("STAKING_REWARD", "Staking Reward"),
                            ("FUNDRAISE_CONTRIBUTION", "Fundraise Contribution"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="purchase_fu_user_id_1bb69d_idx"
                    ),
                    models.Index(
                        fields=["created_date"], name="purchase_fu_created_f23442_idx"
                    ),
                    models.Index(
                        fields=["credit_type"], name="purchase_fu_credit__8992dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StakingSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "rsc_balance",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="User's RSC balance at snapshot time",
                        max_digits=19,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Time-weighted multiplier (1.0x to 7.5x)",
                        max_digits=5,
                    ),
                ),
                (
                    "weighted_balance",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="RSC balance multiplied by time-weighted multiplier",
                        max_digits=19,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staking_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="purchase_st_snapsho_0321b0_idx"
                    ),
                    models.Index(
                        fields=["user", "snapshot_date"],
                        name="purchase_st_user_id_7426b9_idx",
                    ),
                ],
                "unique_together": {("user", "snapshot_date")},
            },
        ),
    ]
