# Generated by Django 5.2.10 on 2026-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0038_usdbalance_usdfundraisecontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_type",
            field=models.TextField(
                choices=[("CARD", "Card"), ("ACH", "ACH Bank Transfer")], default="CARD"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.TextField(
                choices=[
                    ("FAILED", "Failed"),
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                ],
                default="SUCCEEDED",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.TextField(
                choices=[
                    ("APC", "Article Processing Charge"),
                    ("RSC_PURCHASE", "RSC Purchase"),
                    ("FUNDING_CREDITS", "Funding Credits"),
                ],
                default="APC",
            ),
        ),
    ]
