# Generated by Django 5.2.10 on 2026-01-29 08:50

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0041_add_initial_rsc_purchase_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndaomentAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedTextField(
                        help_text="Endaoment access token"
                    ),
                ),
                (
                    "refresh_token",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, help_text="Endaoment refresh token", null=True
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="Access token expiration time"),
                ),
                (
                    "endaoment_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Endaoment's user ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endaoment_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
