# Generated by Django 5.2.10 on 2026-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0042_endaomentaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="amount_rsc",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="RSC equivalent at contribution date",
                max_digits=19,
                null=True,
            ),
        ),
    ]
