# Generated by Django 5.2.11 on 2026-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0042_endaomentaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="destination_org_id",
            field=models.CharField(
                blank=True,
                help_text="Intended destination organization ID in Endaoment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="endaoment_transfer_id",
            field=models.CharField(
                blank=True,
                help_text="Endaoment grant transfer ID (external ID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="origin_fund_id",
            field=models.CharField(
                blank=True,
                help_text="Origin fund (DAF) ID in Endaoment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="status",
            field=models.CharField(
                choices=[("SUBMITTED", "SUBMITTED"), ("CANCELLED", "CANCELLED")],
                default="SUBMITTED",
                help_text="Processual status of the contribution",
                max_length=32,
            ),
        ),
    ]
