# Generated by Django 5.2.11 on 2026-02-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0042_endaomentaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="destination_org_id",
            field=models.CharField(
                blank=True,
                db_comment="Endaoment destination organization ID",
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="endaoment_transfer_id",
            field=models.CharField(
                blank=True,
                db_comment="Endaoment grant transfer ID (external ID)",
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="origin_fund_id",
            field=models.CharField(
                blank=True,
                db_comment="Endaoment origin fund ID (DAF)",
                default="",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="usdfundraisecontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "COMPLETED"),
                    ("RESERVED", "RESERVED"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                db_comment="Contribution lifecycle status for fundraise processing",
                default="COMPLETED",
                max_length=16,
            ),
        ),
    ]
