# Generated by Django 5.2.11 on 2026-02-11 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0044_remove_usd_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="author",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="btc_address",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="eth_address",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="rsc_address",
        ),
        migrations.AddField(
            model_name="wallet",
            name="address",
            field=models.CharField(db_index=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="nonce",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("CONFIRMED", "Confirmed")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_type",
            field=models.CharField(
                choices=[("EXTERNAL", "External"), ("CDP_EMBEDDED", "CDP Embedded")],
                default="EXTERNAL",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CONFIRMED")),
                fields=("address",),
                name="unique_confirmed_address",
            ),
        ),
    ]
