# Generated by Django 5.2.11 on 2026-02-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0044_remove_usd_balance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
