# Generated by Django 5.2.11 on 2026-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0046_create_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="short_title",
            field=models.CharField(
                blank=True,
                help_text="Short display title for the grant",
                max_length=255,
                null=True,
            ),
        ),
    ]
