# Generated by Django 5.2.11 on 2026-02-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0047_grant_short_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="circle_base_wallet_id",
            field=models.CharField(
                blank=True,
                help_text="Circle wallet ID for the Base chain.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="circle_wallet_id",
            field=models.CharField(
                blank=True,
                help_text="Circle wallet ID for the Ethereum chain.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
