# Generated by Django 5.2.12 on 2026-03-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0048_wallet_circle_base_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="balance_records",
                to="purchase.purchase",
            ),
        ),
    ]
