# Generated by Django 5.2.12 on 2026-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0050_balance_purchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="lock_type",
        ),
    ]
