# Generated by Django 5.2.12 on 2026-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0051_remove_balance_lock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="rsc_usd_rate",
            field=models.FloatField(
                blank=True,
                help_text="RSC-to-USD exchange rate at the time of purchase (USD per RSC).",
                null=True,
            ),
        ),
    ]
