# Generated by Django 5.2.12 on 2026-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0052_purchase_rsc_usd_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="rsc_usd_rate",
            field=models.FloatField(
                blank=True,
                help_text="RSC-to-USD exchange rate at the time of purchase.",
                null=True,
            ),
        ),
    ]
