# Generated by Django 5.2.13 on 2026-04-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0053_alter_purchase_rsc_usd_rate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Support",
        ),
    ]
