# Generated by Django 5.2.13 on 2026-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0053_alter_purchase_rsc_usd_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="application_visibility",
            field=models.CharField(
                choices=[
                    ("OPTIONAL", "Applicant chooses"),
                    ("PRIVATE", "Applications must be private"),
                    ("PUBLIC", "Applications must be public"),
                ],
                default="OPTIONAL",
                help_text="Privacy rule applied to preregistrations applying to this grant. OPTIONAL lets the applicant choose; PRIVATE/PUBLIC overrides the applicant's is_public setting.",
                max_length=16,
            ),
        ),
    ]
