# Generated by Django 5.2.13 on 2026-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0054_grant_application_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="external_payment_id",
            field=models.TextField(unique=True),
        ),
    ]
