# Generated by Django 5.2.14 on 2026-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0055_payment_external_payment_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_method",
            field=models.CharField(choices=[("OFF_CHAIN", "OFF_CHAIN")], max_length=16),
        ),
    ]
