# Generated by Django 5.2.15 on 2026-07-10 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("purchase", "0056_alter_purchase_purchase_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="lock_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("FUNDING_CREDIT", "Funding Credit"),
                    ("REFERRAL_BONUS", "Referral Bonus"),
                    ("STAKING_YIELD", "Staking Yield"),
                    ("PROMOTIONAL", "Promotional"),
                ],
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="balance",
            index=models.Index(
                condition=models.Q(("lock_type__isnull", False)),
                fields=["lock_type"],
                name="balance_lock_type_idx",
            ),
        ),
    ]
