# Generated by Django 5.2.14 on 2026-06-02 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0056_alter_purchase_purchase_method"),
        (
            "reputation",
            "0118_withdrawal_broadcast_nonce_alter_deposit_paid_status_and_more",
        ),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fundraise",
            index=models.Index(
                fields=["unified_document_id", "status"], name="fundraise_ud_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundraise",
            index=models.Index(
                fields=["status", "end_date"], name="fundraise_status_end_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["unified_document_id", "status"], name="grant_ud_status_idx"
            ),
        ),
    ]
