# Generated by Django 5.2.14 on 2026-06-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0057_fundraise_fundraise_ud_status_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fundraise",
            name="fundraise_ud_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="fundraise",
            name="fundraise_status_end_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="grant",
            name="grant_ud_status_idx",
        ),
    ]
