# Generated by Django 5.2.17 on 2026-09-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0060_alter_rscexchangerate_price_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("BOOST", "BOOST"),
                    ("DOI", "DOI"),
                    ("FUNDRAISE_CONTRIBUTION", "FUNDRAISE_CONTRIBUTION"),
                    ("FUNDING_POOL_CONTRIBUTION", "FUNDING_POOL_CONTRIBUTION"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FundingPool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount_holding",
                    models.DecimalField(
                        db_comment="RSC currently held in the pool and available to distribute",
                        decimal_places=10,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "amount_distributed",
                    models.DecimalField(
                        db_comment="RSC distributed from the pool into proposal fundraises",
                        decimal_places=10,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        db_comment="Whether the pool accepts contributions and distributions",
                        default="OPEN",
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="Grant creator at pool creation time",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.OneToOneField(
                        db_comment="Grant this pool belongs to (one pool per grant)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_pool",
                        to="purchase.grant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingDistribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="RSC amount moved from the pool into the proposal fundraise",
                        decimal_places=10,
                        max_digits=19,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "APPLIED"),
                            ("REVERSED", "REVERSED"),
                            ("SETTLED", "SETTLED"),
                        ],
                        db_comment="APPLIED while in escrow; REVERSED on close; SETTLED on complete",
                        default="APPLIED",
                        max_length=32,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_comment="Grant application whose proposal fundraise was topped up",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_distributions",
                        to="purchase.grantapplication",
                    ),
                ),
                (
                    "distributed_by",
                    models.ForeignKey(
                        db_comment="User who performed the distribution (audit only; no wallet debit)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fundraise_purchase",
                    models.OneToOneField(
                        db_comment="Audit Purchase on the proposal fundraise; identifies pool-sourced slices on close/complete",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_distribution",
                        to="purchase.purchase",
                    ),
                ),
                (
                    "target_fundraise",
                    models.ForeignKey(
                        db_comment="Proposal fundraise that received the pool top-up",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_distributions",
                        to="purchase.fundraise",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        db_comment="Pool the funds were drawn from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="purchase.fundingpool",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fundingpool",
            index=models.Index(fields=["status"], name="purchase_fu_status_pool_idx"),
        ),
        migrations.AddIndex(
            model_name="fundingdistribution",
            index=models.Index(
                fields=["pool", "status"], name="purchase_fu_pool_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundingdistribution",
            index=models.Index(
                fields=["target_fundraise", "status"],
                name="purchase_fu_tfund_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fundingdistribution",
            index=models.Index(fields=["status"], name="purchase_fu_status_dist_idx"),
        ),
    ]
