# Generated by Django 5.2.17 on 2026-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0061_alter_purchase_purchase_type_fundingpool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.TextField(
                choices=[
                    ("APC", "Article Processing Charge"),
                    ("RSC_PURCHASE", "RSC Purchase"),
                    ("FUNDING_CREDITS_PURCHASE", "Funding Credits Purchase"),
                ],
                default="APC",
            ),
        ),
    ]
