# Generated by Django 5.2.17 on 2026-09-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0061_alter_purchase_purchase_type_fundingpool_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="boost_time",
        ),
    ]
