# Generated by Django 5.2.17 on 2026-09-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0062_remove_purchase_boost_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Support",
        ),
    ]
