# Generated by Django 5.2.10 on 2026-02-03 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertSearch",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="Research description or document content used for the search."
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("abstract", "abstract"),
                            ("pdf", "pdf"),
                            ("custom_query", "custom_query"),
                            ("full_content", "full_content"),
                        ],
                        default="abstract",
                        max_length=32,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Expert count, expertise_level, region, state, gender, etc.",
                    ),
                ),
                (
                    "excluded_expert_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of expert full names to exclude (for multiple runs on same doc).",
                    ),
                ),
                ("llm_model", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=512)),
                (
                    "expert_results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of expert dicts: name, title, affiliation, expertise, email, notes, sources.",
                    ),
                ),
                ("expert_count", models.IntegerField(default=0)),
                ("report_pdf_url", models.URLField(blank=True, max_length=2048)),
                ("report_csv_url", models.URLField(blank=True, max_length=2048)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_research_ai_expert_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document-based search; null for custom query.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_searches",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_expert_search",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedEmail",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expert_name", models.CharField(blank=True, max_length=255)),
                ("expert_title", models.CharField(blank=True, max_length=255)),
                ("expert_affiliation", models.CharField(blank=True, max_length=512)),
                ("expert_email", models.CharField(blank=True, max_length=255)),
                ("expertise", models.CharField(blank=True, max_length=512)),
                ("email_subject", models.TextField(blank=True)),
                ("email_body", models.TextField(blank=True)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("collaboration", "collaboration"),
                            ("consultation", "consultation"),
                            ("conference", "conference"),
                            ("peer-review", "peer-review"),
                            ("publication", "publication"),
                            ("rfp-outreach", "rfp-outreach"),
                            ("custom", "custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("sent", "sent")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_research_ai_generated_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expert_search",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_emails",
                        to="research_ai.expertsearch",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_generated_email",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddIndex(
            model_name="expertsearch",
            index=models.Index(
                fields=["created_by", "status"], name="research_ai_es_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="expertsearch",
            index=models.Index(fields=["status"], name="research_ai_es_status"),
        ),
        migrations.AddIndex(
            model_name="generatedemail",
            index=models.Index(fields=["created_by"], name="research_ai_ge_created_by"),
        ),
    ]
