# Generated by Django 5.2.11 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertsearch",
            name="name",
            field=models.CharField(
                blank=True,
                db_comment="Optional user-defined search name; auto-filled from document title if not provided.",
                max_length=512,
            ),
        ),
    ]
