# Generated by Django 5.2.11 on 2026-02-22 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0002_add_expert_search_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_comment="User-defined template name.", max_length=255
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_title", models.CharField(blank=True, max_length=255)),
                ("contact_institution", models.CharField(blank=True, max_length=512)),
                ("contact_email", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=64)),
                ("contact_website", models.CharField(blank=True, max_length=512)),
                (
                    "outreach_context",
                    models.TextField(
                        blank=True,
                        db_comment="Context provided to the LLM when generating emails.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Only one template per user can be active at a time.",
                        default=False,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_research_ai_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_email_template",
                "ordering": ["-updated_date"],
                "indexes": [
                    models.Index(
                        fields=["created_by"], name="research_ai_et_created_by"
                    ),
                    models.Index(
                        fields=["created_by", "is_active"],
                        name="research_ai_et_user_active",
                    ),
                ],
            },
        ),
    ]
