# Generated by Django 5.2.11 on 2026-02-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0003_emailtemplate"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentInvitedExpert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "expert_search",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Search that surfaced this expert for this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_invited_experts",
                        to="research_ai.expertsearch",
                    ),
                ),
                (
                    "generated_email",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Generated email if invite tied to one; null if only in expert_results.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_invited_experts",
                        to="research_ai.generatedemail",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_invited_experts",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_invited_expert_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_document_invited_expert",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["unified_document"], name="research_ai_die_unified_doc"
                    ),
                    models.Index(
                        fields=["expert_search"], name="research_ai_die_expert_search"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unified_document", "user"),
                        name="research_ai_die_doc_user_unique",
                    )
                ],
            },
        ),
    ]
