# Generated by Django 5.2.11 on 2026-03-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0004_alter_generatedemail_expert_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
