# Generated by Django 5.2.11 on 2026-03-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0004_document_invited_expert"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailtemplate",
            name="research_ai_et_user_active",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="is_active",
        ),
    ]
