# Generated by Django 5.2.11 on 2026-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0005_alter_generatedemail_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="email_body",
            field=models.TextField(
                blank=True,
                db_comment="Body for fixed-template; may contain {{entity.field}}.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="email_subject",
            field=models.TextField(
                blank=True,
                db_comment="Subject for fixed-template; may contain {{entity.field}}.",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("prompt-context", "Prompt context"),
                    ("fixed-template", "Fixed template"),
                ],
                db_comment="prompt-context (LLM) or fixed-template (variable substitution).",
                default="prompt-context",
                max_length=32,
            ),
        ),
    ]
