# Generated by Django 5.2.12 on 2026-03-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0048_wallet_circle_base_wallet_id"),
        (
            "research_ai",
            "0005_emailtemplate_email_body_emailtemplate_email_subject_and_more",
        ),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RFPSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("summary_content", models.TextField(blank=True)),
                (
                    "executive_comparison_summary",
                    models.TextField(
                        blank=True,
                        db_comment="Funder-facing comparison when top proposals are close.",
                    ),
                ),
                (
                    "executive_comparison_updated_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_rfp_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_ai_rfp_summary",
                        to="purchase.grant",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_rfp_summary",
                "ordering": ["-updated_date"],
            },
        ),
        migrations.CreateModel(
            name="ProposalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("poor", "poor"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("overall_score_numeric", models.IntegerField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=512)),
                ("llm_model", models.CharField(blank=True, max_length=256)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_proposal_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Funding opportunity context; null for standalone review.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_reviews",
                        to="purchase.grant",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        db_comment="Preregistration unified document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_reviews",
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_proposal_review",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["grant", "status"], name="research_ai_pr_grant_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(grant__isnull=False),
                        fields=("unified_document", "grant"),
                        name="research_ai_pr_ud_grant_nn",
                    ),
                    models.UniqueConstraint(
                        condition=Q(grant__isnull=True),
                        fields=("unified_document",),
                        name="research_ai_pr_ud_standalone",
                    ),
                ],
            },
        ),
    ]
