# Generated by Django 5.2.12 on 2026-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research_ai",
            "0005_emailtemplate_email_body_emailtemplate_email_subject_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_institution",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_title",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="contact_website",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="outreach_context",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="template_type",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_body",
            field=models.TextField(
                blank=True, db_comment="Body; may contain {{entity.field}}."
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_subject",
            field=models.TextField(
                blank=True, db_comment="Subject; may contain {{entity.field}}."
            ),
        ),
        migrations.AlterField(
            model_name="generatedemail",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaboration", "collaboration"),
                    ("consultation", "consultation"),
                    ("conference", "conference"),
                    ("peer-review", "peer-review"),
                    ("publication", "publication"),
                    ("rfp-outreach", "rfp-outreach"),
                    ("custom", "custom"),
                ],
                db_comment="LLM prompt key; null when placeholder is for fixed {{}} template only.",
                default="custom",
                max_length=32,
                null=True,
            ),
        ),
    ]
