# Generated by Django 5.2.12 on 2026-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0006_remove_emailtemplate_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertsearch",
            name="additional_context",
            field=models.TextField(
                blank=True,
                db_comment="Optional user notes to steer expert-finder alongside the RFP/query.",
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("sending", "sending"),
                    ("send_failed", "send_failed"),
                    ("closed", "closed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
