# Generated by Django 5.2.12 on 2026-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0007_expertsearch_additional_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedemail",
            name="bounced_at",
            field=models.DateTimeField(
                blank=True, db_comment="Timestamp of bounce email event.", null=True
            ),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="open_count",
            field=models.IntegerField(
                db_comment="Number of email open events.", default=0
            ),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="opened_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="Timestamp of first tracked email open event.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="ses_message_id",
            field=models.CharField(
                blank=True,
                db_comment="SES message ID to correlate email events.",
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("sending", "sending"),
                    ("send_failed", "send_failed"),
                    ("closed", "closed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
