# Generated by Django 5.2.12 on 2026-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0008_remove_expertsearch_excluded_expert_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="last_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="Last time an outreach email was sent to this expert address (any search).",
                null=True,
            ),
        ),
    ]
