# Generated by Django 5.2.12 on 2026-04-10 15:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research_ai",
            "0008_generatedemail_bounced_at_generatedemail_open_count_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertsearch",
            name="excluded_expert_names",
        ),
        migrations.AddField(
            model_name="expertsearch",
            name="excluded_search_ids",
            field=models.JSONField(
                blank=True,
                db_comment="Expert Search ids to exclude from new search results.",
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="expertsearch",
            name="expert_results",
            field=models.JSONField(
                blank=True,
                db_comment="Deprecated: use SearchExpert + Expert rows; may be empty after migration.",
                default=list,
            ),
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_comment="Normalized lowercase for matching.",
                        db_index=True,
                        max_length=254,
                    ),
                ),
                (
                    "honorific",
                    models.CharField(
                        blank=True, db_comment="e.g. Dr, Prof, Mr, Ms", max_length=64
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True, db_comment="Credentials e.g. PhD, MD", max_length=64
                    ),
                ),
                (
                    "academic_title",
                    models.CharField(
                        blank=True,
                        db_comment="Role e.g. Professor, Associate Professor",
                        max_length=255,
                    ),
                ),
                ("affiliation", models.TextField(blank=True)),
                ("expertise", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "last_email_sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Last time an outreach email was sent to this expert address (any search).",
                        null=True,
                    ),
                ),
                (
                    "registered_user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="RH user who signed up with this expert email.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_ai_expert_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_expert",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="SearchExpert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_experts",
                        to="research_ai.expert",
                    ),
                ),
                (
                    "expert_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_experts",
                        to="research_ai.expertsearch",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_search_expert",
                "ordering": ["expert_search", "position"],
            },
        ),
        migrations.DeleteModel(
            name="DocumentInvitedExpert",
        ),
        migrations.AddIndex(
            model_name="expert",
            index=models.Index(
                fields=["registered_user"], name="ra_expert_reg_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expert",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="research_ai_expert_email_lower_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="searchexpert",
            index=models.Index(
                fields=["expert_search", "position"], name="ra_se_search_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchexpert",
            constraint=models.UniqueConstraint(
                fields=("expert_search", "expert"),
                name="research_ai_se_search_expert_unique",
            ),
        ),
    ]
