# Generated by Django 5.2.13 on 2026-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0009_expert_and_search_expert"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertsearch",
            name="excluded_search_ids",
            field=models.JSONField(
                blank=True,
                db_comment="Expert ids to exclude from new search results.",
                default=list,
            ),
        ),
    ]
