# Generated by Django 5.2.13 on 2026-05-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0010_expertsearch_excluded_search_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertsearch",
            name="excluded_expert_names",
        ),
        migrations.RemoveField(
            model_name="expertsearch",
            name="expert_results",
        ),
        migrations.DeleteModel(
            name="DocumentInvitedExpert",
        ),
    ]
