# Generated by Django 5.2.14 on 2026-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0011_remove_expertsearch_excluded_expert_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="is_manually_added",
            field=models.BooleanField(
                db_comment="True if this expert has ever been manually added to a search by a user. Used to prioritize manual entries in search result listings.",
                default=False,
            ),
        ),
    ]
