# Generated by Django 5.2.14 on 2026-05-20 19:35

from django.db import migrations, models


def backfill_is_manually_added(apps, schema_editor):
    """
    Set is_manually_added=True for any Expert whose ``sources`` JSON already
    contains a ``{"type": "manual"}`` entry from earlier manual additions.
    """
    Expert = apps.get_model("research_ai", "Expert")
    Expert.objects.filter(
        sources__contains=[{"type": "manual"}]
    ).update(is_manually_added=True)


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0011_remove_expertsearch_excluded_expert_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="is_manually_added",
            field=models.BooleanField(
                db_comment="True if this expert has ever been manually added to a search by a user. Used to prioritize manual entries in search result listings.",
                default=False,
            ),
        ),
        migrations.RunPython(
            backfill_is_manually_added,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
