# Generated by Django 5.2.14 on 2026-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_ai", "0012_expert_is_manually_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="profile",
            field=models.JSONField(
                blank=True,
                db_comment=(
                    "Persisted, source-attributed researcher profile built once by "
                    "researcher_profile_service (OpenAlex/ORCID resolver + web "
                    "search) and reused by the proposal draft engine and source "
                    "verifier."
                ),
                default=dict,
            ),
        ),
    ]
