# Generated by Django 5.2.14 on 2026-06-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0013_expert_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertsearch",
            name="excluded_search_ids",
        ),
    ]
