# Generated by Django 5.2.14 on 2026-06-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0009_alter_note_document_type"),
        ("research_ai", "0014_remove_expertsearch_excluded_search_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("BUILDING_PROFILE", "Building Profile"),
                            ("DRAFTING", "Drafting"),
                            ("JUDGING", "Judging"),
                            ("REVISING", "Revising"),
                            ("VERIFYING", "Verifying"),
                            ("WRITING_NOTE", "Writing Note"),
                            ("DONE", "Done"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("rounds_used", models.IntegerField(default=0)),
                (
                    "run_config",
                    models.JSONField(
                        blank=True,
                        db_comment="Snapshot of the models/config that actually ran: generator model, judge panel roster, max_rounds, etc. Recorded for reproducibility since the engine's roster is configurable and the loop is non-deterministic.",
                        default=dict,
                    ),
                ),
                (
                    "final_scores",
                    models.JSONField(
                        blank=True, db_comment="Last panel rollup.", default=dict
                    ),
                ),
                (
                    "gate_report",
                    models.JSONField(
                        blank=True,
                        db_comment="Programmatic gate results.",
                        default=dict,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="User who triggered the draft; null for system/automatic runs or if the user is later deleted (the job record is kept for diagnostics).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_research_ai_proposal_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_drafts",
                        to="note.note",
                    ),
                ),
                (
                    "search_expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_drafts",
                        to="research_ai.searchexpert",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_proposal_draft",
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(fields=["status"], name="research_ai_pd_status"),
                    models.Index(
                        fields=["search_expert", "status"],
                        name="research_ai_pd_search_status",
                    ),
                ],
            },
        ),
    ]
