# Generated by Django 5.2.14 on 2026-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0015_proposaldraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposaldraft",
            name="last_submission",
            field=models.JSONField(
                blank=True,
                db_comment="The last draft the agent submitted (sections, prosemirror, plain_text, citations). On a COMPLETED run the accepted draft also lives on the linked Note; this field exists so a FAILED run's rejected draft is still inspectable, since it is never written as a Note.",
                default=dict,
            ),
        ),
    ]
