# Generated by Django 5.2.15 on 2026-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0016_proposaldraft_last_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedemail",
            name="complained_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="Timestamp of complaint (spam report) email event.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generatedemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("bounced", "bounced"),
                    ("complained", "complained"),
                    ("draft", "draft"),
                    ("sent", "sent"),
                    ("processing", "processing"),
                    ("failed", "failed"),
                    ("sending", "sending"),
                    ("send_failed", "send_failed"),
                    ("closed", "closed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
