# Generated by Django 5.2.15 on 2026-07-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_ai", "0017_generatedemail_complained_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PROPOSAL_DRAFT", "Proposal Draft"),
                            ("NOTEBOOK_CHAT", "Notebook Chat"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        db_comment=(
                            "The system prompt for this conversation. A flow that "
                            "changes the system prompt starts a new conversation."
                        )
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "User who owns this conversation; null for "
                            "headless/system runs."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_research_ai_agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_conversation",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="proposaldraft",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_drafts",
                to="research_ai.agentconversation",
            ),
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("stop_reason", models.CharField(blank=True, max_length=64)),
                ("iterations", models.IntegerField(default=0)),
                ("model_id", models.CharField(blank=True, max_length=256)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        db_comment=(
                            "Snapshot of the agent config for reproducibility: "
                            "max_iterations, max_tokens, temperature, tool names, "
                            "and flow-specific knobs."
                        ),
                        default=dict,
                    ),
                ),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                ("cache_read_tokens", models.BigIntegerField(default=0)),
                ("cache_write_tokens", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="research_ai.agentconversation",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_run",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        db_comment="Per-conversation message order, starting at 1."
                    ),
                ),
                ("role", models.CharField(max_length=16)),
                (
                    "content",
                    models.JSONField(
                        db_comment=(
                            "The exact serialized block list from the neutral "
                            "agent Message shape, subject only to the configured "
                            "large-string truncation cap."
                        )
                    ),
                ),
                ("input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("output_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_read_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_write_tokens", models.BigIntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=64)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="research_ai.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_message",
                "ordering": ["conversation", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="agentconversation",
            index=models.Index(
                fields=["created_by", "kind"], name="ra_agent_conv_user_kind"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["conversation"], name="ra_agent_run_conv_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["status"], name="ra_agent_run_status"),
        ),
        migrations.AddIndex(
            model_name="agentmessage",
            index=models.Index(fields=["run"], name="ra_agent_msg_run_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="ra_msg_conv_seq_unique"
            ),
        ),
    ]
