# Generated by Django 5.2.15 on 2026-07-21 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0009_alter_note_document_type"),
        ("research_ai", "0018_proposal_draft_outreach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.CharField(
                        blank=True,
                        db_comment=(
                            "Stable identifier for the workflow that created the "
                            "conversation, such as proposal_draft or notebook_chat."
                        ),
                        max_length=64,
                    ),
                ),
                ("next_trace_sequence", models.PositiveBigIntegerField(default=1)),
                ("next_chat_sequence", models.PositiveBigIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "Owning user; null for headless workflows or deleted users."
                        ),
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_ai_agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_conversation",
            },
        ),
        migrations.AddField(
            model_name="proposaldraft",
            name="agent_conversation",
            field=models.OneToOneField(
                blank=True,
                db_comment=(
                    "Durable agent history for this draft. SET_NULL keeps the "
                    "completed proposal when trace data is deleted."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_draft",
                to="research_ai.agentconversation",
            ),
        ),
        migrations.CreateModel(
            name="NoteAgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_links",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversation_links",
                        to="note.note",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_note_agent_conversation",
            },
        ),
        migrations.CreateModel(
            name="AgentConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "User"), ("ASSISTANT", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="research_ai.agentconversationmessage",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_conversation_message",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("INTERRUPTED", "Interrupted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("system_prompt", models.TextField(blank=True)),
                ("final_output", models.JSONField(blank=True, default=dict)),
                ("stop_reason", models.CharField(blank=True, max_length=64)),
                ("error_type", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("iterations", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "cache_read_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "cache_write_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "total_latency_ms",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("next_message_sequence", models.PositiveIntegerField(default=1)),
                ("next_context_sequence", models.PositiveIntegerField(default=1)),
                (
                    "publish_output_to_chat",
                    models.BooleanField(
                        db_comment=(
                            "Durable publication intent. A successful execution "
                            "without a generated chat message remains eligible for "
                            "repair."
                        ),
                        default=False,
                    ),
                ),
                (
                    "context_parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "Prior execution whose durable context supplies this "
                            "attempt's model context."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="continuations",
                        to="research_ai.agentexecution",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "replaces_output_of",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "Execution whose public assistant message this "
                            "regeneration replaces."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_outputs",
                        to="research_ai.agentexecution",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="research_ai.agentexecution",
                    ),
                ),
                (
                    "trigger_message",
                    models.ForeignKey(
                        blank=True,
                        db_comment=(
                            "Canonical human message reused by retries and "
                            "regenerations."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_executions",
                        to="research_ai.agentconversationmessage",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_execution",
                "ordering": ["conversation_id", "attempt"],
            },
        ),
        migrations.AddField(
            model_name="agentconversationmessage",
            name="generated_by_execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_chat_message",
                to="research_ai.agentexecution",
            ),
        ),
        migrations.CreateModel(
            name="AgentContextMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=32)),
                ("content", models.JSONField(default=list)),
                ("is_compacted", models.BooleanField(default=False)),
                (
                    "original_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_messages",
                        to="research_ai.agentexecution",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_context_message",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecutionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("execution_sequence", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=32)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("HUMAN", "Human"),
                            ("BACKEND", "Backend"),
                            ("MODEL", "Model"),
                            ("TOOL", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(default=list)),
                ("provider_stop_reason", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "cache_read_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "cache_write_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("latency_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_truncated", models.BooleanField(default=False)),
                (
                    "original_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_messages",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="research_ai.agentexecution",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_execution_message",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="agentconversation",
            index=models.Index(
                fields=["user", "updated_date"], name="ra_agent_conv_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="agentconversation",
            index=models.Index(fields=["workflow"], name="ra_agent_conv_workflow"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["status", "started_at"], name="ra_agent_exec_status_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="noteagentconversation",
            constraint=models.UniqueConstraint(
                fields=("note", "conversation"), name="ra_note_agent_conv_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentexecution",
            constraint=models.UniqueConstraint(
                fields=("conversation", "attempt"), name="ra_agent_exec_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                fields=("conversation",),
                name="ra_agent_exec_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="agentconversationmessage",
            index=models.Index(
                fields=["conversation", "is_active", "sequence"],
                name="ra_agent_chat_visible",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentconversationmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="ra_agent_chat_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcontextmessage",
            constraint=models.UniqueConstraint(
                fields=("execution", "sequence"),
                name="ra_agent_context_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentexecutionmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="ra_agent_trace_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentexecutionmessage",
            constraint=models.UniqueConstraint(
                fields=("execution", "execution_sequence"),
                name="ra_agent_exec_msg_sequence",
            ),
        ),
    ]
