# Generated by Django 5.2.15 on 2026-07-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_ai", "0018_proposal_draft_outreach"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PROPOSAL_DRAFT", "Proposal Draft"),
                            ("NOTEBOOK_CHAT", "Notebook Chat"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("system_prompt", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Null for headless/system runs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_research_ai_agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_conversation",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="proposaldraft",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                db_comment="Agent transcript of the drafting run. SET_NULL so deleting a transcript keeps the draft's own summary fields for diagnostics.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_drafts",
                to="research_ai.agentconversation",
            ),
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        db_comment="The AgentResult stop reason on success, or the error's stop reason (when it carries one) on failure.",
                        max_length=32,
                    ),
                ),
                (
                    "iterations",
                    models.IntegerField(db_comment="Model turns taken.", default=0),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        db_comment="The provider model actually used.",
                        max_length=2048,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        db_comment="Snapshot of the run's knobs: max_iterations, max_tokens, temperature, toolset names. Recorded for reproducibility.",
                        default=dict,
                    ),
                ),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                ("cache_read_tokens", models.BigIntegerField(default=0)),
                ("cache_write_tokens", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        db_comment="finished_at - created_date (created_date is the start).",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Earlier execution attempt retried by this run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retry_runs",
                        to="research_ai.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_run",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="AgentTranscriptEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        db_comment="Per-conversation transcript position, allocated under a conversation row lock."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("backend", "Backend"),
                            ("tool", "Tool"),
                            ("agent", "Agent"),
                        ],
                        db_comment="Provenance of the provider-context entry: human chat input, a backend-composed prompt, tool results, or the agent itself.",
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        db_comment="The serialized provider-neutral block list. The block vocabulary is additive; consumers must tolerate unrecognized block types."
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        db_comment="Internal annotations that are not provider content blocks.",
                        null=True,
                    ),
                ),
                ("input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("output_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_read_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_write_tokens", models.BigIntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("stop_reason", models.CharField(blank=True, max_length=32)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_entries",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_entries",
                        to="research_ai.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_transcript_entry",
                "ordering": ["conversation", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"),
                        name="research_ai_ate_conv_seq_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        db_comment="Independent position in the user-facing conversation."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        db_comment="Structured content rendered by the product chat interface."
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "produced_by_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Execution that produced an assistant message; null for users.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="output_chat_messages",
                        to="research_ai.agentrun",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="research_ai.agentchatmessage",
                    ),
                ),
                (
                    "transcript_entry",
                    models.OneToOneField(
                        blank=True,
                        db_comment="Internal transcript entry from which this message was derived.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_message",
                        to="research_ai.agenttranscriptentry",
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_chat_message",
                "ordering": ["conversation", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "sequence"),
                        name="research_ai_acm_conv_seq_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="agentrun",
            name="trigger_message",
            field=models.ForeignKey(
                blank=True,
                db_comment="User chat message that triggered this run; null for headless runs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_runs",
                to="research_ai.agentchatmessage",
            ),
        ),
    ]
