# Generated by Django 5.2.14 on 2026-07-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "research_ai",
            "0019_agentconversation_proposaldraft_agent_conversation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedemail",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("linkedin", "LinkedIn"),
                    ("x", "X"),
                    ("other", "Other"),
                ],
                db_comment="Outreach channel when marked sent (email / linkedin / x / other). Empty until sent.",
                default="",
                max_length=16,
            ),
        ),
    ]
