# Generated by Django 5.2.14 on 2026-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_ai", "0020_generatedemail_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcontextmessage",
            name="provider_state",
            field=models.JSONField(default=dict),
        ),
    ]
