# Generated by Django 5.2.15 on 2026-07-31 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0021_agentcontextmessage_provider_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedemail",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="generatedemail",
            name="notes",
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="channels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("email", "Email"), ("linkedin", "LinkedIn"), ("x", "X")],
                    max_length=16,
                ),
                blank=True,
                db_comment="Outreach channels when marked sent (email / linkedin / x). Empty until sent.",
                default=list,
                size=None,
            ),
        ),
    ]
