# Generated by Django 5.2.16 on 2026-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0022_remove_generatedemail_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposaldraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
