# Generated by Django 5.2.16 on 2026-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0024_agentconversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposaldraft",
            name="model_ref",
            field=models.CharField(
                blank=True,
                db_comment="User-selected generator model as a provider-prefixed model ref; empty runs the configured default. What actually ran is snapshotted in run_config.",
                default="",
                max_length=255,
            ),
        ),
    ]
