# Generated by Django 5.2.17 on 2026-09-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0027_agentexecution_usage_reservation_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconversation",
            name="is_removed",
            field=models.BooleanField(
                db_comment="Soft delete: the user removed the conversation. Rows are kept for audit and usage accounting; every user-facing lookup excludes them.",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="removed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
