# Generated by Django 5.2.17 on 2026-09-22 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0061_alter_purchase_purchase_type_fundingpool_and_more"),
        ("research_ai", "0028_agentconversation_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconversation",
            name="intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fund", "I want to fund"),
                    ("need_funding", "I need funding"),
                ],
                db_comment="For assistant chats: whether the user is here to fund research (their notes are RFPs) or to get funding (their notes are proposals). Blank leaves the note type to the model.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agentconversation",
            name="selected_grant",
            field=models.ForeignKey(
                blank=True,
                db_comment="The Request for Proposals the user set out to answer, applied to the proposal note this chat creates.",
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="purchase.grant",
            ),
        ),
    ]
