# Generated by Django 5.2.17 on 2026-09-26 09:31

import django.contrib.postgres.fields
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0028_agentconversation_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedemail",
            name="gmail_message_id",
            field=models.CharField(
                blank=True,
                db_comment="Gmail API message ID to correlate send and bounce events.",
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="gmail_thread_id",
            field=models.CharField(
                blank=True,
                db_comment="Gmail thread ID for the sent outreach message.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="open_tracking_token",
            field=models.CharField(
                blank=True,
                db_comment=(
                    "Opaque token for the open-tracking pixel; set at send time."
                ),
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="OutreachMailboxConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Gmail")],
                        db_comment="Mailbox provider; only gmail in v1.",
                        default="gmail",
                        max_length=16,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="Normalized personal Gmail address used as From.",
                        max_length=254,
                    ),
                ),
                (
                    "refresh_token",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted OAuth refresh token."
                    ),
                ),
                (
                    "access_token",
                    encrypted_fields.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted OAuth access token."
                    ),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="When the access token expires.",
                        null=True,
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        db_comment="OAuth scopes granted for this connection.",
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("needs_reauth", "Needs reauth"),
                            ("revoked", "Revoked"),
                        ],
                        db_comment="active / needs_reauth / revoked.",
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        db_comment="Last auth or send error message, if any.",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="When the mailbox was last successfully connected.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="One active outreach mailbox per editor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_mailbox_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_outreach_mailbox_connection",
            },
        ),
    ]
