# Generated by Django 5.2.17 on 2026-09-29 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0028_agentconversation_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        db_comment="Canonical MIME type resolved from the upload; S3 enforces it.",
                        max_length=128,
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                (
                    "etag",
                    models.CharField(
                        blank=True,
                        db_comment="ETag of the completed object; overwriting the object changes it.",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADING",
                        max_length=16,
                    ),
                ),
                (
                    "processing_started_date",
                    models.DateTimeField(
                        blank=True,
                        db_comment="When a worker picked the file up; null while it is queued.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        db_comment="User-safe reason the file could not be processed.",
                        max_length=255,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, db_comment="Text extracted for the agent to read."
                    ),
                ),
                ("text_truncated", models.BooleanField(default=False)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Set when the file is attached to a message in this conversation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="research_ai.agentconversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        db_comment="The user message the file was sent with; null until then.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="research_ai.agentconversationmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="The uploader; null once they removed the file or their account, which leaves the row for the purge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_ai_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "research_ai_agent_file",
            },
        ),
    ]
