# Generated by Django 5.2.17 on 2026-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0029_agentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentfile",
            name="pages_without_text",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="PDF pages left without readable text (scans or figures no OCR read); null for other formats and files processed before this was recorded.",
                null=True,
            ),
        ),
    ]
