# Generated by Django 5.2.17 on 2026-10-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0030_generatedemail_gmail_message_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedemail",
            name="gmail_message_id",
        ),
        migrations.RemoveField(
            model_name="generatedemail",
            name="gmail_thread_id",
        ),
        migrations.DeleteModel(
            name="OutreachMailboxConnection",
        ),
    ]
