# Generated by Django 6.1.1 on 2026-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_ai", "0030_agentfile_pages_without_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusageevent",
            name="tier",
            field=models.CharField(blank=True, db_default="", max_length=32),
        ),
        migrations.AddIndex(
            model_name="llmusageevent",
            index=models.Index(
                fields=["tier", "created_date"], name="ra_usage_tier_date"
            ),
        ),
    ]
