"""
User interaction event types for tracking and ML processing via Personalize.
"""

BOUNTY_SOLUTION_SUBMITTED = "BOUNTY_SOLUTION_SUBMITTED"
BOUNTY_SOLUTION_AWARDED = "BOUNTY_SOLUTION_AWARDED"
BOUNTY_CREATED = "BOUNTY_CREATED"
BOUNTY_CONTRIBUTED = "BOUNTY_CONTRIBUTED"
ITEM_UPVOTED = "ITEM_UPVOTED"
FEED_ITEM_CLICK = "FEED_ITEM_CLICK"
PAGE_VIEW = "PAGE_VIEW"

EVENT_CHOICES = [
    (BOUNTY_SOLUTION_SUBMITTED, BOUNTY_SOLUTION_SUBMITTED),
    (BOUNTY_SOLUTION_AWARDED, BOUNTY_SOLUTION_AWARDED),
    (BOUNTY_CREATED, BOUNTY_CREATED),
    (BOUNTY_CONTRIBUTED, BOUNTY_CONTRIBUTED),
    (ITEM_UPVOTED, ITEM_UPVOTED),
    (FEED_ITEM_CLICK, FEED_ITEM_CLICK),
    (PAGE_VIEW, PAGE_VIEW),
]
