# Generated by Django 2.2 on 2021-08-04 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchhub_document', '0021_auto_20210804_1850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('result_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', models.SlugField(max_length=1024)),
                ('title', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hypotheses', to=settings.AUTH_USER_MODEL)),
                ('unified_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_citations', to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='hypothesis.Hypothesis')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
