# Generated by Django 2.2 on 2021-08-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='result_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
