# Generated by Django 2.2 on 2021-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0003_auto_20210810_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='renderable_text',
            field=models.TextField(null=True),
        ),
    ]
