# Generated by Django 2.2 on 2021-08-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0004_auto_20210812_2006'),
        ('hypothesis', '0004_auto_20210812_2043'),
    ]

    operations = [
    ]
