# Generated by Django 2.2 on 2021-09-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0005_hypothesis_discussion_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='hypothesis',
        ),
        migrations.AddField(
            model_name='citation',
            name='hypothesis',
            field=models.ManyToManyField(db_index=True, related_name='citations', to='hypothesis.Hypothesis'),
        ),
    ]
