# Generated by Django 2.2 on 2021-09-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0006_auto_20210915_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
