# Generated by Django 2.2 on 2021-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0007_auto_20210915_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='type',
            field=models.CharField(choices=[('REJECT', 'REJECT'), ('SUPPORT', 'SUPPORT')], default='SUPPORT', max_length=255),
        ),
    ]
