# Generated by Django 2.2 on 2021-11-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0008_citation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='type',
            field=models.CharField(choices=[('REJECT', 'REJECT'), ('SUPPORT', 'SUPPORT')], db_index=True, default='SUPPORT', max_length=255),
        ),
    ]
