# Generated by Django 2.2 on 2021-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0010_auto_20211104_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='vote_score',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Updated through signal'),
        ),
    ]
