# Generated by Django 2.2 on 2021-11-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0011_citation_vote_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='type',
            new_name='citation_type',
        ),
    ]
