# Generated by Django 2.2 on 2022-01-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20211022_0126'),
        ('hypothesis', '0012_auto_20211118_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypothesis',
            name='authors',
            field=models.ManyToManyField(related_name='authored_hypotheses', to='user.Author'),
        ),
    ]
