# Generated by Django 2.2 on 2022-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0014_hypothesis_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
