# Generated by Django 2.2 on 2022-10-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0064_bounty_effort_level'),
        ('hypothesis', '0014_hypothesis_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypothesis',
            name='from_bounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='reputation.Bounty'),
        ),
    ]
