# Generated by Django 4.1 on 2023-02-15 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hypothesis", "0015_hypothesis_from_bounty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_hypothesis_citations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
