# Generated by Django 4.1 on 2023-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hypothesis", "0016_alter_citation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hypothesis",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
