# Generated by Django 4.2.14 on 2024-08-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0056_remove_thread_citation_remove_thread_hypothesis"),
        ("hypothesis", "0017_citation_score_hypothesis_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hypothesis",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="hypothesis",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="hypothesis",
            name="from_bounty",
        ),
        migrations.RemoveField(
            model_name="hypothesis",
            name="note",
        ),
        migrations.RemoveField(
            model_name="hypothesis",
            name="unified_document",
        ),
        migrations.DeleteModel(
            name="Citation",
        ),
        migrations.DeleteModel(
            name="Hypothesis",
        ),
    ]
