# Generated by Django 2.2.5 on 2019-10-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20191002_0122'),
        ('paper', '0002_paper_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='paper', to='summary.Summary'),
        ),
    ]
