# Generated by Django 2.2.5 on 2019-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20190919_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_papers', to='user.UserProfile'),
        ),
    ]
