# Generated by Django 2.2.5 on 2019-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_paper_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET NULL', related_name='papers', to='summary.Summary'),
        ),
    ]
