# Generated by Django 2.2.6 on 2019-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20191002_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(default='paper.pdf', upload_to='papers/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
