# Generated by Django 2.2.6 on 2019-10-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='uploads/papers/%Y/%m/%d'),
        ),
    ]
