# Generated by Django 2.2.6 on 2019-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_paper_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
