# Generated by Django 2.2.6 on 2019-10-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_paper_paper_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_type',
            new_name='publication_type',
        ),
    ]
