# Generated by Django 2.2.6 on 2019-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_auto_20191009_1324'),
        ('paper', '0009_auto_20191008_1957'),
    ]

    operations = [
    ]
