# Generated by Django 2.2.6 on 2019-10-21 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0010_merge_20191011_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
