# Generated by Django 2.2.6 on 2019-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_paper_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
