# Generated by Django 2.2.6 on 2019-11-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0012_auto_20191030_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_publish_date',
            field=models.DateField(null=True),
        ),
    ]
