# Generated by Django 2.2.7 on 2019-11-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0014_auto_20191109_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_papers', to='user.Author'),
        ),
    ]
