# Generated by Django 2.2.7 on 2019-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0015_auto_20191111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authored_papers', to='user.Author'),
        ),
    ]
