# Generated by Django 2.2.7 on 2019-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0015_auto_20191111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
