# Generated by Django 2.2.7 on 2019-11-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0016_auto_20191119_2054'),
        ('paper', '0016_auto_20191118_2225'),
    ]

    operations = [
    ]
