# Generated by Django 2.2.7 on 2019-11-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0017_merge_20191119_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_papers', to='user.Author'),
        ),
    ]
