# Generated by Django 2.2.7 on 2019-12-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0018_auto_20191120_1647'),
        ('paper', '0018_auto_20191125_1956'),
    ]

    operations = [
    ]
