# Generated by Django 2.2.8 on 2020-01-02 23:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0019_merge_20191202_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='csl_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='bibliographic metadata as a single Citation Styles Language JSON item.'),
        ),
    ]
