# Generated by Django 2.2.9 on 2020-01-21 01:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0020_paper_csl_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_file_license',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='information on PDF availability in the Unpaywall OA Location data format.'),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default=''),
        ),
    ]
