# Generated by Django 2.2.9 on 2020-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0021_auto_20200121_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-paper_publish_date']},
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
