# Generated by Django 2.2.9 on 2020-01-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0021_auto_20200121_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_file_license',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default=''),
        ),
    ]
