# Generated by Django 2.2.9 on 2020-02-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0022_auto_20200211_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='summary.Summary'),
        ),
    ]
