# Generated by Django 2.2.10 on 2020-02-13 20:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0023_auto_20200213_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='csl_item',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='bibliographic metadata as a single Citation Styles Language JSON item.', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='information on PDF availability in the Unpaywall OA Location data format.', null=True),
        ),
    ]
