# Generated by Django 2.2.10 on 2020-02-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0022_auto_20200211_1731'),
        ('paper', '0025_auto_20200213_2032'),
    ]

    operations = [
    ]
