# Generated by Django 2.2.10 on 2020-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0026_merge_20200217_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
