# Generated by Django 2.2.10 on 2020-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0027_auto_20200217_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_title',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, unique=True),
        ),
    ]
