# Generated by Django 2.2.10 on 2020-02-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0023_auto_20200214_0011'),
        ('paper', '0027_auto_20200217_2107'),
    ]

    operations = [
    ]
