# Generated by Django 2.2.10 on 2020-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0028_merge_20200222_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tagline',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
