# Generated by Django 2.2.10 on 2020-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0023_auto_20200214_0011'),
        ('paper', '0029_auto_20200218_2334'),
    ]

    operations = [
    ]
