# Generated by Django 2.2.10 on 2020-02-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0029_auto_20200224_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='retrieved_from_external_source',
            field=models.BooleanField(default=False),
        ),
    ]
