# Generated by Django 2.2.11 on 2020-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0030_paper_retrieved_from_external_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to='uploads/papers/%Y/%m/%d'),
        ),
    ]
