# Generated by Django 2.2.10 on 2020-02-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0030_merge_20200219_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_title',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
