# Generated by Django 2.2.11 on 2020-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0031_auto_20200319_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
