# Generated by Django 2.2.11 on 2020-03-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0032_auto_20200319_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
