# Generated by Django 2.2.11 on 2020-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0033_auto_20200319_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='uploads/papers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url_for_landing_page',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
