# Generated by Django 2.2.11 on 2020-03-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0033_figure_figure_type'),
        ('paper', '0034_auto_20200319_0439'),
    ]

    operations = [
    ]
