# Generated by Django 2.2.11 on 2020-03-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0034_auto_20200319_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Hides the paper from the public.'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Hides the paper because it is not allowed.'),
        ),
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='_paper_references_+', to='paper.Paper'),
        ),
    ]
