# Generated by Django 2.2.11 on 2020-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0035_auto_20200319_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='paper.Paper'),
        ),
    ]
