# Generated by Django 2.2.11 on 2020-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0036_auto_20200319_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='external_source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
