# Generated by Django 2.2.11 on 2020-03-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0037_paper_external_source'),
        ('paper', '0035_merge_20200323_1718'),
    ]

    operations = [
    ]
