# Generated by Django 2.2.11 on 2020-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0040_auto_20200406_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
