# Generated by Django 2.2.11 on 2020-04-20 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0041_paper_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='pdf_file_license',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pdf_location',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pdf_url_for_landing_page',
        ),
        migrations.AddField(
            model_name='paper',
            name='oa_pdf_location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, help_text='PDF availability in Unpaywall OA Location format.', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_license',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf_license_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='raw_authors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='MetadataRetrievalAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CROSSREF', 'CROSSREF'), ('MANUBOT', 'MANUBOT'), ('PARSE_PDF', 'PARSE_PDF')], max_length=125)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_retrieval_attempts', to='paper.Paper')),
            ],
        ),
    ]
