# Generated by Django 2.2.11 on 2020-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0042_auto_20200420_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataretrievalattempt',
            name='method',
            field=models.CharField(choices=[('CROSSREF_DOI', 'CROSSREF_DOI'), ('CROSSREF_QUERY', 'CROSSREF_QUERY'), ('MANUBOT_DOI', 'MANUBOT_DOI'), ('MANUBOT_PDF_URL', 'MANUBOT_PDF_URL'), ('MANUBOT_URL', 'MANUBOT_URL'), ('PARSE_PDF', 'PARSE_PDF')], max_length=125),
        ),
    ]
