# Generated by Django 2.2.12 on 2020-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0043_auto_20200420_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='discussion_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
