# Generated by Django 2.2.12 on 2020-04-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0044_auto_20200428_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
