# Generated by Django 2.2.12 on 2020-04-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0045_auto_20200428_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
