# Generated by Django 2.2.12 on 2020-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0047_auto_20200429_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='vote_avg_epoch',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
