# Generated by Django 2.2.12 on 2020-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0048_auto_20200429_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
