# Generated by Django 2.2.12 on 2020-04-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0049_auto_20200429_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='vote_avg_epoch',
            new_name='hot_score',
        ),
    ]
