# Generated by Django 2.2.12 on 2020-05-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0051_additionalfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='external_source_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
