# Generated by Django 2.2.12 on 2020-05-11 15:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0052_paper_external_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='alternate_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
