# Generated by Django 2.2.12 on 2020-05-11 15:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0053_paper_alternate_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='alternate_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
