# Generated by Django 2.2.12 on 2020-05-11 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0054_auto_20200511_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='alternate_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
