# Generated by Django 2.2.12 on 2020-05-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0057_figure_created_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to=settings.AUTH_USER_MODEL),
        ),
    ]
