# Generated by Django 2.2.13 on 2020-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0058_figure_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file_created_location',
            field=models.CharField(blank=True, choices=[('PROGRESS', 'Progress')], default=None, max_length=255, null=True),
        ),
    ]
