# Generated by Django 2.2.15 on 2020-08-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0061_auto_20200824_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
