# Generated by Django 2.2.16 on 2020-10-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0062_paper_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('PRE_REGISTRATION', 'PRE_REGISTRATION')], default='REGULAR', max_length=32),
        ),
    ]
