# Generated by Django 2.2 on 2020-10-12 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0063_paper_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='paper.Paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
