# Generated by Django 2.2 on 2020-11-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0064_featuredpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
