# Generated by Django 2.2 on 2020-11-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0066_auto_20201104_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
