# Generated by Django 2.2 on 2021-01-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0072_auto_20201120_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='twitter_score',
            field=models.IntegerField(default=1),
        ),
    ]
