# Generated by Django 2.2 on 2020-12-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0072_auto_20201120_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='bullet_low_quality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary_low_quality',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
