# Generated by Django 2.2 on 2021-01-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0073_paper_twitter_score'),
        ('paper', '0073_auto_20201214_2314'),
    ]

    operations = [
    ]
