# Generated by Django 2.2 on 2021-02-09 16:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0073_paper_twitter_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='external_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
