# Generated by Django 2.2 on 2020-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0073_auto_20201214_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='bullet_low_quality',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='summary_low_quality',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
