# Generated by Django 2.2 on 2021-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0074_paper_external_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='twitter_mentions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
