# Generated by Django 2.2 on 2021-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0075_auto_20210224_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_file_extract',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='uploads/papers/%Y/%m/%d/pdf_extract'),
        ),
    ]
