# Generated by Django 2.2 on 2021-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0076_paper_pdf_file_extract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='edited_file_extract',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='uploads/papers/%Y/%m/%d/edited_extract'),
        ),
    ]
