# Generated by Django 2.2 on 2021-03-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0075_paper_twitter_score_updated_date'),
        ('paper', '0077_paper_edited_file_extract'),
    ]

    operations = [
    ]
