# Generated by Django 2.2 on 2021-05-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0078_merge_20210311_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='completeness',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PARTIAL', 'PARTIAL'), ('INCOMPLETE', 'INCOMPLETE')], default='INCOMPLETE', max_length=16),
        ),
    ]
