# Generated by Django 2.2 on 2021-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0078_merge_20210311_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='hot_score',
            field=models.IntegerField(db_index=True, default=0, help_text='Legacy. Refer to UnifiedDocument'),
        ),
    ]
