# Generated by Django 2.2 on 2021-06-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0079_paper_completeness'),
        ('paper', '0079_auto_20210603_2345'),
    ]

    operations = [
    ]
