# Generated by Django 2.2 on 2021-06-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0080_merge_20210611_0247'),
        ('paper', '0080_merge_20210611_0528'),
    ]

    operations = [
    ]
