# Generated by Django 2.2 on 2021-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0081_auto_20210701_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='twitter_score_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
