# Generated by Django 2.2 on 2022-02-09 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0082_auto_20210717_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to='uploads/papers/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
