# Generated by Django 2.2 on 2022-02-09 05:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0083_auto_20220209_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='alternate_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paper',
            name='external_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
