# Generated by Django 2.2 on 2022-03-01 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paper", "0084_auto_20220209_0543"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "paper_status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "INITIATED"),
                            ("FAILED", "FAILED"),
                            ("PROCESSING", "PROCESSING"),
                            ("PROCESSING_CROSSREF", "PROCESSING_CROSSREF"),
                            ("PROCESSING_MANUBOT", "PROCESSING_MANUBOT"),
                            (
                                "PROCESSING_SEMANTIC_SCHOLAR",
                                "PROCESSING_SEMANTIC_SCHOLAR",
                            ),
                        ],
                        default="INITIATED",
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(max_length=1024, unique=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="\n            RH User account that submitted this paper.\n            NOTE: user didnt necessarily had to be the author.\n        ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
