# Generated by Django 2.2 on 2022-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_papers'),
        ('paper', '0084_auto_20220209_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='papers', to='tag.Tag'),
        ),
    ]
