# Generated by Django 2.2 on 2022-03-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0085_papersubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmission",
            name="paper",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission",
                to="paper.Paper",
            ),
        ),
    ]
