# Generated by Django 2.2 on 2022-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0086_papersubmission_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='paper_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INITIATED', 'INITIATED'), ('FAILED', 'FAILED'), ('PROCESSING', 'PROCESSING'), ('PROCESSING_CROSSREF', 'PROCESSING_CROSSREF'), ('PROCESSING_MANUBOT', 'PROCESSING_MANUBOT'), ('PROCESSING_SEMANTIC_SCHOLAR', 'PROCESSING_SEMANTIC_SCHOLAR')], default='INITIATED', max_length=32),
        ),
    ]
