# Generated by Django 2.2 on 2022-03-08 22:40

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0087_auto_20220304_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='paper_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INITIATED', 'INITIATED'), ('FAILED', 'FAILED'), ('FAILED', 'FAILED_DUPLICATE'), ('FAILED_TIMEOUT', 'FAILED_TIMEOUT'), ('PROCESSING', 'PROCESSING'), ('PROCESSING_CROSSREF', 'PROCESSING_CROSSREF'), ('PROCESSING_MANUBOT', 'PROCESSING_MANUBOT')], default='INITIATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='uploaded_by',
            field=models.ForeignKey(default=1, help_text='\n            RH User account that submitted this paper.\n            NOTE: user didnt necessarily had to be the author.\n        ', on_delete=django.db.models.deletion.CASCADE, related_name='paper_submissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.HashIndex(fields=['url'], name='paper_paper_url_hix'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.HashIndex(fields=['pdf_url'], name='paper_paper_pdf_url_hix'),
        ),
    ]
