# Generated by Django 2.2 on 2022-03-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0088_auto_20220308_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
    ]
