# Generated by Django 2.2 on 2022-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0090_auto_20220329_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='status_read',
            field=models.BooleanField(default=False),
        ),
    ]
