# Generated by Django 2.2 on 2022-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0091_auto_20220330_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='paper_status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('INITIATED', 'INITIATED'), ('FAILED', 'FAILED'), ('FAILED', 'FAILED_DUPLICATE'), ('FAILED_TIMEOUT', 'FAILED_TIMEOUT'), ('FAILED_DOI', 'FAILED_DOI'), ('PROCESSING', 'PROCESSING'), ('PROCESSING_CROSSREF', 'PROCESSING_CROSSREF'), ('PROCESSING_MANUBOT', 'PROCESSING_MANUBOT'), ('PROCESSING_DOI', 'PROCESSING_DOI')], default='INITIATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
