# Generated by Django 2.2 on 2022-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0093_asyncpaperupdator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='title',
            field=models.CharField(blank=True, help_text='User generated title', max_length=1024, null=True),
        ),
    ]
