# Generated by Django 2.2 on 2022-04-29 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0094_auto_20220429_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='paper_submission',
            field=models.OneToOneField(help_text='Self-explanatory', on_delete=django.db.models.deletion.CASCADE, related_name='async_updator', to='paper.PaperSubmission'),
        ),
    ]
