# Generated by Django 2.2 on 2022-05-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0030_researchhubpost_doi'),
        ('paper', '0095_auto_20220429_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='unified_document_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_new', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
