# Generated by Django 2.2 on 2022-05-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0096_paper_unified_document_new'),
    ]

    operations = [
        migrations.RunSQL(""" UPDATE "paper_paper" SET "unified_document_new_id" = (SELECT U0."id" FROM "researchhub_document_researchhubunifieddocument" U0 WHERE U0."paper_id" = ("paper_paper"."id") LIMIT 1) """)
        # migrations.RunSQL(""" UPDATE "paper_paper" SET "unified_document_new_id" = "paper_paper"."unified_document_id" """),
    ]
