# Generated by Django 2.2 on 2022-05-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchhub_document', '0031_remove_researchhubunifieddocument_paper'),
        ('paper', '0097_paper_uni_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='unified_document_new',
            new_name='unified_document'
        ),
    ]
