# Generated by Django 2.2 on 2022-05-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0098_auto_20220506_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='unified_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
