# Generated by Django 2.2 on 2022-05-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0098_auto_20220506_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_legacy', related_query_name='flag_legacy', to='paper.Paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='unified_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_legacy', related_query_name='vote_legacy', to='paper.Paper'),
        ),
    ]
