# Generated by Django 2.2 on 2022-05-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0099_auto_20220506_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagPaperLegacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_flags', related_query_name='paper_flag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotePaperLegacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('vote_type', models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote')])),
                ('is_removed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_votes', related_query_name='paper_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asyncpaperupdator',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='votepaperlegacy',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_legacy', related_query_name='vote', to='paper.Paper'),
        ),
        migrations.AddField(
            model_name='flagpaperlegacy',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_legacy', related_query_name='flag', to='paper.Paper'),
        ),
        migrations.AddConstraint(
            model_name='votepaperlegacy',
            constraint=models.UniqueConstraint(fields=('paper', 'created_by'), name='unique_paper_vote'),
        ),
        migrations.AddConstraint(
            model_name='flagpaperlegacy',
            constraint=models.UniqueConstraint(fields=('paper', 'created_by'), name='unique_paper_flag'),
        ),
    ]
