# Generated by Django 2.2 on 2022-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0099_auto_20220506_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='uploaded_date',
            new_name='created_date',
        ),
    ]
