# Generated by Django 2.2 on 2022-05-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0099_auto_20220510_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='score',
            new_name='paper_score',
        ),
    ]
