# Generated by Django 2.2 on 2022-06-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0102_auto_20220601_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPaper',
        ),
    ]
