# Generated by Django 2.2 on 2022-06-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0103_delete_featuredpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='hot_score',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_score',
        ),
    ]
