# Generated by Django 2.2 on 2022-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('paper', '0106_paper_oa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='tag.Concept'),
        ),
    ]
