# Generated by Django 4.1 on 2022-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0106_paper_oa_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="alternate_ids",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="paper",
            name="csl_item",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="bibliographic metadata as a single Citation Styles Language JSON item.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="external_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="oa_pdf_location",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="PDF availability in Unpaywall OA Location format.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="raw_authors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
