# Generated by Django 4.1 on 2022-11-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0107_alter_paper_alternate_ids_alter_paper_csl_item_and_more"),
        ("paper", "0107_auto_20221116_2153"),
    ]

    operations = []
