# Generated by Django 4.1 on 2022-12-19 23:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0108_merge_20221128_2322"),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              ALTER TABLE paper_paper ADD COLUMN url_svf tsvector GENERATED ALWAYS AS (
                setweight(to_tsvector('english', coalesce(url, '')), 'A')
              ) STORED;
            ''',

            reverse_sql='''
              ALTER TABLE paper_paper DROP COLUMN url_svf;
            '''
        ),
        # migrations.AddField(
        #     model_name="paper",
        #     name="url_svf",
        #     field=django.contrib.postgres.search.SearchVectorField(null=True),
        # ),
        migrations.AlterField(
            model_name="papersubmission",
            name="paper_status",
            field=models.CharField(
                choices=[
                    ("COMPLETE", "COMPLETE"),
                    ("INITIATED", "INITIATED"),
                    ("FAILED", "FAILED"),
                    ("FAILED", "FAILED_DUPLICATE"),
                    ("FAILED_TIMEOUT", "FAILED_TIMEOUT"),
                    ("FAILED_DOI", "FAILED_DOI"),
                    ("PROCESSING", "PROCESSING"),
                    ("PROCESSING_CROSSREF", "PROCESSING_CROSSREF"),
                    ("PROCESSING_MANUBOT", "PROCESSING_MANUBOT"),
                    ("PROCESSING_OPENALEX", "PROCESSING_OPENALEX"),
                    ("PROCESSING_SEMANTIC_SCHOLAR", "PROCESSING_SEMANTIC_SCHOLAR"),
                    ("PROCESSING_UNPAYWALL", "PROCESSING_UNPAYWALL"),
                    ("PROCESSING_DOI", "PROCESSING_DOI"),
                ],
                default="INITIATED",
                max_length=32,
            ),
        ),
        # migrations.AddIndex(
        #     model_name="paper",
        #     index=django.contrib.postgres.indexes.GinIndex(
        #         fields=["url_svf"], name="paper_paper_url_svf_0e3081_gin"
        #     ),
        # ),
    ]
