# Generated by Django 4.1 on 2022-12-20 01:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0109_paper_url_svf_alter_papersubmission_paper_status_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="paper",
        #     name="url_svf",
        #     field=django.contrib.postgres.search.SearchVectorField(null=True),
        # ),
        migrations.AddIndex(
            model_name="paper",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["url_svf"], name="paper_paper_url_svf_0e3081_gin"
            ),
        ),
    ]
