# Generated by Django 4.1 on 2023-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0111_alter_paper_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
