# Generated by Django 4.1 on 2023-06-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ("citation", "0008_citationentry_paper"),
        ("paper", "0112_paper_score"),
    ]

    operations = [
        # No-op: The citation app was been removed.
        # The relation between papersubmission and citation
        # was dropped in migration 0156.
        #
        # migrations.AddField(
        #     model_name="papersubmission",
        #     name="citation",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="paper_submissions",
        #         to="citation.citationentry",
        #     ),
        # ),
    ]
