# Generated by Django 4.1 on 2023-06-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ("citation", "0008_citationentry_paper"),  # Citation app deleted
        ("paper", "0112_paper_score"),
    ]

    operations = [
        # The `citation` field was removed and the citation app was deleted.
        # This migration is kept for history but is a no-op migration.
        # The field removal is handled in migration 0156
        # migrations.AddField(
        #     model_name="papersubmission",
        #     name="citation",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="paper_submissions",
        #         to="citation.citationentry",
        #     ),
        # ),
    ]
