# Generated by Django 4.1 on 2023-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0112_paper_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="html_file_key",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="html_generation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
