# Generated by Django 4.1 on 2023-09-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0113_papersubmission_citation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="twitter_score",
            field=models.IntegerField(default=0),
        ),
    ]
