# Generated by Django 4.1 on 2023-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0114_alter_paper_twitter_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="open_alex_raw_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
