# Generated by Django 4.1 on 2023-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0115_paper_open_alex_raw_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="automated_bounty_created",
            field=models.BooleanField(default=False),
        ),
    ]
