# Generated by Django 4.1 on 2023-11-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paper", "0116_paper_automated_bounty_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papersubmission",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="\n            RH User account that submitted this paper.\n            NOTE: user didnt necessarily had to be the author.\n        ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
