# Generated by Django 4.1 on 2024-01-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0117_alter_papersubmission_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="is_pdf_removed_by_moderator",
            field=models.BooleanField(
                default=False, help_text="Hides the PDF because it infringes Copyright."
            ),
        ),
    ]
