# Generated by Django 4.1 on 2024-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0118_paper_is_pdf_removed_by_moderator"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperFetchLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("OPENALEX", "OPENALEX")], max_length=255
                    ),
                ),
                (
                    "fetch_type",
                    models.CharField(
                        choices=[
                            ("FETCH_NEW", "FETCH_NEW"),
                            ("FETCH_UPDATE", "FETCH_UPDATE"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "SUCCESS"), ("FAILED", "FAILED")],
                        max_length=255,
                    ),
                ),
                ("num_papers_success", models.IntegerField(default=0)),
                ("num_papers_failed", models.IntegerField(default=0)),
            ],
        ),
    ]
