# Generated by Django 4.1 on 2024-02-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0119_paperfetchlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paperfetchlog",
            old_name="num_papers_failed",
            new_name="total_papers_processed",
        ),
        migrations.RemoveField(
            model_name="paperfetchlog",
            name="num_papers_success",
        ),
    ]
