# Generated by Django 4.1 on 2024-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "paper",
            "0120_rename_num_papers_failed_paperfetchlog_total_papers_processed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paperfetchlog",
            name="fetch_since_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paperfetchlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                ],
                max_length=255,
            ),
        ),
    ]
