# Generated by Django 4.1.13 on 2024-04-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0121_paperfetchlog_fetch_since_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="twitter_mentions",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="twitter_score",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="twitter_score_updated_date",
        ),
    ]
