# Generated by Django 4.1 on 2024-05-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0122_remove_paper_twitter_mentions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="is_retracted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="mag_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="openalex_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="pubmed_central_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="pubmed_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="work_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
