# Generated by Django 4.1 on 2024-05-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0104_author_country_code_author_i10_index"),
        ("institution", "0004_institution_openalex_created_date_and_more"),
        ("paper", "0123_paper_is_retracted_paper_language_paper_mag_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAuthorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author_position",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("middle", "Middle"),
                            ("last", "Last"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_corresponding", models.BooleanField(default=False)),
                (
                    "raw_author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="user.author",
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="authors",
                        to="institution.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
