# Generated by Django 4.1 on 2024-05-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0105_remove_author_academic_verification_and_more"),
        ("institution", "0004_institution_openalex_created_date_and_more"),
        ("paper", "0125_workauthorship_work_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author_position",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("middle", "Middle"),
                            ("last", "Last"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_corresponding", models.BooleanField(default=False)),
                (
                    "raw_author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="user.author",
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        related_name="authors", to="institution.institution"
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="paper.paper",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="WorkAuthorship",
        ),
    ]
