# Generated by Django 4.2.14 on 2024-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0127_historicalpaper"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="authorship",
            constraint=models.UniqueConstraint(
                fields=("paper", "author"), name="unique_paper_author"
            ),
        ),
    ]
