# Generated by Django 4.2.14 on 2024-08-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0128_authorship_unique_paper_author"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="historicalpaper",
        #     name="summary",
        # ),
        # migrations.RemoveField(
        #     model_name="paper",
        #     name="summary",
        # ),
    ]
