# Generated by Django 4.2.14 on 2024-08-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0129_remove_historicalpaper_summary_remove_paper_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("total_citation_count", models.IntegerField()),
                ("citation_change", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[("OpenAlex", "OpenAlex"), ("Legacy", "Legacy")],
                        max_length=255,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_citations",
                        to="paper.paper",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
