# Generated by Django 4.2.15 on 2024-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0130_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorship",
            name="source",
            field=models.TextField(
                choices=[("AUTHOR_MIGRATION", "Author Migration")], null=True
            ),
        ),
    ]
