# Generated by Django 4.2.15 on 2024-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0121_alter_userverification_status"),
        ("paper", "0131_authorship_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="authorship_authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Authors that participated in the research paper",
                related_name="papers",
                through="paper.Authorship",
                to="user.author",
            ),
        ),
    ]
