# Generated by Django 4.2.15 on 2024-09-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0133_paperfetchlog_next_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperfetchlog",
            name="journal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BIORXIV", "BIORXIV"),
                    ("MEDRXIV", "MEDRXIV"),
                    ("ARXIV", "ARXIV"),
                    ("CHEMRXIV", "CHEMRXIV"),
                    ("RESEARCH_SQUARE", "RESEARCH_SQUARE"),
                    ("OSF", "OSF"),
                    ("PEERJ", "PEERJ"),
                    ("AUTHOREA", "AUTHOREA"),
                    ("SSRN", "SSRN"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paperfetchlog",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
