# Generated by Django 4.2.15 on 2024-09-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0134_paperfetchlog_journal_paperfetchlog_updated_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetadataRetrievalAttempt",
        ),
    ]
