# Generated by Django 4.2.15 on 2024-09-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0135_delete_metadataretrievalattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
