# Generated by Django 4.2.15 on 2024-09-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0136_delete_vote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flag",
        ),
    ]
