# Generated by Django 4.2.15 on 2024-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0137_delete_flag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdditionalFile",
        ),
    ]
