# Generated by Django 4.2.15 on 2024-10-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0138_delete_additionalfile"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                models.Func("doi", function="UPPER"), name="paper_paper_doi_upper_idx"
            ),
        ),
    ]
