# Generated by Django 4.2.15 on 2024-10-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0139_paper_paper_paper_doi_upper_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=255)),
                ("base_doi", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="paper.paper",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
