# Generated by Django 4.2.15 on 2024-10-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0139_paper_paper_paper_doi_upper_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="authors",
        ),
    ]
