# Generated by Django 4.2.15 on 2024-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0139_paper_paper_paper_doi_upper_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                fields=["paper", "figure_type"], name="figure_paper_type_idx"
            ),
        ),
    ]
