# Generated by Django 4.2.15 on 2024-10-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0140_figure_figure_paper_type_idx"),
        ("paper", "0141_paperversion"),
    ]

    operations = []
