# Generated by Django 4.2.16 on 2024-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0143_alter_paperversion_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorship",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
