# Generated by Django 4.2.16 on 2024-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0144_authorship_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorship",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
