# Generated by Django 4.2.16 on 2024-11-14 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paper", "0145_authorship_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAPC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apcs",
                        to="paper.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAPCDeclaration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration_type",
                    models.CharField(
                        choices=[
                            (
                                "ACCEPT_TERMS_AND_CONDITIONS",
                                "Accept Terms and Conditions",
                            ),
                            ("AUTHORIZE_CC_BY_4_0", "Authorize CC BY 4.0"),
                            ("CONFIRM_AUTHORS_RIGHTS", "Confirm Authors Rights"),
                            (
                                "CONFIRM_ORIGINALITY_AND_COMPLIANCE",
                                "Confirm Originality and Compliance",
                            ),
                            (
                                "ACKNOWLEDGE_OPEN_PEER_REVIEWS",
                                "Acknowledge Open Peer Reviews",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the declaration has been accepted",
                    ),
                ),
                (
                    "accepted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the declaration was accepted",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        help_text="User who accepted this declaration",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_apc_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper_apc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="paper.paperapc",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["paper_apc", "declaration_type", "accepted_by"],
                        name="paper_paper_paper_a_d36926_idx",
                    )
                ],
                "unique_together": {("paper_apc", "declaration_type", "accepted_by")},
            },
        ),
    ]
