# Generated by Django 4.2.16 on 2024-11-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0145_authorship_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperversion",
            name="original_paper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_paper",
                to="paper.paper",
            ),
        ),
    ]
