# Generated by Django 4.2.16 on 2024-11-14 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paper", "0146_paperversion_original_paper"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicalpaper",
            name="paper_series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="paper.paperseries",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="paper_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="papers",
                to="paper.paperseries",
            ),
        ),
        migrations.CreateModel(
            name="PaperSeriesDeclaration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration_type",
                    models.CharField(
                        choices=[
                            (
                                "ACCEPT_TERMS_AND_CONDITIONS",
                                "Accept Terms and Conditions",
                            ),
                            ("AUTHORIZE_CC_BY_4_0", "Authorize CC BY 4.0"),
                            ("CONFIRM_AUTHORS_RIGHTS", "Confirm Authors Rights"),
                            (
                                "CONFIRM_ORIGINALITY_AND_COMPLIANCE",
                                "Confirm Originality and Compliance",
                            ),
                            (
                                "ACKNOWLEDGE_OPEN_PEER_REVIEWS",
                                "Acknowledge Open Peer Reviews",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the declaration has been accepted",
                    ),
                ),
                (
                    "accepted_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the declaration was accepted",
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        help_text="User who accepted this declaration",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_apc_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="paper.paperseries",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["paper_series", "declaration_type", "accepted_by"],
                        name="paper_paper_paper_s_d60310_idx",
                    )
                ],
                "unique_together": {
                    ("paper_series", "declaration_type", "accepted_by")
                },
            },
        ),
    ]
