# Generated by Django 4.2.16 on 2024-12-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0147_paperseries_historicalpaper_paper_series_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="authors",
        ),
    ]
