# Generated by Django 4.2.16 on 2024-12-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0148_remove_paper_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="authorship_authors",
            new_name="authors",
        ),
    ]
