# Generated by Django 4.2.16 on 2024-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0149_rename_authorship_authors_paper_authors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authorship",
            name="unique_paper_author",
        ),
        migrations.AddConstraint(
            model_name="authorship",
            constraint=models.UniqueConstraint(
                fields=("author", "paper"), name="paper_authorship_paper_author_unique"
            ),
        ),
    ]
