# Generated by Django 4.2.17 on 2024-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0150_remove_authorship_unique_paper_author_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authorship",
            name="paper_authorship_paper_author_unique",
        ),
        migrations.AddConstraint(
            model_name="authorship",
            constraint=models.UniqueConstraint(
                fields=("paper", "author"), name="unique_paper_author"
            ),
        ),
    ]
