# Generated by Django 5.1.5 on 2025-02-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "paper",
            "0151_remove_authorship_paper_authorship_paper_author_unique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="hubs",
        ),
    ]
