# Generated by Django 5.1.5 on 2025-05-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0152_remove_paper_hubs"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperversion",
            name="journal",
            field=models.CharField(
                blank=True,
                choices=[("RESEARCHHUB", "ResearchHub Journal")],
                help_text="The journal this paper version belongs to",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paperversion",
            name="publication_status",
            field=models.CharField(
                choices=[("PREPRINT", "Preprint"), ("PUBLISHED", "Published")],
                default="PREPRINT",
                help_text="Indicates whether this is a preprint or a published article",
                max_length=20,
            ),
        ),
    ]
