# Generated by Django 5.1.5 on 2025-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0152_remove_paper_hubs"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperversion",
            name="journal",
            field=models.TextField(
                blank=True,
                choices=[("RESEARCHHUB", "ResearchHub Journal")],
                help_text="The journal this paper version belongs to",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paperversion",
            name="publication_status",
            field=models.TextField(
                choices=[("PREPRINT", "Preprint"), ("PUBLISHED", "Published")],
                default="PREPRINT",
                help_text="Indicates whether this is a preprint or a published article",
            ),
        ),
    ]
