# Generated by Django 5.1.5 on 2025-05-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0153_paperversion_journal_paperversion_publication_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPaper",
        ),
    ]
