# Generated by Django 5.2.2 on 2025-08-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0154_delete_historicalpaper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="moderators",
        ),
    ]
