# Generated by Django 5.2.2 on 2025-08-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0155_remove_paper_moderators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papersubmission",
            name="citation",
        ),
    ]
