# Generated by Django 5.2.2 on 2025-08-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0156_remove_papersubmission_citation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paper",
            name="paper_paper_url_svf_0e3081_gin",
        ),
        migrations.RemoveIndex(
            model_name="paper",
            name="paper_paper_pdf_url_d431cf_gin",
        ),
        migrations.RemoveIndex(
            model_name="paper",
            name="paper_paper_doi_svf_618fa4_gin",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="doi_svf",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="pdf_url_svf",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="url_svf",
        ),
    ]
