# Generated by Django 5.2.2 on 2025-08-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0157_remove_paper_paper_paper_url_svf_0e3081_gin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="bullet_low_quality",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="downloads",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="summary_low_quality",
        ),
    ]
