# Generated by Django 5.2.2 on 2025-08-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0158_remove_paper_bullet_low_quality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="alternate_ids",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="is_retracted",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="mag_id",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="publication_type",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="pubmed_central_id",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="pubmed_id",
        ),
    ]
