# Generated by Django 5.2.2 on 2025-08-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0159_remove_paper_alternate_ids_remove_paper_is_retracted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="is_removed_by_user",
        ),
    ]
