# Generated by Django 5.2.2 on 2025-08-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0160_remove_paper_is_removed_by_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="views",
        ),
    ]
