# Generated by Django 5.2.2 on 2025-08-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0161_remove_paper_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="edited_file_extract",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="pdf_file_extract",
        ),
    ]
