# Generated by Django 5.2.2 on 2025-08-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0162_remove_paper_edited_file_extract_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="oa_pdf_location",
        ),
    ]
