# Generated by Django 5.2.2 on 2025-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0163_remove_paper_oa_pdf_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperfetchlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("ARXIV", "ARXIV"),
                    ("BIOARXIV", "BIOARXIV"),
                    ("CHEMRXIV", "CHEMRXIV"),
                    ("OPENALEX", "OPENALEX"),
                ],
                max_length=255,
            ),
        ),
    ]
