# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0164_alter_paperfetchlog_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="tagline",
        ),
    ]
