# Generated by Django 5.2.6 on 2025-09-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0165_remove_paper_tagline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="completeness",
        ),
    ]
