# Generated by Django 5.2.7 on 2025-10-08 23:07
# Converted to no-op: Migration already applied in staging
# Production will use zero-downtime migrations 0167a-0167d instead

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0166_remove_paper_completeness"),
    ]

    operations = [
        # No-op migration - staging already has this applied
        # Production uses the split migrations below
    ]
