# Generated by Django 5.2.7 on 2025-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0166_remove_paper_completeness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="paper_publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
