# Generated by Django 5.2.7 on 2025-10-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0167_alter_paper_paper_publish_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="abstract_src",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="abstract_src_type",
        ),
    ]
