# Generated by Django 5.2.7 on 2025-10-10 00:04
# Step 1 of zero-downtime migration: Add new DateTimeField column

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0167_alter_paper_paper_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="paper_publish_date_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
