# Generated by Django 5.2.7 on 2025-10-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0167_alter_paper_paper_publish_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="figure",
            name="created_location",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="file_created_location",
        ),
    ]
