# Generated by Django 5.2.7 on 2025-11-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0168_remove_figure_created_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="abstract_src",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="abstract_src_type",
        ),
    ]
