# Generated by Django 5.2.8 on 2025-11-30 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0169_remove_paper_abstract_src_and_more"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("user", "0136_alter_author_headline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["paper_publish_date"], name="paper_paper_publish_date_idx"
            ),
        ),
    ]
