# Generated by Django 5.2.8 on 2025-12-05 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0169_remove_paper_abstract_src_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this figure is the primary image for the paper",
            ),
        ),
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                fields=["paper", "is_primary"], name="figure_paper_primary_idx"
            ),
        ),
    ]
