# Generated by Django 5.2.9 on 2025-12-13 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0170_add_paper_publish_date_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this figure is the primary image for the paper",
            ),
        ),
        migrations.AddIndex(
            model_name="figure",
            index=models.Index(
                condition=models.Q(("is_primary", True)),
                fields=["paper"],
                name="figure_paper_primary_idx",
            ),
        ),
    ]
