# Generated by Django 5.2.9 on 2025-12-16 20:49

import paper.storage.figure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0171_figure_is_primary_figure_figure_paper_primary_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="figure",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="WebP thumbnail for fast loading in feeds",
                null=True,
                storage=paper.storage.figure_storage.FigureStorage(),
                upload_to="uploads/figures/thumbnails/%Y/%m/%d",
            ),
        ),
        migrations.AlterField(
            model_name="figure",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=paper.storage.figure_storage.FigureStorage(),
                upload_to="uploads/figures/%Y/%m/%d",
            ),
        ),
    ]
