# Generated by Django 5.2.9 on 2025-12-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0172_figure_thumbnail_alter_figure_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="title_abstract_embedding",
            field=models.JSONField(
                blank=True,
                help_text="1024-dimensional embedding vector for semantic search",
                null=True,
            ),
        ),
    ]
