# Generated by Django 5.2.9 on 2025-12-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0172_figure_thumbnail_alter_figure_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="XPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "post_id",
                    models.CharField(
                        db_index=True,
                        help_text="The unique ID of the post on X",
                        max_length=64,
                    ),
                ),
                (
                    "author_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The X user ID of the post author",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", help_text="The text content of the post"
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the post was created on X",
                        null=True,
                    ),
                ),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("repost_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("quote_count", models.PositiveIntegerField(default=0)),
                ("impression_count", models.PositiveIntegerField(default=0)),
                (
                    "paper",
                    models.ForeignKey(
                        help_text="The paper this X post references",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="x_posts",
                        to="paper.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
                "indexes": [
                    models.Index(
                        fields=["paper", "-posted_date"],
                        name="paper_xpost_paper_i_1f05b2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("paper", "post_id"), name="unique_paper_x_post"
                    )
                ],
            },
        ),
    ]
