# Generated by Django 5.2.14 on 2026-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0172_figure_thumbnail_alter_figure_file"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paperversion",
            index=models.Index(
                condition=models.Q(
                    ("base_doi__isnull", False), ("journal", "RESEARCHHUB")
                ),
                fields=["base_doi", "-created_date"],
                name="paper_ver_rh_doi_created_idx",
            ),
        ),
    ]
