# Generated by Django 5.2 on 2026-05-28 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0172_figure_thumbnail_alter_figure_file"),
        ("user", "0145_riskscore_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="APPROVED",
                help_text="Moderation status used to gate public visibility.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Moderator who approved or declined this work",
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="reviewed_papers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="reviewed_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the work was approved or declined",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(fields=["status"], name="paper_paper_status_idx"),
        ),
    ]
