# Generated by Django 2.2.8 on 2019-12-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('do_not_email', models.BooleanField(default=False)),
                ('is_opted_out', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('bounced_date', models.DateTimeField(default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
