# Generated by Django 2.2.9 on 2020-01-10 16:20

from django.db import migrations, models
import django.db.models.deletion
import mailing_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.BooleanField(default=False)),
                ('comments', models.BooleanField(default=True)),
                ('replies', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='notification_frequency',
            field=models.CharField(choices=[('ALL', 'All'), ('DAILY', 'Daily'), ('3HOUR', '3-hour')], default='All', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='thread_subscription',
            field=mailing_list.models.SubscriptionField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_list.ThreadSubscription'),
        ),
    ]
