# Generated by Django 2.2.9 on 2020-01-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailing_list.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_list', '0002_auto_20200110_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='thread_subscription',
            field=mailing_list.models.SubscriptionField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_recipient', to='mailing_list.ThreadSubscription'),
        ),
    ]
