# Generated by Django 2.2.9 on 2020-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_auto_20200110_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='notification_frequency',
            field=models.IntegerField(choices=[('IMMEDIATE', 0), ('DAILY', 1440), ('3HOUR', 180)]),
        ),
    ]
