# Generated by Django 2.2.9 on 2020-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0007_emailrecipient_next_cursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.BooleanField(default=False)),
                ('replies', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='comment_subscription',
            field=models.OneToOneField(null=True, on_delete=models.CASCADE, related_name='email_recipient', to='mailing_list.CommentSubscription'),
        ),
    ]
