# Generated by Django 2.2.10 on 2020-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0010_auto_20200221_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
