# Generated by Django 2.2.10 on 2020-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0012_auto_20200227_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestsubscription',
            name='notification_frequency',
            field=models.IntegerField(choices=[('IMMEDIATE', 0), ('THREE_HOUR', 180), ('DAILY', 1440), ('WEEKLY', 10080)], default=10080),
        ),
    ]
