# Generated by Django 2.2.11 on 2020-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0014_emailtasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtasklog',
            name='notification_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
