# Generated by Django 2.2 on 2022-01-25 23:05

from django.db import migrations, models
import django.db.models.deletion
import mailing_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0016_auto_20200511_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_frequency', models.IntegerField(choices=[('IMMEDIATE', 0), ('THREE_HOUR', 180), ('DAILY', 1440), ('WEEKLY', 10080)], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('none', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='hub_subscription',
            field=mailing_list.models.SubscriptionField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_recipient', to='mailing_list.HubSubscription'),
        ),
    ]
