# Generated by Django 2.2 on 2022-01-25 23:05

from django.db import migrations, models
import django.db.models.deletion
import mailing_list.models


def add_editor_subscriptions(apps, schema_editor):
    try:
        User = apps.get_model('user', 'User')
        EmailRecipient = apps.get_model('mailing_list', 'EmailRecipient')
        HubSubscription = apps.get_model('mailing_list', 'HubSubscription')
        Hub = apps.get_model('hub', 'Hub')
        ContentType = apps.get_model('contenttypes', 'ContentType')

        editors = User.objects.filter(
                permissions__isnull=False,
                permissions__access_type='EDITOR',
                permissions__content_type=ContentType.objects.get_for_model(Hub)
            ).distinct()
        for editor in editors.iterator():
            email_recipient = EmailRecipient.objects.filter(email=editor.email)
            if email_recipient.exists():
                obj = email_recipient.first()
                if not obj.hub_subscription:
                    subscription = HubSubscription.objects.create(
                        none=True,
                        notification_frequency=10080
                    )
                    obj.hub_subscription = subscription
                    obj.save()
            else:
                continue
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0016_auto_20200511_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_frequency', models.IntegerField(choices=[('IMMEDIATE', 0), ('THREE_HOUR', 180), ('DAILY', 1440), ('WEEKLY', 10080)], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('none', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='hub_subscription',
            field=mailing_list.models.SubscriptionField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_recipient', to='mailing_list.HubSubscription'),
        ),
        migrations.RunPython(add_editor_subscriptions, migrations.RunPython.noop)
    ]
