# Generated by Django 2.2 on 2022-09-27 18:44

from django.db import migrations, models
import django.db.models.deletion
import mailing_list.models


def migrate_bounty_hub_digest(apps, schema_editor):
    EmailRecipient = apps.get_model('mailing_list', 'EmailRecipient')
    BountyDigestSubscription = apps.get_model('mailing_list', 'BountyDigestSubscription')

    for recipient in EmailRecipient.objects.all().iterator():
        try:
            recipient.bounty_digest_subscription = BountyDigestSubscription.objects.create()
            recipient.save()
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0017_auto_20220125_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyDigestSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notification_frequency', models.IntegerField(choices=[('IMMEDIATE', 0), ('THREE_HOUR', 180), ('DAILY', 1440), ('WEEKLY', 10080)], default=10080)),
                ('none', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailrecipient',
            name='bounty_digest_subscription',
            field=mailing_list.models.SubscriptionField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_recipient', to='mailing_list.BountyDigestSubscription'),
        ),
        migrations.RunPython(migrate_bounty_hub_digest),
    ]
