# Generated by Django 5.2.15 on 2026-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0018_auto_20220927_1844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailrecipient",
            name="reply_subscription",
        ),
        migrations.RemoveField(
            model_name="emailrecipient",
            name="thread_subscription",
        ),
        migrations.DeleteModel(
            name="ReplySubscription",
        ),
        migrations.DeleteModel(
            name="ThreadSubscription",
        ),
    ]
