# Generated by Django 5.2.15 on 2026-07-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0019_remove_emailrecipient_reply_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailrecipient",
            name="bounty_digest_subscription",
        ),
        migrations.RemoveField(
            model_name="emailrecipient",
            name="digest_subscription",
        ),
        migrations.RemoveField(
            model_name="emailrecipient",
            name="hub_subscription",
        ),
        migrations.RemoveField(
            model_name="emailrecipient",
            name="paper_subscription",
        ),
        migrations.DeleteModel(
            name="BountyDigestSubscription",
        ),
        migrations.DeleteModel(
            name="DigestSubscription",
        ),
        migrations.DeleteModel(
            name="HubSubscription",
        ),
        migrations.DeleteModel(
            name="PaperSubscription",
        ),
    ]
