# Generated by Django 5.2.15 on 2026-07-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_list",
            "0020_remove_emailrecipient_bounty_digest_subscription_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTaskLog",
        ),
    ]
