# Generated by Django 5.2.15 on 2026-07-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0021_delete_emailtasklog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailrecipient",
            name="comment_subscription",
        ),
        migrations.DeleteModel(
            name="CommentSubscription",
        ),
    ]
