# Generated by Django 5.2.15 on 2026-07-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0022_remove_emailrecipient_comment_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailrecipient",
            name="next_cursor",
        ),
    ]
