# Generated by Django 5.2.15 on 2026-07-28 11:57

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0023_remove_emailrecipient_next_cursor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailrecipient",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="emailrecipient_email_lower_idx",
            ),
        ),
    ]
