# Generated by Django 5.2.15 on 2026-07-30 08:53

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0023_remove_emailrecipient_next_cursor"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOptOut",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="Normalized to lowercase for matching.",
                        db_index=True,
                        max_length=254,
                    ),
                ),
                (
                    "opted_out_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="mailing_list_email_opt_out_email_lower_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "email",
                                django.db.models.functions.text.Trim(
                                    django.db.models.functions.text.Lower("email")
                                ),
                            )
                        ),
                        name="mailing_list_email_opt_out_email_normalized",
                    ),
                ],
            },
        ),
    ]
