# Generated by Django 5.2.15 on 2026-08-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0024_emailoptout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailRecipient",
        ),
    ]
