# Generated by Django 2.2.11 on 2020-04-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_websitevisits_saw_signup_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisits',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
