# Generated by Django 2.2.11 on 2020-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200410_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitevisits',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
    ]
