# Generated by Django 2.2.13 on 2020-06-24 21:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0058_figure_created_by'),
        ('analytics', '0005_websitevisits_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.CharField(blank=True, choices=[('CLICK', 'CLICK'), ('VIEW', 'VIEW')], default=None, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_location', models.CharField(blank=True, choices=[('FEED', 'FEED'), ('HUB', 'HUB'), ('PAPER', 'PAPER'), ('PROGRESS', 'PROGRESS')], default=None, max_length=255, null=True)),
                ('created_location_meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('paper_is_boosted', models.BooleanField()),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='paper.Paper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_events', related_query_name='paper_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
