# Generated by Django 4.2.15 on 2024-10-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_paperevent_created_location_meta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaperEvent",
        ),
    ]
