# Generated by Django 5.2.7 on 2025-10-27 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_delete_paperevent"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteractions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("BOUNTY_SOLUTION_SUBMITTED", "BOUNTY_SOLUTION_SUBMITTED"),
                            ("BOUNTY_SOLUTION_AWARDED", "BOUNTY_SOLUTION_AWARDED"),
                            ("BOUNTY_CREATED", "BOUNTY_CREATED"),
                            ("BOUNTY_CONTRIBUTED", "BOUNTY_CONTRIBUTED"),
                            ("ITEM_UPVOTED", "ITEM_UPVOTED"),
                            ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                            ("PAGE_VIEW", "PAGE_VIEW"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("event_timestamp", models.DateTimeField()),
                ("is_synced_with_personalize", models.BooleanField(default=False)),
                (
                    "personalize_rec_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_u_user_id_41f9cf_idx"
                    ),
                    models.Index(fields=["event"], name="analytics_u_event_0073d3_idx"),
                    models.Index(
                        fields=["event_timestamp"],
                        name="analytics_u_event_t_7eb45e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "event",
                            "unified_document",
                            "content_type",
                            "object_id",
                        ),
                        name="unique_user_event_interaction",
                    )
                ],
            },
        ),
    ]
