# Generated by Django 5.2.7 on 2025-10-27 17:52

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_delete_paperevent"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteractions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("BOUNTY_SOLUTION_SUBMITTED", "BOUNTY_SOLUTION_SUBMITTED"),
                            ("BOUNTY_SOLUTION_AWARDED", "BOUNTY_SOLUTION_AWARDED"),
                            ("BOUNTY_CREATED", "BOUNTY_CREATED"),
                            ("BOUNTY_CONTRIBUTED", "BOUNTY_CONTRIBUTED"),
                            ("ITEM_UPVOTED", "ITEM_UPVOTED"),
                            ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                            ("PAGE_VIEW", "PAGE_VIEW"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("event_timestamp", models.DateTimeField()),
                ("is_synced_with_personalize", models.BooleanField(default=False)),
                (
                    "personalize_rec_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_u_user_id_41f9cf_idx"
                    ),
                    models.Index(fields=["event"], name="analytics_u_event_0073d3_idx"),
                    models.Index(
                        fields=["event_timestamp"],
                        name="analytics_u_event_t_7eb45e_idx",
                    ),
                ],
                "constraints": [],
            },
        ),
        migrations.AddIndex(
            model_name="userinteractions",
            index=models.Index(
                fields=["is_synced_with_personalize"],
                name="idx_synced_personalize",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "ITEM_UPVOTED",
                            "BOUNTY_SOLUTION_SUBMITTED",
                            "BOUNTY_SOLUTION_AWARDED",
                            "BOUNTY_CREATED",
                            "BOUNTY_CONTRIBUTED",
                        ],
                    )
                ),
                fields=(
                    "user",
                    "event",
                    "unified_document",
                    "content_type",
                    "object_id",
                ),
                name="unique_non_repeatable_interactions",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("user"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(("event__in", ["FEED_ITEM_CLICK", "PAGE_VIEW"])),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
