# Generated by Django 5.2.7 on 2025-11-09 13:13

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_userinteractions"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_non_repeatable_interactions",
        ),
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_daily_repeatable_interactions",
        ),
        migrations.AddField(
            model_name="userinteractions",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Session ID (from Amplitude analytics_id) for anonymous and authenticated users",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractions",
            index=models.Index(
                fields=["session_id"], name="analytics_u_session_45c345_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__in", ["UPVOTE"]), ("user__isnull", False)),
                fields=(
                    "user",
                    "event",
                    "unified_document",
                    "content_type",
                    "object_id",
                ),
                name="unique_non_repeatable_interactions",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("session_id"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(("event__in", ["FEED_ITEM_CLICK", "PAGE_VIEW"])),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
