# Generated by Django 5.2.7 on 2025-11-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_userinteractions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteractions",
            name="impressions",
            field=models.TextField(
                blank=True,
                help_text="Pipe-delimited unified document IDs from Amplitude events",
                null=True,
            ),
        ),
    ]
