# Generated by Django 5.2.7 on 2025-10-27 21:04

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_userinteractions"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_user_event_interaction",
        ),
        migrations.AddIndex(
            model_name="userinteractions",
            index=models.Index(
                fields=["is_synced_with_personalize"], name="idx_synced_personalize"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "ITEM_UPVOTED",
                            "BOUNTY_SOLUTION_SUBMITTED",
                            "BOUNTY_SOLUTION_AWARDED",
                            "BOUNTY_CREATED",
                            "BOUNTY_CONTRIBUTED",
                        ],
                    )
                ),
                fields=(
                    "user",
                    "event",
                    "unified_document",
                    "content_type",
                    "object_id",
                ),
                name="unique_non_repeatable_interactions",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("user"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(("event__in", ["FEED_ITEM_CLICK", "PAGE_VIEW"])),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
