# Generated by Django 5.2.7 on 2025-11-15 12:23

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0010_remove_userinteractions_unique_non_repeatable_interactions_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_daily_repeatable_interactions",
        ),
        migrations.RemoveIndex(
            model_name="userinteractions",
            name="analytics_u_session_45c345_idx",
        ),
        migrations.RemoveField(
            model_name="userinteractions",
            name="session_id",
        ),
        migrations.AddField(
            model_name="userinteractions",
            name="external_user_id",
            field=models.CharField(
                blank=True,
                help_text="External user ID (from Amplitude analytics_id) for anonymous and authenticated users",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractions",
            index=models.Index(
                fields=["external_user_id"], name="analytics_u_externa_7738c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("external_user_id"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(("event__in", ["FEED_ITEM_CLICK", "PAGE_VIEW"])),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
