# Generated by Django 5.2.8 on 2025-11-26 02:22

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0012_remove_userinteractions_unique_daily_repeatable_interactions_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_non_repeatable_interactions",
        ),
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_daily_repeatable_interactions",
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="event",
            field=models.CharField(
                choices=[
                    ("UPVOTE", "UPVOTE"),
                    ("COMMENT_CREATED", "COMMENT_CREATED"),
                    ("PEER_REVIEW_CREATED", "PEER_REVIEW_CREATED"),
                    ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                    ("PAGE_VIEW", "PAGE_VIEW"),
                    ("DOCUMENT_TAB_CLICKED", "DOCUMENT_TAB_CLICKED"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("event__in", ["UPVOTE", "COMMENT_CREATED", "PEER_REVIEW_CREATED"]),
                    ("user__isnull", False),
                ),
                fields=(
                    "user",
                    "event",
                    "unified_document",
                    "content_type",
                    "object_id",
                ),
                name="unique_non_repeatable_interactions",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("external_user_id"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(
                    (
                        "event__in",
                        ["FEED_ITEM_CLICK", "PAGE_VIEW", "DOCUMENT_TAB_CLICKED"],
                    )
                ),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
