# Generated by Django 5.2.8 on 2025-12-29

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_remove_userinteractions_unique_non_repeatable_interactions_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_non_repeatable_interactions",
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="event",
            field=models.CharField(
                choices=[
                    ("UPVOTE", "UPVOTE"),
                    ("COMMENT_CREATED", "COMMENT_CREATED"),
                    ("PEER_REVIEW_CREATED", "PEER_REVIEW_CREATED"),
                    ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                    ("PAGE_VIEW", "PAGE_VIEW"),
                    ("DOCUMENT_TAB_CLICKED", "DOCUMENT_TAB_CLICKED"),
                    ("DOCUMENT_SAVED_TO_LIST", "DOCUMENT_SAVED_TO_LIST"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "UPVOTE",
                            "COMMENT_CREATED",
                            "PEER_REVIEW_CREATED",
                            "DOCUMENT_SAVED_TO_LIST",
                        ],
                    ),
                    ("user__isnull", False),
                ),
                fields=(
                    "user",
                    "event",
                    "unified_document",
                    "content_type",
                    "object_id",
                ),
                name="unique_non_repeatable_interactions",
            ),
        ),
    ]
