# Generated by Django 5.2.9 on 2026-01-12 23:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0013_remove_userinteractions_unique_non_repeatable_interactions_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_daily_repeatable_interactions",
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="event",
            field=models.CharField(
                choices=[
                    ("UPVOTE", "UPVOTE"),
                    ("COMMENT_CREATED", "COMMENT_CREATED"),
                    ("PEER_REVIEW_CREATED", "PEER_REVIEW_CREATED"),
                    ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                    ("PAGE_VIEW", "PAGE_VIEW"),
                    ("DOCUMENT_TAB_CLICKED", "DOCUMENT_TAB_CLICKED"),
                    ("FEED_ITEM_IMPRESSION", "FEED_ITEM_IMPRESSION"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("external_user_id"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "FEED_ITEM_CLICK",
                            "PAGE_VIEW",
                            "DOCUMENT_TAB_CLICKED",
                            "FEED_ITEM_IMPRESSION",
                        ],
                    )
                ),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
