# Generated by Django 5.2.9 on 2026-01-07 20:17

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0014_userinteractions_document_saved_to_list_event"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinteractions",
            name="unique_daily_repeatable_interactions",
        ),
        migrations.AlterField(
            model_name="userinteractions",
            name="event",
            field=models.CharField(
                choices=[
                    ("UPVOTE", "UPVOTE"),
                    ("COMMENT_CREATED", "COMMENT_CREATED"),
                    ("PEER_REVIEW_CREATED", "PEER_REVIEW_CREATED"),
                    ("FEED_ITEM_CLICK", "FEED_ITEM_CLICK"),
                    ("PAGE_VIEW", "PAGE_VIEW"),
                    ("DOCUMENT_TAB_CLICKED", "DOCUMENT_TAB_CLICKED"),
                    ("DOCUMENT_SAVED_TO_LIST", "DOCUMENT_SAVED_TO_LIST"),
                    ("FEED_ITEM_ABSTRACT_EXPANDED", "FEED_ITEM_ABSTRACT_EXPANDED"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteractions",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("event_timestamp"),
                models.F("external_user_id"),
                models.F("event"),
                models.F("unified_document"),
                models.F("content_type"),
                models.F("object_id"),
                condition=models.Q(
                    (
                        "event__in",
                        [
                            "FEED_ITEM_CLICK",
                            "PAGE_VIEW",
                            "DOCUMENT_TAB_CLICKED",
                            "FEED_ITEM_ABSTRACT_EXPANDED",
                        ],
                    )
                ),
                name="unique_daily_repeatable_interactions",
            ),
        ),
    ]
