# Generated by Django 5.2.10 on 2026-01-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0014_make_content_type_object_id_nullable"),
        (
            "analytics",
            "0015_remove_userinteractions_unique_daily_repeatable_interactions_and_more",
        ),
    ]

    operations = []
