# Generated by Django 5.2.13 on 2026-04-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0016_merge_20260113_1541"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteVisits",
        ),
    ]
