# Generated by Django 5.2 on 2025-04-22 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("researchhub_document", "0067_researchhubpost_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSavedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("list_name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "list_name")},
            },
        ),
        migrations.CreateModel(
            name="UserSavedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "is_removed_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        db_comment=(
                            "The unified document associated with the saved content entry."
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user to update the instance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_saved.usersavedlist",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="usersavedlist",
            index=models.Index(
                fields=["created_by", "list_name", "is_removed"],
                name="idx_user_list_removed",
            ),
        ),
        migrations.AddIndex(
            model_name="usersavedlist",
            index=models.Index(
                fields=["created_by", "is_removed"], name="idx_user_removed"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersavedlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("created_by", "list_name"),
                name="unique_user_list_name_not_removed",
            ),
        ),
        migrations.AddIndex(
            model_name="usersavedentry",
            index=models.Index(
                fields=["parent_list", "is_removed"], name="idx_list_removed"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersavedentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("parent_list", "unified_document"),
                name="unique_active_list_and_doc",
            ),
        ),
    ]
