# Generated by Django 5.2.8 on 2025-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_saved", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersavedentry",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usersavedlist",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
