# Generated by Django 5.2.2 on 2025-08-25 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0068_alter_researchhubpost_document_type_and_more"),
        ("user_saved", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSavedListPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("EDIT", "Edit"),
                            ("ADMIN", "Admin"),
                        ],
                        default="VIEW",
                        max_length=10,
                    ),
                ),
            ],
        ),
        # Remove old constraints that don't match our new approach
        migrations.RemoveConstraint(
            model_name="usersavedentry",
            name="unique_active_list_and_doc",
        ),
        migrations.RemoveConstraint(
            model_name="usersavedlist",
            name="unique_user_list_name_not_removed",
        ),
        # Add missing fields that SoftDeletableModel expects
        migrations.AddField(
            model_name="usersavedlist",
            name="is_removed_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        # Add missing updated_by field for UserSavedList
        migrations.AddField(
            model_name="usersavedlist",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to update the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to="user.user",
            ),
        ),
        # Remove unused fields from initial migration
        # Note: is_public and is_removed_date kept for SoftDeletableModel
        # Add new fields we need
        migrations.AddField(
            model_name="usersavedentry",
            name="document_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersavedentry",
            name="document_deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersavedentry",
            name="document_title_snapshot",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="usersavedentry",
            name="document_type_snapshot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Update field definitions to match our models
        migrations.AlterField(
            model_name="usersavedentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AlterField(
            model_name="usersavedentry",
            name="unified_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="researchhub_document.researchhubunifieddocument",
            ),
        ),
        # Add new constraints that match our models
        migrations.AddConstraint(
            model_name="usersavedlist",
            constraint=models.UniqueConstraint(
                fields=["created_by", "list_name"],
                name="unique_user_list_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersavedentry",
            constraint=models.UniqueConstraint(
                fields=["parent_list", "unified_document"],
                name="unique_list_document",
                condition=models.Q(unified_document__isnull=False),
            ),
        ),
        # Add indexes we need
        migrations.AddIndex(
            model_name="usersavedentry",
            index=models.Index(
                fields=["document_deleted"], name="idx_document_deleted"
            ),
        ),
        migrations.AddIndex(
            model_name="usersavedlist",
            index=models.Index(fields=["share_token"], name="idx_share_token"),
        ),
        # Add UserSavedListPermission fields
        migrations.AddField(
            model_name="usersavedlistpermission",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="usersavedlistpermission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last user to update the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_%(app_label)s_%(class)s",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="usersavedlistpermission",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="user_saved.usersavedlist",
            ),
        ),
        migrations.AddField(
            model_name="usersavedlistpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
        # Add constraint for UserSavedListPermission
        migrations.AddConstraint(
            model_name="usersavedlistpermission",
            constraint=models.UniqueConstraint(
                fields=["list", "user"],
                name="unique_list_user_permission",
            ),
        ),
        # Add index for UserSavedListPermission
        migrations.AddIndex(
            model_name="usersavedlistpermission",
            index=models.Index(
                fields=["list", "user", "permission"],
                name="idx_list_user_permission",
            ),
        ),
    ]
