# Generated by Django 5.2.14 on 2026-06-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_saved", "0002_alter_usersavedentry_updated_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersavedlist",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="usersavedlist",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="UserSavedEntry",
        ),
        migrations.DeleteModel(
            name="UserSavedList",
        ),
    ]
