# Generated by Django 5.2.11 on 2026-02-05 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantSession",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("researcher", "Researcher"), ("funder", "Funder")],
                        help_text="Whether the user is creating a proposal or funding opportunity",
                        max_length=32,
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        default=list,
                        help_text="List of messages in the conversation (role, content pairs)",
                    ),
                ),
                (
                    "field_state",
                    models.JSONField(
                        default=dict,
                        help_text="Current state of collected fields (field_name: {status, value})",
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all required fields have been collected",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="The final assembled payload ready for submission",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_date"],
                        name="assistant_a_user_id_bc19f6_idx",
                    ),
                    models.Index(
                        fields=["is_complete"], name="assistant_a_is_comp_aaff45_idx"
                    ),
                ],
            },
        ),
    ]
