# Generated by Django 5.2.11 on 2026-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsession",
            name="note_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the note created by the frontend for this session",
                null=True,
            ),
        ),
    ]
