# Generated by Django 5.2.11 on 2026-02-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_assistantsession_note_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantsession",
            name="last_seen_note_content_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the NoteContent version last sent to the AI",
                null=True,
            ),
        ),
    ]
