# Generated by Django 2.2 on 2021-09-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20210928_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='recipient_email',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
