# Generated by Django 2.2 on 2021-10-06 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0003_organizationinvitation_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationinvitation_sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizationinvitation_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NoteInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField()),
                ('key', models.CharField(max_length=32, unique=True)),
                ('recipient_email', models.CharField(max_length=64)),
                ('invite_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER')], default='VIEWER', max_length=8)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteinvitation_sent_invites', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noteinvitation_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
