# Generated by Django 2.2 on 2021-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0005_noteinvitation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteinvitation',
            name='invite_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER'), ('MEMBER', 'MEMBER'), ('COMMENTER', 'COMMENTER'), ('NO_ACCESS', 'NO_ACCESS')], default='VIEWER', max_length=8),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='invite_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER'), ('MEMBER', 'MEMBER'), ('COMMENTER', 'COMMENTER'), ('NO_ACCESS', 'NO_ACCESS')], default='VIEWER', max_length=8),
        ),
    ]
