# Generated by Django 4.1 on 2022-11-11 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invite", "0006_auto_20211006_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteinvitation",
            name="invite_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EDITOR", "EDITOR"),
                    ("VIEWER", "VIEWER"),
                    ("MEMBER", "MEMBER"),
                    ("COMMENTER", "COMMENTER"),
                    ("NO_ACCESS", "NO_ACCESS"),
                ],
                default="VIEWER",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="noteinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sent_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="noteinvitation",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="invite_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EDITOR", "EDITOR"),
                    ("VIEWER", "VIEWER"),
                    ("MEMBER", "MEMBER"),
                    ("COMMENTER", "COMMENTER"),
                    ("NO_ACCESS", "NO_ACCESS"),
                ],
                default="VIEWER",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_sent_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
