# Generated by Django 2.2 on 2022-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0006_auto_20211006_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteinvitation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='noteinvitation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
