# Generated by Django 4.2.15 on 2024-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invite", "0007_alter_noteinvitation_invite_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteinvitation",
            name="invite_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EDITOR", "EDITOR"),
                    ("ASSISTANT_EDITOR", "ASSISTANT_EDITOR"),
                    ("ASSOCIATE_EDITOR", "ASSOCIATE_EDITOR"),
                    ("SENIOR_EDITOR", "SENIOR_EDITOR"),
                    ("VIEWER", "VIEWER"),
                    ("MEMBER", "MEMBER"),
                    ("COMMENTER", "COMMENTER"),
                    ("NO_ACCESS", "NO_ACCESS"),
                ],
                default="VIEWER",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="invite_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EDITOR", "EDITOR"),
                    ("ASSISTANT_EDITOR", "ASSISTANT_EDITOR"),
                    ("ASSOCIATE_EDITOR", "ASSOCIATE_EDITOR"),
                    ("SENIOR_EDITOR", "SENIOR_EDITOR"),
                    ("VIEWER", "VIEWER"),
                    ("MEMBER", "MEMBER"),
                    ("COMMENTER", "COMMENTER"),
                    ("NO_ACCESS", "NO_ACCESS"),
                ],
                default="VIEWER",
                max_length=16,
            ),
        ),
    ]
