"""
Constants for AWS Personalize item data export.

Defines field names, CSV headers, and data types matching the Avro schema.
"""

# CSV Field Names (matching Avro schema)
ITEM_ID = "ITEM_ID"
ITEM_TYPE = "ITEM_TYPE"
HUB_L1 = "HUB_L1"
HUB_L2 = "HUB_L2"
HUB_IDS = "HUB_IDS"
JOURNAL_HUB_ID = "JOURNAL_HUB_ID"
AUTHOR_IDS = "AUTHOR_IDS"
CREATION_TIMESTAMP = "CREATION_TIMESTAMP"
TEXT = "TEXT"
TITLE = "TITLE"
UPVOTE_SCORE = "UPVOTE_SCORE"
# Bluesky metrics
BLUESKY_POST_COUNT = "BLUESKY_POST_COUNT"
BLUESKY_TOTAL_LIKES = "BLUESKY_TOTAL_LIKES"
BLUESKY_TOTAL_QUOTES = "BLUESKY_TOTAL_QUOTES"
BLUESKY_TOTAL_REPLIES = "BLUESKY_TOTAL_REPLIES"
BLUESKY_TOTAL_REPOSTS = "BLUESKY_TOTAL_REPOSTS"
# X metrics
X_POST_COUNT = "X_POST_COUNT"
X_TOTAL_LIKES = "X_TOTAL_LIKES"
X_TOTAL_QUOTES = "X_TOTAL_QUOTES"
X_TOTAL_REPLIES = "X_TOTAL_REPLIES"
X_TOTAL_REPOSTS = "X_TOTAL_REPOSTS"
X_TOTAL_IMPRESSIONS = "X_TOTAL_IMPRESSIONS"
# GitHub metrics
GITHUB_TOTAL_MENTIONS = "GITHUB_TOTAL_MENTIONS"
GITHUB_CODE_MENTIONS = "GITHUB_CODE_MENTIONS"
CITATION_COUNT_TOTAL = "CITATION_COUNT_TOTAL"
PEER_REVIEW_COUNT_TOTAL = "PEER_REVIEW_COUNT_TOTAL"
HAS_ACTIVE_BOUNTY = "HAS_ACTIVE_BOUNTY"
BOUNTY_HAS_SOLUTIONS = "BOUNTY_HAS_SOLUTIONS"
RFP_IS_OPEN = "RFP_IS_OPEN"
RFP_HAS_APPLICANTS = "RFP_HAS_APPLICANTS"
PROPOSAL_IS_OPEN = "PROPOSAL_IS_OPEN"
PROPOSAL_HAS_FUNDERS = "PROPOSAL_HAS_FUNDERS"

# Delimiter for list fields (HUB_IDS, AUTHOR_IDS)
DELIMITER = "|"

# Limits for fields to prevent data bloat
MAX_HUB_IDS = 20

# CSV Headers (in order for the CSV file)
CSV_HEADERS = [
    ITEM_ID,
    ITEM_TYPE,
    HUB_L1,
    HUB_L2,
    HUB_IDS,
    JOURNAL_HUB_ID,
    CREATION_TIMESTAMP,
    TEXT,
    TITLE,
    UPVOTE_SCORE,
    BLUESKY_POST_COUNT,
    BLUESKY_TOTAL_LIKES,
    BLUESKY_TOTAL_QUOTES,
    BLUESKY_TOTAL_REPLIES,
    BLUESKY_TOTAL_REPOSTS,
    X_POST_COUNT,
    X_TOTAL_LIKES,
    X_TOTAL_QUOTES,
    X_TOTAL_REPLIES,
    X_TOTAL_REPOSTS,
    X_TOTAL_IMPRESSIONS,
    GITHUB_TOTAL_MENTIONS,
    GITHUB_CODE_MENTIONS,
    CITATION_COUNT_TOTAL,
    PEER_REVIEW_COUNT_TOTAL,
    HAS_ACTIVE_BOUNTY,
    BOUNTY_HAS_SOLUTIONS,
    RFP_IS_OPEN,
    RFP_HAS_APPLICANTS,
    PROPOSAL_IS_OPEN,
    PROPOSAL_HAS_FUNDERS,
]

# Default values for each field
FIELD_DEFAULTS = {
    # String/ID fields (nullable)
    ITEM_ID: None,
    ITEM_TYPE: None,
    HUB_L1: None,
    HUB_L2: None,
    HUB_IDS: None,
    JOURNAL_HUB_ID: None,
    CREATION_TIMESTAMP: None,
    TEXT: None,
    TITLE: None,
    # Integer fields (counts, scores)
    UPVOTE_SCORE: 0,
    BLUESKY_POST_COUNT: 0,
    BLUESKY_TOTAL_LIKES: 0,
    BLUESKY_TOTAL_QUOTES: 0,
    BLUESKY_TOTAL_REPLIES: 0,
    BLUESKY_TOTAL_REPOSTS: 0,
    X_POST_COUNT: 0,
    X_TOTAL_LIKES: 0,
    X_TOTAL_QUOTES: 0,
    X_TOTAL_REPLIES: 0,
    X_TOTAL_REPOSTS: 0,
    X_TOTAL_IMPRESSIONS: 0,
    GITHUB_TOTAL_MENTIONS: 0,
    GITHUB_CODE_MENTIONS: 0,
    CITATION_COUNT_TOTAL: 0,
    PEER_REVIEW_COUNT_TOTAL: 0,
    # Boolean fields (flags)
    HAS_ACTIVE_BOUNTY: False,
    BOUNTY_HAS_SOLUTIONS: False,
    RFP_IS_OPEN: False,
    RFP_HAS_APPLICANTS: False,
    PROPOSAL_IS_OPEN: False,
    PROPOSAL_HAS_FUNDERS: False,
}

# Document types to exclude from export
EXCLUDED_DOCUMENT_TYPES = ["NOTE", "HYPOTHESIS"]

# Document types to include in export
SUPPORTED_DOCUMENT_TYPES = [
    "GRANT",
    "PREREGISTRATION",
    "DISCUSSION",
    "QUESTION",
    "PAPER",
]

# Text field maximum length (to prevent CSV cell overflow)
# Applied to both TITLE and TEXT fields
MAX_TEXT_LENGTH = 950

# ITEM_TYPE mapping for Personalize export
# Maps internal document_type to Personalize-friendly type names
ITEM_TYPE_MAPPING = {
    "PREREGISTRATION": "PROPOSAL",
    "GRANT": "RFP",
    "DISCUSSION": "POST",
    "QUESTION": "QUESTION",
    "PAPER": "PAPER",
}
