#!/bin/sh
# Deploy researchhub-backend to staging

start="Deploying to staging environments:"
echo $start

echo "Creating requirements.txt"
pipenv lock --requirements > requirements.txt

echo "Deploying to staging-backend"
eb deploy staging-backend

done="Finished executing staging deployment"
echo $done
