#!/bin/sh
# Deploy researchhub-backend to production

start="Deploying to production environments:"
echo $start

echo "Creating requirements.txt"
pipenv lock --requirements > requirements.txt

echo "Deploying to production"
eb deploy production-2

echo "Deploying to production"
eb deploy production-worker-2

done="Finished executing production deployment"
echo $done
