#!/bin/sh
# Deploy researchhub-backend to staging

start="Deploying to staging environments:"
echo $start

# echo "Creating requirements.txt"
# pipenv lock --requirements > requirements.txt

echo "Deploying"

eb deploy staging-backend-3
eb deploy staging-backend-3-worker
eb deploy staging-backend-3-worker-cermine

git checkout HEAD -- requirements.txt

done="Finished executing staging deployment"
echo $done
