AUTHOR_CLAIM = "AUTHOR_CLAIM"

CLOSED = "CLOSED"
DENIED = "DENIED"
INITIATED = "INITIATED"
"""
  Nullified signifies that the author was
  claimed by someone else during process
"""
NULLIFIED = "NULLIFIED"
OPEN = "OPEN"


AUTHOR_CLAIM_CASE_STATUS = [
    (CLOSED, CLOSED),
    (DENIED, DENIED),
    (INITIATED, INITIATED),
    (NULLIFIED, NULLIFIED),
    (OPEN, OPEN),
]

RH_CASE_TYPES = [
    (AUTHOR_CLAIM, AUTHOR_CLAIM)
]
