# Generated by Django 4.1 on 2024-05-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0057_alter_researchhubpost_document_type_and_more"),
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedDocumentTopics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("relevancy_score", models.FloatField(default=0.0)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="through_unified_document",
                        to="topic.topic",
                    ),
                ),
                (
                    "unified_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researchhub_document.researchhubunifieddocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
