# Generated by Django 4.1 on 2024-05-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0002_unifieddocumenttopics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("openalex_id", models.CharField(max_length=255, unique=True)),
                ("display_name", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("openalex_id", models.CharField(max_length=255, unique=True)),
                ("display_name", models.TextField()),
                (
                    "domain_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="topic.domain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="topic",
            name="domain_display_name",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="domain_openalex_id",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="field_display_name",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="field_openalex_id",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="subfield_display_name",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="subfield_openalex_id",
        ),
        migrations.AddField(
            model_name="topic",
            name="openalex_updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Subfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("openalex_id", models.CharField(max_length=255, unique=True)),
                ("display_name", models.TextField()),
                (
                    "field_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfields",
                        to="topic.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="subfield_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="topic.subfield",
            ),
        ),
    ]
