# Generated by Django 4.1 on 2024-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0003_domain_field_remove_topic_domain_display_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="domain_id",
            new_name="domain",
        ),
        migrations.RenameField(
            model_name="subfield",
            old_name="field_id",
            new_name="field",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="subfield_id",
            new_name="subfield",
        ),
        migrations.AddField(
            model_name="topic",
            name="openalex_created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
