# Generated by Django 4.1 on 2024-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0004_rename_domain_id_field_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="cited_by_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="works_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
