# Generated by Django 4.1 on 2024-05-10 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0005_alter_topic_cited_by_count_alter_topic_works_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
