# Generated by Django 4.2.13 on 2024-07-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0006_alter_topic_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifieddocumenttopics",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
