# Generated by Django 4.2.15 on 2024-09-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researchhub_document", "0059_alter_researchhubpost_document_type_and_more"),
        ("topic", "0007_unifieddocumenttopics_is_primary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unifieddocumenttopics",
            unique_together={("unified_document", "topic")},
        ),
    ]
