from typing import Dict, Optional, Tuple

ARXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "cs.ai": ("Computer Science", "Artificial Intelligence"),
    "cs.ar": ("Computer Science", "Hardware Architecture"),
    "cs.cc": ("Computer Science", "Computational Complexity"),
    "cs.ce": ("Computer Science", "Computational Engineering"),
    "cs.cg": ("Computer Science", "Computational Geometry"),
    "cs.cl": ("Computer Science", "Natural Language Processing"),
    "cs.cr": ("Computer Science", "Cryptography and Security"),
    "cs.cv": ("Computer Science", "Computer Vision"),
    "cs.cy": ("Computer Science", "Computers and Society"),
    "cs.db": ("Computer Science", "Databases"),
    "cs.dc": ("Computer Science", "Distributed Computing"),
    "cs.dl": ("Computer Science", "Digital Libraries"),
    "cs.dm": ("Computer Science", "Discrete Mathematics"),
    "cs.ds": ("Computer Science", "Data Structures and Algorithms"),
    "cs.et": ("Computer Science", "Emerging Technologies"),
    "cs.fl": ("Computer Science", "Formal Languages"),
    "cs.gl": ("Computer Science", "General Literature"),
    "cs.gr": ("Computer Science", "Graphics"),
    "cs.gt": ("Computer Science", "Game Theory"),
    "cs.hc": ("Computer Science", "Human-Computer Interaction"),
    "cs.ir": ("Computer Science", "Information Retrieval"),
    "cs.it": ("Computer Science", "Information Theory"),
    "cs.lg": ("Computer Science", "Machine Learning"),
    "cs.lo": ("Computer Science", "Logic"),
    "cs.ma": ("Computer Science", "Multiagent Systems"),
    "cs.mm": ("Computer Science", "Multimedia"),
    "cs.ms": ("Computer Science", "Mathematical Software"),
    "cs.na": ("Computer Science", "Numerical Analysis"),
    "cs.ne": ("Computer Science", "Neural Computing"),
    "cs.ni": ("Computer Science", "Networking"),
    "cs.oh": ("Computer Science", "Miscellaneous"),
    "cs.os": ("Computer Science", "Operating Systems"),
    "cs.pf": ("Computer Science", "Performance"),
    "cs.pl": ("Computer Science", "Programming Languages"),
    "cs.ro": ("Computer Science", "Robotics"),
    "cs.sc": ("Computer Science", "Symbolic Computation"),
    "cs.sd": ("Computer Science", "Sound"),
    "cs.se": ("Computer Science", "Software Engineering"),
    "cs.si": ("Computer Science", "Social Networks"),
    "cs.sy": ("Computer Science", "Systems and Control"),
    "econ.em": ("Economics", "Econometrics"),
    "econ.gn": ("Economics", "General Economics"),
    "econ.th": ("Economics", "Economic Theory"),
    "eess.as": ("Engineering", "Audio and Speech Processing"),
    "eess.iv": ("Engineering", "Image and Video Processing"),
    "eess.sp": ("Engineering", "Signal Processing"),
    "eess.sy": ("Engineering", "Systems and Control"),
    "math.ac": ("Mathematics", "Commutative Algebra"),
    "math.ag": ("Mathematics", "Algebraic Geometry"),
    "math.ap": ("Mathematics", "Analysis of PDEs"),
    "math.at": ("Mathematics", "Algebraic Topology"),
    "math.ca": ("Mathematics", "Classical Analysis"),
    "math.co": ("Mathematics", "Combinatorics"),
    "math.ct": ("Mathematics", "Category Theory"),
    "math.cv": ("Mathematics", "Complex Variables"),
    "math.dg": ("Mathematics", "Differential Geometry"),
    "math.ds": ("Mathematics", "Dynamical Systems"),
    "math.fa": ("Mathematics", "Functional Analysis"),
    "math.gm": ("Mathematics", "General Mathematics"),
    "math.gn": ("Mathematics", "General Topology"),
    "math.gr": ("Mathematics", "Group Theory"),
    "math.gt": ("Mathematics", "Geometric Topology"),
    "math.ho": ("Mathematics", "History and Overview"),
    "math.it": ("Mathematics", "Information Theory"),
    "math.kt": ("Mathematics", "K-Theory"),
    "math.lo": ("Mathematics", "Logic"),
    "math.mg": ("Mathematics", "Metric Geometry"),
    "math.mp": ("Physics", "Mathematical Physics"),
    "math.na": ("Mathematics", "Numerical Analysis"),
    "math.nt": ("Mathematics", "Number Theory"),
    "math.oa": ("Mathematics", "Operator Algebras"),
    "math.oc": ("Mathematics", "Systems and Control"),
    "math.pr": ("Mathematics", "Probability"),
    "math.qa": ("Mathematics", "Quantum Algebra"),
    "math.ra": ("Mathematics", "Rings and Algebras"),
    "math.rt": ("Mathematics", "Representation Theory"),
    "math.sg": ("Mathematics", "Symplectic Geometry"),
    "math.sp": ("Mathematics", "Spectral Theory"),
    "math.st": ("Statistics", "Statistics Theory"),
    "astro-ph": ("Physics", "Astrophysics"),
    "astro-ph.co": ("Physics", "Cosmology"),
    "astro-ph.ep": ("Physics", "Planetary Science"),
    "astro-ph.ga": ("Physics", "Galaxies"),
    "astro-ph.he": ("Physics", "High Energy Astrophysics"),
    "astro-ph.im": ("Physics", "Instrumentation"),
    "astro-ph.sr": ("Physics", "Solar and Stellar"),
    "cond-mat": ("Physics", "Condensed Matter"),
    "cond-mat.dis-nn": ("Physics", "Disordered Systems"),
    "cond-mat.mes-hall": ("Physics", "Mesoscale Physics"),
    "cond-mat.mtrl-sci": ("Physics", "Materials Science"),
    "cond-mat.other": ("Physics", "Other Condensed Matter"),
    "cond-mat.quant-gas": ("Physics", "Quantum Gases"),
    "cond-mat.soft": ("Physics", "Soft Matter"),
    "cond-mat.stat-mech": ("Physics", "Statistical Mechanics"),
    "cond-mat.str-el": ("Physics", "Strongly Correlated"),
    "cond-mat.supr-con": ("Physics", "Superconductivity"),
    "gr-qc": ("Physics", "General Relativity"),
    "hep-ex": ("Physics", "High Energy Experiment"),
    "hep-lat": ("Physics", "Lattice Physics"),
    "hep-ph": ("Physics", "High Energy Phenomenology"),
    "hep-th": ("Physics", "High Energy Theory"),
    "math-ph": ("Physics", "Mathematical Physics"),
    "nlin": ("Physics", "Nonlinear Sciences"),
    "nlin.ao": ("Physics", "Adaptation and Self-Organization"),
    "nlin.cd": ("Physics", "Chaotic Dynamics"),
    "nlin.cg": ("Physics", "Cellular Automata"),
    "nlin.ps": ("Physics", "Pattern Formation"),
    "nlin.si": ("Physics", "Exactly Solvable Systems"),
    "nucl-ex": ("Physics", "Nuclear Experiment"),
    "nucl-th": ("Physics", "Nuclear Theory"),
    "quant-ph": ("Physics", "Quantum Physics"),
    "physics": ("Physics", "General Physics"),
    "physics.acc-ph": ("Physics", "Accelerator Physics"),
    "physics.ao-ph": ("Physics", "Atmospheric Physics"),
    "physics.app-ph": ("Physics", "Applied Physics"),
    "physics.atm-clus": ("Physics", "Atomic Clusters"),
    "physics.atom-ph": ("Physics", "Atomic Physics"),
    "physics.bio-ph": ("Biology", "Biological Physics"),
    "physics.chem-ph": ("Chemistry", "Chemical Physics"),
    "physics.class-ph": ("Physics", "Classical Physics"),
    "physics.comp-ph": ("Physics", "Computational Physics"),
    "physics.data-an": ("Physics", "Data Analysis"),
    "physics.ed-ph": ("Physics", "Physics Education"),
    "physics.flu-dyn": ("Physics", "Fluid Dynamics"),
    "physics.gen-ph": ("Physics", "General Physics"),
    "physics.geo-ph": ("Physics", "Geophysics"),
    "physics.hist-ph": ("Physics", "History of Physics"),
    "physics.ins-det": ("Physics", "Instrumentation"),
    "physics.med-ph": ("Medicine", "Medical Physics"),
    "physics.optics": ("Physics", "Optics"),
    "physics.plasm-ph": ("Physics", "Plasma Physics"),
    "physics.pop-ph": ("Physics", "Popular Physics"),
    "physics.soc-ph": ("Social Sciences", "Physics and Society"),
    "physics.space-ph": ("Physics", "Space Physics"),
    "q-bio": ("Biology", "Quantitative Biology"),
    "q-bio.bm": ("Biology", "Biomolecules"),
    "q-bio.cb": ("Biology", "Cell Biology"),
    "q-bio.gn": ("Biology", "Genetics and Genomics"),
    "q-bio.mn": ("Biology", "Molecular Networks"),
    "q-bio.nc": ("Biology", "Neuroscience"),
    "q-bio.ot": ("Biology", "Other Quantitative Biology"),
    "q-bio.pe": ("Biology", "Populations and Evolution"),
    "q-bio.qm": ("Biology", "Quantitative Methods"),
    "q-bio.sc": ("Biology", "Subcellular Processes"),
    "q-bio.to": ("Biology", "Tissues and Organs"),
    "q-fin": ("Economics", "Quantitative Finance"),
    "q-fin.cp": ("Economics", "Computational Finance"),
    "q-fin.ec": ("Economics", "Financial Economics"),
    "q-fin.gn": ("Economics", "General Finance"),
    "q-fin.mf": ("Economics", "Mathematical Finance"),
    "q-fin.pm": ("Economics", "Portfolio Management"),
    "q-fin.pr": ("Economics", "Securities Pricing"),
    "q-fin.rm": ("Economics", "Risk Management"),
    "q-fin.st": ("Economics", "Statistical Finance"),
    "q-fin.tr": ("Economics", "Trading and Market Microstructure"),
    "stat": ("Statistics", "General Statistics"),
    "stat.ap": ("Statistics", "Applications"),
    "stat.co": ("Statistics", "Computation"),
    "stat.me": ("Statistics", "Methodology"),
    "stat.ml": ("Computer Science", "Machine Learning"),
    "stat.ot": ("Statistics", "Miscellaneous"),
    "stat.th": ("Statistics", "Statistics Theory"),
}
