from typing import Dict, Optional, Tuple

BIORXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "animal behavior and cognition": ("biology", "neuroscience"),
    "biochemistry": ("biology", "biochemistry"),
    "bioengineering": ("engineering", "bioengineering"),
    "bioinformatics": ("biology", "bioinformatics"),
    "biophysics": ("biology", "biophysics"),
    "cancer biology": ("biology", "cancer-biology"),
    "cell biology": ("biology", "cell-biology"),
    "developmental biology": ("biology", "developmental-biology"),
    "ecology": ("biology", "ecology"),
    "evolutionary biology": ("biology", "evolutionary-biology"),
    "genetics": ("biology", "genetics-and-genomics"),
    "genomics": ("biology", "genetics-and-genomics"),
    "immunology": ("biology", "immunology"),
    "microbiology": ("biology", "microbiology"),
    "molecular biology": ("biology", "molecular-biology"),
    "neuroscience": ("biology", "neuroscience"),
    "paleontology": ("biology", "paleontology"),
    "pathology": ("biology", "pathology"),
    "physiology": ("biology", "physiology"),
    "plant biology": ("biology", "plant-biology"),
    "synthetic biology": ("biology", "synthetic-biology"),
    "systems biology": ("biology", "systems-biology"),
    "zoology": ("biology", "zoology"),
    "clinical trials": ("medicine", "clinical-trials"),
    "epidemiology": ("medicine", "epidemiology"),
    "pharmacology and toxicology": ("biology", "pharmacology"),
    "scientific communication and education": (
        "social-sciences",
        "scientific-communication-and-education",
    ),
}
