from typing import Dict, Optional, Tuple

BIORXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "animal behavior and cognition": ("Biology", "Neuroscience"),
    "biochemistry": ("Biology", "Biochemistry"),
    "bioengineering": ("Engineering", "Bioengineering"),
    "bioinformatics": ("Biology", "Bioinformatics"),
    "biophysics": ("Biology", "Biophysics"),
    "cancer biology": ("Biology", "Cancer Biology"),
    "cell biology": ("Biology", "Cell Biology"),
    "developmental biology": ("Biology", "Developmental Biology"),
    "ecology": ("Biology", "Ecology"),
    "evolutionary biology": ("Biology", "Evolutionary Biology"),
    "genetics": ("Biology", "Genetics and Genomics"),
    "genomics": ("Biology", "Genetics and Genomics"),
    "immunology": ("Biology", "Immunology"),
    "microbiology": ("Biology", "Microbiology"),
    "molecular biology": ("Biology", "Molecular Biology"),
    "neuroscience": ("Biology", "Neuroscience"),
    "paleontology": ("Biology", "Paleontology"),
    "pathology": ("Biology", "Pathology"),
    "physiology": ("Biology", "Physiology"),
    "plant biology": ("Biology", "Plant Biology"),
    "synthetic biology": ("Biology", "Synthetic Biology"),
    "systems biology": ("Biology", "Systems Biology"),
    "zoology": ("Biology", "Zoology"),
    "clinical trials": ("Medicine", "Clinical Trials"),
    "epidemiology": ("Medicine", "Epidemiology"),
    "pharmacology and toxicology": ("Biology", "Pharmacology"),
    "scientific communication and education": (
        "Social Sciences",
        "Scientific Communication and Education",
    ),
}
