"""
ChemRxiv category mappings to ResearchHub categories and subcategories.

Maps ChemRxiv's chemistry categories to ResearchHub's category structure.
"""

from typing import Dict, Optional, Tuple

CHEMRXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "agriculture and food chemistry": ("Chemistry", "Food Chemistry"),
    "analytical chemistry": ("Chemistry", "Analytical Chemistry"),
    "biological and medicinal chemistry": (
        "Chemistry",
        "Medicinal Chemistry",
    ),
    "catalysis": ("Chemistry", "Catalysis"),
    "chemical education": ("Chemistry", "Chemical Education"),
    "chemical engineering and industrial chemistry": (
        "Engineering",
        "Chemical Engineering",
    ),
    "earth, space, and environmental chemistry": (
        "Chemistry",
        "Environmental Chemistry",
    ),
    "energy": ("Chemistry", "Physics"),
    "inorganic chemistry": ("Chemistry", "Inorganic Chemistry"),
    "materials chemistry": ("Chemistry", "Materials Chemistry"),
    "materials science": ("Engineering", "Materials Science"),
    "nanoscience": ("Chemistry", "Nanochemistry"),
    "organic chemistry": ("Chemistry", "Organic Chemistry"),
    "organometallic chemistry": ("Chemistry", "Organometallic Chemistry"),
    "physical chemistry": ("Chemistry", "Physical Chemistry"),
    "polymer science": ("Chemistry", "Materials Science"),
    "theoretical and computational chemistry": (
        "Chemistry",
        "Computational Chemistry",
    ),
    "analytical apparatus": ("Chemistry", "Analytical Chemistry"),
    "analytical chemistry - general": ("Chemistry", "Analytical Chemistry"),
    "biochemical analysis": ("Biochemistry", "Analytical Biochemistry"),
    "chemoinformatics": ("Chemistry", "Computational Chemistry"),
    "electrochemical analysis": ("Electrochemistry", "Analytical Chemistry"),
    "environmental analysis": ("Chemistry", "Environmental Chemistry"),
    "high-throughput screening": ("Chemistry", "Analytical Chemistry"),
    "imaging": ("Chemistry", "Analytical Chemistry"),
    "mass spectrometry": ("Chemistry", "Analytical Chemistry"),
    "microscopy": ("Chemistry", "Analytical Chemistry"),
    "separation science": ("Chemistry", "Analytical Chemistry"),
    "spectroscopy (anal. chem.)": ("Chemistry", "Analytical Chemistry"),
    "biochemistry": ("Biology", "Biochemistry"),
    "bioengineering and biotechnology": ("Engineering", "Bioengineering"),
    "bioinformatics and computational biology": (
        "Biology",
        "Bioinformatics",
    ),
    "biophysics": ("Biology", "Biophysics"),
    "cell and molecular biology": ("Biology", "Cell Biology"),
    "chemical biology": ("Chemistry", "Chemical Biology"),
    "drug discovery and drug delivery systems": ("Chemistry", "Medicinal Chemistry"),
    "environmental biology": ("Biology", "Ecology"),
    "microbiology": ("Biology", "Microbiology"),
    "plant biology": ("Biology", "Plant Biology"),
    "acid catalysis": ("Chemistry", "Catalysis"),
    "base catalysis": ("Chemistry", "Catalysis"),
    "biocatalysis": ("Chemistry", "Catalysis"),
    "electrocatalysis": ("Chemistry", "Catalysis"),
    "heterogeneous catalysis": ("Chemistry", "Catalysis"),
    "homogeneous catalysis": ("Chemistry", "Catalysis"),
    "nanocatalysis - reactions & mechanisms": (
        "Chemistry",
        "Catalysis",
    ),
    "organocatalysis": ("Chemistry", "Catalysis"),
    "photocatalysis": ("Chemistry", "Catalysis"),
    "redox catalysis": ("Chemistry", "Catalysis"),
    "chemical education - general": ("Chemistry", "Chemical Education"),
    "fluid mechanics": ("Engineering", "Chemical Engineering"),
    "industrial manufacturing": ("Engineering", "Chemical Engineering"),
    "natural resource recovery": ("Engineering", "Chemical Engineering"),
    "petrochemicals": ("Engineering", "Chemical Engineering"),
    "pharmaceutical industry": ("Engineering", "Chemical Engineering"),
    "process control": ("Engineering", "Chemical Engineering"),
    "quality control": ("Engineering", "Chemical Engineering"),
    "reaction engineering": ("Engineering", "Chemical Engineering"),
    "thermodynamics (chem. eng.)": ("Engineering", "Chemical Engineering"),
    "transport phenomena (chem. eng.)": ("Engineering", "Chemical Engineering"),
    "water purification": ("Engineering", "Chemical Engineering"),
    "atmospheric chemistry": ("Chemistry", "Environmental Chemistry"),
    "environmental science": ("Chemistry", "Environmental Chemistry"),
    "geochemistry": ("Chemistry", "Geochemistry"),
    "hydrology and water chemistry": ("Chemistry", "Environmental Chemistry"),
    "soil science": ("Chemistry", "Environmental Chemistry"),
    "space chemistry": ("Chemistry", "Astrochemistry"),
    "wastes": ("Chemistry", "Environmental Chemistry"),
    "energy storage": ("Chemistry", "Physics"),
    "fuel cells": ("Chemistry", "Electrochemistry"),
    "fuels - energy science": ("Chemistry", "Chemical Engineering"),
    "photovoltaics": ("Chemistry", "Materials Chemistry"),
    "piezoelectricity and thermoelectricity": (
        "Physics",
        "Condensed Matter",
    ),
    "power": ("Chemistry", "Physics"),
    "bioinorganic chemistry": ("Chemistry", "Inorganic Chemistry"),
    "bonding": ("Chemistry", "Inorganic Chemistry"),
    "coordination chemistry (inorg.)": ("Chemistry", "Inorganic Chemistry"),
    "crystallography – inorganic": (
        "Chemistry",
        "Inorganic Chemistry",
    ),
    "electrochemistry": ("Chemistry", "Electrochemistry"),
    "frustrated lewis pairs": ("Chemistry", "Inorganic Chemistry"),
    "inorganic acid/base chemistry": ("Chemistry", "Inorganic Chemistry"),
    "kinetics and mechanism - inorganic reactions": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "lanthanides and actinides": ("Chemistry", "Inorganic Chemistry"),
    "ligands (inorg.)": ("Chemistry", "Inorganic Chemistry"),
    "magnetism": ("Chemistry", "Inorganic Chemistry"),
    "main group chemistry (inorg.)": ("Chemistry", "Inorganic Chemistry"),
    "minerals": ("Chemistry", "Inorganic Chemistry"),
    "nuclear chemistry": ("Chemistry", "Nuclear Chemistry"),
    "organometallic compounds": ("Chemistry", "Organometallic Chemistry"),
    "polymers": ("Chemistry", "Materials Science"),
    "reaction (inorg.)": ("Chemistry", "Inorganic Chemistry"),
    "sensors": ("Chemistry", "Analytical Chemistry"),
    "small molecule activation (inorg.)": (
        "Chemistry",
        "Inorganic Chemistry",
    ),
    "solid state chemistry": ("Chemistry", "Inorganic Chemistry"),
    "solvates": ("Chemistry", "Inorganic Chemistry"),
    "spectroscopy (inorg.)": ("Chemistry", "Inorganic Chemistry"),
    "supramolecular chemistry (inorg.)": (
        "Chemistry",
        "Supramolecular Chemistry",
    ),
    "theory - inorganic": ("Chemistry", "Computational Chemistry"),
    "transition metal complexes (inorg.)": (
        "Chemistry",
        "Inorganic Chemistry",
    ),
    "aggregates and assemblies": ("Chemistry", "Supramolecular Chemistry"),
    "alloys": ("Engineering", "Materials Science"),
    "biocompatible materials": ("Engineering", "Bioengineering"),
    "biodegradable materials": ("Chemistry", "Materials Science"),
    "biological materials": ("Bioengineering", "Materials Science"),
    "carbon-based materials": ("Chemistry", "Materials Science"),
    "catalysts": ("Chemistry", "Catalysis"),
    "ceramics": ("Engineering", "Materials Science"),
    "coating materials": ("Engineering", "Materials Science"),
    "composites": ("Engineering", "Materials Science"),
    "conducting polymers": ("Chemistry", "Materials Science"),
    "controlled-release systems": ("Chemistry", "Chemical Engineering"),
    "coordination polymers": ("Chemistry", "Materials Science"),
    "core-shell materials": ("Chemistry", "Materials Chemistry"),
    "dyes and chromophores": ("Chemistry", "Organic Chemistry"),
    "elastic materials": ("Engineering", "Materials Science"),
    "fibers": ("Engineering", "Materials Science"),
    "fire-resistant materials": ("Engineering", "Materials Science"),
    "fuels - materials": ("Chemistry", "Materials Science"),
    "geological materials": ("Chemistry", "Geochemistry"),
    "granular materials": ("Engineering", "Materials Science"),
    "hybrid organic-inorganic materials": (
        "Chemistry",
        "Materials Science",
    ),
    "hydrogen storage materials": ("Chemistry", "Materials Science"),
    "imaging agents": ("Chemistry", "Medicinal Chemistry"),
    "liquid crystals": ("Chemistry", "Physics"),
    "magnetic materials": ("Physics", "Materials Science"),
    "materials processing": ("Engineering", "Materials Science"),
    "metamaterials": ("Physics", "Materials Science"),
    "multilayers": ("Engineering", "Materials Science"),
    "nanostructured materials - materials": (
        "Chemistry",
        "Nanochemistry",
    ),
    "oligomers": ("Chemistry", "Organic Chemistry"),
    "optical materials": ("Physics", "Optics"),
    "photosensitizers": ("Chemistry", "Materials Chemistry"),
    "surfactants": ("Chemistry", "Chemical Engineering"),
    "thermal conductors and insulators": ("Engineering", "Materials Science"),
    "thin films": ("Engineering", "Materials Science"),
    "nanocatalysis - catalysts & materials": (
        "Chemistry",
        "Nanochemistry",
    ),
    "nanodevices": ("Chemistry", "Nanochemistry"),
    "nanofabrication": ("Chemistry", "Nanochemistry"),
    "nanofluidics": ("Chemistry", "Nanochemistry"),
    "nanostructured materials - nanoscience": (
        "Chemistry",
        "Nanochemistry",
    ),
    "plasmonic and photonic structures and devices": (
        "Physics",
        "Optics",
    ),
    "bioorganic chemistry": ("Chemistry", "Biochemistry"),
    "combinatorial chemistry": ("Chemistry", "Medicinal Chemistry"),
    "crystallography – organic": ("Chemistry", "Organic Chemistry"),
    "natural products": ("Chemistry", "Organic Chemistry"),
    "organic compounds and functional groups": (
        "Chemistry",
        "Organic Chemistry",
    ),
    "organic synthesis and reactions": ("Chemistry", "Organic Chemistry"),
    "photochemistry (org.)": ("Chemistry", "Organic Chemistry"),
    "physical organic chemistry": ("Chemistry", "Organic Chemistry"),
    "process chemistry": ("Chemistry", "Chemical Engineering"),
    "stereochemistry": ("Chemistry", "Organic Chemistry"),
    "supramolecular chemistry (org.)": (
        "Chemistry",
        "Supramolecular Chemistry",
    ),
    "bioorganometallic chemistry": (
        "Chemistry",
        "Organometallic Chemistry",
    ),
    "bond activation": ("Chemistry", "Physical Chemistry"),
    "catalysis": ("Chemistry", "Catalysis"),
    "coordination chemistry (organomet.)": (
        "Chemistry",
        "Organometallic Chemistry",
    ),
    "electrochemistry - organometallic": (
        "Chemistry",
        "Electrochemistry",
    ),
    "kinetics and mechanism - organometallic reactions": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "ligand design": ("Chemistry", "Organometallic Chemistry"),
    "ligands (organomet.)": ("Chemistry", "Organometallic Chemistry"),
    "main group chemistry (organomet.)": (
        "Chemistry",
        "Organometallic Chemistry",
    ),
    "polymerization (organomet.)": ("Chemistry", "Organic Chemistry"),
    "reaction (organomet.)": ("Chemistry", "Organometallic Chemistry"),
    "small molecule activation (organomet.)": (
        "Chemistry",
        "Organometallic Chemistry",
    ),
    "spectroscopy (organomet.)": ("Chemistry", "Organometallic Chemistry"),
    "theory - organometallic": (
        "Chemistry",
        "Computational Chemistry",
    ),
    "transition metal complexes (organomet.)": (
        "Chemistry",
        "Organometallic Chemistry",
    ),
    "biophysical chemistry": ("Chemistry", "Physical Chemistry"),
    "chemical kinetics": ("Chemistry", "Physical Chemistry"),
    "clusters": ("Chemistry", "Physical Chemistry"),
    "crystallography": ("Chemistry", "Physical Chemistry"),
    "electrochemistry - mechanisms, theory & study": (
        "Chemistry",
        "Electrochemistry",
    ),
    "interfaces": ("Chemistry", "Physical Chemistry"),
    "optics": ("Physics", "Optics"),
    "photochemistry (physical chem.)": ("Chemistry", "Physical Chemistry"),
    "physical and chemical processes": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "physical and chemical properties": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "quantum mechanics": ("Chemistry", "Physical Chemistry"),
    "quasiparticles and excitations": ("Physics", "Condensed Matter"),
    "radiation": ("Chemistry", "Physical Chemistry"),
    "robotics": ("Engineering", "Robotics"),
    "self-assembly": (
        "Chemistry",
        "Supramolecular Chemistry",
    ),
    "solution chemistry": ("Chemistry", "Physical Chemistry"),
    "spectroscopy (physical chem.)": ("Chemistry", "Physical Chemistry"),
    "statistical mechanics": ("Physics", "Statistical Mechanics"),
    "structure": ("Chemistry", "Physical Chemistry"),
    "surface": ("Chemistry", "Surface Chemistry"),
    "thermodynamics (physical chem.)": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "transport phenomena (physical chem.)": (
        "Chemistry",
        "Physical Chemistry",
    ),
    "biopolymers": ("Chemistry", "Materials Science"),
    "cellulosic materials": ("Chemistry", "Materials Science"),
    "conducting polymers": ("Chemistry", "Materials Science"),
    "coordination polymers": ("Chemistry", "Materials Science"),
    "drug delivery systems": ("Chemistry", "Medicinal Chemistry"),
    "fluoropolymers": ("Chemistry", "Materials Science"),
    "hydrogels": ("Chemistry", "Materials Science"),
    "inorganic polymers": ("Chemistry", "Materials Science"),
    "organic polymers": ("Chemistry", "Materials Science"),
    "polyelectrolytes - materials": (
        "Chemistry",
        "Materials Science",
    ),
    "polyelectrolytes - polymers": ("Chemistry", "Materials Science"),
    "polymer blends": ("Chemistry", "Materials Science"),
    "polymer brushes": ("Chemistry", "Materials Science"),
    "polymer chains": ("Chemistry", "Materials Science"),
    "polymer morphology": ("Chemistry", "Materials Science"),
    "polymer scaffolds": ("Chemistry", "Materials Science"),
    "polymerization (polymers)": ("Chemistry", "Organic Chemistry"),
    "polymerization catalysts": ("Chemistry", "Catalysis"),
    "polymerization kinetics": ("Chemistry", "Physical Chemistry"),
    "artificial intelligence": (
        "Computer Science",
        "Artificial Intelligence",
    ),
    "chemoinformatics - computational chemistry": (
        "Chemistry",
        "Computational Chemistry",
    ),
    "computational chemistry and modeling": (
        "Chemistry",
        "Computational Chemistry",
    ),
    "machine learning": ("Computer Science", "Machine Learning"),
    "quantum computing": ("Computer Science", "Quantum Computing"),
    "theory - computational": ("Chemistry", "Computational Chemistry"),
    "feed": ("Chemistry", "Food Chemistry"),
    "food": ("Chemistry", "Food Chemistry"),
}
