"""
ChemRxiv category mappings to ResearchHub categories and subcategories.

Maps ChemRxiv's chemistry categories to ResearchHub's category structure.
"""

from typing import Dict, Optional, Tuple

CHEMRXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "agriculture and food chemistry": ("chemistry", "food-chemistry"),
    "analytical chemistry": ("chemistry", "analytical-chemistry"),
    "catalysis": ("chemistry", "catalysis"),
    "chemical education": ("chemistry", "chemical-education"),
    "energy": ("chemistry", "physics"),
    "inorganic chemistry": ("chemistry", "inorganic-chemistry"),
    "materials chemistry": ("chemistry", "materials-chemistry"),
    "materials science": ("engineering", "materials-science"),
    "nanoscience": ("chemistry", "nanochemistry"),
    "organic chemistry": ("chemistry", "organic-chemistry"),
    "organometallic chemistry": ("chemistry", "organometallic-chemistry"),
    "physical chemistry": ("chemistry", "physical-chemistry"),
    "polymer science": ("chemistry", "materials-science"),
    "analytical apparatus": ("chemistry", "analytical-chemistry"),
    "analytical chemistry - general": ("chemistry", "analytical-chemistry"),
    "biochemical analysis": ("biochemistry", "analytical-biochemistry"),
    "chemoinformatics": ("chemistry", "computational-chemistry"),
    "electrochemical analysis": ("electrochemistry", "analytical-chemistry"),
    "environmental analysis": ("chemistry", "environmental-chemistry"),
    "high-throughput screening": ("chemistry", "analytical-chemistry"),
    "imaging": ("chemistry", "analytical-chemistry"),
    "mass spectrometry": ("chemistry", "analytical-chemistry"),
    "microscopy": ("chemistry", "analytical-chemistry"),
    "separation science": ("chemistry", "analytical-chemistry"),
    "spectroscopy (anal. chem.)": ("chemistry", "analytical-chemistry"),
    "biochemistry": ("biology", "biochemistry"),
    "bioengineering and biotechnology": ("engineering", "bioengineering"),
    "biophysics": ("biology", "biophysics"),
    "cell and molecular biology": ("biology", "cell-biology"),
    "chemical biology": ("chemistry", "chemical-biology"),
    "drug discovery and drug delivery systems": ("chemistry", "medicinal-chemistry"),
    "environmental biology": ("biology", "ecology"),
    "microbiology": ("biology", "microbiology"),
    "plant biology": ("biology", "plant-biology"),
    "acid catalysis": ("chemistry", "catalysis"),
    "base catalysis": ("chemistry", "catalysis"),
    "biocatalysis": ("chemistry", "catalysis"),
    "electrocatalysis": ("chemistry", "catalysis"),
    "heterogeneous catalysis": ("chemistry", "catalysis"),
    "homogeneous catalysis": ("chemistry", "catalysis"),
    "organocatalysis": ("chemistry", "catalysis"),
    "photocatalysis": ("chemistry", "catalysis"),
    "redox catalysis": ("chemistry", "catalysis"),
    "chemical education - general": ("chemistry", "chemical-education"),
    "fluid mechanics": ("engineering", "chemical-engineering"),
    "industrial manufacturing": ("engineering", "chemical-engineering"),
    "natural resource recovery": ("engineering", "chemical-engineering"),
    "petrochemicals": ("engineering", "chemical-engineering"),
    "pharmaceutical industry": ("engineering", "chemical-engineering"),
    "process control": ("engineering", "chemical-engineering"),
    "quality control": ("engineering", "chemical-engineering"),
    "reaction engineering": ("engineering", "chemical-engineering"),
    "thermodynamics (chem. eng.)": ("engineering", "chemical-engineering"),
    "transport phenomena (chem. eng.)": ("engineering", "chemical-engineering"),
    "water purification": ("engineering", "chemical-engineering"),
    "atmospheric chemistry": ("chemistry", "environmental-chemistry"),
    "environmental science": ("chemistry", "environmental-chemistry"),
    "geochemistry": ("chemistry", "geochemistry"),
    "hydrology and water chemistry": ("chemistry", "environmental-chemistry"),
    "soil science": ("chemistry", "environmental-chemistry"),
    "space chemistry": ("chemistry", "astrochemistry"),
    "wastes": ("chemistry", "environmental-chemistry"),
    "energy storage": ("chemistry", "physics"),
    "fuel cells": ("chemistry", "electrochemistry"),
    "fuels - energy science": ("chemistry", "chemical-engineering"),
    "photovoltaics": ("chemistry", "materials-chemistry"),
    "power": ("chemistry", "physics"),
    "bioinorganic chemistry": ("chemistry", "inorganic-chemistry"),
    "bonding": ("chemistry", "inorganic-chemistry"),
    "coordination chemistry (inorg.)": ("chemistry", "inorganic-chemistry"),
    "electrochemistry": ("chemistry", "electrochemistry"),
    "frustrated lewis pairs": ("chemistry", "inorganic-chemistry"),
    "inorganic acid/base chemistry": ("chemistry", "inorganic-chemistry"),
    "lanthanides and actinides": ("chemistry", "inorganic-chemistry"),
    "ligands (inorg.)": ("chemistry", "inorganic-chemistry"),
    "magnetism": ("chemistry", "inorganic-chemistry"),
    "main group chemistry (inorg.)": ("chemistry", "inorganic-chemistry"),
    "minerals": ("chemistry", "inorganic-chemistry"),
    "nuclear chemistry": ("chemistry", "nuclear-chemistry"),
    "organometallic compounds": ("chemistry", "organometallic-chemistry"),
    "polymers": ("chemistry", "materials-science"),
    "reaction (inorg.)": ("chemistry", "inorganic-chemistry"),
    "sensors": ("chemistry", "analytical-chemistry"),
    "solid state chemistry": ("chemistry", "inorganic-chemistry"),
    "solvates": ("chemistry", "inorganic-chemistry"),
    "spectroscopy (inorg.)": ("chemistry", "inorganic-chemistry"),
    "theory - inorganic": ("chemistry", "computational-chemistry"),
    "aggregates and assemblies": ("chemistry", "supramolecular-chemistry"),
    "alloys": ("engineering", "materials-science"),
    "biocompatible materials": ("engineering", "bioengineering"),
    "biodegradable materials": ("chemistry", "materials-science"),
    "biological materials": ("bioengineering", "materials-science"),
    "carbon-based materials": ("chemistry", "materials-science"),
    "catalysts": ("chemistry", "catalysis"),
    "ceramics": ("engineering", "materials-science"),
    "coating materials": ("engineering", "materials-science"),
    "composites": ("engineering", "materials-science"),
    "conducting polymers": ("chemistry", "materials-science"),
    "controlled-release systems": ("chemistry", "chemical-engineering"),
    "coordination polymers": ("chemistry", "materials-science"),
    "core-shell materials": ("chemistry", "materials-chemistry"),
    "dyes and chromophores": ("chemistry", "organic-chemistry"),
    "elastic materials": ("engineering", "materials-science"),
    "fibers": ("engineering", "materials-science"),
    "fire-resistant materials": ("engineering", "materials-science"),
    "fuels - materials": ("chemistry", "materials-science"),
    "geological materials": ("chemistry", "geochemistry"),
    "granular materials": ("engineering", "materials-science"),
    "hydrogen storage materials": ("chemistry", "materials-science"),
    "imaging agents": ("chemistry", "medicinal-chemistry"),
    "liquid crystals": ("chemistry", "physics"),
    "magnetic materials": ("physics", "materials-science"),
    "materials processing": ("engineering", "materials-science"),
    "metamaterials": ("physics", "materials-science"),
    "multilayers": ("engineering", "materials-science"),
    "oligomers": ("chemistry", "organic-chemistry"),
    "optical materials": ("physics", "optics"),
    "photosensitizers": ("chemistry", "materials-chemistry"),
    "surfactants": ("chemistry", "chemical-engineering"),
    "thermal conductors and insulators": ("engineering", "materials-science"),
    "thin films": ("engineering", "materials-science"),
    "nanodevices": ("chemistry", "nanochemistry"),
    "nanofabrication": ("chemistry", "nanochemistry"),
    "nanofluidics": ("chemistry", "nanochemistry"),
    "bioorganic chemistry": ("chemistry", "biochemistry"),
    "combinatorial chemistry": ("chemistry", "medicinal-chemistry"),
    "crystallography – organic": ("chemistry", "organic-chemistry"),
    "natural products": ("chemistry", "organic-chemistry"),
    "organic synthesis and reactions": ("chemistry", "organic-chemistry"),
    "photochemistry (org.)": ("chemistry", "organic-chemistry"),
    "physical organic chemistry": ("chemistry", "organic-chemistry"),
    "process chemistry": ("chemistry", "chemical-engineering"),
    "stereochemistry": ("chemistry", "organic-chemistry"),
    "bond activation": ("chemistry", "physical-chemistry"),
    "catalysis": ("chemistry", "catalysis"),
    "ligand design": ("chemistry", "organometallic-chemistry"),
    "ligands (organomet.)": ("chemistry", "organometallic-chemistry"),
    "polymerization (organomet.)": ("chemistry", "organic-chemistry"),
    "reaction (organomet.)": ("chemistry", "organometallic-chemistry"),
    "spectroscopy (organomet.)": ("chemistry", "organometallic-chemistry"),
    "biophysical chemistry": ("chemistry", "physical-chemistry"),
    "chemical kinetics": ("chemistry", "physical-chemistry"),
    "clusters": ("chemistry", "physical-chemistry"),
    "crystallography": ("chemistry", "physical-chemistry"),
    "interfaces": ("chemistry", "physical-chemistry"),
    "optics": ("physics", "optics"),
    "photochemistry (physical chem.)": ("chemistry", "physical-chemistry"),
    "quantum mechanics": ("chemistry", "physical-chemistry"),
    "quasiparticles and excitations": ("physics", "condensed-matter"),
    "radiation": ("chemistry", "physical-chemistry"),
    "robotics": ("engineering", "robotics"),
    "solution chemistry": ("chemistry", "physical-chemistry"),
    "spectroscopy (physical chem.)": ("chemistry", "physical-chemistry"),
    "statistical mechanics": ("physics", "statistical-mechanics"),
    "structure": ("chemistry", "physical-chemistry"),
    "surface": ("chemistry", "surface-chemistry"),
    "biopolymers": ("chemistry", "materials-science"),
    "cellulosic materials": ("chemistry", "materials-science"),
    "conducting polymers": ("chemistry", "materials-science"),
    "coordination polymers": ("chemistry", "materials-science"),
    "drug delivery systems": ("chemistry", "medicinal-chemistry"),
    "fluoropolymers": ("chemistry", "materials-science"),
    "hydrogels": ("chemistry", "materials-science"),
    "inorganic polymers": ("chemistry", "materials-science"),
    "organic polymers": ("chemistry", "materials-science"),
    "polyelectrolytes - polymers": ("chemistry", "materials-science"),
    "polymer blends": ("chemistry", "materials-science"),
    "polymer brushes": ("chemistry", "materials-science"),
    "polymer chains": ("chemistry", "materials-science"),
    "polymer morphology": ("chemistry", "materials-science"),
    "polymer scaffolds": ("chemistry", "materials-science"),
    "polymerization (polymers)": ("chemistry", "organic-chemistry"),
    "polymerization catalysts": ("chemistry", "catalysis"),
    "polymerization kinetics": ("chemistry", "physical-chemistry"),
    "machine learning": ("computer-science", "machine-learning"),
    "quantum computing": ("computer-science", "quantum-computing"),
    "theory - computational": ("chemistry", "computational-chemistry"),
    "feed": ("chemistry", "food-chemistry"),
    "food": ("chemistry", "food-chemistry"),
}
