"""
Master list of ResearchHub categories and subcategories.
This provides a single source of truth for all category mappings.
"""

from typing import Dict, List, Optional

# Master category and subcategory structure
# Format: {
#     "Category Name": [
#         "Subcategory 1",
#         "Subcategory 2",
#         ...
#     ]
# }
RESEARCHHUB_CATEGORIES: Dict[str, List[str]] = {
    "Biology": [
        "Biochemistry",
        "Bioinformatics",
        "Biophysics",
        "Cancer Biology",
        "Cell Biology",
        "Developmental Biology",
        "Ecology",
        "Evolutionary Biology",
        "Genetics",
        "Genomics",
        "Immunology",
        "Microbiology",
        "Molecular Biology",
        "Neuroscience",
        "Paleontology",
        "Pathology",
        "Pharmacology",
        "Physiology",
        "Plant Biology",
        "Systems Biology",
        "Synthetic Biology",
        "Toxicology",
        "Zoology",
    ],
    "Medicine": [
        "Clinical Trials",
        "Epidemiology",
        "Medical Physics",
        "Public Health",
        "Translational Medicine",
    ],
    "Computer Science": [
        "Artificial Intelligence",
        "Computational Complexity",
        "Computational Engineering",
        "Computational Geometry",
        "Computer Vision",
        "Cryptography and Security",
        "Data Structures and Algorithms",
        "Databases",
        "Distributed Computing",
        "Formal Languages",
        "Game Theory",
        "Graphics",
        "Hardware Architecture",
        "Human-Computer Interaction",
        "Information Retrieval",
        "Information Theory",
        "Logic",
        "Machine Learning",
        "Natural Language Processing",
        "Neural Computing",
        "Networking",
        "Operating Systems",
        "Programming Languages",
        "Robotics",
        "Software Engineering",
        "Sound",
    ],
    "Physics": [
        "Astrophysics",
        "Atomic Physics",
        "Chemical Physics",
        "Computational Physics",
        "Condensed Matter",
        "Cosmology",
        "Fluid Dynamics",
        "General Relativity",
        "Geophysics",
        "High Energy Experiment",
        "High Energy Phenomenology",
        "High Energy Theory",
        "Instrumentation",
        "Lattice Physics",
        "Mathematical Physics",
        "Nuclear Experiment",
        "Nuclear Theory",
        "Optics",
        "Plasma Physics",
        "Quantum Physics",
        "Statistical Mechanics",
    ],
    "Mathematics": [
        "Algebraic Geometry",
        "Algebraic Topology",
        "Analysis of PDEs",
        "Category Theory",
        "Classical Analysis",
        "Combinatorics",
        "Commutative Algebra",
        "Complex Variables",
        "Differential Geometry",
        "Discrete Mathematics",
        "Dynamical Systems",
        "Functional Analysis",
        "General Mathematics",
        "General Topology",
        "Geometric Topology",
        "Group Theory",
        "History and Overview",
        "Information Theory",
        "K-Theory",
        "Logic",
        "Metric Geometry",
        "Number Theory",
        "Numerical Analysis",
        "Operator Algebras",
        "Optimization and Control",
        "Probability",
        "Quantum Algebra",
        "Representation Theory",
        "Rings and Algebras",
        "Spectral Theory",
        "Statistics Theory",
        "Symplectic Geometry",
    ],
    "Chemistry": [
        "Chemical Physics",
        "Organic Chemistry",
        "Inorganic Chemistry",
        "Physical Chemistry",
        "Analytical Chemistry",
    ],
    "Engineering": [
        "Audio and Speech Processing",
        "Bioengineering",
        "Computational Engineering",
        "Image and Video Processing",
        "Signal Processing",
        "Systems and Control",
    ],
    "Economics": [
        "Computational Finance",
        "Econometrics",
        "Economic Theory",
        "Financial Economics",
        "General Economics",
        "General Finance",
        "Mathematical Finance",
        "Portfolio Management",
        "Quantitative Finance",
        "Risk Management",
        "Securities Pricing",
        "Statistical Finance",
        "Trading and Market Microstructure",
    ],
    "Statistics": [
        "Applications",
        "Computation",
        "Machine Learning",
        "Methodology",
        "Statistics Theory",
    ],
    "Social Sciences": [
        "Physics and Society",
        "Scientific Communication and Education",
    ],
}
