"""
MedRxiv to ResearchHub category mappings.
Maps MedRxiv subject areas to ResearchHub categories and subcategories.
"""

from typing import Dict, Optional, Tuple

MEDRXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "addiction medicine": ("medicine", "psychiatry"),
    "allergy and immunology": ("medicine", "immunology"),
    "anesthesia": ("medicine", "anesthesiology"),
    "cardiovascular medicine": ("medicine", "cardiology"),
    "dentistry and oral medicine": ("medicine", "dentistry"),
    "dermatology": ("medicine", "dermatology"),
    "emergency medicine": ("medicine", "emergency-medicine"),
    "endocrinology (including diabetes mellitus and metabolic disease)": (
        "medicine",
        "endocrinology",
    ),
    "epidemiology": ("medicine", "epidemiology"),
    "forensic medicine": ("biology", "pathology"),
    "gastroenterology": ("medicine", "gastroenterology"),
    "genetic and genomic medicine": ("biology", "genetics-and-genomics"),
    "geriatric medicine": ("medicine", "internal-medicine"),
    "health economics": ("medicine", "health-economics"),
    "health informatics": ("medicine", "health-informatics"),
    "health policy": ("medicine", "health-policy"),
    "health systems and quality improvement": ("medicine", "health-policy"),
    "hematology": ("medicine", "hematology"),
    "hiv/aids": ("medicine", "infectious-disease"),
    "infectious diseases (except hiv/aids)": ("medicine", "infectious-disease"),
    "intensive care and critical care medicine": ("medicine", "critical-care-medicine"),
    "medical education": ("medicine", "medical-education"),
    "medical ethics": ("medicine", "medical-ethics"),
    "nephrology": ("medicine", "nephrology"),
    "neurology": ("medicine", "neurology"),
    "nursing": ("medicine", "nursing"),
    "nutrition": ("medicine", "nutrition"),
    "obstetrics and gynecology": ("medicine", "obstetrics-and-gynecology"),
    "occupational and environmental health": ("medicine", "public-health"),
    "oncology": ("medicine", "oncology"),
    "ophthalmology": ("medicine", "ophthalmology"),
    "orthopedics": ("medicine", "orthopedics"),
    "otolaryngology": ("medicine", "otolaryngology"),
    "pain medicine": ("medicine", "pain-medicine"),
    "palliative medicine": ("medicine", "palliative-medicine"),
    "pathology": ("biology", "pathology"),
    "pediatrics": ("medicine", "pediatrics"),
    "pharmacology and therapeutics": ("medicine", "pharmacology"),
    "primary care research": ("medicine", "internal-medicine"),
    "psychiatry and clinical psychology": ("medicine", "psychiatry"),
    "public and global health": ("medicine", "public-health"),
    "radiology and imaging": ("medicine", "radiology"),
    "rehabilitation medicine and physical therapy": (
        "medicine",
        "physical-therapy",
    ),
    "respiratory medicine": ("medicine", "pulmonology"),
    "rheumatology": ("medicine", "rheumatology"),
    "sexual and reproductive health": ("medicine", "reproductive-health"),
    "sports medicine": ("medicine", "sports-medicine"),
    "surgery": ("medicine", "surgery"),
    "toxicology": ("biology", "pharmacology"),
    "transplantation": ("medicine", "surgery"),
    "urology": ("medicine", "urology"),
}
