"""
MedRxiv to ResearchHub category mappings.
Maps MedRxiv subject areas to ResearchHub categories and subcategories.
"""

from typing import Dict, Optional, Tuple

MEDRXIV_MAPPINGS: Dict[str, Tuple[str, Optional[str]]] = {
    "addiction medicine": ("Medicine", "Psychiatry"),
    "allergy and immunology": ("Medicine", "Immunology"),
    "anesthesia": ("Medicine", "Anesthesiology"),
    "cardiovascular medicine": ("Medicine", "Cardiology"),
    "dentistry and oral medicine": ("Medicine", "Dentistry"),
    "dermatology": ("Medicine", "Dermatology"),
    "emergency medicine": ("Medicine", "Emergency Medicine"),
    "endocrinology (including diabetes mellitus and metabolic disease)": (
        "Medicine",
        "Endocrinology",
    ),
    "epidemiology": ("Medicine", "Epidemiology"),
    "forensic medicine": ("Biology", "Forensic Medicine"),
    "gastroenterology": ("Medicine", "Gastroenterology"),
    "genetic and genomic medicine": ("Medicine", "Genetics and Genomics"),
    "geriatric medicine": ("Medicine", "Internal Medicine"),
    "health economics": ("Medicine", "Health Economics"),
    "health informatics": ("Medicine", "Health Informatics"),
    "health policy": ("Medicine", "Health Policy"),
    "health systems and quality improvement": ("Medicine", "Health Policy"),
    "hematology": ("Medicine", "Hematology"),
    "hiv/aids": ("Medicine", "Infectious Disease"),
    "infectious diseases (except hiv/aids)": ("Medicine", "Infectious Disease"),
    "intensive care and critical care medicine": ("Medicine", "Critical Care Medicine"),
    "medical education": ("Medicine", "Medical Education"),
    "medical ethics": ("Medicine", "Medical Ethics"),
    "nephrology": ("Medicine", "Nephrology"),
    "neurology": ("Medicine", "Neurology"),
    "nursing": ("Medicine", "Nursing"),
    "nutrition": ("Medicine", "Nutrition"),
    "obstetrics and gynecology": ("Medicine", "Reproductive Health"),
    "occupational and environmental health": ("Medicine", "Public Health"),
    "oncology": ("Medicine", "Oncology"),
    "ophthalmology": ("Medicine", "Ophthalmology"),
    "orthopedics": ("Medicine", "Surgery"),
    "otolaryngology": ("Medicine", "Surgery"),
    "pain medicine": ("Medicine", "Pain Medicine"),
    "palliative medicine": ("Medicine", "Oncology"),
    "pathology": ("Biology", "Pathology"),
    "pediatrics": ("Medicine", "Pediatrics"),
    "pharmacology and therapeutics": ("Medicine", "Pharmacology"),
    "primary care research": ("Medicine", "Internal Medicine"),
    "psychiatry and clinical psychology": ("Medicine", "Psychiatry"),
    "public and global health": ("Medicine", "Public Health"),
    "radiology and imaging": ("Medicine", "Radiology"),
    "rehabilitation medicine and physical therapy": (
        "Medicine",
        "Physical Therapy",
    ),
    "respiratory medicine": ("Medicine", "Pulmonology"),
    "rheumatology": ("Medicine", "Rheumatology"),
    "sexual and reproductive health": ("Medicine", "Reproductive Health"),
    "sports medicine": ("Medicine", "Sports Medicine"),
    "surgery": ("Medicine", "Surgery"),
    "toxicology": ("Biology", "Pharmacology"),
    "transplantation": ("Medicine", "Surgery"),
    "urology": ("Medicine", "Urology"),
}
