ABUSIVE_OR_RUDE = "ABUSIVE_OR_RUDE"
COPY_RIGHT = "COPY_RIGHT"
LOW_QUALITY = "LOW_QUALITY"
NOT_CONSTRUCTIVE = "NOT_CONSTRUCTIVE"
PLAGIARISM = "PLAGIARISM"
SPAM = "SPAM"

FLAG_REASON_CHOICES = [
    (ABUSIVE_OR_RUDE, ABUSIVE_OR_RUDE),
    (COPY_RIGHT, COPY_RIGHT),
    (LOW_QUALITY, LOW_QUALITY),
    (NOT_CONSTRUCTIVE, NOT_CONSTRUCTIVE),
    (PLAGIARISM, PLAGIARISM),
    (SPAM, SPAM),
]
