ABUSIVE_OR_RUDE = "ABUSIVE_OR_RUDE"
COPYRIGHT = "COPYRIGHT"
LOW_QUALITY = "LOW_QUALITY"
NOT_CONSTRUCTIVE = "NOT_CONSTRUCTIVE"
PLAGIARISM = "PLAGIARISM"
SPAM = "SPAM"
NOT_SPECIFIED = "NOT_SPECIFIED"

FLAG_REASON_CHOICES = [
    (ABUSIVE_OR_RUDE, ABUSIVE_OR_RUDE),
    (COPYRIGHT, COPYRIGHT),
    (LOW_QUALITY, LOW_QUALITY),
    (NOT_CONSTRUCTIVE, NOT_CONSTRUCTIVE),
    (PLAGIARISM, PLAGIARISM),
    (SPAM, SPAM),
    (NOT_SPECIFIED, NOT_SPECIFIED),
]

# User-specific flag reasons (for flagging user accounts)
SPAM_ACCOUNT = "SPAM_ACCOUNT"
FAKE_IDENTITY = "FAKE_IDENTITY"
HARASSMENT = "HARASSMENT"
POLICY_VIOLATION = "POLICY_VIOLATION"
SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"
OTHER = "OTHER"

USER_FLAG_REASON_CHOICES = [
    (SPAM_ACCOUNT, SPAM_ACCOUNT),
    (FAKE_IDENTITY, FAKE_IDENTITY),
    (HARASSMENT, HARASSMENT),
    (POLICY_VIOLATION, POLICY_VIOLATION),
    (SUSPICIOUS_ACTIVITY, SUSPICIOUS_ACTIVITY),
    (OTHER, OTHER),
]

# Set for O(1) validation lookups
USER_FLAG_REASONS = frozenset({
    SPAM_ACCOUNT,
    FAKE_IDENTITY,
    HARASSMENT,
    POLICY_VIOLATION,
    SUSPICIOUS_ACTIVITY,
    OTHER,
})

# Verdict choices include both content and user flag reasons, plus their NOT_ variants
VERDICT_REASON_CHOICES = (
    FLAG_REASON_CHOICES
    + [(f"NOT_{tup[0]}", f"NOT_{tup[0]}") for tup in FLAG_REASON_CHOICES]
    + USER_FLAG_REASON_CHOICES
    + [(f"NOT_{tup[0]}", f"NOT_{tup[0]}") for tup in USER_FLAG_REASON_CHOICES]
)

VERDICT_OPEN = "OPEN"
VERDICT_APPROVED = "APPROVED"
VERDICT_REMOVED = "REMOVED"

VERDICT_FILTER_CHOICES = (
    (VERDICT_OPEN, VERDICT_OPEN),
    (VERDICT_APPROVED, VERDICT_APPROVED),
    (VERDICT_REMOVED, VERDICT_REMOVED),
)
