# Generated by Django 2.2 on 2022-04-03 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussion', '0041_auto_20211006_0640'),
        ('note', '0005_notetemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchhub_document', '0030_researchhubpost_doi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('unified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='REQUESTED', max_length=32)),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_requested', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CHANGES_REQUESTED', 'CHANGES_REQUESTED')], default='PENDING', max_length=32)),
                ('discussion_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_review', to='discussion.Thread')),
                ('doc_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_review_decisions', to='note.NoteContent')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='peer_review.PeerReview')),
                ('unified_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchhub_document.ResearchhubUnifiedDocument')),
            ],
        ),
    ]
