# Generated by Django 2.2 on 2022-04-03 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_notetemplate'),
        ('researchhub_document', '0030_researchhubpost_doi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreviewrequest',
            name='invited_by_user',
        ),
        migrations.RemoveField(
            model_name='peerreviewrequest',
            name='invited_user',
        ),
        migrations.AddField(
            model_name='peerreviewrequest',
            name='doc_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.NoteContent'),
        ),
        migrations.AddField(
            model_name='peerreviewrequest',
            name='requested_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerreviewrequest',
            name='unified_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_requests', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
        migrations.AlterField(
            model_name='peerreviewrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=32),
        ),
    ]
