# Generated by Django 2.2 on 2022-04-05 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peer_review', '0004_auto_20220405_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'INVITED'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='INVITED', max_length=32)),
                ('invited_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_users_invited', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_invites', to=settings.AUTH_USER_MODEL)),
                ('peer_review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='peer_review.PeerReviewRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
