# Generated by Django 2.2 on 2022-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0006_auto_20220405_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreviewinvite',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
