# Generated by Django 2.2 on 2022-04-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0010_auto_20220408_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreviewrequest',
            name='peer_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_requests', to='peer_review.PeerReviewRequest'),
        ),
    ]
