# Generated by Django 2.2 on 2022-04-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0012_auto_20220409_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewdecision',
            name='discussion_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_review_decision', to='discussion.Thread'),
        ),
    ]
