# Generated by Django 2.2 on 2022-04-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0013_auto_20220411_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewdecision',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('CHANGES_REQUESTED', 'CHANGES_REQUESTED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='peerreviewdecision',
            name='doc_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_review_decisions', to='note.NoteContent'),
        ),
    ]
