# Generated by Django 2.2 on 2022-04-11 19:13

import datetime
from datetime import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0014_auto_20220411_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 11, 19, 13, 37, 381105, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peerreviewdecision',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 11, 19, 13, 43, 130029, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerreviewdecision',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
