# Generated by Django 2.2 on 2022-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0015_auto_20220411_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreviewinvite',
            name='peer_review_request',
        ),
        migrations.AddField(
            model_name='peerreviewinvite',
            name='peer_review_request',
            field=models.ManyToManyField(related_name='invites', to='peer_review.PeerReviewRequest'),
        ),
    ]
