# Generated by Django 2.2 on 2022-04-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0016_auto_20220417_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreviewinvite',
            name='peer_review_request',
        ),
        migrations.AddField(
            model_name='peerreviewinvite',
            name='peer_review_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='peer_review.PeerReviewRequest'),
            preserve_default=False,
        ),
    ]
