# Generated by Django 2.2 on 2022-04-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0017_auto_20220417_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewinvite',
            name='peer_review_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.PeerReviewRequest'),
        ),
    ]
