# Generated by Django 2.2 on 2022-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0018_auto_20220422_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewdecision',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewdecision',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewinvite',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewinvite',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='peerreviewrequest',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
