# Generated by Django 2.2 on 2022-04-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0018_auto_20220419_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='unified_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_reviews', to='researchhub_document.ResearchhubUnifiedDocument'),
        ),
    ]
