# Generated by Django 4.2.15 on 2024-08-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0057_remove_thread_peer_review"),
        ("peer_review", "0019_alter_peerreviewinvite_inviter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peerreviewdecision",
            name="discussion_thread",
        ),
        migrations.RemoveField(
            model_name="peerreviewdecision",
            name="doc_version",
        ),
        migrations.RemoveField(
            model_name="peerreviewdecision",
            name="peer_review",
        ),
        migrations.RemoveField(
            model_name="peerreviewdecision",
            name="unified_document",
        ),
        migrations.RemoveField(
            model_name="peerreviewinvite",
            name="inviter",
        ),
        migrations.RemoveField(
            model_name="peerreviewinvite",
            name="peer_review_request",
        ),
        migrations.RemoveField(
            model_name="peerreviewinvite",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="peerreviewrequest",
            name="doc_version",
        ),
        migrations.RemoveField(
            model_name="peerreviewrequest",
            name="peer_review",
        ),
        migrations.RemoveField(
            model_name="peerreviewrequest",
            name="requested_by_user",
        ),
        migrations.RemoveField(
            model_name="peerreviewrequest",
            name="unified_document",
        ),
        migrations.DeleteModel(
            name="PeerReview",
        ),
        migrations.DeleteModel(
            name="PeerReviewDecision",
        ),
        migrations.DeleteModel(
            name="PeerReviewInvite",
        ),
        migrations.DeleteModel(
            name="PeerReviewRequest",
        ),
    ]
