scopus_to_rh_map = {
    'Multidisciplinary': 'Multidisciplinary Science',
    'General Agricultural and Biological Sciences': 'Botany',
    'Agricultural and Biological Sciences (miscellaneous)': 'Botany',
    'Agronomy and Crop Science': 'Botany',
    'Animal Science and Zoology': 'Zoology',
    'Aquatic Science': 'Zoology',
    'Ecology, Evolution, Behavior and Systematics': 'Evolutionary Biology',
    'Food Science': 'Nutrition',
    'Forestry': 'Ecology',
    'Horticulture': 'Botany',
    'Insect Science': 'Zoology',
    'Plant Science': 'Botany',
    'Soil Science': 'Ecology',
    'General Arts and Humanities': 'Art',
    'Arts and Humanities (miscellaneous)': 'Art',
    'History': 'History',
    'Language and Linguistics': 'Anthropology',
    'Archaeology': 'Geology',
    'Classics': 'Literature',
    'Conservation': 'Ecology',
    'History and Philosophy of Science': 'Metascience',
    'Literature and Literary Theory': 'Literature',
    'Museology': 'Anthropology',
    'Music': 'Art',
    'Philosophy': 'Philosophy',
    'Religious studies': 'Anthropology',
    'Visual Arts and Performing Arts': 'Art',
    'General Biochemistry, Genetics and Molecular Biology': 'Molecular Biology',
    'Biochemistry, Genetics and Molecular Biology (miscellaneous)': 'Molecular Biology',
    'Ageing': 'Longevity',
    'Biochemistry': 'Biochemistry',
    'Biophysics': 'Biophysics',
    'Biotechnology': 'Biotechnology',
    'Cancer Research': 'Oncology',
    'Cell Biology': 'Cell Biology',
    'Clinical Biochemistry': 'Biochemistry',
    'Developmental Biology': 'Developmental Biology',
    'Endocrinology': 'Endocrinology',
    'Genetics': 'Genetics',
    'Molecular Biology': 'Molecular Biology',
    'Molecular Medicine': 'Medicine',
    'Physiology': 'Physiology',
    'Structural Biology': 'Biology',
    'General Business, Management and Accounting': 'Business ',
    'Business, Management and Accounting (miscellaneous)': 'Business',
    'Accounting': 'Business',
    'Business and International Management': 'Business',
    'Management Information Systems': 'Business',
    'Management of Technology and Innovation': 'Business',
    'Marketing': 'Business',
    'Organizational Behavior and Human Resource Management': 'Psychology',
    'Strategy and Management': 'Business ',
    'Tourism, Leisure and Hospitality Management': 'Business ',
    'Industrial relations': 'Business ',
    'General Chemical Engineering': 'Chemical Engineering',
    'Chemical Engineering (miscellaneous)': 'Chemical Engineering',
    'Bioengineering': 'Biotechnology',
    'Catalysis': 'Biochemistry',
    'Chemical Health and Safety': 'Pharmacology',
    'Colloid and Surface Chemistry': 'Chemistry',
    'Filtration and Separation': 'Physics',
    'Fluid Flow and Transfer Processes': 'Fluid Dynamics',
    'Process Chemistry and Technology': 'Chemistry',
    'General Chemistry': 'Chemistry',
    'Chemistry (miscellaneous)': 'Chemistry',
    'Analytical Chemistry': 'Analytical Chemistry',
    'Electrochemistry': 'Chemistry',
    'Inorganic Chemistry': 'Chemistry',
    'Organic Chemistry': 'Chemistry',
    'Physical and Theoretical Chemistry': 'Chemistry',
    'Spectroscopy': 'Methodology',
    'General Computer Science': 'Computer Science',
    'Computer Science (miscellaneous)': 'Computer Science',
    'Artificial Intelligence': 'Artificial Intelligence',
    'Computational Theory and Mathematics': 'Computer Science',
    'Computer Graphics and Computer-Aided Design': 'Computer Science',
    'Computer Networks and Communications': 'Distributed Computing',
    'Computer Science Applications': 'Computer Science',
    'Computer Vision and Pattern Recognition': 'Computer Science',
    'Hardware and Architecture': 'Engineering',
    'Human-Computer Interaction': 'Human-Computer Interaction',
    'Information Systems': 'Computer Science',
    'Signal Processing': 'Methodology',
    'Software': 'Computer Science',
    'General Decision Sciences': 'Business',
    'Decision Sciences (miscellaneous)': 'Business',
    'Information Systems and Management': 'Business',
    'Management Science and Operations Research': 'Business',
    'Statistics, Probability and Uncertainty': 'Statistics',
    'General Earth and Planetary Sciences': 'Geology',
    'Earth and Planetary Sciences (miscellaneous)': 'Geology',
    'Atmospheric Science': 'Environmental Science',
    'Computers in Earth Sciences': 'Computer Science',
    'Earth-Surface Processes': 'Geology',
    'Economic Geology': 'Geology',
    'Geochemistry and Petrology': 'Geology',
    'Geology': 'Geology',
    'Geophysics': 'Geology',
    'Geotechnical Engineering and Engineering Geology': 'Geology',
    'Oceanography': 'Ecology',
    'Palaeontology': 'Biology',
    'Space and Planetary Science': 'Astrophysics',
    'Stratigraphy': 'Geology',
    'General Economics, Econometrics and Finance': 'Economics',
    'Economics, Econometrics and Finance (miscellaneous)': 'Economics',
    'Economics and Econometrics': 'Economics',
    'Finance': 'Finance',
    'General Energy': 'Physics',
    'Energy (miscellaneous)': 'Physics',
    'Energy Engineering and Power Technology': 'Engineering',
    'Fuel Technology': 'Engineering',
    'Nuclear Energy and Engineering': 'Nuclear Physics',
    'Renewable Energy, Sustainability and the Environment': 'Environmental Science',
    'General Engineering': 'Engineering',
    'Engineering (miscellaneous)': 'Engineering',
    'Aerospace Engineering': 'Engineering',
    'Automotive Engineering': 'Engineering',
    'Biomedical Engineering': 'Bioengineering',
    'Civil and Structural Engineering': 'Engineering',
    'Computational Mechanics': 'Computer Science',
    'Control and Systems Engineering': 'Engineering',
    'Electrical and Electronic Engineering': 'Engineering',
    'Industrial and Manufacturing Engineering': 'Engineering',
    'Mechanical Engineering': 'Engineering',
    'Mechanics of Materials': 'Materials Science',
    'Ocean Engineering': 'Engineering',
    'Safety, Risk, Reliability and Quality': 'Business',
    'Media Technology': 'Anthropology',
    'Building and Construction': 'Business',
    'Architecture ': 'Architecture',
    'General Environmental Science': 'Environmental Science',
    'Environmental Science (miscellaneous)': 'Environmental Science',
    'Ecological Modelling': 'Ecology',
    'Ecology': 'Ecology',
    'Environmental Chemistry': 'Environmental Science',
    'Environmental Engineering': 'Environmental Science',
    'Global and Planetary Change': 'Environmental Science',
    'Health, Toxicology and Mutagenesis': 'Pharmacology',
    'Management, Monitoring, Policy and Law': 'Business',
    'Nature and Landscape Conservation': 'Environmental Science',
    'Pollution': 'Environmental Science',
    'Waste Management and Disposal': 'Environmental Science',
    'Water Science and Technology': 'Environmental Science',
    'General Immunology and Microbiology': 'Immunology',
    'Immunology and Microbiology (miscellaneous) ': 'Immunology',
    'Applied Microbiology and Biotechnology': 'Biotechnology',
    'Immunology': 'Immunology',
    'Microbiology': 'Microbiology',
    'Parasitology': 'Microbiology',
    'Virology': 'Microbiology',
    'General Materials Science': 'Materials Science',
    'Materials Science (miscellaneous)': 'Materials Science',
    'Biomaterials': 'Materials Science',
    'Ceramics and Composites': 'Materials Science',
    'Electronic, Optical and Magnetic Materials': 'Materials Science',
    'Materials Chemistry': 'Materials Science',
    'Metals and Alloys': 'Materials Science',
    'Polymers and Plastics': 'Materials Science',
    'Surfaces, Coatings and Films': 'Materials Science',
    'General Mathematics': 'Mathematics',
    'Mathematics (miscellaneous)': 'Mathematics',
    'Algebra and Number Theory': 'Mathematics',
    'Analysis': 'Mathematics',
    'Applied Mathematics': 'Mathematics',
    'Computational Mathematics': 'Mathematics',
    'Control and Optimization': 'Mathematics',
    'Discrete Mathematics and Combinatorics': 'Mathematics',
    'Geometry and Topology': 'Mathematics',
    'Logic': 'Logic',
    'Mathematical Physics': 'Mathematics',
    'Modelling and Simulation': 'Mathematics',
    'Numerical Analysis': 'Mathematics',
    'Statistics and Probability': 'Statistics',
    'Theoretical Computer Science': 'Computer Science',
    'General Medicine': 'Medicine',
    'Medicine (miscellaneous)': 'Medicine',
    'Anatomy': 'Physiology',
    'Anesthesiology and Pain Medicine': 'Anesthesiology',
    'Biochemistry, medical': 'Biochemistry',
    'Cardiology and Cardiovascular Medicine': 'Medicine',
    'Critical Care and Intensive Care Medicine': 'Medicine',
    'Complementary and alternative medicine': 'Medicine',
    'Dermatology': 'Medicine',
    'Drug guides': 'Pharmacology',
    'Embryology': 'Developmental Biology',
    'Emergency Medicine': 'Medicine',
    'Endocrinology, Diabetes and Metabolism': 'Endocrinology',
    'Epidemiology': 'Epidemiology',
    'Family Practice': 'Medicine',
    'Gastroenterology': 'Medicine',
    'Genetics(clinical)': 'Genetics',
    'Geriatrics and Gerontology': 'Medicine',
    'Health Informatics': 'Bioinformatics',
    'Health Policy': 'Medicine',
    'Hematology': 'Medicine',
    'Hepatology': 'Medicine',
    'Histology': 'Medicine',
    'Immunology and Allergy': 'Immunology',
    'Internal Medicine': 'Medicine',
    'Infectious Diseases': 'Medicine',
    'Microbiology (medical)': 'Microbiology',
    'Nephrology': 'Medicine',
    'Clinical Neurology': 'Neuroscience',
    'Obstetrics and Gynaecology': 'Medicine',
    'Oncology': 'Oncology',
    'Ophthalmology': 'Medicine',
    'Orthopedics and Sports Medicine': 'Medicine',
    'Otorhinolaryngology': 'Medicine',
    'Pathology and Forensic Medicine': 'Pathology',
    'Pediatrics, Perinatology, and Child Health': 'Medicine',
    'Pharmacology (medical)': 'Pharmacology',
    'Physiology (medical)': 'Physiology',
    'Psychiatry and Mental health': 'Psychiatry',
    'Public Health, Environmental and Occupational Health': 'Epidemiology',
    'Pulmonary and Respiratory Medicine': 'Medicine',
    'Radiology Nuclear Medicine and imaging': 'Medicine',
    'Rehabilitation': 'Medicine',
    'Reproductive Medicine': 'Medicine',
    'Reviews and References, Medical': 'Medicine',
    'Rheumatology': 'Medicine',
    'Surgery': 'Medicine',
    'Transplantation': 'Medicine',
    'Urology': 'Medicine',
    'General Neuroscience': 'Neuroscience',
    'Neuroscience (miscellaneous)': 'Neuroscience',
    'Behavioral Neuroscience': 'Psychology',
    'Biological Psychiatry': 'Psychiatry',
    'Cellular and Molecular Neuroscience': 'Neuroscience',
    'Cognitive Neuroscience': 'Neuroscience',
    'Developmental Neuroscience': 'Developmental Biology',
    'Endocrine and Autonomic Systems': 'Endocrinology',
    'Neurology': 'Neuroscience',
    'Sensory Systems': 'Neuroscience',
    'General Nursing': 'Medicine',
    'Nursing (miscellaneous)': 'Medicine',
    'Advanced and Specialised Nursing': 'Medicine',
    'Assessment and Diagnosis': 'Medicine',
    'Care Planning': 'Medicine',
    'Community and Home Care': 'Medicine',
    'Critical Care': 'Medicine',
    'Emergency': 'Medicine',
    'Fundamentals and skills': 'Medicine',
    'Gerontology': 'Medicine',
    'Issues, ethics and legal aspects': 'Medicine',
    'Leadership and Management': 'Business',
    'LPN and LVN': 'Medicine',
    'Maternity and Midwifery': 'Medicine',
    'Medical‚ÄìSurgical': 'Medicine',
    'Nurse Assisting': 'Medicie',
    'Nutrition and Dietetics': 'Nutrition',
    'Oncology(nursing)': 'Oncology',
    'Pathophysiology': 'Pathology',
    'Pediatrics': 'Medicine',
    'Pharmacology (nursing)': 'Pharmacology',
    'Phychiatric Mental Health': 'Psychiatry',
    'Research and Theory': 'Metascience',
    'Review and Exam Preparation': 'Education',
    'General Pharmacology, Toxicology and Pharmaceutics': 'Pharmacology',
    'Pharmacology, Toxicology and Pharmaceutics (miscellaneous)': 'Pharmacology',
    'Drug Discovery': 'Pharmacology',
    'Pharmaceutical Science': 'Pharmacology',
    'Pharmacology': 'Pharmacology',
    'Toxicology': 'Pharmacology',
    'General Physics and Astronomy': 'Physics',
    'Physics and Astronomy (miscellaneous)': 'Physics',
    'Acoustics and Ultrasonics': 'Physics',
    'Astronomy and Astrophysics': 'Astrophysics',
    'Condensed Matter Physics': 'Physics',
    'Instrumentation': 'Methodology',
    'Nuclear and High Energy Physics': 'Nuclear Physics',
    'Atomic and Molecular Physics, and Optics': 'Optics',
    'Radiation': 'Physics',
    'Statistical and Nonlinear Physics': 'Physics',
    'Surfaces and Interfaces': 'Physics',
    'General Psychology': 'Psychology',
    'Psychology (miscellaneous)': 'Psychology',
    'Applied Psychology': 'Psychology',
    'Clinical Psychology': 'Psychology',
    'Developmental and Educational Psychology': 'Psychology',
    'Experimental and Cognitive Psychology': 'Psychology',
    'Neuropsychology and Physiological Psychology': 'Psychology',
    'Social Psychology': 'Psychology',
    'General Social Sciences': 'Anthropology',
    'Social Sciences (miscellaneous)': 'Anthropology',
    'Development': 'Education',
    'Education': 'Education',
    'Geography, Planning and Development': 'Geography',
    'Health(social science)': 'Medicine',
    'Human Factors and Ergonomics': 'Business',
    'Law': 'Law',
    'Library and Information Sciences': 'Metascience',
    'Linguistics and Language': 'Anthropology',
    'Safety Research': 'Business',
    'Sociology and Political Science': 'Sociology',
    'Transportation': 'business',
    'Anthropology': 'Anthropology',
    'Communication': 'Business ',
    'Cultural Studies': 'Anthropology',
    'Demography': 'Anthropology',
    'Gender Studies': 'Anthropology',
    'Life-span and Life-course Studies': 'Longevity',
    'Political Science and International Relations': 'Political Science',
    'Public Administration': 'Political Science',
    'Urban Studies': 'Political Science',
    'General Veterinary': 'Veterinary Science',
    'Veterinary (miscalleneous)': 'Veterinary Science',
    'Equine': 'Veterinary Science',
    'Food Animals': 'Veterinary Science',
    'Small Animals': 'Veterinary Science',
    'General Dentistry': 'Medicine',
    'Dentistry (miscellaneous)': 'Medicine',
    'Dental Assisting': 'Medicine',
    'Dental Hygiene': 'Medicine',
    'Oral Surgery': 'Medicine',
    'Orthodontics': 'Medicine',
    'Periodontics': 'Medicine',
    'General Health Professions': 'Medicine',
    'Health Professions (miscellaneous)': 'Medicine',
    'Chiropractics': 'Medicine',
    'Complementary and Manual Therapy': 'Medicine',
    'Emergency Medical Services': 'Medicine',
    'Health Information Management': 'Medicine',
    'Medical Assisting and Transcription': 'Medicine',
    'Medical Laboratory Technology': 'Medicine',
    'Medical Terminology': 'Medicine ',
    'Occupational Therapy': 'Medicine ',
    'Optometry': 'Medicine ',
    'Pharmacy': 'Pharmacology',
    'Physical Therapy, Sports Therapy and Rehabilitation': 'Medicine',
    'Podiatry': 'Medicine',
    'Radiological and Ultrasound Technology': 'Medicie',
    'Respiratory Care': 'Medicine',
    'Speech and Hearing': 'Medicine',
    'Medical–Surgical': 'Medicine',
}
