from decimal import Decimal

MINIMUM_FUNDRAISE_CONTRIBUTION_AMOUNT_RSC = Decimal("0.01")
MAXIMUM_FUNDRAISE_CONTRIBUTION_AMOUNT_RSC = Decimal(1000000)

# USD amounts in cents
MINIMUM_FUNDRAISE_CONTRIBUTION_AMOUNT_USD_CENTS = 100  # $1.00
MAXIMUM_FUNDRAISE_CONTRIBUTION_AMOUNT_USD_CENTS = 100000000  # $1,000,000.00
USD_FUNDRAISE_FEE_PERCENT = 9  # 9% fee on USD contributions
