from .currency import ETHER, USD

RSC_EXCHANGE_CURRENCY = ((USD, USD), (ETHER, ETHER))

COIN_GECKO = "COIN_GECKO"
MORALIS = "MORALIS"
UNI_SWAP = "UNI_SWAP"

PRICE_SOURCES = ((COIN_GECKO, COIN_GECKO), (MORALIS, MORALIS), (UNI_SWAP, UNI_SWAP))
