name: Build

on:
  workflow_call:
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CONTAINER_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write # required for requesting JWT token from AWS

    steps:
      - name: Check out sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Git SHA
        id: git_sha
        run: |
          GIT_SHA=$(git rev-parse HEAD)
          echo "$GIT_SHA" > src/git_hash.txt
          SHORT_GIT_SHA=${GIT_SHA:0:7}
          echo "short=$SHORT_GIT_SHA" >> "$GITHUB_OUTPUT"
          echo "long=$GIT_SHA" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Build and push image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ env.CONTAINER_REPOSITORY }}:${{ steps.git_sha.outputs.long }}
          cache-from: type=gha,scope=researchhub-backend-arm64
          cache-to: type=gha,mode=max,scope=researchhub-backend-arm64
