name: Database Migration

on:
  workflow_call:
    inputs:
      git_ref:
        description: "Git hash or branch to run the migrations from"
        required: true
        type: string
    outputs:
      git_sha:
        description: "The commit the migrations ran from"
        value: ${{ jobs.migrate.outputs.git_sha }}

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CONTAINER_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}
  DEPLOY_ROLE_ARN: ${{ vars.STAGING_DEPLOY_ROLE_ARN }}
  MIGRATION_TASK_PARAMETER: /researchhub/staging/tasks/database-migration/run-task

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write # required for requesting JWT token from AWS
    outputs:
      git_sha: ${{ steps.git_sha.outputs.long }}

    steps:
      - name: Checkout application repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.git_ref }}

      - name: Get Git SHA
        id: git_sha
        run: |
          echo "long=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify container image exists
        env:
          IMAGE_TAG: ${{ steps.git_sha.outputs.long }}
        run: |
          REPOSITORY_NAME=${CONTAINER_REPOSITORY#*/}
          aws ecr describe-images \
            --repository-name "$REPOSITORY_NAME" \
            --image-ids "imageTag=$IMAGE_TAG" \
            > /dev/null

      - name: Assume staging deploy role
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          role-session-name: github-actions-database-migration-session
          role-chaining: true
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          aws-region: ${{ env.AWS_REGION }}
          retry-max-attempts: 3

      - name: Run database migrations
        env:
          IMAGE_URI: ${{ env.CONTAINER_REPOSITORY }}:${{ steps.git_sha.outputs.long }}
        run: |
          docker/run-migration-task.sh "$IMAGE_URI" "$MIGRATION_TASK_PARAMETER"
