name: Django Tests

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.12
    - name: Install dependencies
      working-directory: ./src
      run: |
        pip install pipenv
        pipenv install 
    - name: Lint with flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test note/tests --keepdb
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test note/tests --keepdb