CITATION_TYPE = {
    'REJECT': 'REJECT',
    'SUPPORT': 'SUPPORT',
}

CITATION_TYPE_CHOICES = [
    (CITATION_TYPE['REJECT'], CITATION_TYPE['REJECT']),
    (CITATION_TYPE['SUPPORT'], CITATION_TYPE['SUPPORT']),
]
